UI/gui.c
uchicago-cs/chiventure pull request #1002
Opened 2021-05-14 19:49 UTC by eao10000

Created two new files called gui.c and gui.h. In these files there is a function being created called start_gui, which was inspired by the start_ui function, meant to start a chiventure game with gui/graphics. There is a skeleton of the function stop_gui that will be implemented in the future. In addition chiventure.c was changed to check if the user wants to use gui, doing this by a boolean  to see graphical need as well as checking if the user is calling gui, by seeing if gui is flagged (--gui).

2021-05-14 20:02 UTC, zoetorok approved these changes

2021-05-14 20:35 UTC, MaxineK36 requested changes
A couple of minor formatting changes!

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +        if(!strcmp(argv[1],"--gui"))
nit: spacing 
Should be `if (!strcmp(argv[1], "--gui"))`

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +            if (!game)
Formatting: lines 69-72 should be further indented

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +            //Double checks that they user said gui
Line 74's comment should be sufficient

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +    //Boolean to see if gui is trying to be used
Formatting: comments that precede a block of code should be block comments; e.g.
`/* Boolean to see if gui is trying to be used */`

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +            if((argc == 3) && (!strcmp(argv[2],"--gui")))
Please adjust the spacing here as well

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +    if(graphical)
nit: spacing

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +        /***GUI***/
Please condense these into one, more detailed block comment

2021-05-14 20:35 UTC, MaxineK36 commented on src/chiventure.c
> +        /*** UI ***/
Ditto here

2021-05-14 20:35 UTC, MaxineK36 commented on src/ui/src/gui.c
> +/* MAIN_WIN_NUM will indicate we are in the main window
These don't appear to be used and should be deleted

2021-05-15 03:01 UTC, MaxineK36 approved these changes
looks good!

2021-05-15 15:59 UTC, borjasotomayor requested changes
Looks good overall, but there are a few things that need to be changed (see comments in the code)

2021-05-15 15:59 UTC, borjasotomayor commented on include/ui/gui.h
> +void start_gui(chiventure_ctx_t *ctx, const char *banner);
The `banner` parameter is no longer necessary to start a GUI

2021-05-15 15:59 UTC, borjasotomayor commented on include/ui/gui.h
> +#define UI_H
Update include guards to `GUI_H`

2021-05-15 15:59 UTC, borjasotomayor commented on include/ui/gui.h
> +#define MIN_ROWS 24
`MIN_COLS` and `MIN_ROWS` are only needed to launch the placeholder "THIS IS GUI" placeholder text interface, so they should be moved inside `gui.c`

2021-05-15 15:59 UTC, borjasotomayor commented on src/chiventure.c
> +        else
They way this if-else is written, you would not be able to run chiventure like this:

`./chiventure --gui game.wdl`

I suggest you only support the following parameters for now:

- No parameters: `./chiventure`
- 1 parameter: `./chiventure --gui` or `./chiventure game.wdl`
- 2 parameters: `./chiventure --gui game.wdl`

Any other syntax would just be invalid. So, you would need to structure the if-elses like this:

- If the number of parameters is 1 (i.e., if `argc == 2`)
  - If argv[1] is `--gui`, set `graphical` to true
  - Otherwise, assume `argv[1]` is specifying a file
- If the number of parameters is 2 (i.e., if `argc == 3`)
  - Check if `argv[1]` is `--gui`. If it isn't, that is an error.
  - If `argv[1]` is `--gui`, assume `argv[2]` specifies a file.

2021-05-15 15:59 UTC, borjasotomayor commented on src/chiventure.c
> +        /*If graphical is false the user will be using UI */
The following lines from the top of the main function:

```
    struct winsize w;
    ioctl(STDIN_FILENO, TIOCGWINSZ, &w);
    int ncols = w.ws_col, nrows = w.ws_row;
    if (ncols < MIN_COLS || nrows < MIN_ROWS) {
        fprintf(stderr, "Chiventure prefers to run in terminals of at least %d columns and %d rows. Please resize your terminal!\n", MIN_COLS, MIN_ROWS);
        exit(1);
    }
```

Should be moved inside this else branch, since they only apply when running a text-based interface.

2021-05-15 15:59 UTC, borjasotomayor commented on src/chiventure.c
> +            //Helps prevent errors when there is no loaded game
Use `/* block comments */` instead of `// inline comments`

Remember that inline comments [should be used sparingly](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#inline-comments). There are very few circumstances where an inline comment is merited.

2021-05-16 21:49 UTC, borjasotomayor requested changes
The changes look good, but the logic for handling the parameters is not quite there yet (see latest comments)

2021-05-16 21:49 UTC, borjasotomayor commented on src/chiventure.c
> +        }
The 2-argument case is missing the code to load the game file. If chiventure is run like this:

```
./chiventure --gui game.wdl
```

The second parameter is effectively ignored.

2021-05-16 21:49 UTC, borjasotomayor commented on src/chiventure.c
> +            fprintf(stderr, "Could not load game: %s\n", argv[1]);
`argv[1]` should be `argv[2]`

2021-05-17 17:03 UTC, borjasotomayor approved these changes
Polished up a few details in the code but, other than that, LGTM! :shipit:

2021-05-17 17:42 UTC, merged

2021-05-17 19:47 UTC, eao10000 commented
The gui.c and gui.h has been implemented, where it includes the basic start_gui function, and a skeleton of stop_gui. In this issue chiventure.c has been updated now to call start_gui if gui is flagged (--gui).  I am closing this issue, start_gui and stop_gui will be expanded upon in future issues.

2021-05-20 04:14 UTC, MaxineK36 commented
Issue Score: ✔️

Comments:
Good work overall! Two things to improve for next time:
- When a pull request issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
- The reviewer for this PR approved the PR without comment. Please make sure that you always do a full review of the code, even if the senior developer has already provided their review. In the rare cases where there truly isn't anything to improve in the PR, make sure to leave a comment confirming that you reviewed the code and don't have any changes to suggest. If the senior dev has left their review, it can also be useful to indicate whether you agree with it or not.

<!-- {"score": "check"} -->