Create and Implement deep memory copy functionality for Stat and Effect Structs
uchicago-cs/chiventure pull request #1003
Opened 2021-05-15 21:07 UTC by jasulcaf

(closes #933)

This is connected to my Issue #933 which set out to provide a way for users to create deep copy memories for structs. In Issue #877, there was some strangeness with memory happening due to pointers trying to access already free'd memory because the same memory was being used with multiple pointers existing (which created some odd dependencies).

An overview of implemented changes:

1. Created the following functions: `copy_global_stat` and `copy_stat` ; `copy_global_effect` and `copy_effect.` 

     - The similarity of names is intentional as the functions serve the purpose of either creating a deep copy of the global version of the struct (`copy_global_stat` and `copy_global_effect` respectively) or a deep copy of the more versatile non-global versions (`copy_stat` and `copy_effect` respectively).

2. Added `free_global_effect` and `free_stat_effect.` This abstracted code that frees an effect (both global and non-global types) which facilitated testing as well as provide a way for someone to free an effect (that isn't necessarily in a hash) easily without having to manually free each time.

2021-05-15 22:08 UTC, LapsededPacifist requested changes
I left comments on a lot of little things. There were two big things that I noticed.
1. It wasn't clear to me why (struct)_new was being used sometimes and why (struct)_init was being used sometimes in the copy functions. You wrote 4 different copy functions, and had 3 different methods of copying in them. This could be fine, but I don't understand the differences.
2. In the tests for copying, you should check that all the fields are being copied correctly. The code to copy them looks fine, so I don't think there will be a problem here. It is just good practice to make sure they are being check in case something breaks in the future.

2021-05-15 22:08 UTC, LapsededPacifist commented on tests/game-state/test_stats.c
> +
This is a lot of asserts checking for things that aren't really relevant to this test. I guess there isn't a problem having them here, but it makes it a bit more confusing to see what the test is doing (The name free_stat_effect is very clear, not that confusing)

2021-05-15 22:08 UTC, LapsededPacifist commented on tests/game-state/test_stats.c
> +
Same as the previous comments, should be checking that the fields in copy are the same as in effect.

2021-05-15 22:08 UTC, LapsededPacifist commented on src/game-state/src/stats.c
> +
This can also be fixed by using stats_new

2021-05-15 22:55 UTC, jasulcaf commented on src/game-state/src/stats.c
> +
Yes, I debated whether or not to use stats_new or not. My issue with using `stats_new` is that `stats_init` always sets `stat->val `and `stat->max` to the same value while stat->modifier is always set to 1. This will not always be the case, so I decided to manually initialize the stat fields to be the same as the original to avoid having to check for specific cases. Hopefully that makes more sense as to why I didn't use stats_new, but I will definitely include a check that copy isn't null!

2021-05-15 22:59 UTC, jasulcaf commented on src/game-state/src/stats.c
> +
You're definitely right! I was checking how the tests where creating effects and they did this manually, but your suggestion is much better (it's shorter and also easier to read and already checks for null)

2021-05-15 23:04 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
You're correct. I for some reason thought that checking twice would be better though it doesn't really make much sense now that I think about it. I will also explicitly make sure to check to test for the names and max values like you mentioned.

2021-05-15 23:08 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
Also, I decided to explicitly check that the pointers are not the same. I did this in line 214-215 in a different test, so it was definitely an oversight not to include this in more of my tests.

2021-05-15 23:11 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +}
I was just wanting to make it explicitly clear that freeing the originals didn't result in freeing the copies as well (if that was the case, then the asserts would fail). As per another comment you made, I am testing the technical fact that the pointers will be different before but I will also make sure that the formats are the same so as to be consistent

2021-05-15 23:14 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
It was for the exact same reason that you mentioned, I was wanting to make it explicitly clear that stats_new was working properly in my own test. But you are right, that's a different test altogether so it is redundant for the purpose of testing `copy_stat`

2021-05-15 23:20 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
I'll definitely add this, thanks for the suggestion.

2021-05-15 23:29 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +    change_stat_max(sh, "XP", 25);
That is indeed a different test for a different function, but from what I gather you would _not_ be adding c1 and c2 there. That's because the implementation of `add_stat` strictly goes against this due to the following lines: 
```
HASH_FIND(hh, *sh, s->key, strlen(s->key), check);

    if (check != NULL)
    {
        return FAILURE;
    }
```
That is, if the hash already contains a stat with a given name (check is _not_ equal to NULL), then it cannot be added.

2021-05-15 23:32 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +}
I definitely did. Actually, that adds for a great point, I should update the Pull Request Introduction to mention that I checked _all_ functions I added with the valgrind command used in #919

2021-05-15 23:35 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
That's very fair, those asserts are checking other functions more than free_stat_effect. Maybe simply checking for Null, for both the global and effect variable, is enough? That way the test at least ensures that we aren't passing Null into the free function

2021-05-15 23:39 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
Will definitely add this test.

(As for strcmp, Criterion actually has a `cr_assert_str_eq` built in so I just use this. Regardless thanks! I would have either forgotten or needed to look it up).

2021-05-15 23:43 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
Added the test like for previous comments.

2021-05-16 00:22 UTC, LapsededPacifist requested changes
I had one tiny nitpick, but I think it is good. Just add the one assert and I will approve it (I added a few other comments,  but none of them required anything).

2021-05-16 00:22 UTC, LapsededPacifist commented on tests/game-state/test_stats.c
> +        cr_assert_fail("copy_stat results in new stat and original stat having same char*");
I like that you are checking the pointers aren't the same, but little nitpick is that you aren't actually checking the strings themselves are equal.

2021-05-16 00:22 UTC, LapsededPacifist commented on tests/game-state/test_stats.c
> +    change_stat_max(sh, "XP", 25);
Alright sounds good. I was just curious about it.

2021-05-16 00:22 UTC, LapsededPacifist commented on tests/game-state/test_stats.c
> +
There is no penalty for checking more things. I just found it a little bit strange to have asserts not relevant to the tests. When in doubt, just keep them in I think.

2021-05-16 00:30 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +        cr_assert_fail("copy_stat results in new stat and original stat having same char*");
Will add a condition to check this

2021-05-16 00:32 UTC, jasulcaf commented on tests/game-state/test_stats.c
> +
That makes sense, I just added a comment over those asserts then to hopefully make it less strange.

2021-05-16 00:36 UTC, LapsededPacifist approved these changes
Updates for all my comments look good.

2021-05-17 01:29 UTC, MaxineK36 approved these changes
This looks awesome, great work!

2021-05-17 01:31 UTC, merged

2021-05-17 03:17 UTC, jasulcaf commented
Summary:
This Pull Request sought to implement a way to create deep memory copy functions for both stat and effect structs. This can prove useful in the future in case an effect or stat wants to involved in different aspects of Chiventure _but_ we don't want to run into dependencies issues such as what was found in #877. As such, the following functions where added to fulfill this goal: 
- `copy_global_stat` and `copy_stat:` Creates deep memory copies of global and versatile non-global version of stat struct.
- `copy_global_effect` and `copy_effect:` Creates deep memory copies of global and versatile non-global version of effect struct.

Through the process of testing the functions I created, I abstracted code to free effect structs from already implemented code in stats.c. This facillitated testing tremendously and also provides a way for Users to free effect structs that aren't _necessarily_ in hash tables. The functions are the following:
- `free_global_effect` and `free_stat_effect:` Frees global and versatile non-global version of effect structs respectively

2021-05-20 04:12 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! Your summary and closing statement are particularly clear and detailed; the bullet points make it easy to understand exactly what was changed.

<!-- {"score": "check-plus-plus"} -->