Implementation of conditional dialogue and action-dialogue integrations; writing of dialogue unit tests
uchicago-cs/chiventure pull request #1008
Opened 2021-05-16 19:09 UTC by jeyeong

Introduced the following changes to the dialogue module.

**Conditional Dialogue**
- Allow dialogue designers to designate certain edges (i.e. dialogue options) as "conditional," that is, only accessible if the player has fulfilled certain conditions.
- The implementation makes use of conditions from game-state/conditions.h.
- To make start_conversation() and run_conversation_step() work with conditional dialogue, some revisions had to be made: (1) Implemented a function to check for which edges are "available" upon reaching the node. (2) Generating the option numbers in the return string based on these "available" nodes.
- The edge and edge_list struct also had to be revised.
- Multiple conditions are possible.

**Action Integrations**
- Allow nodes to have associated actions, for example, giving the player an item, or starting a quest.
- This was achieved by implementing a node_action struct (a linked list) and an associated do_node_actions() function. Upon reaching each node, do_node_actions() is called, executing each action.
- Multiple actions per node are possible.

**Unit Tests** (in npc/test_dialogue.c)
- Tests for the basic functions, such as the init, new, free functions, as well as add_node() and add_edge().
- Tests for dialogue execution, i.e. start_conversation() and run_conversation_step().
- Tests for conditional dialogue.
- Tests for actions.
- NOTE: 2/3 of the action tests fail. They fail due to an oversight in the implementation of items.

2021-05-17 02:15 UTC, pkasner requested changes
For the most part looks good. Obviously the tests need to pass, so those will need to be figured out. Most important change is probably making sure item possession is handled gracefully for the npc and player if there is a transfer during dialogue. Also this perhaps would have been better as two pull requests, one for conditional dialogue and one for actions.

2021-05-17 02:15 UTC, pkasner commented on src/npc/src/dialogue.c
> -    for (i = 1; i < input && i < c->cur_node->num_edges; i++) {
The logic in this step is a little difficult to follow. Not sure if that's something to clarify with more comments or just me being slow to process how the while conditions interact with the if statement. Perhaps specify that the input value associated with an edge is equal to its order in the linked list ignoring any unavailable edges before it.

2021-05-17 02:15 UTC, pkasner commented on tests/npc/test_dialogue.c
> +   results in 2 available edges */
Some of these tests are probably redundant/don't seem to add additional coverage. No reason to delete them, but something to be aware of for the future.

2021-05-17 02:15 UTC, pkasner commented on include/npc/dialogue.h
> + */
Because the actual initiating of quests is left as to do, so this should be fine for now.

2021-05-17 02:50 UTC, jeyeong commented on include/npc/dialogue.h
> +    char *action_id;
Yes, that's correct. Action_type identifies the action being taken. Though it seems like that isn't so clear.

2021-05-17 02:52 UTC, jeyeong commented on include/npc/dialogue.h
> + */
Ah, I see. Technically, it isn't completely out of the question to convert a string into a long int, and vice versa.

2021-05-17 02:55 UTC, jeyeong commented on src/npc/src/dialogue.c
> +                int rc = add_item_to_player(game->curr_player, item);
That's actually a good point. One thing we would have to provide if we want to remove the item from the NPC's inventory is a pointer to the NPC we are currently speaking to. Which we may have to think about.

2021-05-17 02:57 UTC, jeyeong commented on src/npc/src/dialogue.c
> +                int rc = add_item_to_player(game->curr_player, item);
This current code itself, however, fails generally due to the item bug. I was considering fixing that error before moving on to a more proper implementation.

2021-05-17 03:03 UTC, jeyeong commented on src/npc/src/dialogue.c
> -    for (i = 1; i < input && i < c->cur_node->num_edges; i++) {
How did that get there? Was this from an old commit? The original idea of "i < c->cur_node->num_edges" was to handle the event where input is > than the number of available options. But I've since changed that implementation!

2021-05-17 03:03 UTC, pkasner commented on src/npc/src/dialogue.c
> +                int rc = add_item_to_player(game->curr_player, item);
With regard to keeping track of the npc we're talking to, I notice this function takes the game struct as a parameter, which means it can access the game's mode. In conversation mode, the mode structs mode_ctx field contains the npc's npc_id.

2021-05-17 03:07 UTC, pkasner commented on src/npc/src/dialogue.c
> -    for (i = 1; i < input && i < c->cur_node->num_edges; i++) {
I think I clicked the wrong line with this comment. Check the code immediately underneath maybe?

2021-05-17 03:10 UTC, jeyeong commented on tests/npc/test_dialogue.c
> +   results in 2 available edges */
Thanks for pointing that out. My thought process for the conditional dialogue tests were as follows:
1. Conditional edge, not passed
2. Conditional edge, passed
3. 1 Unconditional edge + 1 Conditional edge, passed (testing for interaction between conditional, unconditional edges)
4. 2 Unconditional edges + 2 Conditional edges, 1 pass, 1 fail (testing for interaction between the two conditional edges)

Are you saying including test #4 alone would perhaps have sufficed?

2021-05-17 03:27 UTC, jeyeong commented on include/npc/dialogue.h
> +    char *action_id;
I renamed action_type to simply action

2021-05-17 03:29 UTC, jeyeong commented on src/npc/src/dialogue.c
> +                int rc = add_item_to_player(game->curr_player, item);
Ah, that would be convenient. Can you point me to the function that returns the npc struct using the npc_id?

2021-05-17 03:32 UTC, jeyeong commented on src/npc/src/dialogue.c
> -    for (i = 1; i < input && i < c->cur_node->num_edges; i++) {
Ah, I see what you mean by hard to follow. This was the logic I needed to implement to make sure we end up at the correct edge. Perhaps I should state that explicitly in a comment.

2021-05-17 03:34 UTC, pkasner commented on tests/npc/test_dialogue.c
> +   results in 2 available edges */
I think 1 and 4 probably would have sufficed. 1 still seems like a useful edge case (as it returns 1 instead of 0 like the others).

2021-05-17 05:54 UTC, pkasner commented on src/npc/src/dialogue.c
> +                int rc = add_item_to_player(game->curr_player, item);
There currently is no such function, but it can be done with the HASH_FIND uthash macro. However, this also assumes that the npc/mode_operation branch is merged, which adds the all_npcs field as a hast table to chiventure's game struct. I do think I will probably add a get_npc function or something of the sort to that branch in the npc module.

2021-05-17 06:12 UTC, pkasner commented on src/npc/src/dialogue.c
> +                int rc = add_item_to_player(game->curr_player, item);
The get_npc() function in game.h in the npc/mode_operation branch now does that job.

2021-05-17 13:04 UTC, jeyeong commented on tests/npc/test_dialogue.c
> +   results in 2 available edges */
Got it, that makes sense. I've removed the redundant 2 & 3.

2021-05-17 13:13 UTC, jeyeong commented on src/npc/src/dialogue.c
> +                int rc = add_item_to_player(game->curr_player, item);
Great!

2021-05-17 17:49 UTC, pkasner commented
This looks good! I'm tentatively approving this, but I think we should still wait to merge this until after the npc/mode_operation branch can be merged. That way we can make sure conversation mode still works and we can do some integration testing.

2021-05-17 17:51 UTC, pkasner approved these changes
My above see my above comment that should've been attached to this review.

2021-05-22 17:54 UTC, jeyeong commented
After @pkasner 's pull request got merged, the code no longer compiled. I've made the changes so that it compiles now.

2021-05-24 15:54 UTC, jeyeong commented
I remodelled the GIVE_ITEM and TAKE_ITEM actions so that they interact with NPCs rather than the game. Also, since npc_new() was redefined in a recent update, I updated the example files so that they now work.

2021-05-24 20:54 UTC, lilyehsani requested changes
Really great job overall! Added a few comments, many of which are just questions.

2021-05-24 20:54 UTC, lilyehsani commented on src/npc/src/dialogue.c
> +    totlen += 1;
Was the change from 2 to 1 here intentional?

2021-05-24 20:54 UTC, lilyehsani commented on src/npc/src/dialogue.c
Again, should probably write a to-do for add_start_battle

2021-05-24 20:54 UTC, lilyehsani commented on src/npc/src/dialogue.c
> -    assert(strlen(npc_dialogue) < MAX_DIA_LEN);
Why delete these?

2021-05-24 20:54 UTC, lilyehsani commented on src/npc/src/dialogue.c
> +node_action_t *node_action_new(node_action_type action, char *action_id)
Should write corresponding init/free functions for this.

2021-05-24 21:24 UTC, jeyeong commented on include/npc/dialogue.h
> -    int option_number;
No, I've updated the create_return_string() function so it works independent of `option_number`.

2021-05-24 21:27 UTC, jeyeong commented on include/npc/dialogue.h
> +int add_start_quest(convo_t *c, char *node_id, char *quest_id);
I see. Would it be better to: (1) convert to long int into a string (using sprintf), or (2) create a union struct that could hold different types of IDs?

2021-05-24 21:33 UTC, jeyeong commented on include/npc/dialogue.h
Done

2021-05-24 21:35 UTC, jeyeong commented on include/npc/dialogue.h
> +int add_start_quest(convo_t *c, char *node_id, char *quest_id);
Actually, I'll just leave it as a to-do for now, since I don't believe the quest team has fully implemented quests into Chiventure

2021-05-24 21:35 UTC, jeyeong commented on include/npc/dialogue.h
> +int add_start_quest(convo_t *c, char *node_id, char *quest_id);
Actually, I'll just leave it as a to-do for now, since I don't believe we are able to integrate quests with dialogue at this point in time

2021-05-24 21:37 UTC, jeyeong commented on src/npc/examples/npc_example.c
>      convo_t *c = convo_new();
Done

2021-05-24 21:39 UTC, jeyeong commented on src/npc/examples/npc_example.c
>      convo_t *c = convo_new();
I only removed the commented code, instead of deleting the file because I think this was one of the files Prof. Sotomayor wanted students to refer to to get an idea of how monkeypatching works.

2021-05-24 21:40 UTC, jeyeong commented on src/npc/src/dialogue.c
> +    totlen += 1;
It was, the reason is because previously, I had wanted two newlines to be printed. But I realized that the CLI doesn't handle multiple newlines and only prints 1, so I changed it to only have 1 newline.

2021-05-24 21:40 UTC, jeyeong commented on src/npc/src/dialogue.c
Done

2021-05-24 21:41 UTC, jeyeong commented on src/npc/src/dialogue.c
> -    assert(strlen(npc_dialogue) < MAX_DIA_LEN);
I realized that I was doing assertion testing twice: once in new() and once in init(). So I removed the assertions in new() and kept them in init()

2021-05-24 21:52 UTC, jeyeong commented on src/npc/src/dialogue.c
> +node_action_t *node_action_new(node_action_type action, char *action_id)
Done

2021-05-24 21:53 UTC, jeyeong commented on src/npc/src/dialogue.c
> +node_action_t *node_action_new(node_action_type action, char *action_id)
The free function was free_action_list() but I guess that wasn't very clear. I've renamed it to free_node_actions()

2021-05-24 22:34 UTC, lilyehsani commented on src/npc/src/dialogue.c
> +    totlen += 1;
Sounds good

2021-05-25 00:21 UTC, lilyehsani commented on src/npc/src/dialogue.c
> -    assert(strlen(npc_dialogue) < MAX_DIA_LEN);
Ah I see

2021-05-25 00:21 UTC, lilyehsani commented on include/npc/dialogue.h
> -    int option_number;
Gotcha

2021-05-25 00:21 UTC, lilyehsani commented on include/npc/dialogue.h
> +int add_start_quest(convo_t *c, char *node_id, char *quest_id);
Sounds good

2021-05-25 00:22 UTC, lilyehsani commented on src/npc/examples/npc_example.c
>      convo_t *c = convo_new();
Awesome!

2021-05-25 00:23 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-05-25 00:24 UTC, merged

2021-05-25 01:37 UTC, jeyeong commented
Summary of changes made:
- Added conditional dialogue functionality to dialogues.
- Added actions to dialogue (e.g. you can gain an item from a dialogue node).
- Wrote dialogue unit tests.

Next steps:
- Complete the load_npc module, so that NPCs can be loaded from WDL files.
- Write a working game demo featuring NPCs and dialogue.

2021-06-07 02:00 UTC, lilyehsani commented
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- This PR represents a large amount of work that could've been integrated into `dev` through smaller PRs earlier in the quarter. Remember that you should not treat PRs as a singular event to merge all or most of your work into `dev`. Integrating incrementally can help identify integration issues early, as well as ensure that you are not rushing to merge all your code towards the end of a sprint. For example, the conditional dialogue, dialogue actions, and unit tests could have been separated into 3 or some combination of 2 PRs.

<!-- {"score": "check-plus"} -->