Implementing support for the history command
uchicago-cs/chiventure pull request #1009
Opened 2021-05-16 21:45 UTC by dchen0258

In relation to issue #271 
Goal: CLI previously supported "HIST" as a command, that printed out the user's history of commands. This command was causing a lot of issues during integration and testing, so we stopped supporting it. The goal of this issue is to debug the history operation and add support for it again.
Changes: Created new command list struct and new command list function in game state, add HIST entry to cmd.c, append command to linked list when new command is entered in cli in cmd.c, in operations.c for the hist_operation iterate through the linked list and print each command, changed the make file to include the new command.c file in game state folder

2021-05-17 15:32 UTC, ecoble requested changes
This looks great! There is a little bit of module refactoring to be done, but on the whole nice work!

2021-05-17 15:32 UTC, ecoble commented on include/game-state/command.h
> +#ifndef _COMMAND_H
"Commands" are more related to the CLI/parsing aspect of Chiventure and don't actually affect the game state until later in the pipeline when they have been processed through action management. Instead of making this a game state module, I would move it into the CLI module.

2021-05-18 18:23 UTC, ecoble requested changes
A couple small things, mostly style changes.

2021-05-18 18:23 UTC, ecoble commented on include/cli/cmdlist.h
> +    char* command;
Please be consistent with placement of *, looks like most other places you have type *name, so lets go with that.

2021-05-18 18:23 UTC, ecoble commented on include/cli/cmdlist.h
> +command_list_t* new_command_list(char* command);
Same thing here about placement of *

2021-05-18 18:23 UTC, ecoble commented on include/game-state/game.h
> +
Remove this whitespace change so that we aren't changing game state files.

2021-05-18 18:23 UTC, ecoble commented on src/cli/src/cmd.c
> +#include "game-state/game.h"
Do we still need game.h?

2021-05-18 18:23 UTC, ecoble commented on src/cli/src/cmd.c
> +        LL_APPEND(ctx->command_history,new_command);
Please put a space after the comma

2021-05-18 18:23 UTC, ecoble commented on src/common/src/ctx.c
> +    ctx->command_history = new_command_list(NULL);
I forgot to mention something important about using utlist, the head of the list should always be NULL. So instead of using new_command_list here, just set it equal to NULL.

2021-05-18 18:23 UTC, ecoble commented on src/cli/src/operations.c
> +    command_list_t* temp = new_command_list(NULL);
Same here for * placement

2021-05-18 18:23 UTC, ecoble commented on src/cli/src/cmd.c
> +        command_list_t* new_command = new_command_list(s);
Same here for * placement

2021-05-18 21:48 UTC, mberamendiconde reviewed
Looks great overall! :-)

2021-05-18 21:48 UTC, mberamendiconde commented on src/cli/src/cmd.c
> +    if (s != NULL) {
I think Elizabeth mentioned in another PR that we should use the Allman style of indentation with,
 if (_____)
{
...
}

So I could just change the code to match that style. Otherwise this looks great!

2021-05-18 21:48 UTC, mberamendiconde commented on src/cli/src/cmdlist.c
> +    if (command == NULL) {
Same thing here, I suggest Allman style indentation

2021-05-18 21:48 UTC, mberamendiconde commented on src/cli/src/operations.c
> +        if (temp->command != NULL) {
Suggest Allman style indentation here too!

2021-05-19 03:39 UTC, dchen0258 commented on src/cli/src/cmd.c
> +    if (s != NULL) {
ok makes sense, thanks!

2021-05-19 04:37 UTC, ecoble approved these changes

2021-05-19 16:02 UTC, borjasotomayor requested changes
Adding the command history in `chiventure_ctx_t` sounds good to me, but I think we should instead create a `cli_ctx_t` type to store CLI-specific context information (similar to how there is a `ui_ctx_t` type), and place the command history there. That way, if we need to add additional CLI-related information to `chiventure_ctx_t`, it will be more clearly separated into component-specific contexts objects (if we do this, then it probably makes sense to move `lookup_t **table` in to that CLI context).

Since that will involve a fair amount of refactoring (given that the lookup table is used in several different places), we should just create a separate backlog issue for that refactoring. Please create that issue, and I will approve the PR once that's done.

2021-05-19 16:49 UTC, dchen0258 commented
The new issue regarding the cli_ctx struct has been created. It is issue #1060.

2021-05-19 17:47 UTC, borjasotomayor approved these changes
LGTM! :shipit:

2021-05-19 19:26 UTC, mberamendiconde approved these changes
Looks great now! Appreciate the Allman style changes :-)

2021-05-21 07:55 UTC, merged

2021-05-21 07:58 UTC, dchen0258 commented
This solution should work for the foreseeable future unless major changes are made. The only one I can think of is the adding a new cli struct, but that should only require some small refactoring of code!

2021-05-25 16:45 UTC, ecoble commented
Issue Score: ✔️++

Comments:
Great job implementing the HIST command, and using linked lists to do it! The summary and closing statement are great too, and great job @mberamendiconde for a thorough review!

<!-- {"score": "check-plus-plus"} -->