Implemented the Stats/Effects and Skilltree sections of the Player Interface Plan
uchicago-cs/chiventure pull request #1011
Opened 2021-05-17 01:29 UTC by WPDolan

We have implemented our planned functionalities described under the "Stats/Effects" and the "Skilltree" sections of our player interface implementation [plan](https://github.com/uchicago-cs/chiventure/wiki/Player-~-Interface-Implementation-Plan). This pull request furthers our plan to implement all planned features of the interface as described in Issue #952.

Our additions specifically provide functionality for interacting with the player struct's `player_combat_skills`, `player_noncombat_skills`, `player_stats`, and `player_effects` fields. 

Functions added include:
- `player_add_combat_skill/player_add_noncombat_skill`, 
-  `player_remove_combat_skill/player_remove_noncombat_skill` , 
- `player_has_combat_skill/player_has_noncombat_skill` 
- `player_add_stat`
- `player_change_stat`
- `player_change_stat_max`
- `player_get_stat_current`
- `player_add_stat_effect`
We have also pushed tests for each of these functions, which should provide the skilltrees and game-state (currently action-management) teams the ability to interact with a player over the course of the game without the additional cognitive load of handling the multitude of specific data structures referenced within the player struct. 

Additionally, we fixed a few small errors in `stats.c` where integers were unintentionally cast to doubles.  We also noticed that `get_stat_current` in `stats.c` only checks a stat's value against its corresponding global maximum, while ignoring its local maximum value. From looking at the tests in `test_stats.c` this appears to be an intended design choice, albeit a strange one. Our test for `player_get_stat_current` reflects the original design.

Future pull requests will implement the remaining sections of the interface plan.

2021-05-17 04:57 UTC, LapsededPacifist approved these changes
I made some comments, but I don't think there is anything that needs fixing. Just some minor things that would probably be nice to have, but I don't think are necessary. 
Mostly just checking the things the functions modified instead of just making sure they returned success and also creating new inventory for both combat and noncombat skills every test when only one is used.

2021-05-17 04:57 UTC, LapsededPacifist commented on tests/game-state/test_player.c
> +
I guess you don't need to add a check that wizardry is actually a part of player->player_combat_skills since there are probably tests for inventory_skill_add, but it would be nice to know that they are actually being added properly and not just returning success without the proper modifications being made.

2021-05-17 04:57 UTC, LapsededPacifist commented on tests/game-state/test_player.c
> +
Same comment as the last function.

2021-05-17 04:57 UTC, LapsededPacifist commented on tests/game-state/test_player.c
> +
There isn't really a reason to create before inventories if you are only testing combat_skill. It isn't going to hurt anything, so no reason to change it before that portion of code is modified when future implementations of player_new automatically create those inventories.

2021-05-17 04:57 UTC, LapsededPacifist commented on tests/game-state/test_player.c
> +
See previous comments about checking if something is actually in the array and not just returning SUCCESS without doing its job.

2021-05-17 04:57 UTC, LapsededPacifist commented on tests/game-state/test_player.c
> +
Same as above.

2021-05-17 04:57 UTC, LapsededPacifist commented on tests/game-state/test_player.c
> +Test(player, has_combat_skill)
You aren't testing any of the cases where you actually have to search the inventory since it is either the first item or there is no item in the inventory at all and it just ends. 
Normally this would be a problem, but since you are just using existing functions that have already been tested (Hopefully) I think this is probably fine.

2021-05-18 15:08 UTC, MaxineK36 requested changes
This looks good overall! I do think Stephen's suggestions are worth addressing; please make those changes and then I'll take a look again.

2021-05-18 23:31 UTC, WPDolan commented on tests/game-state/test_player.c
> +
The unnecessary inventories have been removed

2021-05-18 23:33 UTC, WPDolan commented on tests/game-state/test_player.c
> +
I have included additional assert statements in all four tests (for adding and removing skills in combat/noncombat inventories) to check if the pointers in the inventory struct have actually been updated after a skill has been added/removed.

2021-05-18 23:38 UTC, WPDolan commented on tests/game-state/test_player.c
> +Test(player, has_combat_skill)
I have updated both the `player_has_combat_skill` and `player_has_noncombat_skill` functions to check inventories with more than one skill.

2021-05-19 00:31 UTC, LapsededPacifist approved these changes
Changes look good. I just looked at the new ones since the last review, but I can't imagine any way that the stuff you just changed would affect any of the other changes.

2021-05-19 23:03 UTC, MaxineK36 approved these changes
Looks great!

2021-05-19 23:04 UTC, merged

2021-05-20 00:15 UTC, WPDolan commented
Closing statement:

After further refining the tests for the interface, the pull request has been merged. The Stats/Effects and Skilltree sections of the player interface plan have been fully implemented. Members of the game-state and skilltree teams should now be able to interact with player structs as needed over the course of a game.

Future sections of the interface plan will be implemented into the player module in Issues #1053, #1057, and #1058.

2021-05-22 20:24 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Excellent work! You did a particularly good job making it easy to track progress on the large player project by setting up issues for the future tasks and linking them in your closing summary.

<!-- {"score": "check-plus-plus"} -->