Added new functions in the npc_mov module and updated relevant tests
uchicago-cs/chiventure pull request #1012
Opened 2021-05-17 06:19 UTC by torresszy

The two major functions left unfinished from last year, `move_npc_indefinite` and `auto_gen_movement` have been implemented under the `npc_move` module in this pull request. `move_npc_indefinite` will move an existing NPC with an indefinite move type from one room to another. `auto_gen_movement` will randomly generate a list of rooms and append the list to a given NPC's path. In addition, we have implemented two new functions, `get_npc_num_rooms` and `get_num_rooms`. `get_npc_num_rooms` takes a `npc_mov` struct and returns the number of rooms a NPC has in its list of rooms to visit. `get_num_rooms` is a helper function for `auto_gen_movement` that returns the total number of rooms in a given game. In addition, new tests are created for these functions in `test_npc_move.c`. One thing to be noted is that in both `move_npc_indefinite` and `auto_gen_movement`, we have inherited the concept of time from last year NPC team's implementation. However, this concept is not yet well-established in Chiventure at this point. Therefore, Updates on these functions may be needed when a more matured system on "time" is developed in the future.

Summary of major changes:

Added new functions, `move_npc_indefinite`, `get_npc_num_rooms`, `get_num_rooms`,and `auto_gen_movement`, in `npc_move.c` and their headers in `npc_move.h`.
Added new tests for these functions in `test_npc_move.c`

2021-05-17 06:43 UTC, mbutera17 requested changes
Looks great - Just need Xavier's addition and one small typo.

2021-05-17 06:43 UTC, mbutera17 commented on tests/npc/test_npc_move.c
> +
Include test for move_npc_indefinite from Xavier

2021-05-17 06:43 UTC, mbutera17 commented on tests/npc/test_rooms_npc.c
> +Test (npcs_in_room, delet_npc_from_room)
Fix typo: "delet_npc_from_room" -> "delete_npc_from_room"

2021-05-17 17:56 UTC, xlewellen approved these changes
Everything looks good!

2021-05-18 03:07 UTC, mbutera17 approved these changes
Looks good! Changes requested in my previous review have been resolved.

2021-05-27 04:06 UTC, lilyehsani requested changes
Looks really good! Added a few comments, mostly style

2021-05-27 04:06 UTC, lilyehsani commented on tests/npc/test_npc_move.c
> +    cr_assert_eq(cnt, num_rooms_in_npc, "room_count returns %d, but there should be %d rooms in npc_mov",
Change the next couple of lines to be under 80 characters

2021-05-27 04:06 UTC, lilyehsani commented on tests/npc/test_npc_move.c
> +    cr_assert_eq(cnt, num_rooms_in_npc, "room_count returns %d, but there should be %d rooms in npc_mov",
Under 80 characters

2021-05-27 04:38 UTC, mbutera17 commented on src/npc/src/npc_move.c
> +            head->room = head->next->room; // not sure if this is correct
Sorry about the confusion of this comment - I had initially written this when I was drafting the function to point out to Torres & Xavier where I was confused. Turns out my suspicion was correct and that line was fixed and now works as intended.

2021-05-31 18:44 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-05-31 18:45 UTC, merged

2021-05-31 21:53 UTC, torresszy commented
This is the closing comment for this pull request; it has been merged successfully and all goals have been achieved. No major changes were needed since the beginning of this pull request. There were a few formatting and stylistic issues but they were resolved very quickly.

One note for future implementation, as I mentioned at the beginning of this PR as well, is that `move_npc_indefinite` and `auto_gen_movement` under `npc_move.h` inherit mainly the implementation and design logic from last year's NPC team, which includes this concept of "time" in seconds. However, This feature is currently not supported by Chiventure, so these two functions cannot be used practically at the moment unless with some modifications. Future teams can and should think about 1) how to bring the concept of "time" into the overall Chiventure, or 2) another way to keep track of the progression of the game.

2021-06-07 02:07 UTC, lilyehsani commented
Issue Score: ✔️++

Comments:
Great work overall! The summary and closing of this PR are very thorough.

<!-- {"score": "check-plus-plus"} -->