made changes on skill levelling prerequisites and tests
uchicago-cs/chiventure pull request #1015
Opened 2021-05-17 19:24 UTC by Joshuashou

Integrated prerequisite leveling to the skill-tree files, and changed tests to accommodate and test these structural changes.

2021-05-23 20:51 UTC, rohangupta2806 requested changes
I've suggested one change that can be carried out by either creating a struct or by writing a couple of small methods.  Everything else looks good.

2021-05-23 20:51 UTC, rohangupta2806 commented on include/skilltrees/skilltree.h
> + *   - prereq_level: An out-paramter. The level that is a prerequisite to earn a skill
The out parameter behavious does not seem like the best approach.  Can we create a new struct that holds all the prerequisite skills and level and number?  Or we could even split this up into different functions that return 1 of the 3 things if we don't want to create a new struct

2021-05-24 21:56 UTC, m-ghosal commented on include/skilltrees/skilltree.h
> +* Since it is simply an unsigned integer
i think the skill_prereqs_missing function already takes care of the the scenario in which a prereq level is missing, so a new function for that doesn't seem necessary.

2021-05-25 09:06 UTC, Joshuashou commented on include/skilltrees/skilltree.h
> + *   - prereq_level: An out-paramter. The level that is a prerequisite to earn a skill
Just resolved the issues, repushed!

2021-05-25 09:07 UTC, Joshuashou commented on include/skilltrees/skilltree.h
> +* Since it is simply an unsigned integer
just changed this and git pushed!

2021-05-25 14:35 UTC, rohangupta2806 approved these changes
Okay, it looks great now.  Approved.

2021-05-25 22:07 UTC, m-ghosal approved these changes
Looks good to me :)

2021-05-26 06:15 UTC, firatciftci requested changes
I have requested mostly stylistic changes, but there are also some other comments as well. Check them out and let me know if you have any questions/issues.

2021-05-26 06:15 UTC, firatciftci commented on include/skilltrees/skilltree.h
> +   //this is an ADDITIONAL pre_req to the lists of skill_nodes preceding the tree
Minor stylistic issue: Make sure that your comments are indented the same amount as the code surrounding them. Also, make sure to leave a blank space between `//` and the comment text.

2021-05-26 06:15 UTC, firatciftci commented on src/skilltrees/src/skilltree.c
> +    if(pos == -1) {
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-26 06:15 UTC, firatciftci commented on src/skilltrees/src/skilltree.c
> +unsigned int get_number_skill_prereqs(skill_tree_t* tree, sid_t sid){
There should be a space character between `)` and `{` at the end of the line.

2021-05-26 06:15 UTC, firatciftci commented on src/skilltrees/src/skilltree.c
> +unsigned int get_prereq_level(skill_tree_t* tree, sid_t sid){
There should be a space character between `)` and `{` at the end of the line.

2021-05-26 06:15 UTC, firatciftci commented on src/skilltrees/src/skilltree.c
> +    if(pos == -1) {
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-26 06:15 UTC, firatciftci commented on src/skilltrees/src/skilltree.c
> +    skill_t** acquired = (skill_t**)malloc(*num_acquired_prereqs*sizeof(skill_t*));
There should be blank spaces surrounding the multiplication action symbol `*` on this line.

2021-05-26 06:15 UTC, firatciftci commented on src/skilltrees/src/skilltree.c
> +                                unsigned int* prereqlevel,
This line should be indented one space character leftward to match the indentation of the other lines above and below it.

2021-05-26 06:15 UTC, firatciftci commented on src/skilltrees/src/skilltree.c
> +    skill_t** missing = skill_prereqs_missing(tree, inventory, skill->sid, &levelpointer,
I think we should match the name of this new variable to camel_case and change it to be `level_pointer` instead.

Alternatively, it could make sense to have this be an `unsigned int *`, and we could rename it to be simply `level`, and pass `level` instead of `&level_pointer` inside the function call.

2021-05-26 06:15 UTC, firatciftci commented on tests/skilltrees/skilltree_test.c
> +// Test(skilltree_tests, skill_node_new_test)
Why have all of the skilltree tests been commented out? Are there immediate plans to refactor these before the soft freeze at the end of this week?

2021-05-26 08:01 UTC, Joshuashou commented on tests/skilltrees/skilltree_test.c
> +// Test(skilltree_tests, skill_node_new_test)
Yes, since a lot of these tests are reliant on the new effect implementations, I am refactoring them in the spring this week, will get it done before the end of the week.

2021-05-26 21:44 UTC, firatciftci approved these changes
Looks good to me!

2021-05-26 21:45 UTC, merged

2021-06-02 23:07 UTC, firatciftci commented
Issue Score: ✔️

Comments:
Good work! I have two things to comment on:
- The summary for this PR is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples).
- When an PR is done, you should include a final comment summarizing what was merged to `dev` and what work remains to be done, if any.

<!-- {"score": "check"} -->