Added DSL grammar file: Implementation of the core features of the DSL grammar
uchicago-cs/chiventure pull request #1029
Opened 2021-05-18 05:00 UTC by tessied

We have implemented the grammar for a few of the core features of the DSL. This pull request consists of a lark grammar file which describes the DSL language, according to the [user stories](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-User-Stories) and the [design](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar) we came up with. 

Some of the features that were implemented in this grammar are:
- Declaring a game
- Declaring a room (with connections, properties, items)
- Declaring an item (with properties, actions)
- Declaring variables
- Adding escape characters for strings
- Attributing properties to items

This pull request also includes a README, a parser file as a placeholder for future implementation of the parser, and a few examples for demonstration. This pull request reflects the implementation done in issues #931, #977, and #981.

2021-05-19 04:50 UTC, ecoble requested changes

2021-05-19 04:50 UTC, ecoble commented on src/dsl/examples/distaff.dsl
> +
Are these extra lines intentional?

2021-05-19 04:50 UTC, ecoble commented on src/dsl/examples/distaff.dsl
> +   ITEM Door IN room B
Is it intentional that this is the only item where the room is specified like this?

2021-05-19 04:50 UTC, ecoble commented on src/dsl/src/dsl_parser.py
> +class TreeToDict(Transformer):
For all of these functions, I think it would be useful to write a comment saying what all these single letter variables are (s, k, v) and their type. If they are the same across all the functions, you can just put one comment for it at the top.

2021-05-20 18:38 UTC, r-e-stern requested changes
There's a lot more flexibility in the parser now than the documentation originally imagined (re: connections, etc.), so we should remember to note that.

Actions don't parse correctly quite yet.

2021-05-20 18:38 UTC, r-e-stern commented on src/dsl/examples/distaff.dsl
> +   connections: NORTH TO room A
The [docs](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-User-Stories#simple-declarations) seem to indicate that we want a comma-separated list for connections, but this works too if we want, we just have to update the docs accordingly.

2021-05-20 18:38 UTC, r-e-stern commented on src/dsl/examples/short_example.dsl
> +    action: OPEN, BREAK
This doesn't actually parse correctly as a list of actions; instead it thinks OPEN is the property and the rest of the inside is the value.

2021-05-20 19:31 UTC, tessied commented on src/dsl/examples/distaff.dsl
> +
Yes, these lines are the first half of the room declaration for `room B`. We broke up the `long desc` into two lines with a few blank lines in between to demonstrate that we have defined our grammar generously so that the parser does not break even if there are extra lines here and there. I have made the comment  `#intentional line break` to make this clear in the file.

2021-05-20 19:38 UTC, tessied commented on src/dsl/examples/distaff.dsl
> +   ITEM Door IN room B
Yes, this is the second half of the declaration for `room B`. We added the blank lines in between these two halves to show that the parser works with line breaks (see previous [comment](https://github.com/uchicago-cs/chiventure/pull/1029#discussion_r636410162) regarding line breaks in `long desc`) . For the `ITEM Door`, we also intentionally declared that it is in room B to show that our parser allows users to specify the locations of items if they wish.

2021-05-20 19:43 UTC, tessied commented on src/dsl/examples/distaff.dsl
> +   connections: NORTH TO room A
We have defined the grammar such that it gives the user the option to specify connections using either a comma-separated list or line breaks — both work properly. We could note this flexibility in the documentation.

2021-05-20 20:00 UTC, jacknugent1529 commented on src/dsl/examples/short_example.dsl
> +    action: OPEN, BREAK
Thanks for pointing that out. Previously the parser correctly interpreted it, but the transforming function had errors. It should be fixed now so that all action ids are recognized and properties are associated with the correct actions.

2021-05-20 20:12 UTC, r-e-stern approved these changes

2021-05-20 20:20 UTC, jacknugent1529 commented on src/dsl/src/dsl_parser.py
> +class TreeToDict(Transformer):
The variable `s` represents what is passed to the function by Lark (it seemed to be common notation in the examples). As we're "compressing" the parsing tree, the key, `k` is always a string, while the value may take on different formats. We could list all of these, but in the future there might be additions. I added comments in commit eef06d1 to specify what the value type is in relevant locations.

2021-05-21 07:13 UTC, ecoble commented on src/dsl/examples/distaff.dsl
> +   ITEM Door IN room B
Great! What does that mean for items that are not specified in a specific room? Are they still located in the room they are under?

2021-05-21 07:17 UTC, ecoble commented on src/dsl/distaff.dsl
> +# This is a dsl version of the distaff game. Actions have not yet been
Do we need this file? It looks the same as the one in the example directory.

2021-05-21 14:42 UTC, tessied commented on src/dsl/distaff.dsl
> +# This is a dsl version of the distaff game. Actions have not yet been
Thank you for pointing that out! That was indeed an extra file that we did not have to include. I have since deleted the file (commit [`de2149a`](https://github.com/uchicago-cs/chiventure/pull/1029/commits/de2149a21ec1b354919391c8253be64260470d18)).

2021-05-21 14:45 UTC, tessied commented on src/dsl/examples/distaff.dsl
> +   ITEM Door IN room B
Yes! For items that are not specified in a room, the default case applies and the item is located in the room that they are under. The same is also true for properties that are not assigned to a specific item - the default case associates them with the item/room they are under.

2021-05-22 22:04 UTC, r-e-stern requested changes

2021-05-22 22:04 UTC, r-e-stern commented on src/dsl/examples/short_example.dsl
> +      OPEN condition: "Door is in front of you."
The OPEN condition does not parse.

2021-05-22 22:22 UTC, jacknugent1529 commented on src/dsl/examples/short_example.dsl
> +      OPEN condition: "Door is in front of you."
That was due to a slight indexing error. It is fixed now

2021-05-22 22:58 UTC, r-e-stern approved these changes

2021-05-23 22:08 UTC, ecoble approved these changes
LGTM!

2021-05-23 22:20 UTC, merged

2021-05-24 15:35 UTC, tessied commented
Closing statement: We added a DSL grammar file in `src/dsl` along with a parsing file and a few examples. Since opening the pull request, we made several changes to ensure that the features parse correctly. The changes have been merged and the `dev` branch now has the DSL grammar file, closing the pull request.

2021-05-25 16:42 UTC, ecoble commented
Issue Score: ✔️++

Comments:
Great job, the DSL is looking amazing! The documentation in the closing statement and summary are great as well, and thanks @r-e-stern for such a thorough review!

<!-- {"score": "check-plus-plus"} -->