Fixing chiventure segfault when trying to load wdl file
uchicago-cs/chiventure pull request #1036
Opened 2021-05-18 18:39 UTC by samdonio

Previously chiventure would have a seg fault when the user tried using the load_wdl command at all. This is because the cli didn't correctly check if the path was valid, and also because the wdl module doesn't currently load wdl files correctly. Now, the cli returns that the path is invalid and that the wdl loading isn't complete yet and doesn't seg fault anymore.

Closes #1030

2021-05-18 20:30 UTC, samdonio commented
After more changes to the way that load_wdl_operation works, the LOAD_WDL command now checks whether the file exists, then checks if the file has the ending of .wdl, and if either of these are not true it tells the user that the path/file is invalid. Also, the function now correctly loads a chiventure game if the path is correct, meaning that the user can now use LOAD_WDL to load wdl files from inside the game whenever they want.

2021-05-19 04:55 UTC, ecoble requested changes

2021-05-19 04:55 UTC, ecoble commented on src/cli/src/operations.c
> +bool validate_wdl_filename(char *filename)
I think it is safe to remove the previous validate_filename function, I don't think we use .dat files anymore for Chiventure.

2021-05-19 04:55 UTC, ecoble commented on src/cli/src/operations.c
> +    const char *ending = &filename[len - 4];
4 is a bit of a magic number here, can we create another variable, maybe something like "file_extension_length"

2021-05-19 05:07 UTC, samdonio commented on src/cli/src/operations.c
> +    const char *ending = &filename[len - 4];
file_extension_length int has been made

2021-05-19 05:07 UTC, samdonio commented on src/cli/src/operations.c
> +bool validate_wdl_filename(char *filename)
This function has been removed from the operations.c and operations.h file

2021-05-20 03:38 UTC, ecoble requested changes
Looks great! Just a couple style fixes, you can probably just fix them with astyle.

2021-05-20 03:38 UTC, ecoble commented on src/cli/src/operations.c
>      if(len < min_filename_length)
Spacing after "if"

2021-05-20 03:38 UTC, ecoble commented on src/cli/src/operations.c
> +    else{
Looks like the rest of this file is using allman style brackets, lets stick with that.

2021-05-20 03:38 UTC, ecoble commented on src/cli/src/operations.c
> +    if(valid_path == -1) //Triggers if file does not exist
Spacing

2021-05-20 03:38 UTC, ecoble commented on src/cli/src/operations.c
>      if(game == NULL)
Spacing

2021-05-20 07:43 UTC, dchen0258 approved these changes
Looks good! Very neat solution.

2021-05-21 07:27 UTC, merged

2021-05-25 16:38 UTC, ecoble commented
Issue Score: ✔️+

Comments:
Great job, thanks for fixing this! Be sure to put closing statements on your PRs as well, just as you would for issues.

<!-- {"score": "check-plus"} -->