Implementing support for input suggestions when input is misspelled
uchicago-cs/chiventure pull request #1041
Opened 2021-05-18 20:09 UTC by dchen0258

In relation to issue #1004.
Goal: To create a feature by which if a user types in a word not supported by chiventure but similarly spelled to a supported input, it will be suggested to the user. For example, if the user meant to type 'take" but types "tak" , the user will see "did you mean: take" printed to the window, rather than "command not supported".
Changes: Created a new array that contains all possible actions. In the function "action_error_operation" rather than just printing out "command not supported", it compares the input to each action in the list, and returns the one that is most alike.

2021-05-20 03:48 UTC, ecoble requested changes

2021-05-20 03:48 UTC, ecoble commented on src/cli/src/operations.c
> +int compare(char* word, char* action, int initial)
Since these are helper functions without their own definition in the .h file, you should include header comments for these functions here.

2021-05-20 03:48 UTC, ecoble commented on src/cli/src/operations.c
> +    if (current > initial){
Is there a reason to set initial = current here? It seems like the point is just to return the greater of current and initial, in which case you can just return current if it's greater than initial or initial if it's not. Please correct me if I'm missing something.

2021-05-20 03:48 UTC, ecoble commented on src/cli/src/operations.c
> +    if (index == -1) {
You do not need the else part of this statement, since you have a return statement within the if. You could also simplify this to use the ternary conditional operator (though it is not necessary if you don't want to).

2021-05-20 03:48 UTC, ecoble commented on src/cli/src/operations.c
> +    } else {
Same here about not needing this inside an else.

2021-05-20 03:48 UTC, ecoble commented on src/cli/src/operations.c
> +    if (tokens[0] == NULL) {
This seems like a bit of a special case, it may be worth telling the user specifically that their action was NULL, because it could indicate a larger bug which is useful information.

2021-05-20 05:32 UTC, samdonio requested changes
There didn't seem to be any problems besides what Elizabeth had pointed out, but just some style changes should be made. Otherwise, nice work!

2021-05-20 05:32 UTC, samdonio commented on src/cli/src/operations.c
> +    if (current > initial){
Besides what Elizabeth said, the style of this should probably be corrected to fit with the rest of chiventure, as we are using Allman style so having the brace on the same line as the for and if's is incorrect. This is also a little pedantic but there maybe shouldn't just be the empty line on line 32. This can probably be fixed quickly with astyle.

2021-05-20 05:32 UTC, samdonio commented on src/cli/src/operations.c
> +            if (temp > initial) {
Again, allman style.

2021-05-20 05:32 UTC, samdonio commented on src/cli/src/operations.c
> +    if (index == -1) {
allman

2021-05-20 05:32 UTC, samdonio commented on src/cli/src/operations.c
> +    if (tokens[0] == NULL) {
allman

2021-05-20 05:32 UTC, samdonio commented on src/cli/src/operations.c
> +    } else {
allman

2021-05-21 07:32 UTC, ecoble approved these changes
Great job!

2021-05-21 19:15 UTC, samdonio approved these changes
The style looks much better now, great job!

2021-05-21 19:26 UTC, merged

2021-05-21 19:40 UTC, dchen0258 commented
Closing statement: 
There are possible enhancements to the issue: allowing multiple suggestions, not only based on the number of matching letters, but also the size of the words. This would require a much more length function, and probably can be an enhancement for the future!

2021-05-25 16:35 UTC, ecoble commented
Issue Score: ✔️++

Comments:
Great job on this issue! This was definitely a tougher task, and you implemented a great solution!

<!-- {"score": "check-plus-plus"} -->