Cli/parse with linked lists
uchicago-cs/chiventure pull request #1048
Opened 2021-05-18 23:23 UTC by Beza20

With this pull request we have enabled a user to input multiple commands at once using a connecting word "and." This was done by using a helper function <strtokstr_r> that has very similar structure as the C built-in function <strtok_r.> It parses through a string and tokenizes a segment of that string whenever it finds the inputed delimiter of a string type. Then we use the helper function to read the cmd line and store the tokenized segment of the input into a utlist. Note: Each element in the utlist has to further be parsed breaking it up using a space. And then in the UI module, we made sure that all of the command segments put into the utlist are iteratively changed into a command struct by calling the <cmd_from_string> and executed. And with that this pull request will introduce the "and" feature to chiventure resolving issue #275.

2021-05-20 04:17 UTC, ecoble requested changes
This is looking great!

2021-05-20 04:17 UTC, ecoble commented on src/cli/src/parser.c
> +    while (strstr(s,delim)==s)
Please put spaces around ==

2021-05-20 04:17 UTC, ecoble commented on src/cli/src/parser.c
> +        s+=strlen(delim);
Same here with spaces around +=

2021-05-20 04:17 UTC, ecoble commented on src/cli/src/parser.c
> +            }
Watch bracket spacing

2021-05-20 04:17 UTC, ecoble commented on src/cli/src/parser.c
> +    end = strstr (s, delim);
No space between function name and parentheses

2021-05-20 04:17 UTC, ecoble commented on src/cli/src/parser.c
> +        tokenized_cmds *new_thing = malloc(sizeof(tokenized_cmds));
Having a more descriptive name than "new_thing" would be good, maybe something like "new phrase"

2021-05-21 00:26 UTC, Beza20 commented on src/cli/src/cmd.c
> +    if(s == NULL)
Yeah good catch. Amazing that it didn't make it crash. But we missed it when we adjusted the code while forgetting that after parsing with "and" we forgot to additionally parse with space.

2021-05-21 07:37 UTC, ecoble requested changes
A couple more style things but it's looking great!

2021-05-21 07:37 UTC, ecoble commented on src/cli/src/cmd.c
> +
Can we remove both of these extra new lines? So that we aren't unnecessarily changing this file.

2021-05-21 07:37 UTC, ecoble commented on src/cli/src/parser.c
> +    if(strcmp(input, "") == 0)
Space after if

2021-05-21 07:37 UTC, ecoble commented on src/cli/src/parser.c
> +    while(input[i])
Space after while

2021-05-21 07:37 UTC, ecoble commented on src/cli/src/parser.c
> +    while(token != NULL)
Space after while

2021-05-21 07:37 UTC, ecoble commented on src/cli/src/parser.c
> +    if(token != NULL)
Space after if

2021-05-21 07:37 UTC, ecoble commented on src/ui/src/print_functions.c
> +        //iteratively goes through each tokenized cmds
It would be better to make this a block comment with this style:
/*
 *
 */

2021-05-21 20:17 UTC, samdonio reviewed
Overall looks good, just have some small comments

2021-05-21 20:17 UTC, samdonio commented on src/cli/src/parser.c
> +        return NULL;
I'm a little confused on whats going on here, isn't save_ptr just a pointer to s, so setting s = *save_ptr the same as saying s = s? Also, why test if s == NULL in the else if, if s == NULL then this will never be run?

2021-05-21 20:17 UTC, samdonio commented on src/cli/src/parser.c
> +    while (strstr(s,delim) == s)
This is very minor but just for style this could be changed to strstr(s, delim)

2021-05-21 20:17 UTC, samdonio commented on src/cli/src/parser.c
> +    }
This may need to be looked at when/if case insensitivity gets implemented.

2021-05-22 01:42 UTC, Beza20 commented on src/cli/src/parser.c
> +    while (strstr(s,delim) == s)
well, the while loop needs to run only as long as strstr outputs s.

2021-05-22 01:43 UTC, Beza20 commented on src/cli/src/parser.c
> +    }
well when case sensitivity gets implemented the only thing might be that we would have no need for it but for now I believe it's fine.

2021-05-22 01:46 UTC, Beza20 commented on src/cli/src/parser.c
> +        return NULL;
we also wanted to check if this is an empty line. The helper function runs through an iteration the same way the built-in C function strtok_r does and is basically translated line by line and we have made sure it passes all tests.

2021-05-22 01:47 UTC, Beza20 commented on src/cli/src/parser.c
> +    while (strstr(s,delim) == s)
it's not enough that it is just not outputting NULL

2021-05-23 22:04 UTC, ecoble approved these changes
Great job!

2021-05-23 22:23 UTC, samdonio approved these changes
Good job working on a pretty major change!

2021-05-23 22:35 UTC, Beza20 commented
we have enabled a user to input multiple commands at once using a connecting word "and." This was done by using a helper function <strtokstr_r> that has very similar structure as the C built-in function <strtok_r.> It parses through a string and tokenizes a segment of that string whenever it finds the inputed delimiter of a string type. Then we use the helper function to read the cmd line and store the tokenized segment of the input into a utlist. Note: Each element in the utlist has to further be parsed breaking it up using a space. And then in the UI module, we made sure that all of the command segments put into the utlist are iteratively changed into a command struct by calling the <cmd_from_string> and executed. And with that this pull request has introduced the "and" feature to chiventure resolving issue #275.

2021-05-24 16:42 UTC, merged

2021-05-24 17:23 UTC, Beza20 commented
we have enabled a user to input multiple commands at once using a connecting word "and." This was done by using a helper function <strtokstr_r> that has very similar structure as the C built-in function <strtok_r.> It parses through a string and tokenizes a segment of that string whenever it finds the inputed delimiter of a string type. Then we use the helper function to read the cmd line and store the tokenized segment of the input into a utlist. Note: Each element in the utlist has to further be parsed breaking it up using a space. And then in the UI module, we made sure that all of the command segments put into the utlist are iteratively changed into a command struct by calling the <cmd_from_string> and executed. And with that this pull request has introduced the "and" feature to chiventure resolving issue #275.

2021-05-25 16:32 UTC, ecoble commented
Issue Score: ✔️++

Comments:
Amazing work on this issue! This was definitely a tricky issue, and a huge improvement to the parser! And your documentation on this PR is great too!

<!-- {"score": "check-plus-plus"} -->