Added a level type condition to limit player actions based on their current level
uchicago-cs/chiventure pull request #1051
Opened 2021-05-19 02:28 UTC by WPDolan

We have added a new `level_condition_t` condition type to the condition module as described in Issue #929. This new condition type seeks to limit actions based off of the `level` field in the player struct. Actions with level type conditions will only be able to be performed if the player's level meets or exceeds the given level requirement. The new level condition type lays out the groundwork for creating more conditionals to restrict actions based off of fields stored in the new player struct.

The main additions in the PR involve three new functions to handle level conditions
-  `level_condition_new` creates the new level type conditions. It takes an integer for the minimum level and a pointer to a player whose level will be checked.
- `check_level_condition` checks if the player's level meets the level requirement
- `valid_level_condition` ensures that the `level_condition_t` points to an existing player 

This PR also updates the switch statements in the `check_condition`, `valid_condition`, and `free_condition` functions to call the new level functions if given a level type condition. Future condition types based off of other fields in the player struct will also need to update these switch statements.

2021-05-19 02:56 UTC, jasulcaf commented on src/game-state/src/condition.c
> +}
I was confused here that I didn't see a return case for LOW_LEVEL so I was wondering how that Return value is possible. Is that something found in get_player? I do not believe that to be the case so some clarification here would be nice (I thought you where going to call check_level_condition() here as a return case).

2021-05-19 02:57 UTC, jasulcaf commented on tests/game-state/test_condition.c
> +    "correctly mark conditon as attribute");
I think you meant "condition" when fixing the spelling mistake

2021-05-19 02:57 UTC, jasulcaf commented on tests/game-state/test_condition.c
> +    "correctly mark conditon as inventory");
Here too ("condition" vs. "conditon")

2021-05-19 02:57 UTC, jasulcaf commented on tests/game-state/test_condition.c
>      cr_assert_eq(valid, PLAYER_NULL, "valid_condiiton() expected PLAYER_NULL(6) "
Function name should be `valid_condition()` but was spelled valid_condiiton()

2021-05-19 03:13 UTC, jasulcaf requested changes
Clarification on Header for `valid_level_condition` is required. Otherwise code looks good!

2021-05-19 04:36 UTC, WPDolan commented on src/game-state/src/condition.c
> +}
I had originally planned for `valid_level_condition` to return LOW_LEVEL if the player's level did not meet the level requirement. In my original design, I had accidentally planned for the functionality now found `check_level_condition` to be in `valid_level_condition`. I removed all cases where LOW_LEVEL was returned, but I forgot to remove mention of LOW_LEVEL in the function comment. The line referencing LOW_LEVEL has now been removed.

2021-05-19 04:38 UTC, jasulcaf approved these changes
Looks good now!

2021-05-19 23:13 UTC, MaxineK36 requested changes
I had a couple of questions about the changes, and one or two changes that should be addressed. Looks great overall though!

2021-05-19 23:13 UTC, MaxineK36 commented on src/game-state/src/condition.c
> +    level_condition_t *new_condition = malloc(sizeof(level_condition_t));
Is there a reason this is `malloc`'ed but `condition_wrapper` is `calloc`ed?

2021-05-19 23:13 UTC, MaxineK36 commented on src/game-state/src/condition.c
> +bool check_level_condition(level_condition_t *condition)
Since `get_level(condition->player_to_check) >= condition->level_required` is itself a boolean, you don't need to nest it in an `if` statement. Instead, this function can just be 
`return (get_level(condition->player_to_check) >= condition->level_required)`

2021-05-19 23:13 UTC, MaxineK36 commented on tests/game-state/test_condition.c
> +    cr_assert_eq(condition->condition_tag, ATTRIBUTE, "attribute_condition_new() failed to "
Thanks for fixing these typos!

2021-05-19 23:13 UTC, MaxineK36 commented on tests/game-state/test_condition.c
> +    // PLAYER_NULL
Why the documentation change here?

2021-05-20 00:22 UTC, WPDolan commented on tests/game-state/test_condition.c
> +    // PLAYER_NULL
This appeared to be an error from the old documentation. The following assert statement checks against PLAYER_NULL, not CONDITION_NULL.

2021-05-20 00:32 UTC, WPDolan commented on src/game-state/src/condition.c
> +    level_condition_t *new_condition = malloc(sizeof(level_condition_t));
I `calloc`ed the wrapper to keep the logic of the `level_condition_new` function in line with the existing `inventory_condition_new` and `attribute_condition_new` functions. The original justification for using `calloc` is not given in any documentation from the previous developers of `condition.c`.

2021-05-20 00:35 UTC, WPDolan commented on src/game-state/src/condition.c
> +bool check_level_condition(level_condition_t *condition)
Good catch! I have updated the function

2021-05-20 02:01 UTC, MaxineK36 approved these changes
Looks great!

2021-05-20 02:05 UTC, merged

2021-05-20 02:30 UTC, WPDolan commented
Closing statement:

Level type conditionals have been successfully merged into chiventure. Future issues will implement new condition types for fields in the player struct to further restrict when actions may be performed.

2021-05-22 20:22 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Excellent work! It would also be helpful if your closing statement provided a very short bulleted summary of what was merged.

<!-- {"score": "check-plus-plus"} -->