Playerclass/hashtable: Refactor class_t, and make it a hashtable.
uchicago-cs/chiventure pull request #1061
Opened 2021-05-19 21:03 UTC by jackcasey067

This is connected to issue #1042.  Originally, I was looking at how we would load classes into memory from WDL, and I noticed that there is nothing currently that holds every class declared by a game author.  Therefore, I decided to make a class hashtable, which stores every class in the game.

Since doing this would involve modifying the class_t struct itself (adding a hashtable handle `hh`), I decided use this as a moment to reconsider the fields in class_t.  This would need to be done before moving on to WDL class -> in-memory class conversion anyway, since doing that will involve specifying what JSON classes should look like.

The following changes were made (in broad strokes):
- I made class_t a hashtable by adding a UTHASH handle to the struct.
- I added functions for manipulating the hashtable, so that future users will not have to suffer through the somewhat confusing macros.
- I added tests for the new functions.
- I fused the noncombat and combat skill inventories into one `starting_skills` inventory.  I also did this in player_t.
- I renamed stats to base_stats, for clarity.  At one point, class_t contained a player's currently updated stats, but that is no longer the case.  In fact, all of the fields in class_t are meant to be static and unchanging under normal circumstances now (changing info exists in player_t, npc_t, and combatant_t).

2021-05-19 23:01 UTC, WPDolan approved these changes
I am reviewing this PR on behalf of the action management team, and am thus only looking at the changes that affect game-state modules. All of the changes that concern game-state (combining the skill inventory fields in the `player_t` struct in the player module) make sense and will reduce cognitive load when handling the player's skills. 

These changes will cause merge conflicts with [Pull Request 1011](url) because 1011 implements functions that depend on the old skill inventory fields. Fortunately, the merge conflict should only involve refactoring the player's skill inventory functions to consider the one combined inventory.

2021-05-21 01:49 UTC, jackcasey067 commented
I merged dev into this branch, and fixed the problems that @WPDolan warned about above.

2021-05-21 21:25 UTC, ideclue commented on include/playerclass/class.h
> +int add_or_replace_class(class_hash_t** hashtable, class_t* class);
I'm not sure if the language "add_or_replace" is the best choice here. I think "set" is typically used when it's assumed something will either be added or replaced.

2021-05-21 21:39 UTC, ideclue requested changes
I reviewed the portions of the code relevant to the `playerclass` module. Overall looks good, but I think the function design for a couple of the hash table functions (delete and add_or_replace) should be reviewed and maybe updated. Documentation looks great!

2021-05-21 21:39 UTC, ideclue commented on include/playerclass/class.h
> + *
Design question: Why is the free function not separated? It might be useful to have these operations separated for easier debugging. Also, if there is a scenario where we would like to use a class that is not in a hash table.
I would consider changing "delete" to two separated functions: "remove" and "free"

2021-05-21 21:39 UTC, ideclue commented on src/playerclass/src/class.c
> +    HASH_ADD_STR(*hashtable, name, class);
It's a little concerning that there's no check if this function, HASH_ADD_STR successfully adds the class. Would it be possible to return result code?

2021-05-21 21:39 UTC, ideclue commented on src/playerclass/src/class.c
> +        class_free(replaced_class);
Same issues as with "add_class": no result code returned

2021-05-21 21:39 UTC, ideclue commented on tests/playerclass/test_class.c
> +}
This test majes no reference to the "freeing" component of "delete." Hence why "freeing" and "removal" should be separated.

2021-05-21 21:56 UTC, jackcasey067 commented on include/playerclass/class.h
> +int add_or_replace_class(class_hash_t** hashtable, class_t* class);
I think I agree, this `set_class` is a better name.

2021-05-21 22:07 UTC, jackcasey067 commented on src/playerclass/src/class.c
> +    HASH_ADD_STR(*hashtable, name, class);
HASH_ADD_STR doesn't return anything, unfortunately, so I don't have access to whether or not it failed.

Also, I trust the macros a lot.  If they fail, it's our fault for putting the wrong input in, which is why I check and return FAILURE in advance.  

Good idea though; if HASH_ADD_STR did return an error code, it would be a good idea to pass that in our return.

2021-05-21 22:09 UTC, jackcasey067 commented on src/playerclass/src/class.c
> +        class_free(replaced_class);
Similarly, HASH_REPLACE_STR does not return an error code.  See above.

2021-05-21 22:23 UTC, jackcasey067 commented on include/playerclass/class.h
> + *
I am iffy on this one, and could go either way.  I think freeing the memory in a class is something we should do in the `delete` function, to pull down complexity just a little bit.  I don't think it is likely that someone in the future will want to remove a class from the hashtable and still use it.  I am more concerned about someone assuming a function called delete (or remove) frees a struct when it actually does not free it, causing insidious memory leaks.  What do you think?

2021-05-23 03:27 UTC, ideclue commented on include/playerclass/class.h
> + *
@firatciftci What do you think of this design question?

2021-05-23 03:28 UTC, ideclue approved these changes
I am approving the PR as it now reflects some of the design changes I suggested. However, I still believe it might be useful to separate the "freeing" and "removing" elements of the `delete` function.

2021-05-23 21:52 UTC, WPDolan approved these changes
The functions associated with the now removed `player_noncombat_skills` and `player_combat_skills` skill inventories have been successfully refactored to account for the new `player_skills` field. 

I have no issues with the way that the functions themselves were changed, and the changes made to the skill inventory tests stick to the original philosophies that the action-management team had when designing them.

2021-05-25 02:33 UTC, firatciftci commented on include/playerclass/class.h
> + *
I think this is fine as is – in terms of the use case of the function, I agree with @jackcasey067 that the expected use case will probably always be deleting the struct from the hash table and free'ing it at the same time. If a need for freeing the struct from memory separately arises in the future, the developers then can easily change this. For now, let's keep it as is.

2021-05-25 02:34 UTC, firatciftci approved these changes
Everything looks good to me, great work!

2021-05-25 02:35 UTC, merged

2021-05-25 02:37 UTC, jackcasey067 commented
Closing comment: After making a few suggested changes, and resolving a few clashes that occurred with another PR, this branch was merged into `dev`.  Classes are now hashable.

2021-06-02 23:20 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great work!

<!-- {"score": "check-plus-plus"} -->