Implement Do Custom Action - Running AST Action Blocks
uchicago-cs/chiventure pull request #1065
Opened 2021-05-20 16:53 UTC by LapsededPacifist

This pull request is the replacement of [PR 802](https://github.com/uchicago-cs/chiventure/pull/802).
It adds functions to evaluate conditional blocks, run AST_blocks (Which only is implemented for action blocks), and run custom actions. Tests were added to these functions in their respective test files.
Modifications were also made to the conditional_type enum, so that eval_conditional_block could distinguish between less and and greater than (and LTE/GTE).

2021-05-20 17:05 UTC, jasulcaf commented on src/custom-actions/include/interface.h
> + * - num_args: The number of arguments being passed in
There are 3 parameters specified but the function `do_custom_action()` only takes in one variable (the action)

2021-05-20 17:08 UTC, jasulcaf commented on src/custom-actions/src/ast_block.c
> +  if(block == NULL) return SUCCESS;
A bit of a nit pick but shouldn't the check, if block == NULL, be the first line since there is no need to declare int returnV if that doesn't pass? (Also, the return SUCCESS should be on a new line, not on the same line as the if statement).

2021-05-20 17:14 UTC, jasulcaf commented on src/custom-actions/src/ast_block.c
> +      return run_ast_block(block->next);
The if statement "return" should be indented (and in a new line for the case BRANCH). At first I thought this was calling two returns on every case but upon looking at it more, I realized it was just an if statement return.

2021-05-20 17:15 UTC, jasulcaf commented on src/custom-actions/src/conditional_block.c
> +
Extremely Nit-Picky but the extra line probably shouldn't be there since all the previous cases where one after another

2021-05-20 17:18 UTC, jasulcaf commented on src/custom-actions/src/interface.c
> +    */
I am guessing this is work that can be done in the future correct? My only comment here would be if this future work has been documented as "to do" in some other place (maybe in a summary or even as a open Issue).

2021-05-20 17:34 UTC, LapsededPacifist commented on src/custom-actions/src/interface.c
> +    */
This will be documented as to do soon. I just haven't quite gotten around to creating an issue for it. I will add documentation here when that issue is created as well as in the summary.
Related to this, I wasn't sure if I should drop this comment or not. This function will eventually be moved to a different file, and since branch_blocks are going to be totally redone, I don't think anything here will be helpful.

2021-05-20 17:34 UTC, jasulcaf commented on tests/custom-actions/test_interface_functions.c
> +}
I am a bit confused as to why there was the creation of all these blocks but there was no cr_assert_<> tests following. In simple words, I am confused as to what exactly this test is testing for.

2021-05-20 17:36 UTC, LapsededPacifist commented on tests/custom-actions/test_interface_functions.c
> +}
Currently it is testing nothing as branch blocks don't exist. This was a test written from the previous group, and I wasn't sure what to do with it. I probably should have just deleted it, but I had kind of thought that maybe it would be used again someday. 
I will just go back and delete it now.

2021-05-20 17:40 UTC, jasulcaf commented on tests/custom-actions/test_interface_functions.c
> +}
I see. In that case, either comment it out explaining what it could be used for in the future, or delete it seems like the best options. Either works fine.

2021-05-21 02:22 UTC, jasulcaf approved these changes
After changing the (minor) things I had pointed out, looks good now!

2021-05-21 20:49 UTC, MaxineK36 requested changes
A couple of small fixes/clarifications

2021-05-21 20:49 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +      returnV = do_branch_block(block->block->branch_block);
Conventionally, `returnV` should be `rc` for "return code"

2021-05-21 20:49 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +	return FAILURE;
nit: line 116 should be indented

2021-05-21 20:49 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +  if(block == NULL)
nit: spacing

2021-05-21 20:49 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +      return FAILURE;
why does conditional return failure?

2021-05-21 20:49 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    }
You should have a default case

2021-05-21 20:49 UTC, MaxineK36 commented on src/custom-actions/src/conditional_block.c
> +    return check_eq(block->left,block->right);
nit: spacing after comma (on all lines)

2021-05-21 23:09 UTC, LapsededPacifist commented on src/custom-actions/src/ast_block.c
> +      return FAILURE;
I added a brief comment about this, but basically it is just because it isn't executable. This function is meant to run a custom-action, and the conditional blocks just become a Boolean not an action.

2021-05-23 02:44 UTC, MaxineK36 reviewed
One last clarification

2021-05-23 02:44 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +      //To be implemented
What part is to-be-implemented? If nothing has been implemented for BRANCH yet, it might make sense for this to return failure

2021-05-24 06:26 UTC, LapsededPacifist commented on src/custom-actions/src/ast_block.c
> +      //To be implemented
Do_branch_block was what wasn't implemented. I had set it up, so that it would just skip over branch blocks. However, I updated it so that it would return failure for now probably makes more sense in the short term.

2021-05-24 15:05 UTC, MaxineK36 approved these changes
Looks great!

2021-05-24 15:37 UTC, merged

2021-05-24 16:02 UTC, LapsededPacifist commented
Functionality for running Custom-Actions with only action blocks has been merged.
Functions do_custom_action and run_ast_block were added for this function.  Currently, they fail when run with anything besides a list of AST_action_blocks. List functionality for making this list will be added in [issue 1069](https://github.com/uchicago-cs/chiventure/issues/1069) and the ability to branch will be added in [issue 1068](https://github.com/uchicago-cs/chiventure/issues/1068). 
To support the functionality of branch blocks, eval_conditional_block was added. It returns a boolean based off of comparing the attributes in the conditional with the specified operator. This currently has no implementation and required a slight restructuring of the conditional_type_t enum, so that there was a way to differentiate between less than and greater than when evaluating a conditional.  Required minor modifications to the tests in test_branch_block and test_conditional_block.

2021-05-31 04:16 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Excellent job taking over this existing branch and merging it to dev! You did a particularly good job linking the issues relating to future work in your closing statement.

<!-- {"score": "check-plus-plus"} -->