Integrating graphics with chiventure by displaying a single
uchicago-cs/chiventure pull request #1075
Opened 2021-05-21 18:32 UTC by grkapoor17

I worked mostly inside src/ui/src/gui.c trying to update

2021-05-22 08:49 UTC, xWngl requested changes
The code itself looks good, but when I was running the GUI, I noticed that closing the GUI using ctrl+d, although it successfully closed the window, resulted in a segfault. It doesn't appear to affect the running of the program at all, but something to take a look at.

2021-05-22 16:05 UTC, grkapoor17 commented
Following @xWngl 's comment about the segmentation fault, I revisited the code and realized that when the CloseWindow() function was called if ctrl+d is pressed, the code and the loop still runs, i.e, I didn't exit out of the code. Thus, I resolved this problem by exiting out after the CloseWindown() function is called in the conditional checking if the ctrl+d keys are pressed.

2021-05-22 16:11 UTC, xWngl approved these changes
Looks good!

2021-05-23 02:55 UTC, MaxineK36 requested changes
A couple of stylistic fixes, but the functionality looks great!

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/CMakeLists.txt
> +    message(WARNING "Won't build graphics examples because raylib could not be found")
Nit: this should now say something like "Won't build graphical interface because raylib could not be found"

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +    int ScreenWidth = 800;
These should be `#define`d constants

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +                // NOTE: Only allow keys in range [32..125]
Why only keys in this range?

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +        // Get pressed key (character) on the queue
nit: indent this comment, and it should be a block comment `/* ... */`

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +            // Check if more characters have been pressed on the same frame
Should also be a block comment

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +                // NOTE: Only allow keys in range [32..125]
Should also be a block comment

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +                if (letterCount < 0) letterCount = 0;
For readability, please make this mulitple lines

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +        if (mouseOnText) framesCounter++;
Should also be formatted as multiple lines

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +            // use the command to string function to turn name into a command
These should all be block comments

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +	    name[letterCount] = (char) 32;
nit: indentation

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +	BeginDrawing();
nit: indentation

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +        // Loading just one image is a temporary solution
Reminder about block comments

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +        int xbuf = 5;
Please add some comments explaining this last chunk of code (lines 133 - 151)

2021-05-23 02:55 UTC, MaxineK36 commented on src/ui/src/gui.c
> +    EndDrawing();
nit: indentation

2021-05-25 20:22 UTC, grkapoor17 commented
Following @MaxineK36 's comments and changes requested, I have added block comments to gui.c explaining what several parts of the code does. I also updated the CMakeLists error message that will load if the raylib library cannot be found. Moreover, I have defined constants in gui.h to remove magic numbers.

2021-05-25 20:25 UTC, MaxineK36 approved these changes
LGTM!

2021-05-25 20:39 UTC, merged

2021-05-25 21:12 UTC, borjasotomayor commented
Please note that this PR breaks the build in environments that don't have raylib installed (there was a recent post on #general about this). In particular, building the `ui` component _cannot_ depend on raylib being installed, since the UI component only uses a text-based interface that does not depend on Raylib.

2021-05-26 17:29 UTC, xWngl commented
Modified the chiventure CMake file, ui CMake file, and chiventure.c to only require raylib for run_gui() function. Chiventure can now be built and run without the raylib library, however if you attempt to run a chiventure game with the --gui flag without raylib, it will produce an error message

2021-05-26 19:37 UTC, borjasotomayor reviewed
The changes to chiventure.c and the CMake files look good to me! (I've also verified that the code builds and runs correctly in environments with and without raylib)

2021-05-26 19:44 UTC, MaxineK36 reviewed
The updates look great to me!

2021-05-27 17:59 UTC, grkapoor17 commented
In this pull request, we have successfully merged code from the gui/integrate_graphic into dev. This involved changes to gui.c, gui.h and the CMakeLists. Particularly, we have integrated a graphical interface with chiventure such that if you run a chiventure game with a --gui flag, a graphical split screen will be displayed with the upper half displaying a chiventure banner and the lower half comprises of an input and output text box. This was done using a run_gui() function. Moreover, the image that is displayed, "chiventure.png" was added to src/ui/src and updates also had to be made to the Chiventure CMakeLists as well as the ui CMakeLists. It must be noted that the code was merged twice. This is because there was initially an error that would not let the code compile unless the user had raylib installed and this was problematic as a user does not need raylib to run the normal ui interface. Thus, changes were made to chiventure.c as well as the CMakeLists to fix this issue.

2021-05-31 04:21 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Excellent work! You did a particularly good job providing a useful closing statement that explains some of the weird PR history. Going forward, you might also want to try using bullet points to make your summary a little easier to read (about 4-5 bullet points is usually equivalent to 1 paragraph for length purposes)

<!-- {"score": "check-plus-plus"} -->