Openworld: Convert room_generate() into a general purpose, single-room loading + connecting function
uchicago-cs/chiventure pull request #1077
Opened 2021-05-21 21:08 UTC by Justin08784

`room_generate()` was refactored into a general-purpose function for generating a single room around any given room in the game, and connecting the two rooms with paths. We did this by adding room_t *curr, char *dir_to_curr, char *dir_to_new params. We removed the gencontext_t *context param because it served no purpose (as of now).

Redundant code in recursive_generate() and multi_room_generate() was replaced with a call to room_generate().

room_generate() functionality for picking random directions was organized into a new helper called pick_random_dir(). Relevant tests were added.

- some very annoying bugs were fixed (details [here](https://github.com/uchicago-cs/chiventure/issues/1033#issuecomment-846226439))

2021-05-21 21:28 UTC, ahmed-sumaiya approved these changes
Looks good to me!

2021-05-21 21:43 UTC, MaxineK36 requested changes
A couple of notes; the biggest one is that `dir` is frequently used to abbreviate `directory`, and so to avoid confusion `direction` should be written out

2021-05-21 21:43 UTC, MaxineK36 commented on include/openworld/autogenerate.h
> +int pick_random_dir(room_t *curr, char *out_dir_to_curr, char *out_dir_to_new);
Since `dir` is so often shortened to `directory`, it would be helpful to call this `pick_random_direction` (and change all other abbreviations)

2021-05-21 21:43 UTC, MaxineK36 commented on include/openworld/autogenerate.h
> + * - gencontex_t *context: pointer to a gencontext. Not NULL.
By "Not NULL" do you mean it's guaranteed somehow not to be null, or expected not to be null? this should be specified

2021-05-21 21:43 UTC, MaxineK36 commented on include/openworld/autogenerate.h
> + * - dir_to_parent: direction to the parent pivot. Not NULL.
ditto here, and please change `dir`

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
>      char directions[4][6];
This `4` should be a defined constant, and then should be used as such later. e.g.
`int NUM_DIRECTIONS = 4` (or, at the beginning of the file, `#define NUM_DIRECTIONS 4`) and then you should use that constant throughout

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    unsigned int initial_dir = rand() % 4;
abbreviations

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    assert(SUCCESS == add_room_to_game(game, new_room)); // this step should never fail
why should it never fail?

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    if (add_path_to_room(curr, path_to_new)) // but this step can?
why?

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    /* should we not make it a responsibility of the caller
What did you determine here? These comments should be removed before merging.

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        char dir_to_curr[6], dir_to_new[6];
where is this 6 coming from?

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    if (add_path_to_room(curr, path_to_new)) // but this step can?
Also is that meant to be `if (add_path_to_room(curr, path_to_new) == SUCCESS)`?

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        if (rc == FAILURE)
You don't need an intermediate integer for this, since you only use it once.

2021-05-21 21:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
>      }
This function doesn't seem to appear in autogenerate.h

2021-05-21 22:19 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
>      }
The function is in autogenerate.h. idk

2021-05-21 22:36 UTC, Justin08784 commented
- Removed dir abbrevs
- Removed magic numbers; introduced constants MAX_DIRECTION_STRLEN, NUM_DIRECTIONS, NUM_COMPASS_DIRECTIONS
- Changed documentation "Not NULL." to "Should not be NULL."

2021-05-21 22:55 UTC, Justin08784 commented
- Replaced 'if' statements in room_generate() with asserts. Made it caller's responsibility to ensure parameter `direction_to_new` is an available direction; if it is not available, an assert will crash room_generate (since this also means that room_generate_failure test is not needed, it was deleted)
-

2021-05-21 22:56 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +    if (add_path_to_room(curr, path_to_new)) // but this step can?
swapped if statements these with asserts

2021-05-21 23:07 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +    assert(SUCCESS == add_room_to_game(game, new_room)); // this step should never fail
room_generate() needs to add a room to the game. If this fails, it should fail.

2021-05-21 23:07 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +    /* should we not make it a responsibility of the caller
I have decided to make it the caller's responsibility, comment has been removed.

2021-05-21 23:08 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +        char dir_to_curr[6], dir_to_new[6];
Defined constant NUM_DIRECTIONS 6

there are six default directions: the compass points + up + down

2021-05-21 23:09 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
>      char directions[4][6];
Defined constant NUM_COMPASS_DIRECTIONS 4 at the top of file

2021-05-21 23:11 UTC, Justin08784 commented on include/openworld/autogenerate.h
> + * - gencontex_t *context: pointer to a gencontext. Not NULL.
Should not be.

2021-05-22 15:51 UTC, MaxineK36 requested changes
One last nitpick, otherwise looks great!

2021-05-22 20:40 UTC, MaxineK36 approved these changes
Looks great!

2021-05-22 20:40 UTC, merged

2021-05-22 21:03 UTC, Justin08784 commented
Closing statement:
Comments by reviewers have been addressed and branch `openworld/refactor-room-generate` is now merged into dev. 

room_generate() was refactored into a general-purpose function for generating a single room around any given room in the game, and connecting the two rooms with paths. It is now called by both higher-level generation functions multi_room_generate() and recursive_generate().

room_generate()'s functionality for picking random directions was organized into a new helper called pick_random_direction(). Relevant tests were added to test_autogenerate.c.

Followups:
The dir abbreviation has been removed and several functions were changed. The source document may need to be updated.

2021-05-31 04:19 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Excellent work! Your summary, updates, and closing statement are all particularly detailed and well-written.

<!-- {"score": "check-plus-plus"} -->