Replace achievement linked lists with non-binary trees
uchicago-cs/chiventure pull request #1080
Opened 2021-05-23 02:07 UTC by gabigarc03

Refactored `quests_state.c`, `quests_state.h`, and `quests_structs.h` with a new `achievement_tree_t` type that replaces the old `achievement_llist_t` type as described in issue #957. Additionally, `test_quests_state.c` has been refactored to accommodate for the new type as described in issue #1078.

2021-05-25 02:03 UTC, ddelgado60 commented on src/quests/src/quests_state.c
> +    while(cur = get_bottom_node(cur)){
I'm a bit iffy on this line. Does C allow for variable assignment in a conditional statement? I believe there was another function that had this same line, too.

2021-05-25 02:05 UTC, ddelgado60 commented on src/quests/src/quests_state.c
> + * Helper function used to find the bottom node on the left side of a tree
Please put documentation in quests_state.h, and add a little /* Refer to quests_state.h */ in place of this.

2021-05-25 02:07 UTC, gabigarc03 commented on src/quests/src/quests_state.c
> + * Helper function used to find the bottom node on the left side of a tree
This function does not need to appear in `quests_state.h` because it is an internal helper function. Documentation within the C file in this instance should be fine.

2021-05-25 02:07 UTC, ddelgado60 commented on src/quests/src/quests_state.c
> + * Traverses the achievement tree to find the achievement with the
Documentation into quests_state.h

2021-05-25 02:09 UTC, ddelgado60 requested changes
Looks great so far, just a few small things to note and change and it should be good. There is some documentation floating around in here, so I advise for it to go into the header file for safe keeping. Also, I'm not sure about assigning a variable in a while loop conditional statement. If the code works and produces results, by all means keep it, but otherwise please let me know how it should work with it. Other than that, it looks great!

2021-05-25 02:10 UTC, ddelgado60 commented on src/quests/src/quests_state.c
> + * Helper function used to find the bottom node on the left side of a tree
Oh okay, gotcha.

2021-05-25 02:10 UTC, ddelgado60 commented on src/quests/src/quests_state.c
> + * Traverses the achievement tree to find the achievement with the
Resolved in above comment.

2021-05-27 05:00 UTC, zsp255 commented on src/quests/src/quests_state.c
> +    while(cur = get_bottom_node(cur)){
yes this is allowed because the loop will break when cur is set to null (i.e when it is the bottom node)

2021-05-27 05:34 UTC, gabigarc03 commented
Refactored the original monkeypatched example with achievement trees. Everything compiles now!! (AKA the Github check passes!!)

2021-05-27 19:28 UTC, ddelgado60 approved these changes

2021-05-30 03:17 UTC, lilyehsani requested changes
Great job overall! Added a few comments.

2021-05-30 04:06 UTC, gabigarc03 commented on src/quests/src/quests_state.c
> +achievement_tree_t *get_bottom_node(achievement_tree_t *t){
Just updated this in commit 286b593!

2021-05-30 04:06 UTC, gabigarc03 commented
Updated formatting to Allman for consistency.

2021-05-31 16:37 UTC, gabigarc03 commented
Updated `find_parent()` documentation.

2021-05-31 16:37 UTC, gabigarc03 commented on src/quests/src/quests_state.c
> +achievement_tree_t *find_parent(achievement_tree_t *tree, char *id) {
Added in commit defe6b8

2021-05-31 16:37 UTC, gabigarc03 commented on src/quests/src/quests_state.c
> +            return NULL; //error printing??
Added in commit defe6b8

2021-05-31 18:10 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-05-31 18:14 UTC, merged

2021-06-01 02:50 UTC, gabigarc03 commented
`quests_structs.h`, `quests_state.h`, `quests_state.c`, `test_quests_state.c`, and `quest-example.c` have all been refactored to use a new `achievement_tree_t` non-binary tree struct instead of the original `achievement_llist_t` linked list struct to allow for multiple quest paths.

2021-06-07 03:48 UTC, lilyehsani commented
Issue Score: ✔️+

Comments:
Great work overall! I have two comments:
- When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests.
- Make sure to assign new PRs to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")

<!-- {"score": "check-plus"} -->