Implement functions for Ast_block_t List Functionality
uchicago-cs/chiventure pull request #1081
Opened 2021-05-23 02:49 UTC by jasulcaf

(closes #1069)

This is connected to @LapsededPacifist and my Issue #1069 which set out to implement functions that allowed for list manipulation of AST_block_t structs. 

Overview of Implemented Changes:

- `list_contains_AST_block`: This function checks whether or not an AST_block_t is found in a linked list already or not.
- `list_add_AST_block`: This function adds an AST_block_t at a _specific_ place in the linked list (denoted by an integer that uses the same indexing as standard array indexing in C aka. 0 denotes adding as the new 1st element of linked list).
       - `append_list_AST_block`: Function for adding a new AST_block to the _end_ of a linked list
       - `prepend_list_AST_block`: Function for adding a new AST_block to the _start_ of a linked list
- `list_how_many_AST_block`: This function checks how long an AST_block_t linked list is
- `list_remove_AST_block`: This function removes a specific AST_bock_t from a linked list (if it is found).

Aside from adding this functionality, we also decided to get rid of the 'prev' field from AST_block_t struct. This was done because this is currently unused (and will remain like so) and so make the developer experience more intuitive.

2021-05-28 19:44 UTC, adishpan commented
Looks good to me.

2021-05-28 19:45 UTC, adishpan approved these changes
Looks good to me.

2021-05-28 19:48 UTC, adishpan approved these changes

2021-05-31 03:53 UTC, MaxineK36 requested changes
Made a couple of comments/asked clarification questions about your list operations; in general, you should be using the utlist macros, and not manually modifying `next`. Please also make sure that your search function behavior is what you intended.

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    if (AST1 == AST2)
This will only return 0 if the two inputs are literally the same pointer. Is this the intended behavior? Generally speaking, comparisons are only useful if they look for the programmer's definition of two structs being the same (e.g. containing the same values)

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +int list_how_many_AST_block(AST_block_t* head)
Use `LL_COUNT` instead of doing this by hand

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    if (tmp)
style: in chiventure overall we tend to use brackets regardless of if the `if` statement is more than one line or not; please maintain that convention (and at least remain consistent inside of a file)

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    if (tmp)
Also, for readability, do a comparison like `if (tmp != NULL)` even though what you have is valid

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    LL_SEARCH(head, tmp, compare, AST_cmp);
Based on how you've written your compare function, this will only return true if the block `compare` is literally in the list (and not if an equivalent block is there)

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +int list_add_AST_block(AST_block_t* head, AST_block_t* add, int num_to_place)
Why would you need to add AST_blocks at a specific location? This kind of manual rearranging somewhat interferes with the usefulness of using `utlist`
If you *do* determine that this is still needed, could you use `LL_INSERT_INORDER`?

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +/* See ast_block.h */
See above comment: could these two functions just use `LL_PREPEND` and `LL_APPEND`?

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    if (list_contains_AST_block(head, del) == false)
If `del` is the *pointer* that exists in the list and you're trying to remove, you can just use `LL_DELETE` directly. If not, this function will always return `FAILURE` due to your `cmp` function

2021-05-31 03:53 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +            /* Set 'next' pointer to NULL do avoid recursive freeing from AST_block_free */
This shouldn't be necessary

2021-05-31 03:53 UTC, MaxineK36 commented on tests/custom-actions/test_ast_block.c
> +
Test your append functions first, and then use those in these tests instead of linking manually

2021-05-31 03:53 UTC, MaxineK36 commented on tests/custom-actions/test_ast_block.c
> +    new_ast->next = second_ast;
Same note here (don't link manually)

2021-05-31 03:53 UTC, MaxineK36 commented on tests/custom-actions/test_ast_block.c
> +    ret_val = list_contains_AST_block(new_ast, second_ast);
Note that this only works because you passed in the same *pointer* you added to the list

2021-05-31 03:53 UTC, MaxineK36 commented on tests/custom-actions/test_ast_block.c
> +    first_ast->next = second_ast;
Again, please don't link manually

2021-05-31 04:05 UTC, LapsededPacifist commented on src/custom-actions/src/ast_block.c
> +    if (AST1 == AST2)
This was the intended behavior because there isn't a key to search by. The only thing to search is the pointer, and the goal was to make sure exact duplicates were not added to the list. If something was added to the list twice, all functionality would break because it would become a loop.
We were initially trying to search by something different, but unlike other structs there aren't any defining features of AST_blocks to search by,

2021-05-31 04:15 UTC, LapsededPacifist commented on src/custom-actions/src/ast_block.c
> +int list_add_AST_block(AST_block_t* head, AST_block_t* add, int num_to_place)
The reason you would need to add AST_blocks at a specific location would be because the order of actions in the list affects is the order that they are executed currently. The thought was that modifications to the custom action after it was created would need to be able to place new actions at specific points in the list.  I don't think that there are any plans for this kind of modification in the future, but it was something I thought would be likely to happen at some point.
I don't believe that LL_INSERT_INORDER could be used for this because (I think) it is just a compare function to put this in the correct location of the list. Our compare function, as pointed out earlier, wouldn't be very useful for this.

2021-05-31 04:22 UTC, LapsededPacifist commented on src/custom-actions/src/ast_block.c
> +    LL_SEARCH(head, tmp, compare, AST_cmp);
As mentioned before, this is intentional. The goal was to check if the that exact block was already in the list to avoid infinite loops.  In hindsight, the LL functions might have protections against that.

2021-05-31 04:45 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    LL_SEARCH(head, tmp, compare, AST_cmp);
In what situation do you imagine this coming up?

2021-05-31 04:46 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +int list_add_AST_block(AST_block_t* head, AST_block_t* add, int num_to_place)
Given that custom actions (like everything else) will be read from the game developer's wdl specification, how would you imagine this coming up?

2021-05-31 04:50 UTC, LapsededPacifist commented on src/custom-actions/src/ast_block.c
> +    LL_SEARCH(head, tmp, compare, AST_cmp);
Well, it came up when Jose and I were writing tests, but yeah it will probably never come up when actually running chiventure.

2021-05-31 04:59 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    LL_SEARCH(head, tmp, compare, AST_cmp);
Ah, got it. Given that this isn't an expected issue, I think it would be reasonable to simply include a note in the function headers for the `add` functions stating that the function assumes that the user won't add duplicates to the list (as this could result in infinite loops)

2021-05-31 05:00 UTC, LapsededPacifist commented on src/custom-actions/src/ast_block.c
> +int list_add_AST_block(AST_block_t* head, AST_block_t* add, int num_to_place)
They could specify changes to an existing actions at some trigger point. However, this could also be done by simply creating a new custom action at that point and removing the old one. 
I don't think there is anything in the near (or really distant) future, so yeah it might make more sense to remove this if it interferes with utlist.

2021-05-31 20:05 UTC, jasulcaf commented on src/custom-actions/src/ast_block.c
> +            /* Set 'next' pointer to NULL do avoid recursive freeing from AST_block_free */
LL_DELETE doesn't bother to change the pointers. So imagine if we have A->B->C and we LL_DELETE B. Then all that will do is set A->C, but we haven't changed the pointer to B yet. If we don't set next pointer to NULL then we get double free() errors.

2021-06-01 17:29 UTC, MaxineK36 requested changes
A few more fixes to work better with utlist

2021-06-01 17:29 UTC, MaxineK36 commented on src/custom-actions/include/ast_block.h
>   */
It may be helpful to make this into two functions -- one that frees a single block, and one that frees a block and all the other blocks in the list.

2021-06-01 17:29 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +        switch(ast->block_type)
This switch statement would go in the normal free function

2021-06-01 17:29 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
>      if (ast->next != NULL)
This would go in the list free function, and would also call LL_DELETE

2021-06-01 17:29 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    int ret_val;
style: call this `count` or something similar but more descriptive than `ret_val`

2021-06-01 17:29 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    del->next = NULL;
If the changes are made to the `free` functions as suggested above, this becomes unnecessary

2021-06-01 18:14 UTC, jasulcaf commented on src/custom-actions/include/ast_block.h
>   */
That seems like a good abstraction idea, will implement this as `AST_free` freeing the resources for _one_ block, and `AST_block_free` will free _all_ blocks

2021-06-01 18:16 UTC, jasulcaf commented on src/custom-actions/src/ast_block.c
> +    int ret_val;
This probably slipped by when we were busy writing tests, changed variable name to `count`!

2021-06-01 18:16 UTC, jasulcaf commented on src/custom-actions/src/ast_block.c
> +    del->next = NULL;
Yes. This was no longer necessary with the abstraction of free functions

2021-06-01 21:07 UTC, MaxineK36 requested changes
2 tiny changes!

2021-06-01 21:07 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +    del->next = NULL;
Please now go ahead and remove this line

2021-06-01 21:07 UTC, MaxineK36 commented on src/custom-actions/src/ast_block.c
> +	    AST_free(elt);
nit: line 107 seems over-indented

2021-06-01 21:19 UTC, MaxineK36 approved these changes
Looks great!

2021-06-01 22:27 UTC, merged

2021-06-01 22:32 UTC, jasulcaf commented
As a summary:

This Pull Request provides list functionality to exist for the AST_block_t struct. Through the process of the Pull Request Reviews however, we decided to eliminate some of the functions we were planning to add. As such, the functions that _have_ been added are the following:

- `append_list_AST_block` : Function for adding a new AST_block to the end of a linked list
- `prepend_list_AST_block` : Function for adding a new AST_block to the start of a linked list
- `list_how_many_AST_block` : Function that checks how long an AST_block_t linked list is
- `list_remove_AST_block` : Function to remove a specific AST_block_t from a linked list (if it is found). Note, this function _does_ free the removed AST_block_t

To be explicit on what functions didn’t go through (and why):

- `list_contains_AST_block:` At this moment in time we don’t have a specific way of identifying an AST_block_t so this function wouldn’t be too useful (would just be checking if a specific pointer is in the list)
- `list_add_AST_block:` The functionality of being able to specify in what spot of the linked list a new AST_block_t should be added to isn’t required as of this Pull Request. If in the future the order of AST_blocks does play an integral role in Chiventure, then there will be a case for adding this function again

Also, through the review phase, we decided to abstract the way that `AST_block_free` functioned. Before, we could only free the _entire_ list of blocks. However, we have added `AST_free` which will only free a _singular_ block. This abstraction helps utilize LL functions and helps with making code cleaner. `AST_block_free` functionality was not changed (still frees the _entire_ list)

2021-06-03 16:30 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Excellent work! Your opening and closing summaries are particularly well-written and makes it easy for readers to understand the intent and outcome of this PR. 

<!-- {"score": "check-plus-plus"} -->