Added the ability to load NPCs from WDL files
uchicago-cs/chiventure pull request #1083
Opened 2021-05-23 18:25 UTC by jeyeong

In preparation for our demo, I added a module called `load_npc` into the WDL directory, which allows us to add NPCs into the game from WDL files. Changes were made to the `load_game` and `validate` modules to enable `load_npc` to work.

NPCs should be specified in WDL files in this manner:
<img width="177" alt="Untitled" src="https://user-images.githubusercontent.com/7861185/119272109-08c75080-bbca-11eb-89f2-97a8f0abb081.png">

An example of loading NPCs into the game can be found in src/npc/example/connected-rooms-npc.wdl. This can be run with the following command from the `build` directory: ./chiventure ../src/npc/examples/connected-rooms-npc.wdl

2021-05-25 02:50 UTC, jeyeong commented
I would like to put this pull request on pause for now.

Given the merging of conditional dialogue + actions into the game today, I would like to make some changes to the load_npc module.

2021-05-27 11:46 UTC, jeyeong commented on src/game-state/src/item.c
> -            item_free(current_item);             /* free it */
Since items now belong to two hash tables, namely, game->all_items and player->inventory (for example), the freeing process is as follows:
1. Items are removed from the player->inventory, npc->inventory, room->items hash tables, but **not freed**.
2. Items are then removed from the game->all_items hash table, and freed at the same time.

2021-05-27 12:32 UTC, jeyeong commented
I've completed the implementation. The summary above has been updated.

2021-05-27 20:52 UTC, pkasner requested changes
Most of my comments shouldn't require changes for this PR, and overall this looks really good. I think it is best to wait for the talk_operation PR to be merged, so that the commented code relying on second hashtable support can be implemented.

2021-05-27 20:52 UTC, pkasner commented on src/game-state/src/item.c
> +int add_item_to_all_items_hash(item_hash_t **all_items, item_t *item)
Is there a reason that this takes an item_hash_t** and not just an item_hash_t*? Or is that just a carryover from previous implementations of similar functions? Just wondering if you figured out why that was

2021-05-27 20:52 UTC, pkasner commented on src/game-state/src/item.c
> -            item_free(current_item);             /* free it */
If the delete_all_items() function is only removing all items from the hash table without freeing them, I believe the HASH_CLEAR macro could be used to simplify that function significantly.

2021-05-27 20:52 UTC, pkasner commented on src/npc/src/dialogue.c
> +                npc_t *npc = get_npc_in_room(game->curr_room,
You say that this would be better if using the get_npc function, but I think using get_npc_in_room makes perfect sense here. In conversation mode, the mode_ctx is necessarily assigned to an npc in the current room via the talk_operation, so the two functions will act equivalently here.

2021-05-27 20:52 UTC, pkasner commented on src/npc/src/dialogue.c
> +                npc = get_npc_in_room(game->curr_room, game->mode->mode_ctx);
Again, I think using get_npc_in_room seems totally fine here.

2021-05-27 20:52 UTC, pkasner commented on src/npc/src/dialogue.c
> +        cur_edge->availability = EDGE_DISABLED;
This temporary solution makes a lot of sense to prevent node actions from being taken multiple times. Because currently if node actions fails, for example because the item the NPC was supposed to give is no longer in their inventory, the run_conversation_step function gives a return code of -1, which will cause a crash via assertion. Perhaps a more graceful solution would involve some manner of specifying if an action failed without treating that case as a full blown error, but for now I agree that this solution is sufficient to prevent those action failures.

2021-05-27 20:52 UTC, pkasner commented on src/wdl/src/load_game.c
> +    set_curr_player(game, p);
Why was this added? I believe this is done in chiventure_ctx_init().

2021-05-27 20:52 UTC, pkasner commented on src/wdl/src/load_npc.c
> +        // add_npc_to_game(g, npc);
Perhaps it is best to wait until the talk_operation can be merged first (which allows npcs to be stored in a second hash table) before this PR. That way all the commented out code can be cleaned up.

2021-05-27 21:40 UTC, jeyeong commented on src/game-state/src/item.c
> -            item_free(current_item);             /* free it */
I saw that you used that in your implementation of multiple hash handles for NPCs, and it was brilliant! In the case of items, however, I don't think we can use HASH_CLEAR, because items are implemented to also be linked lists (to accommodate multiple items with same ID), so there is a more complex hash deletion process.

2021-05-27 21:42 UTC, jeyeong commented on src/game-state/src/item.c
> +int add_item_to_all_items_hash(item_hash_t **all_items, item_t *item)
The function, for some reason, doesn't seem to work properly if we pass an item_hash_t*. I tried using item_hash_t* at first, but I encountered issues adding the item to the hash table correctly. After changing it to item_hash_t**, it worked fine. I have no idea why that is.

2021-05-27 21:46 UTC, jeyeong commented on src/wdl/src/load_npc.c
> +        // add_npc_to_game(g, npc);
Agreed

2021-05-27 21:54 UTC, jeyeong commented on src/wdl/src/load_game.c
> +    set_curr_player(game, p);
Oh is it? I did not realize that. That actually is a problem, though. In order for conditions (`inventory_condition_new()`) to be created, they require the player to be passed as a parameter. But since `chiventure_ctx_init()` happens after the condition creation process, that will be a problem.

2021-05-28 02:13 UTC, pkasner commented on src/game-state/src/item.c
> -            item_free(current_item);             /* free it */
Correct me if I'm wrong, but as I understand it, the reason it's more complicated is because if you delete the head, then you need to add the next element of the list to the hash table. And if you delete an item that's not the head, you just splice it out of the list. And if it's just one element you delete it normally. It seems to me then that you could still use HASH_CLEAR, and the only difference is that the items would remain "linked" together, and we still delete all the buckets. I don't think this interferes with their freeing via delete_all_items_from_game because that function still does go through and free each element in every linked list.

2021-05-28 05:05 UTC, lilyehsani requested changes
Great job overall! Added a few comments. I also did not see anything about loading NPC struct fields like class, movement, or battle (which makes sense as these are new or complex additions). However, it might be good to add some comments about how we would like to support loading these fields in the future.

2021-05-28 13:19 UTC, jeyeong commented on src/game-state/src/item.c
> -            item_free(current_item);             /* free it */
You know what, you're right. It actually makes perfect sense to use HASH_CLEAR. I've updated the code to use it.

2021-05-28 13:21 UTC, jeyeong commented on src/game-state/src/item.c
> +int add_item_to_all_items_hash(item_hash_t **all_items, item_t *item)
Somehow, the item wasn't being added to the hash table. I'm guessing that's the reason why the previous years' team decided to use item_hash_t ** too

2021-05-28 13:29 UTC, jeyeong commented on include/game-state/game.h
> +#include "npc/npc.h"
Done

2021-05-28 13:32 UTC, jeyeong commented on include/wdl/load_condition.h
> +#include <stdio.h>
Done

2021-05-28 13:32 UTC, jeyeong commented on include/wdl/load_npc.h
> +#include <stdio.h>
Done

2021-05-28 13:32 UTC, jeyeong commented on src/game-state/src/game.c
> +        item_t* iter = current_item;
Done

2021-05-28 13:44 UTC, jeyeong commented on include/wdl/load_npc.h
> + * - adds NPCs into the inputted game pointer (currently not possible) and
Revised

2021-05-28 14:22 UTC, jeyeong commented on src/wdl/src/load_game.c
> +    set_curr_player(game, p);
So conditions (and by extension conditional dialogue) cannot be created unless a player struct has been initialized. Thus, in order for us to develop conditional dialogue, we require the player struct to be created prior to dialogue loading. Right now, however, the player struct is created after the game has been loaded, since in `chiventure.c`, `chiventure_ctx_new` is called after `load_game`.

I imagine this would result in issues for other teams too. For example, if we want to assign default classes to players, or if we want to create conditions for quests, we would need the player struct to be initialized first.

A simple solution to this would simply be to move these lines of code:
```
player_t *player1 = player_new("player1");
add_player_to_game(game, player1);
set_curr_player(game, player1);
```
from chiventure_ctx_init (in ctx.c) to game_new (in game.c). Since every call to chiventure_ctx_new (in all the game demos) is preceded by game_new, this should not result in any previous code being broken. It would, however, allow us (and future teams) to work with conditions in Chiventure.

2021-05-28 14:32 UTC, jeyeong commented on src/wdl/src/load_game.c
> +    set_curr_player(game, p);
I've just tested it out, and the Chiventure (together with the demos) compiles fine with the change. Furthermore, conditional dialogue works great. If this is okay with you, I'll make the change.

2021-05-28 16:27 UTC, jeyeong commented on src/wdl/src/load_game.c
> +    set_curr_player(game, p);
To clarify, I will also remove the three lines above (20-22)

2021-05-29 04:04 UTC, jeyeong commented on src/wdl/src/load_game.c
> +    set_curr_player(game, p);
Hey Lily, I've gone ahead and made the change so that we can start working on our game demo tomorrow! If this is not ideal for any reason, please let me know, and I will change it back to what it previously was.

2021-05-29 04:30 UTC, pkasner approved these changes
This LGTM! There was a small section in test_dialogue.c that hadn't been updated for npcs in two hash tables, so I went in fixed that.

2021-05-30 01:18 UTC, jeyeong commented
I edited the HELP command to include "talk to" as a possible command

2021-05-30 01:33 UTC, lilyehsani requested changes
Great changes! Just a few more, especially now that talk operation has been merged.

2021-05-30 01:33 UTC, lilyehsani commented on src/wdl/src/load_game.c
> +    set_curr_player(game, p);
I think this is fine.

2021-05-30 01:33 UTC, lilyehsani commented on src/npc/src/dialogue.c
> +                npc_t *npc = get_npc_in_room(game->curr_room,
I agree with Peter, so you should probably delete this in-code comment and the following one.

2021-05-30 01:33 UTC, lilyehsani commented on src/wdl/src/load_npc.c
> +        // add_npc_to_game(g, npc);
Talk operation has been merged, so you are now able to make these changes.

2021-05-30 13:14 UTC, jeyeong commented on src/wdl/src/load_npc.c
> +        // add_npc_to_game(g, npc);
Done!

2021-05-30 13:14 UTC, jeyeong commented on src/npc/src/dialogue.c
> +                npc_t *npc = get_npc_in_room(game->curr_room,
Done!

2021-05-31 18:16 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-05-31 18:49 UTC, merged

2021-06-02 15:05 UTC, jeyeong commented
**Summary of changes made:**

- Introduced the ability to load NPCs from WDL files. The format for this is specified in images above.
- Modified the items struct, and associated functions, such that items can now belong to two hash tables. Practically, the first hash table an item will belong to is `game->items`, and the second `player->inventory`, etc.

**Next steps:**

- Design our team's game demo.

2021-06-07 03:01 UTC, lilyehsani commented
Issue Score: ✔️++

Comments:
Great work overall! The summary and closing of this PR are very thorough.

<!-- {"score": "check-plus-plus"} -->