Openworld Documentation
uchicago-cs/chiventure pull request #1087
Opened 2021-05-23 21:23 UTC by ahmed-sumaiya

Created a .md file for the openworld module for the chiventure/docs directory which contains:
- A brief description of the openworld module
- A list of wiki pages that include the system and product documentations of the openworld module
- A list of directories of the openworld module with a short description of each file's functionality

Since a feature wishlist [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Open-World-~-Feature-Wishlist) already existed, we created a new [issue](https://github.com/uchicago-cs/chiventure/issues/1085) to update the wiki page with changes made to the openworld module this year and a list of potential new features to be implemented for next year.

2021-05-23 21:58 UTC, Justin08784 requested changes
Looks good, a few nits to resolve

2021-05-23 21:58 UTC, Justin08784 commented on docs/openworld.md
> +- [autogenerate.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/autogenerate.h) - Gathers room specifications from the default's, generates the room, and then puts it directly
Just realized 'puts it directly into chiventure' could sound a little misleading because openworld is not fully integrated yet–– it still relies on monkey patching. Revise.

2021-05-23 21:58 UTC, Justin08784 commented on docs/openworld.md
> +The goal of the openworld module is to implement a feature that allows automatic generation of rooms in chiventure.
Not just generation of rooms, but also items (and hopefully buildings and map structures). Revise to map/world generation.

2021-05-23 22:59 UTC, Justin08784 approved these changes
Looks good!

2021-05-24 09:18 UTC, wmingyan approved these changes
Looks good to me!

2021-05-24 15:39 UTC, MaxineK36 requested changes
A few typos but otherwise looks good!

2021-05-24 15:39 UTC, MaxineK36 commented on docs/openworld.md
> +- [autogenerate.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/autogenerate.h) - Gathers room specifications from the default's and generates the room
nit: *defaults

2021-05-24 15:39 UTC, MaxineK36 commented on docs/openworld.md
> +- [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/gen_structs.h) - Provides the structs that make generation work smoothly
are there few enough structs to list them here?

2021-05-24 15:39 UTC, MaxineK36 commented on docs/openworld.md
> +- ./src
This should be `src/`

2021-05-24 16:36 UTC, ahmed-sumaiya commented on docs/openworld.md
> +- [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/gen_structs.h) - Provides the structs that make generation work smoothly
By "structs", do you mean the function headers? There's quite a lot all four files combined. Should I just list them or do I also have to provide a description for each?

2021-05-24 17:36 UTC, MaxineK36 commented on docs/openworld.md
> +- [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/gen_structs.h) - Provides the structs that make generation work smoothly
Nope, I was specifically referring to the structs in `gen-structs.h`. Right now, you say that `gen_structs.h` "Provides the structs that make generation work smoothly" but don't specify what any of those structs are

2021-05-24 19:28 UTC, MaxineK36 requested changes

2021-05-24 19:28 UTC, MaxineK36 commented on docs/openworld.md
> +    - roomspec_t struct - Carries the necessary info for creating a room
I think these struct headers are useful to include here, but you don't need the full definitions, since that makes it pretty long

2021-05-24 19:36 UTC, ahmed-sumaiya commented on docs/openworld.md
> +    - roomspec_t struct - Carries the necessary info for creating a room
Do you mean I should only leave the names of the structs and a short description but not the whole struct itself?

So basically, instead of writing:
- roomspec_t struct - Carries the necessary info for creating a room
    typedef struct roomspec {
        char *room_name;
        char *short_desc;
        char *long_desc;
        int num_built;
        item_hash_t *items;
        UT_hash_handle hh;
    } roomspec_t;

I would just write:
- roomspec_t struct - Carries the necessary info for creating a room

2021-05-24 20:08 UTC, MaxineK36 commented on docs/openworld.md
> +    - roomspec_t struct - Carries the necessary info for creating a room
Yep, exactly

2021-05-24 21:51 UTC, MaxineK36 approved these changes
LGTM!

2021-05-24 21:55 UTC, merged

2021-05-24 22:45 UTC, ahmed-sumaiya commented
Closing statement:
Comments by reviewers have been addressed and branch openworld/doc is now merged into dev. openworld.md is now available on chiventure/docs.

2021-05-31 04:18 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! You did a particularly good job detailing where the changes can be found in your closing statement. In the future, you can also try improving readability by using markdown to distinguish directory names (e.g. `chiventure/docs`, which is just the text wrapped in `'s)

<!-- {"score": "check-plus-plus"} -->