remade get_random_default_weapon() to decrement enemy's hp, strength, or defense
uchicago-cs/chiventure pull request #1089
Opened 2021-05-24 01:32 UTC by sonnykaiyuenlee

updated battle_logic to ensure the functions are fed the correct combatant (player or enemy) depending on whether the item is a consumable or a weapon. Also completely changed get_random_default_weapon() in battle_default_objects to have negative values which streamlined the process of consuming/using the default objects module/weapons in general.

2021-05-24 21:16 UTC, lczielinski requested changes
Looks good overall, I think the biggest change is that you need to change the function calls to use_battle_item() in battle_command_example.c to match the new ones, and I made a few other comments too. Very creative weapon names and I can't wait for this to be integrated in the example!

2021-05-24 21:16 UTC, lczielinski commented on include/battle/battle_logic.h
> +int use_battle_item(combatant_t *c, battle_t *battle, int id);
This change needs to be updated in battle_command_example.c when this function is called

2021-05-24 21:16 UTC, lczielinski commented on src/battle/src/battle_default_objects.c
> +    int attack_array[] = {-30, -20, 0, 0, 0, 0};
Shouldn't the attack_array correspond to the 3rd and 4th weapons? If so, would it look more like: {0, 0, -5, -10, 0, 0}

2021-05-24 21:16 UTC, lczielinski commented on src/battle/src/battle_default_objects.c
> +    //set effectiveness_decrement?
I think set this to a default 10 for now?

2021-05-24 21:16 UTC, lczielinski commented on src/battle/src/battle_default_objects.c
> +    char* name_array[]= {"SWORD", "HAMMER", "SLIME", "SLEEPING GAS", "SQUID INK", "LAUGHING GAS"};
This is only if you have time, but maybe change the names of the items to just have the first letter capitalized to match the others

2021-05-28 20:44 UTC, lczielinski approved these changes
Looks really great!!

2021-05-31 06:49 UTC, firatciftci requested changes
I've requested some minor stylistic fixes.

2021-05-31 06:49 UTC, firatciftci commented on include/battle/battle_default_objects.h
> + * Parameters: nonest
This should probably be reverted back to `none`.

2021-05-31 06:49 UTC, firatciftci commented on src/battle/src/battle_logic.c
> +    if(item->is_weapon)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-31 06:49 UTC, firatciftci commented on src/battle/src/battle_logic.c
> +    }else
Make sure to leave a blank space between `}` and `else` on this line.

2021-05-31 06:49 UTC, firatciftci commented on tests/battle/test_battle_logic.c
> +    //battle->turn = NULL;
You should get rid of any unused commented out code.

2021-05-31 06:49 UTC, firatciftci commented on tests/battle/test_battle_logic.c
> +
No need to have two extra blank lines here.

2021-05-31 06:49 UTC, firatciftci commented on tests/battle/test_battle_logic.c
> +    //battle_t *battle = set_battle(p, NULL, NULL);
You should get rid of any unused commented out code.

2021-06-02 01:42 UTC, firatciftci approved these changes
Everything looks good to me!

2021-06-02 01:44 UTC, merged

2021-06-06 20:29 UTC, firatciftci commented
Issue Score: ✔️+

Comments:
Good work overall! I only have one thing to comment on:
- When an PR is done, you should include a final comment summarizing what was merged to `dev` and what work remains to be done, if any.

<!-- {"score": "check-plus"} -->