New npc_battle functions
uchicago-cs/chiventure pull request #1090
Opened 2021-05-24 03:56 UTC by amymorrill

After creating the npc_battle struct and its basic functions (new/init/free) in a previous pull request, I now have implemented more functions relating to npc_battle. Hopefully, these functions will help other developers who want to use the npc_battle field in the npc struct. 

Here are a list of the changes in this pull request:
- Created a check_npc_battle() function which takes an npc and returns true if its will_fight and npc_battle fields are compatible
- Created a get_npc_battle() function which takes an npc and returns a pointer to its npc_battle struct or NULL if that npc doesn't have an npc_battle struct
- Moved the get_npc_health() function to be under the get_npc_battle function because health is in npc_battle now, so this order makes sense
- Created an add_battle_to_npc() function which takes an npc and the parameters of an npc_battle struct and adds an npc_battle struct with those parameters to the npc
- Moved change_npc_health() to be under add_battle_to_npc() because health is in npc_battle now, so this order makes sense

2021-05-24 16:05 UTC, northofsophia requested changes
Everything looks good except for line 205 in change_npc_health() where the if statement should be changed to an else if. Other than that, the functions look clean.

2021-05-24 16:05 UTC, northofsophia commented on src/npc/src/npc.c
> +    if ((npc->npc_battle->health + change) < max)
This line should be an else if instead of an if or else the previous if statement "if ((npc->npc_battle->health + change) < 0)" will get overwritten.

2021-05-24 17:36 UTC, amymorrill commented on src/npc/src/npc.c
> +    if ((npc->npc_battle->health + change) < max)
Whoops, good catch, I'll change that!

2021-05-24 18:49 UTC, northofsophia approved these changes
All the functions look good.

2021-05-25 17:35 UTC, lilyehsani requested changes
Great job! Added a few comments.

2021-05-25 17:35 UTC, lilyehsani commented on include/npc/npc.h
I know we talked about moving these to npc_battle.h, but I actually think they make the most sense here.

2021-05-25 17:35 UTC, lilyehsani commented on src/npc/src/npc.c
> +    if (npc->npc_battle == NULL) {
Be consistent with placement of curly braces. You mostly use Allman style, see: https://uchicago-cs.github.io/dev-guide/style_guide_c.html.

2021-05-25 17:35 UTC, lilyehsani commented on src/npc/src/npc.c
> +    if (npc->will_fight == true && npc->npc_battle == NULL) {
Be consistent with placement of curly braces. You mostly use Allman style, see: https://uchicago-cs.github.io/dev-guide/style_guide_c.html.

2021-05-25 20:55 UTC, amymorrill commented on include/npc/npc.h
Okay, I'll leave them as is.

2021-05-25 23:49 UTC, lilyehsani approved these changes
Looks great! Approved.

2021-05-25 23:49 UTC, merged

2021-05-26 04:12 UTC, amymorrill commented
Closing statement: This pull request has now been merged, with no major changes other than those described in its opening statement. The next step will be to write tests for each of these new functions, as described in #1026.

2021-06-07 03:04 UTC, lilyehsani commented
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- The title of a PR has to convey what the PR will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the issue (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.)
<!-- {"score": "check-plus"} -->