Quests/add all quests hash
uchicago-cs/chiventure pull request #1092
Opened 2021-05-24 15:41 UTC by dillonoloughlin

Added an all_quests hash table to the game struct in game.h and added a get_quest() and add_quest_to_game() functions to game.c and game.h as described in the issue #1052.

2021-05-30 19:26 UTC, dillonoloughlin commented
Created a more generalized version of add_quest called add_quest_to_hash in quests_state.c, which takes in a quest_t and a quest_hash_t as parameters. This function allows the user to specify the hash table they would like to add a quest to, so the function can be used to add quests to either the all_quests hash in the game or the current quests hash in the player. I then updated the game.c add_quest_to_game to call add_quest_to_hash with the all_quests hash table as the parameter. I also created a get_quest_from_hash function that takes in a char * quest id, and a hash table. This allows for the user to pull from either the player quest hash table or the game quest hash table. I then updated the get_quest in game.c to call the get_quest_from_hash function.

2021-05-31 23:59 UTC, ddelgado60 commented on src/game-state/src/game.c
> +#include "quests/quests_structs.h"
Might be redundant since quests/quests_state.h includes quests/quests_structs.h

2021-06-01 00:01 UTC, ddelgado60 commented on include/quests/quests_structs.h
> +/* Forward declaration */
Could you explain why this is necessary?

2021-06-01 00:05 UTC, ddelgado60 commented on src/quests/src/quests_state.c
> +    sprintf(buffer, "%ld", quest->quest_id); //need to convert quest_ids to char *
Good for now, but in the future the id could hopefully be changed to char *

2021-06-01 00:09 UTC, ddelgado60 commented on src/game-state/CMakeLists.txt
> +target_link_libraries(game-state quests)
Almost integrated!

2021-06-01 00:14 UTC, ddelgado60 requested changes
Nice work on making a quests hash table! Really great that you are nearly there in integrating quests as a working part of chiventure. I don't think that this will be able to make the final presentation for the sake of time, but I think this is great work. I left a few comments inline, since there was a redundancy or two and I had a question or two on a few parts. I'm not sure if you have written any tests up yet for this, so those may have to be written before this can be merged. Also, quests/implement-trees will most likely be pushed to dev first, so there may be merge conflicts there to address once that happens. I think I will keep this at "request changes" until I can hear back from you.

2021-06-01 16:45 UTC, dillonoloughlin commented on include/quests/quests_structs.h
> +/* Forward declaration */
I was getting an error of "unknown type npc_t" due to circular dependency in chiventure and Lily gave me this as the solution

2021-06-02 01:01 UTC, ddelgado60 approved these changes

2021-06-02 21:12 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-06-02 21:12 UTC, merged

2021-06-07 03:07 UTC, lilyehsani commented
Issue Score: ✔️

Comments:
Great work overall! I have two comments:
- The title of a PR has to convey what the PR will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the PR (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.)
- Like issues, PRs require closing comments. When an PR is done, you should include a final comment summarizing what was merged to `dev` and what work remains to be done, if any.

<!-- {"score": "check"} -->