Implement Variables in the DSL
uchicago-cs/chiventure pull request #1095
Opened 2021-05-24 20:14 UTC by jacknugent1529

Variables are implemented as a pre-parsing addition to the language, so they are evaluated before the language itself is parsed. The exact specifications are described in issue #998, but the basic features are the following
- multi-line variables declared with triple quotes (e.g. `$var = """<content>"""`
- escaped-string variables declared with single quotes (e.g. `$var = "This will evaluate to a string surrounded by quotes")
- Support for template strings similar to python f-strings

The main files added in this pull request are `vars_parser.py` and `vars.lark` which evaluate the  variables in the dsl file. Additionally, there is an example file using variables in several different manners, and the `vars_test.py` file for testing purposes. This will close issue #998.

2021-05-26 13:21 UTC, john-hahn reviewed
The changes made to the files all pertain to the goal of implementing variables in the DSL. First off, the `src/dsl/src/vars.lark` file which sets the rules for the variables, nicely and efficiently denotes what is recognized as triple quotes, escaped strings, key values. `src/dsl/src/vars_parser.py` takes the variables and manipulates it using the functions defined. They essentially make the tree more readable, and Jack has done a nice job with the coding of these functions. Lastly, there is a file for testing the variables out. The `src/dsl/src/dsl_parser.py` file has minimal change, which is the inclusion of the `evalVars` library.

Overall, all these changes are necessary for the implementation of variables, and there isn't any problem I see with the code.

2021-05-26 15:30 UTC, john-hahn approved these changes

2021-05-26 19:34 UTC, ecoble requested changes
This looks great! Just a few small things.

2021-05-26 19:34 UTC, ecoble commented on src/dsl/examples/vars.dsl
> +  intro: $intro {firstname: John, lastname: "Smith"}
Is it intentional that Smith is in quotations and John is not? If so, it might be good to leave a note pointing out that you are showing the flexibility of DSL

2021-05-26 19:34 UTC, ecoble commented on src/dsl/src/vars.lark
> +// ?start: assignment
This comment looks like it should be removed, or turned into prose

2021-05-26 19:34 UTC, ecoble commented on src/dsl/src/vars_test.py
> +# simple script to test the functionality of the evalVars function
This and any other tests file should go in their own tests directory, for now I think you can just nest the tests directory within your src directory, I will check about whether you should put it in the main tests directory since you are using python.

2021-05-26 22:36 UTC, jacknugent1529 commented on src/dsl/examples/vars.dsl
> +  intro: $intro {firstname: John, lastname: "Smith"}
Yes, it is intentional. The quotes are only necessary if escape characters are included. I included a comment to that effect, and it will be mentioned in the documentation.

2021-05-26 22:36 UTC, jacknugent1529 commented on src/dsl/src/vars.lark
> +// ?start: assignment
Yeah, it was not necessary, so I removed it

2021-05-26 22:43 UTC, jacknugent1529 commented on src/dsl/src/vars_test.py
> +# simple script to test the functionality of the evalVars function
This script only printed out the file after the variables had been replaced by the appropriate strings. Since it wasn't a true test file, I instead included the functionality in the `dsl_parser.py` file with the `--debug` flag.

2021-05-27 23:11 UTC, ecoble approved these changes

2021-05-27 23:15 UTC, merged

2021-05-27 23:30 UTC, jacknugent1529 commented
Closing statement: We added support for variables in the dsl. This was implemented as a pre-parsing transformation that replaces references to variables with the variables itself. The main features involve escaped string variables, multi-line variables, and template strings similar to python f-strings. Since opening the pull request, we simplified debugging functionality to use the `--debug` flag with the `dsl_parser.py` instead of needing another script. Since these changes have been successfully merged, this closes issue #998.

2021-06-07 20:39 UTC, ecoble commented
Issue Score: ✔️++

Comments:
Great work adding variables to the DSL, and documenting progress on this PR!

<!-- {"score": "check-plus-plus"} -->