Implement new quest functions, tests, and data structures
uchicago-cs/chiventure pull request #1096
Opened 2021-05-24 21:48 UTC by ddelgado60

This branch is an extension off of quests/implement-trees to preserve work done in that branch, and also implement new tests, functions, and data structures for passive/active quests, stats requirements, and reward types. There is an existing pull request for implement new quest structs, but it seems more strategic to branch off of quests/implement-trees, since work done there was necessary for work done in this branch.

2021-06-02 06:08 UTC, gabigarc03 requested changes
Overall - this looks good! Just left a bunch of minor comments because I'm pedantic.

2021-06-02 06:08 UTC, gabigarc03 commented on tests/quests/test_quests_state.c
> +    stat_req_t *stat_req = create_sample_stat_req();
Do these two functions (`create_sample_rewards()` and `create_sample_stat_req()`) necessarily need to be functions? Alternatively, there might be a benefit to allowing them to take input to make them more flexible and usable for more extensive testing.

2021-06-02 06:08 UTC, gabigarc03 commented on tests/quests/test_quests_state.c
> +                                100, class);
Make sure you're initializing these npcs properly

2021-06-02 06:08 UTC, gabigarc03 commented on tests/quests/test_quests_state.c
> +                                       100, class);
Make sure you're initializing these npcs properly

2021-06-02 06:08 UTC, gabigarc03 commented on tests/quests/test_quests_state.c
> +    int res = add_achievement_to_quest(quest, achievement_to_free, "NULL");
Why is this called `achievement_to_free` when the function being tested is `add_achievement_to_quest`?

2021-06-02 06:08 UTC, gabigarc03 commented on tests/quests/test_quests_state.c
> +	achievement_t* achievement_to_free = achievement_new(mission, id);
Why is this called `achievement_to_free` when it's in a function to test `complete_achievement`?

2021-06-02 18:30 UTC, gabigarc03 approved these changes

2021-06-02 18:30 UTC, gabigarc03 commented
These changes look good!

2021-06-03 01:00 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-06-03 01:00 UTC, merged

2021-06-07 03:42 UTC, lilyehsani commented
Issue Score: ✔️

Comments:
Great work overall! I have a few comments:
- Like issues, PRs require closing comments. When an PR is done, you should include a final comment summarizing what was merged to `dev` and what work remains to be done, if any.
- Make sure to add anyone who is working on this PR as an Assignee
- Make sure to assign new PRs to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")

<!-- {"score": "check"} -->