Restructing of branch_block_t and implementation of do_branch_block
uchicago-cs/chiventure pull request #1102
Opened 2021-05-25 22:12 UTC by LapsededPacifist

Restructures branch blocks to the format seen on the [wiki](https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-~-Current-State-and-Future-Plan-of-Custom-Actions).
Restructures all the related functions and their corresponding tests.
- Resulted in the deletion of 3 quarters of the existing tests as they were not relevant (Testing for all the different enum values)
Added do_branch_block to branch_block.c/.h
- Executes a branch block for if and while loops
- - For loops are executed the same way as while loops. Creating a separate issue for easier creation of for loops.
Added do_branch_block to the implementation of run_ast_block, so that ast_blocks can now run branch_blocks.

2021-05-25 22:16 UTC, jasulcaf commented on src/custom-actions/include/branch_block.h
> + * - Integer of if the block being run was successful
Usually I have seen in the rest of the Chiventure code that people are explicit on the return value. Usually something like the following: "SUCCESS if success, FAILURE if error". I think it'd be good to maintain this trend to make sure that the style of the code is consistent.

2021-05-25 22:17 UTC, jasulcaf commented on src/custom-actions/src/ast_block.c
> +        if (do_branch_block(block->block->branch_block) == FAILURE)
Nit: Indentation of if() seems odd (as if it has 2 extra spaces).

2021-05-25 22:22 UTC, jasulcaf commented on src/custom-actions/src/branch_block.c
> +        return SUCCESS;
I had a question about the decision of returning SUCCESS if block == NULL. This seems like it can give the impression that a branch_block was successfully ran when in fact perhaps nothing happened. Below you return FAILURE for when it's not a valid branch (if either num_conditionals or num_actions <= 0), so I was wondering about how you made the decision to make this return SUCCESS instead of FAILURE if we pass in a NULL branch_block_t

2021-05-25 22:24 UTC, jasulcaf commented on src/custom-actions/src/branch_block.c
> +            }
Nit: The indentation of the closing "}" for the for() loop seems to have an extra space

2021-05-25 22:25 UTC, jasulcaf commented on src/custom-actions/src/branch_block.c
> +	       */
Nit: This could be just a single line comment instead of 3

2021-05-25 22:41 UTC, jasulcaf requested changes
Aside from Nits about spacing, there is one question that I had about `do_branch_block` and the decision to return SUCCESS if block == NULL. Aside from this, looks good and great job on the tests, especially on collapsing some of the tests.

2021-05-25 22:45 UTC, LapsededPacifist commented on src/custom-actions/src/branch_block.c
> +            }
I changed it. It looked fine in emacs, but I deleted the spacing and readded it.

2021-05-25 23:06 UTC, jasulcaf approved these changes
Spacing was corrected and comment about `do_branch_block` was resolved by changing the return to FAILURE if passed in a NULL pointer, so looks good!

2021-05-26 14:18 UTC, MaxineK36 requested changes
Looks good overall! A couple of places could use some clarification

2021-05-26 14:18 UTC, MaxineK36 commented on src/custom-actions/src/branch_block.c
> +                if (eval_conditional_block(block->conditionals[i]) == 0)
Can you add a comment explaining what's happening here?

2021-05-26 14:18 UTC, MaxineK36 commented on src/custom-actions/src/branch_block.c
> +            if (block->num_actions > block->num_conditionals)
Here as well please

2021-05-26 14:18 UTC, MaxineK36 commented on src/custom-actions/src/branch_block.c
> +	      // If the condition to end the loop is different than starting the loop
This should be a block comment (`/* ... */`)

2021-05-26 14:18 UTC, MaxineK36 commented on src/custom-actions/src/branch_block.c
> +	        //No detection or protection for infinite looping
Should also be a block comment

2021-05-28 02:06 UTC, MaxineK36 reviewed
Why is 0 true? In C, generally true is 1 and false is 0; it would be helpful to maintain this convention in the control blocks unless there's a particular design reason for doing otherwise.

2021-05-28 02:31 UTC, LapsededPacifist commented
> Why is 0 true? In C, generally true is 1 and false is 0; it would be helpful to maintain this convention in the control blocks unless there's a particular design reason for doing otherwise.

This is actually a larger problem with custom actions that we just uncovered. TRUE is defined as 0 and FALSE is defined in 1 across all of custom actions.
I believe that the reason for this is match with strcmp, so that it can be used for the list search functions.
This is a significant problem because CLI currently defines TRUE as 1 and FALSE as 0, which means that there are definition conflicts when trying to make custom-actions with the rest of chiventure.

2021-05-28 04:09 UTC, MaxineK36 approved these changes
Looks good!

2021-05-28 04:20 UTC, merged

2021-05-31 04:14 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! Your closing statement is particularly well-written, especially as it explains an unanticipated change that resulted from this PR (changing the macro T/F values).

<!-- {"score": "check-plus-plus"} -->