Openworld: Introduce itemspec_t struct (with associated helpers and tests) and implement probability-based item generation
uchicago-cs/chiventure pull request #1106
Opened 2021-05-26 09:02 UTC by Justin08784

- Introduced `itemspec_t` struct, which allows game authors to –– per `roomspec_t` –– customize item occurrence probability and possible quantity ranges for the item. Relevant tests for helpers–– new, init, and free–– have been added to test_structs.c
The hope is to be able to generate a more diverse and exciting map. 
- Created a new function, generate_items(), which generates the items for each roomspec based on its itemspecs. If an item does not have a corresponding itemspec, the function resorts to the default behavior of spawning with probability 1 (guaranteed spawn) and quantity 1. Relevant tests have been added to test_autogenerate.c
- roomspec_to_room() now calls generate_items() instead of random_items(), which just picked a random subset of items from the roomspec.
- Refactored copy_item_to_hash() so that it can add duplicate items to the same room–– see last year's [item-stacking implementation](https://github.com/uchicago-cs/chiventure/issues/703)

2021-05-26 13:18 UTC, ahmed-sumaiya requested changes

2021-05-26 14:40 UTC, ahmed-sumaiya approved these changes
Looks good to me!

2021-05-28 02:11 UTC, MaxineK36 reviewed
A couple of clarification questions, but looks good overall!

2021-05-28 02:11 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        double spawn_chance = 1;
is there a reason these are given initial default values of 1?

2021-05-28 02:11 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        int num_quantities = max_num - min_num + 1;
what's the logic behind this calculation?

2021-05-28 02:11 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        bool should_spawn = ((double) rand()) / RAND_MAX <= spawn_chance;
why is this separated as a bool instead of placed directly in the if?

2021-05-28 02:11 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    item_hash_t *rv = NULL;
Why is this called `rv`?

2021-05-28 02:24 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +        double spawn_chance = 1;
To mimic the behavior of random_items (the previous function that was called by roomspec_to_room).

random_items spawns 1 instance of each item specified in the roomspec item hash. However, the behavior is slightly different in that random_items() picks a random subset of the item hash, while generate_items iterates through the item hash in a consistent manner.

2021-05-28 02:28 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +        int num_quantities = max_num - min_num + 1;
min_num and max_num prescribes the interval of possible quantities in which the item can spawn. To compute the number of quantities (we need this for calculating the probability of each quantity), we do max - min + 1.

e.g. [2, 4] has three possible values of 2, 3, and 4. This is computed by 4 - 2 + 1 .
Since we decided each quantity is equally likely to occur, the probability is 1/3 = 0.33...

2021-05-28 02:28 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +        bool should_spawn = ((double) rand()) / RAND_MAX <= spawn_chance;
I thought it might look less cluttered.

2021-05-28 02:29 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +    item_hash_t *rv = NULL;
rv for return value

2021-05-28 03:25 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        double spawn_chance = 1;
Ok, makes sense. Please note this in a comment in this section of code.

2021-05-28 03:26 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        int num_quantities = max_num - min_num + 1;
Ok, got it. Please add comments next to `min_num` and `max_num` clarifying that these refer to possible quantities the item can spawn.

2021-05-28 03:26 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        bool should_spawn = ((double) rand()) / RAND_MAX <= spawn_chance;
In this case, I think it'll be more readable in the `if`; declaring a separate bool value usually indicates that it'll be used elsewhere

2021-05-28 03:27 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    item_hash_t *rv = NULL;
Can you name it something more descriptive?

2021-05-31 03:57 UTC, MaxineK36 requested changes
Just a few stylistic fixes!

2021-05-31 03:57 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        double spawn_chance = 1;
Thanks for adding the comment! For stylistic consistency, please put the block comment *before* the relevant section of code (instead of indicating with "^^")

2021-05-31 03:57 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        int num_quantities = max_num - min_num + 1;
Same note here—comment looks great, but please move it up

2021-05-31 03:57 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        if (((double) rand()) / RAND_MAX <= spawn_chance) {
Please add parens around `((double) rand()) / RAND_MAX`

2021-05-31 19:54 UTC, MaxineK36 approved these changes
LGTM!

2021-05-31 20:01 UTC, merged

2021-06-01 00:32 UTC, Justin08784 commented
Closing statement:
Comments by reviewers have been addressed and branch `openworld/add-itemspec` is now merged into dev.

_Summary:_
Additions
- Added itemspec_t struct for specification of occurrence probability and quantity ranges for an item in a specific roomspec. 
- Created new function, generate_items(), for itemspec-based item generation.

_Changes_  
- roomspec_to_room() calls generate_items() instead of random_items(), which just picked a random subset from the roomspec item hash.
- Refactored copy_item_to_hash() so that it can add duplicate items to the same room using item stacking

2021-06-03 16:32 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Awesome work! Your closing statement is particularly clear and well-written.

<!-- {"score": "check-plus-plus"} -->