Implemented the new cli context struct
uchicago-cs/chiventure pull request #1108
Opened 2021-05-26 21:06 UTC by dchen0258

Goal: Currently the command_history is set to be in the chiventure_ctx struct, however, if more cli specific features are to be added, it makes sense to create a new cli_ctx struct to contain this information. The command_history and lookup table should both be placed in this new struct, and any future cli specific information.

Changes: Big changes were new ctx header and c file for the cli_ctx struct. The rest of the changes was a lot of refactoring of code.

2021-05-27 23:03 UTC, ecoble requested changes
Great work! A few small changes.

2021-05-27 23:03 UTC, ecoble commented on src/cli/src/cli_ctx.c
> +    free(cli_ctx);
You'll probably need to iteratively free each element in the command_history here, something like this (taken from the utlist docs, so you will use LL instead of DL): 

DL_FOREACH_SAFE(head,elt,tmp) {
      DL_DELETE(head,elt);
      free(elt);
}

2021-05-27 23:03 UTC, ecoble commented on src/common/src/ctx.c
> +    ctx->cli_ctx = cli_ctx_new();
This should be moved into the init function, where the initialization of the table the command_history list used to be.

2021-05-27 23:38 UTC, borjasotomayor approved these changes
The changes to the non-CLI code look good to me!

2021-05-28 00:25 UTC, mjgoodman321 approved these changes
Looks solid to me!

2021-05-28 06:24 UTC, ecoble approved these changes

2021-05-28 22:20 UTC, merged

2021-05-29 00:00 UTC, dchen0258 commented
Closing statement:
This struct was aimed at making it easier for future cli specific components to be added, so hopefully future classes will find some cool enhancements!

2021-06-07 20:34 UTC, ecoble commented
Issue Score: ✔️++

Comments:
Great job making the new context struct! I think this will definitely help future teams as well as they expand the CLI.

<!-- {"score": "check-plus-plus"} -->