Skilltrees/effect_v2
uchicago-cs/chiventure pull request #1110
Opened 2021-05-27 01:04 UTC by rohangupta2806

This pull request has the implementation for v2 of effects.  This involves implementing player statistic modifying effects and item attribute modifying effects.  Another atomic effect type: item statistic modifying effect, has been added but not implemented.  battle effects were changed to move_unlock and were partially implemented.  Additionally, tests for player statistic modifying effects, item attribute modifying effects, and move effects were added.  Build issues with rpg-battles was solved by changing includes on a number of files- this was carried out by @jackcasey067 from rpg-playerclasses.

2021-05-27 02:43 UTC, rohangupta2806 commented
We had to add a couple of lines to action management code (forward declarations and includes) to allow the code to build properly.  As a result, I've also added William Dolan from action management as a reviewer

2021-05-27 02:47 UTC, Joshuashou commented on include/skilltrees/skill.h
Hmm shouldn't this function return a string? Right now skill_execute is still of type int?

2021-05-27 02:51 UTC, rohangupta2806 commented on include/skilltrees/skill.h
Ah I think in the merge some lines got changed that I missed.  I'm gonna go and fix the comment.  We should still return an int though.

2021-05-27 02:53 UTC, rohangupta2806 commented on include/skilltrees/skill.h
Fixed this issue

2021-05-27 02:53 UTC, Joshuashou approved these changes

2021-05-27 02:53 UTC, Joshuashou commented on include/skilltrees/skilltree.h
> + *  - prereqlevel: an out-parameter, the prerequisite level to level the skill
Didn't we take out these out-parameters in earlier changes?

2021-05-27 02:53 UTC, Joshuashou commented on include/skilltrees/skilltree.h
> + * Returns all prerequisites for a given skill.
I think this should be changed back to prequisite skills

2021-05-27 02:53 UTC, Joshuashou commented on include/skilltrees/skill.h
>  int skill_execute(skill_t* skill, chiventure_ctx_t* ctx);
Shouldn't this function be changed to return a string?

2021-05-27 03:04 UTC, rohangupta2806 commented on include/skilltrees/skilltree.h
> + *  - prereqlevel: an out-parameter, the prerequisite level to level the skill
I just pulled from dev and I still see them, not sure what's up.  I can change this pretty easily if required.

2021-05-27 03:05 UTC, rohangupta2806 commented on include/skilltrees/skilltree.h
> + * Returns all prerequisites for a given skill.
Done.  Don't know how that even happened.

2021-05-27 03:11 UTC, rohangupta2806 commented on include/skilltrees/skill.h
>  int skill_execute(skill_t* skill, chiventure_ctx_t* ctx);
The comment is wrong and has been changed.  We should return an int.

2021-05-27 05:47 UTC, ideclue reviewed
Great job! I left a few comments where I felt clarity/consistency could be improved for future developers.

2021-05-27 05:47 UTC, ideclue commented on include/skilltrees/effect.h
> +//Defines an effect that unlocks a move
This is a small stylistic concern, but try to keep commenting style consistent. `/* */` is generally used for single-line comments, whereas `//` is more for inline comments. In this section of code, you use `//` for both, but below, you switch to  `/* */`.

2021-05-27 05:47 UTC, ideclue commented on include/skilltrees/effect.h
> +     * the rpg-battles team */
Make sure comments like these are clarified for future developer users/not specific to your current team.

2021-05-27 05:47 UTC, ideclue commented on include/skilltrees/effect.h
> +}item_att_effect_t;
I would suggest renaming this to`item_attr_effect_t`. Throughout the rest of the code base, attributes are typically referred to with `attr` rather than `att`, and this would help keep things consistent.

2021-05-27 05:47 UTC, ideclue commented on include/skilltrees/effect.h
> +    //TODO (2022)
Again, make sure this comment is clear for future developer users.

2021-05-27 05:47 UTC, ideclue commented on include/skilltrees/effect.h
> +item_att_effect_t* define_item_att_effect(item_t* item, char* att_id, enum attribute_tag att_tag, attribute_value_t attribute_mod);
Similar to above, I would suggest referring to attribute with `attr` consistently, rather than `att`.

2021-05-27 05:47 UTC, ideclue commented on include/skilltrees/skilltrees_enums.h
> +    INNER_PEACE = 1003,
Make sure to elaborate further on these examples in your documentation and/or code. Right now, it is a little unclear what they refer to here.

2021-05-27 05:47 UTC, ideclue commented on src/skilltrees/src/skill.c
> +    effect_t* skill_effect = skill->skill_effect;
This code could be improved by providing an error message explaining what the error it to the future developer/user, something like `Skill provided was NULL`, rather than just an `assert` statement.

2021-05-27 05:47 UTC, ideclue commented on src/skilltrees/src/skill.c
> +        assert(check==0);
Similar to the comment for lines 75-77, include an error message when `check == 0` in each of these scenarios. This could be really helpful for debugging.

2021-05-27 05:47 UTC, ideclue commented on src/skilltrees/src/effect.c
> +    assert(new_stat_effect->stats != NULL);
Include error message for all of these `assert` statements.

2021-05-27 05:47 UTC, ideclue commented on src/skilltrees/src/effect.c
> +// See effect.h
Since these are single-line comments, they should all be of the form:
`/* See effect.h */`

2021-05-27 05:47 UTC, ideclue commented on src/skilltrees/src/effect.c
> +    effect_t* new_att_effect = (effect_t*)malloc(sizeof(effect_t));
You should always check the return value of `malloc` to make sure it's not null and include an error message when this does occur (as well as after your `assert` statements).

2021-05-27 05:47 UTC, ideclue commented on tests/skilltrees/effect_test.c
> +    /*Checking if everything works*/
Unclear what code this comment is referring to due to the spacing here.

2021-05-27 05:47 UTC, ideclue commented on tests/skilltrees/effect_test.c
> +}
Spacing out some of these longer tests and providing more comments between would really help improve the clarity of the code.

2021-05-27 16:49 UTC, rohangupta2806 commented
I've unassigned @WPDolan and assigned @jasulcaf from action management instead after speaking to their team.

2021-05-27 16:53 UTC, jasulcaf commented on include/skilltrees/effect.h
> +}item_att_effect_t;
I also agree with @ideclue, attributes are referred to with `attr` instead of `att` (see chiventure/include/game-state/item.h line 242 and below)

2021-05-27 16:54 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +     * the rpg-battles team */
Yep, gonna update the wiki page with these changes.

2021-05-27 17:03 UTC, jasulcaf reviewed
As for the forward declarations and includes, there doesn't appear to be any Issues on action management side. Something that I will note is that I agree with what @ideclue mentioned in two of her comments: one being the calling off `attr` instead of `att`; and the second being the more general comment that when writing tests and having various asserts, adding lines to separate out the blocks is _extremely_ helpful in increasing readability

2021-05-27 17:09 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +}item_att_effect_t;
Yep, done this.

2021-05-27 17:10 UTC, rohangupta2806 commented on src/skilltrees/src/effect.c
> +    assert(new_stat_effect->stats != NULL);
Yeah, I've done this by switching to if

2021-05-27 17:11 UTC, rohangupta2806 commented on src/skilltrees/src/effect.c
> +// See effect.h
Done this

2021-05-27 17:17 UTC, rohangupta2806 commented on src/skilltrees/src/effect.c
> +    effect_t* new_att_effect = (effect_t*)malloc(sizeof(effect_t));
Yep, added a check for this

2021-05-27 17:37 UTC, jasulcaf approved these changes
Looks good! The comments I had pointed out have been properly addressed (changing of `att` to `attr,` and more readability incorporated in tests)

2021-05-27 18:04 UTC, ideclue commented
The suggestions I made (changing assert statements, `malloc` return values, and some comment styles) have been implemented, so I think the code is ready to be merged.

2021-05-27 18:05 UTC, ideclue approved these changes

2021-05-27 18:33 UTC, m-ghosal approved these changes
Looks good to me!

2021-05-27 21:27 UTC, firatciftci requested changes
I've requested many changes that are all stylistic issues. Other than that everything looks good!

2021-05-27 21:27 UTC, firatciftci commented on include/game-state/player.h
> +typedef struct skill skill_t;
There should be a blank line after this one to separate the two distinct struct declarations.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +
No need to have a blank line here.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +
No need to have a blank line here.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +}effect_type_t;
Make sure to place a blank space character between `}` and the struct name.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +}player_stat_effect_t;
Make sure to place a blank space character between `}` and the struct name.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +    int* durations;    // The array of durations for how long the effect should be applied
These comments should be block comments (i.e. `/* ... */`) like you have for the `effect_type_t` struct above.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +     * the rpg-battles team */
@rohangupta2806 Minor stylistic issue: A multi-line comment should follow the following style:
```c
/* text
 * text
 */
```

(i.e. the last `*/` should be o a separate line)

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +    move_t* move;      // Specifies the move that will be unlocked
This comment should be a block comment (i.e. `/* ... */`) like you have for the `effect_type_t` struct above.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +}move_effect_t;
Make sure to place a blank space character between `}` and the struct name.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +    attribute_value_t attribute_mod; //The value to which we want to change the attribute
These comments should be block comments (i.e. `/* ... */`) like you have for the `effect_type_t` struct above.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +
No need to have a blank line here.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +}item_attr_effect_t;
Make sure to place a blank space character between `}` and the struct name.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +
No need to have a blank line here.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +// typedef struct stat stat_t;
Make sure to remove any leftover commented out code.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +}item_stat_effect_t;
Make sure to place a blank space character between `}` and the struct name.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +    //TODO (2022)
I think you should either add a more clarifying comment, or even comment out the whole struct and place a clarifying comment on this possible feature expansion for future developers on top of the commented out code block. Up to you.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +    effect_type_t effect_type; // Contains the value of the effect.  Check enum above
This comment should be a block comment (i.e. `/* ... */`) like you have for the `effect_type_t` struct above.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/effect.h
> +}effect_t;
Make sure to place a blank space character between `}` and the struct name.

2021-05-27 21:27 UTC, firatciftci commented on include/skilltrees/skilltrees_enums.h
> +
No need to have a blank line here.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(ctx == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(new_stat_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(new_stat_effect->stats == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    for(int i = 0; i < num_stats; i++)
Make sure to leave a blank space between `for` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    item_attr_effect -> attribute_mod.int_val = attribute_mod.int_val;
These if statements should have their inner statements indented one block rightward and also should be all surrounded by curly brackets.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(player_stat_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(new_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(move_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(new_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(item_attr_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(new_attr_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(et == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/effect.c
> +    if(pointer_to_et == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/skill.c
> +    if(skill == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/skill.c
> +    if(skill -> skill_effect == NULL)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on src/skilltrees/src/skill.c
> +    if(type == PLAYER_STATISTIC_MOD)
Make sure to leave a blank space between `if` and `(` on this line.

2021-05-27 21:27 UTC, firatciftci commented on tests/skilltrees/effect_test.c
> +chiventure_ctx_t* create_player_and_stats (){
Make sure to leave a blank space between `)` and `{` at the end of this line. Also, there should not be a blank space character between the function name and `()`.

2021-05-27 21:27 UTC, firatciftci commented on tests/skilltrees/main.c
> -
I'm not sure why this blank line was removed, but there should be a blank line between the include statements and the main function call.

2021-05-28 06:35 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +// typedef struct stat stat_t;
Done.

2021-05-28 06:36 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +
Done

2021-05-28 06:36 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +
Done

2021-05-28 06:37 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +}effect_type_t;
Done

2021-05-28 06:42 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +    move_t* move;      // Specifies the move that will be unlocked
Done

2021-05-28 06:44 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +    attribute_value_t attribute_mod; //The value to which we want to change the attribute
Done

2021-05-28 06:47 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +    //TODO (2022)
Done

2021-05-28 06:54 UTC, rohangupta2806 commented on src/skilltrees/src/effect.c
> +    item_attr_effect -> attribute_mod.int_val = attribute_mod.int_val;
Done

2021-05-28 06:58 UTC, rohangupta2806 commented on tests/skilltrees/main.c
> -
Think it happened by mistake.  Added it back.

2021-06-02 01:43 UTC, firatciftci approved these changes
Everything looks good to me!

2021-06-02 04:34 UTC, merged

2021-06-04 20:33 UTC, rohangupta2806 commented
Closing comment:  This branch was merged and player statistic modifications and item attribute modifications can now be used by invoking the define_player_stat_effect, define_item_attr_effect, make_player_stat_effect, make_item_attr_effect, and execute_skill functions.  Damage effects were renamed to move_unlocks and have been partially implemented.

In the future, the next year's team will probably need to work on finishing the implementation of move_unlock and implementing item statistic modifying effects.  Additionally, all effects will need a free function to be made for them, to remove them from memory, as we forgot to implement those.  We will make issues for these by tomorrow.  Documentation must also be updated.

2021-06-06 20:41 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great work!

<!-- {"score": "check-plus-plus"} -->