Implemented the Playerclass section of the Player Interface Plan with functionality for deep copying skill inventories
uchicago-cs/chiventure pull request #1123
Opened 2021-05-27 22:26 UTC by WPDolan

We have implemented our planned functionalities described under the "Playerclass" section of our player interface implementation [plan](https://github.com/uchicago-cs/chiventure/wiki/Player-~-Interface-Implementation-Plan) as outlined in Issue #1057.

Changes Include:
- The addition of the  `copy_inventory` function to deep copy `skill_inventory_t` structs.
-  Updates to the `player_set_class()` function and its corresponding test to also set the player's `player_stats`, `player_skills`, and `player_effects` fields when setting a player's class. These fields are deep copied with `copy_inventory()`, `copy_stat()` and `copy_effect()`.

Deep copying fields from the given `class_t` to the `player_t` when setting the class will allow for multiple players to be the same class without the risk of unintentionally modifying every player's stats/effects/skills when modifying the fields of a single player.

The remaining sections of the interface plan will be implemented into the player module in Issues #1053 and #1058.

2021-05-28 22:51 UTC, LapsededPacifist reviewed
I think it looks good. I had the one comment about when classes get freed. Everything else in game-state looked good.
I didn't really review for the changes made to the skill trees section. I briefly looked over the code, and it looked OK. However, I don't really understand many of the changes there.

2021-05-28 22:51 UTC, LapsededPacifist commented on src/game-state/src/player.c
> -        class_free(plyr->player_class);
Not really certain if this is your job, but now that player isn't freeing their own class, should the list of all classes be freed in game? This is the only place that I know of where class_free gets called, so removing it might mean that every class struct is a memory leak.

2021-05-29 04:22 UTC, rohangupta2806 requested changes
Looks good!  I just suggested a couple of changes that are pretty minor.

2021-05-29 04:22 UTC, rohangupta2806 commented on src/skilltrees/src/inventory.c
> +        return NULL;
I would add an error message out here if the copy is NULL

2021-05-29 04:22 UTC, rohangupta2806 commented on tests/skilltrees/inventory_test.c
> +    skill_t* activ1 = (skill_t*)malloc(sizeof(skill_t));
You should be able to just use skill_new here

2021-05-29 04:47 UTC, jasulcaf commented on src/skilltrees/src/inventory.c
> +        return NULL;
Good catch, I was not being consistent with the rest of the code returning error messages in this type of situation. Added this

2021-05-29 04:48 UTC, jasulcaf commented on tests/skilltrees/inventory_test.c
> +    skill_t* activ1 = (skill_t*)malloc(sizeof(skill_t));
I didn't think that I needed all the specific details of a skill to test my function which is why I just malloc'ed, but using skill_new would make the code easier to read, so I am also incorporating this change.

2021-05-29 07:51 UTC, rohangupta2806 approved these changes
All seems good now!

2021-05-30 06:29 UTC, WPDolan commented on src/game-state/src/player.c
> -        class_free(plyr->player_class);
We believe that classes will be allocated at the beginning of the game, and will provide the starting skills/stats for players that choose the class. Some games may allow players to change classes throughout the course of a play session, so we believe that classes will be allocated at game creation, and freed at the end of the game.

2021-05-30 06:32 UTC, LapsededPacifist approved these changes
My only question was answered. I think the code looks good.

2021-05-31 03:11 UTC, jasulcaf commented
This is a general comment regarding a bug with the Pull Request Logs. I am an assignee to this Pull Request, yet in the process of resolving a comment from @rohangupta2806 I was added as a reviewer to this Pull Request. As such, this is just to clarify that I am _not_ a reviewer and this Pull Request does not require any approval from me to be merged.

2021-05-31 04:09 UTC, MaxineK36 requested changes
A few small fixes/clarifications!

2021-05-31 04:09 UTC, MaxineK36 commented on include/game-state/player.h
> + *  player: A player. Must point to already allocated memory.
Looks like `plyr` is used pretty consistently as a parameter in this file; please either change all instances or no instances (unless you have a particular reason for just doing this one)

2021-05-31 04:09 UTC, MaxineK36 commented on src/game-state/src/player.c
> -        class_free(plyr->player_class);
This makes sense to me! In general, frees should happen in parallel to allocations (so if a player doesn't allocate its own class, it shouldn't free it either)

2021-05-31 04:09 UTC, MaxineK36 commented on src/game-state/src/player.c
> -        class_free(plyr->player_class);
Feel free to make a backlog issue (bug) for classes being freed if you think this should be happening but isn't

2021-05-31 04:09 UTC, MaxineK36 commented on src/skilltrees/src/inventory.c
> +    free(inventory->active);
Are these guaranteed to be non-null?

2021-05-31 04:09 UTC, MaxineK36 commented on src/skilltrees/src/inventory.c
> +    /* Fill Array of Active Skills */
This seems to work with the existing functions, but it seems like these sets skills should really be linked lists (one for active, one for passive). Do you have any reason to believe this is not the case?

Otherwise, it would be helpful if you would make a backlog issue for this, as it would be a good task for future teams.

2021-06-01 23:02 UTC, WPDolan commented on include/game-state/player.h
> + *  player: A player. Must point to already allocated memory.
I have replaced all instances of `plyr` with `player` in both player.h and player.c

2021-06-01 23:13 UTC, jasulcaf commented on src/skilltrees/src/inventory.c
> +    free(inventory->active);
Yes. If we take a look at chiventure/src/skilltrees/src/inventory.c, the `inventory_new()` function is always preventively mallocing this memory.

2021-06-01 23:22 UTC, jasulcaf commented on src/skilltrees/src/inventory.c
> +    /* Fill Array of Active Skills */
I believe that the reason this is not the case is because the skilltrees team did not think there'd be a ton of skills added at once, and thus preferred the quick nature of being able to call any specific skill at once (vs. having to go through a lot of linked skills).

2021-06-01 23:27 UTC, rohangupta2806 commented on src/skilltrees/src/inventory.c
> +    /* Fill Array of Active Skills */
Yeah I think the previous years did decide on arrays, and if an array is full, they would make a new array and copy everything over.  We never got around to changing it this year.  We might make a backlog issue on this now that you've pointed it out.

2021-06-01 23:38 UTC, WPDolan commented on src/game-state/src/player.c
> -        class_free(plyr->player_class);
I believe that no current games in chiventure start off with allocating classes, so hopefully this shouldn't be a bug as long as the playerclass team addresses freeing when classes are integrated into playable games.

2021-06-01 23:55 UTC, MaxineK36 approved these changes
Looks good!

2021-06-02 00:02 UTC, merged

2021-06-02 00:41 UTC, WPDolan commented
Closing statement:

The pull request has been merged, and the playerclass section of the [interface plan](https://github.com/uchicago-cs/chiventure/wiki/Player-~-Interface-Implementation-Plan) is now complete, along with additional required functionality for creating deep copies of `skill_inventory` structs.

The core changes and additional functions listed in the opening statement of this pull request remain unchanged. They include:
- The addition of the  `copy_inventory` function to deep copy `skill_inventory_t` structs
-  Updates to the `player_set_class()` function and its corresponding test to also set the player's `player_stats`, `player_skills`, and `player_effects` fields when setting a player's class. These fields are deep copied with `copy_inventory()`, `copy_stat()` and `copy_effect()`
- Updates to `player_free()` to also free the newly deep copied `player_stats`, `player_skills`, and `player_effects` fields

Future pull requests will aim to complete additional sections listed under the interface plan.

2021-06-03 16:34 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! Your closing statement is particularly well-done.

<!-- {"score": "check-plus-plus"} -->