Implementing lowercase case insensitivity
uchicago-cs/chiventure pull request #1124
Opened 2021-05-28 00:11 UTC by mjgoodman321

Case insensitivity is currently unoptimally implemented in Chiventure by uppercasing the vast majority of inputs. The goal of this branch was to streamline case insensitivity by creating a helper function and implementing across as much of chiventure as was necessary to make the whole game case insensitive. Also, case insensitivity was changed to lowercasing the input instead of uppercasing to match industry standards

Linked to Issue #392

2021-05-28 00:33 UTC, LapsededPacifist requested changes
I didn't have any problems with the code modifications. Assuming that case_insensitize2() just changes it lower case (Which it appears to), I don't think there will be any functional problems.
The only change that I want made, is the extra line in the includes in room.h.

2021-05-28 00:33 UTC, LapsededPacifist commented on include/game-state/room.h
> +
There shouldn't be an extra space here.

2021-05-28 00:33 UTC, LapsededPacifist commented on include/game-state/game_state_common.h
> +#endif
This isn't really a problem, but I am very confused by this. The white space was nice before and I am very confused as to why it was changed.

2021-05-28 00:35 UTC, mjgoodman321 commented
Made one last change to the code because I was reviewing some monkeypatched code, and realized that because everybody uses the add_entry function with capitalized strings that I was about to break a lot of code. Decided it was easier to make sure that you could call add_entry with any case of string than to require people to only use lowercase strings

2021-05-28 00:37 UTC, mjgoodman321 commented on include/game-state/game_state_common.h
> +#endif
That's where I put the case insensitivity functions there to begin with, didn't realize I left that space there when I removed them. Sorry!

2021-05-28 01:23 UTC, LapsededPacifist approved these changes
The minor changes to the spacing that I requested look good. 
I am only approving for game-state and action-management, since I only looked at the game-state and action-management code.

2021-05-28 17:44 UTC, Beza20 commented on src/action_management/src/actionmanagement.c
> +    if(strncmp(a->c_name, "pickup", BUFFER_SIZE) == 0)
Why did you need to changed these hard coded strings? shouldn't the fact that you have now made chiventure case insensitive have no effect on how we write our hard coded strings at least that's what I was hoping for when putting in the delimiter for the parse_r function

2021-05-28 17:49 UTC, Beza20 commented
Beautiful! great code to read and follow through and a very valuable functionality for chiventure.

2021-05-28 17:51 UTC, Beza20 approved these changes

2021-05-28 18:48 UTC, mjgoodman321 commented on src/action_management/src/actionmanagement.c
> +    if(strncmp(a->c_name, "pickup", BUFFER_SIZE) == 0)
Well because case insensitivity is being implemented as making everything lowercase, so some hard-coded strings (specifically those that aren't called by a function that lowercases them) have to be made lowercase to work in the framework of the game. There is a version of strcmp that doesn't care about case, but I'm not sure it can be used here because I don't know how important it is to use strncmp here as opposed to a version of the generic strcmp.

2021-05-28 22:34 UTC, ecoble requested changes

2021-05-28 22:34 UTC, ecoble commented on include/cli/cli-utility.h
> +void case_insensitize1(char *input);
I think it would be better to name these functions something more descriptive than case_insensitize1 and case_insensitize2, since those do not describe the differences between these functions. You could maybe name the first one case_insensitize, and the other case_insensitize_alloc, or something along those lines. I realize this is inconvenient since the function is called in so many places, but using find and replace should help.

2021-05-28 22:34 UTC, ecoble commented on src/wdl/src/load_item.c
> +    if(curr == NULL)
Space after if

2021-05-29 14:36 UTC, borjasotomayor requested changes
The changes to the non-CLI part of the code look overall good, but the use of the `case_insensitized_string` function has to be reviewed carefully: in many cases, the string allocated by this function is not being freed, or the use of `case_insensitized_string` is not necessary at all, since the string that is being case-insensitized is being passed to a function that already case-insensitizes its inputs.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/game_action.c
> +    int check = game_action_init(new_action, case_insensitized_string(action_name), success_str, fail_str);
This results in a memory leak, because the string returned by `case_insensitized_string` is copied into `new_action->action_name` inside `game_action_init`, but the original string is never freed. In general, the function would have to be called like this:

```
char *action_name_case = case_insensitized_string(action_name);
int check = game_action_init(new_action, action_name_case, success_str, fail_str);
free(action_name_case);
```

However, in this particular case, it may simply make more sense to call `case_insensitized_string` inside `game_action_init`: after action_name is copied into `new_action->action_name`, just case-insensitize that string (which avoids having to allocate a separate case-insensitized string)

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/game_action.c
> +    action_name = case_insensitized_string(action_name);
Avoid altering the content of the parameter in this way. Instead, do something like this:

```
char *action_name_case = case_insensitized_string(action_name);
```

And then remember to free `action_name_case` at the end of the function.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/item.c
> +    item_id = case_insensitized_string(item_id);
Same as the comment in `src/game-state/src/game_action.c:31`. `item_id` needs to be freed, but a better solution may be to case-insensitize `new_item->item_id` inside `item_init` after `item_id` has been copied into it.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/path.c
> +    direction = case_insensitized_string(direction);
Instead of allocating a new string, just case-insensitize `path->direction` at the end of the function.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/room.c
> +    room_id = case_insensitized_string(room_id);
Instead of allocating a new string here, case-insensitize `new_room->room_id` in `room_init`.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/room.c
> +    direction = case_insensitized_string(direction);
Same as comment in `src/game-state/src/game_action.c:54`. Avoid overwriting the value of the parameter. Create a new variable for the case-insensitized string, and remember to free it once you are done with it.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/room.c
> +    item_id = case_insensitized_string(item_id);
Same as comment in `src/game-state/src/game_action.c:54`. Avoid overwriting the value of the parameter. Create a new variable for the case-insensitized string, and remember to free it once you are done with it.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/room.c
> +    direction = case_insensitized_string(direction);
Same as comment in `src/game-state/src/game_action.c:54`. Avoid overwriting the value of the parameter. Create a new variable for the case-insensitized string, and remember to free it once you are done with it.

2021-05-29 14:36 UTC, borjasotomayor commented on src/wdl/src/load_item.c
> +        return NULL;
Add blank line after this one.

2021-05-29 14:36 UTC, borjasotomayor commented on src/wdl/src/load_item.c
> +            add_action(i, case_insensitized_string(obj_get_str(curr, "action")), obj_get_str(curr, "text_success"), obj_get_str(curr, "text_fail"));
Avoid calling `case_insensitized_string(obj_get_str(curr, "action")` twice to compute the same value. Instead, compute it once at the top of the loop:

```
char *action = case_insensitized_string(obj_get_str(curr, "action"));
```

And remember to free it at the end of the loop.

2021-05-29 14:36 UTC, borjasotomayor commented on src/wdl/src/load_item.c
> +        room_t *item_room = find_room_from_game(g, case_insensitized_string(in));
The string allocated by `case_insensitized_string(in)` is never freed. That said, calling `case_insensitized_string` here is redundant since `find_room_from_game` already case-insensitizes the `room_id` parameter.

2021-05-29 14:36 UTC, borjasotomayor commented on src/game-state/src/game.c
> +    room_id = case_insensitized_string(room_id);
Same as comment in `src/game-state/src/game_action.c:54`. Avoid overwriting the value of the parameter. Create a new variable for the case-insensitized string, and remember to free it once you are done with it.

2021-05-29 14:36 UTC, borjasotomayor commented on src/cli/src/cmd.c
> +    command_name = case_insensitized_string(command_name);
Instead of allocating a new string, just case-insensitize `t->name`

2021-05-29 14:36 UTC, borjasotomayor commented on src/wdl/src/load_room.c
> +        char *id = case_insensitized_string(curr->id);
Case-insensitizing `curr->id` is redundant since that value is only used to call `create_connection`, which in turn calls `find_room_from_game`, which already case-insensitizes the `room_id` parameter.

2021-05-29 14:36 UTC, borjasotomayor commented on src/wdl/src/load_room.c
>              char *to = obj_get_str(conn_curr, "to");
Same issue as `curr->id` above.

2021-05-29 14:36 UTC, borjasotomayor commented on src/wdl/src/load_room.c
> +            direction = case_insensitized_string(direction);
Similar to `curr->id` and `to`: `direction` eventually makes its way to `path_new`, which already case-insensitizes the `direction` parameter.

2021-05-29 19:23 UTC, Justin08784 requested changes
I checked out your most recent commit ee646f7ea5cc5286d8e18623e471edfd5062ddfc.

A massive number of tests are failing and/or crashing in several modules, including openworld, game-state, action-management, and quests.

2021-05-29 19:31 UTC, Justin08784 approved these changes
My previous comment was based on a complete misunderstanding. Changes in the openworld module look fine.

2021-05-29 22:35 UTC, mjgoodman321 commented on include/game-state/item.h
> +#include "cli/cli-utility.h"
Does this apply to other cli files like the example above, or should it only be included in .c files for other modules?

2021-05-29 22:38 UTC, borjasotomayor commented on include/game-state/item.h
> +#include "cli/cli-utility.h"
Since this header files does not include any struct declarations, it should not appear in any `.h` files. Instead, `#include` it only in the C files that use the case-insensitize functions.

2021-05-29 22:44 UTC, mjgoodman321 commented on src/game-state/src/game_action.c
> +    int check = game_action_init(new_action, case_insensitized_string(action_name), success_str, fail_str);
So I know you said I should use `case_insensitized_string` inside of `game_aciton_init`, but could I try using the regular `case_insensitize` since the `new_action->action_name` is already calloced? Since that way there's no chance of producing a string that isn't freed elsewhere.

2021-05-29 22:49 UTC, borjasotomayor commented on src/game-state/src/game_action.c
> +    int check = game_action_init(new_action, case_insensitized_string(action_name), success_str, fail_str);
Yes, sorry, that's what I meant: after `action_name` is copied into `new_action->action_name`, you can just case-insensitize it in-place (using the `case_insensitize` function)

2021-05-29 23:00 UTC, mjgoodman321 commented on src/cli/src/cmd.c
> +    command_name = case_insensitized_string(command_name);
Would it be better to case-insensitize newname as it is assigned to t->name like so:
`t->name = case_insensitize(newname);`
Or to do it separately on the line after?

2021-05-29 23:02 UTC, mjgoodman321 commented on src/cli/src/cmd.c
> +    command_name = case_insensitized_string(command_name);
Wait nevermind that was a dumb question, case_insensitize returns void

2021-05-29 23:30 UTC, mjgoodman321 commented on src/game-state/src/game_action.c
> +    action_name = case_insensitized_string(action_name);
For some reason after implementing this, the two tests in test_item.c have started failing due to `possible_actions` returning a failure, which I'm really confused by since both the modifications to this function and to the load_actions function (the only other function I could find that would affect those tests) shouldn't affect their behavior. I'll go ahead and push all the changes I've made to address your comments so you can see it yourself.

2021-05-30 00:44 UTC, borjasotomayor commented on src/game-state/src/game_action.c
> +    action_name = case_insensitized_string(action_name);
This turned out to be a very subtle bug in how actions were being added to items (which, as far as I can tell, has been in the repository for two years, and I'm surprised it took so long to surface). In a nutshell, whenever you add a struct to a uthash hash table, the key must be in the struct you are adding (it can't be an arbitrary string, separate from the struct). `add_action` was using the `action_name` parameter as the key, when it should've used the `action_name` in the `action` struct.

Anyway, I've pushed the fix, which now makes all the tests pass: https://github.com/uchicago-cs/chiventure/commit/4bfb908133de45c3c81400387fab052cddd213e1

2021-05-30 15:19 UTC, borjasotomayor approved these changes

2021-05-31 10:43 UTC, ecoble approved these changes

2021-05-31 10:48 UTC, merged

2021-05-31 12:59 UTC, mjgoodman321 commented
Closing Statement: case insensitivity has been implemented through the use of two helper functions, case_insensitize and case_insensitized_string, which respectively change a string at its source into its lowercase version and produce a lowercase version of a string out of a given input. Various other changes have been made to hardcoded strings throughout chiventure in order to properly implement case insensitivity (most notably in the actionmanagement module).

2021-06-07 20:23 UTC, ecoble commented
Issue Score: ✔️++

Comments:
Great work on a tough issue! Nice job getting all the proper reviewers, and keeping this PR up to date.

<!-- {"score": "check-plus-plus"} -->