Sound
uchicago-cs/chiventure pull request #1129
Opened 2021-05-28 03:17 UTC by gypark23

This pull request has the initial design and implementation of sound structure and its functions. The sound structure had been designed, yet currently, the essential functions (including load and play sound) are only skeleton functions which are expected to be implemented throughout the Chiventure development. Additionally, this branch also include demo files, which plays sound files using SDL Library.

2021-05-28 03:41 UTC, gypark23 commented
It appears that SDL.h library is not recognized during the GitHub workflow process

2021-05-28 13:50 UTC, borjasotomayor requested changes
The changes to the build files look overall good to me, but they require some tweaks.

2021-05-28 13:50 UTC, borjasotomayor commented on .github/workflows/build-and-test.yml
> +          sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-gfx-dev
These packages should be added to the list of packages that are installed in the "Install Dependencies" step, instead of being a separate step (raylib has a separate step because it is not installable with `apt-get`, not because we need a separate step for each individual dependency)

2021-05-28 13:50 UTC, borjasotomayor commented on CMakeLists.txt
> +include_directories(${SDL2_INCLUDE_DIRS})
Move these two lines above the "# Optional Dependencies" line, since SDL is not an optional dependency.

2021-05-28 19:17 UTC, gypark23 commented
Changes for workflow and CMake are made successfully

2021-05-28 23:14 UTC, ecoble requested changes
Great job! Most of these comments are style related, I would recommend using astyle to automatically fix styling issues. Also, any code that is commented out because it is not compiling should be removed from this PR and put in a separate branch for your work in progress.

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/main.cpp
> +"Kick-Drum-1.wav",
These lines should be indented, I would run this file through astyle to automatically fix all the styling issues.

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/main.cpp
> +    SDL_Window* window = SDL_CreateWindow("Sounds",
Indentation looks off on these lines.

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/main.cpp
> +"Cardi-B-ft.-Megan-Thee-Stallion-–-Wap.mp3"
Indentation

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/main.cpp
> +		//usleep(1000);
Commented code

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/main.cpp
> +    for( int i = 0; i < NUM_WAVEFORMS; i++ )
There should be a space after "for" and no space before "int", so it will look like:

for (int i = ....)

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/demo.c
> +    if(!soundEffect) {
There should be a space after if, I would recommend using astyle to automatically fix the styling here as well.

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/main.cpp
> +#ifdef WIN32
Is it possible to make this a C file? It doesn't look like there is anything here that is C++ specific, but if it is too big of a change before the demo that is okay.

2021-05-28 23:14 UTC, ecoble commented on src/sound/sandbox/sandbox
> +#include "sound/sound.h"
This file has no extension, should it be a .c file?

2021-05-28 23:14 UTC, ecoble commented on src/sound/sound.c
> +<<<<<<< HEAD
Same here with deleting lines left over from merge conflicts

2021-05-28 23:14 UTC, ecoble commented on src/sound/sound.c
> +=======
Here as well

2021-05-28 23:14 UTC, ecoble commented on src/sound/sound.c
> +    if( SDL_OpenAudio( 44100, MIX_DEFAULT_FORMAT, 2, 2048 ) < 0 )
Watch spacing here and throughout the file

2021-05-28 23:14 UTC, ecoble commented on src/sound/sound.c
> +>>>>>>> 11c37048538ee017e7d074cfe77595c915191024
Delete

2021-05-28 23:14 UTC, ecoble commented on src/sound/sound.c
> +    /*
Move non functional code into a separate work in progress branch

2021-05-28 23:14 UTC, ecoble commented on src/sound/sound.c
> +    /*
Same about moving non-functional code

2021-05-28 23:14 UTC, ecoble commented on src/sound/src/hashtable.c
> +int main(){
Is this a test function? If so, it should be in its own test file.

2021-05-29 00:58 UTC, gypark23 commented on include/sound/sound.h
> +/* THE FOLLOWING CODE IS FOR DEMO PURPOSES. THIS
A separate demo.h had been created to accommodate for demo functions.

2021-05-29 01:21 UTC, jiguba commented on src/sound/sandbox/demo.c
> +/*void play_audio(sound_t *name)
Commented code has been deleted.

2021-05-29 01:22 UTC, closed without merging

2021-05-29 01:28 UTC, gypark23 commented
sound branch is now divided into two, sound/dev and sound/inprogress to distinguish already-developed code and currently-developing code. A new pull-request for sound/dev will follow.

2021-05-29 02:29 UTC, gypark23 commented
#1140 now succeeds this pull request.