Creating a demo game for the action management final presentation.
uchicago-cs/chiventure pull request #1133
Opened 2021-05-28 19:58 UTC by LapsededPacifist

Creation of a monkey-patched demo game for the action-management team.

Implements commands showcasing 
- the running of a custom-action IFELSE branch block
- Modifications made to the player class specifically stats

Specific functions are:
- SEEDMG
- RAISEDMG
- MYSTRENGTH
- LEARNSTRENGTH
- CHANGESTRENGTH

2021-05-30 06:56 UTC, WPDolan commented on src/action_management/examples/spring2021-demo.c
> +  dmgCap->attribute_key = strdup(name);
Will having two attributes with the same key cause issues in the demo?

2021-05-30 07:03 UTC, LapsededPacifist commented on src/action_management/examples/spring2021-demo.c
> +  dmgCap->attribute_key = strdup(name);
It isn't great practice and would probably cause errors if being placed into the same hash, it will not cause any problems here. You would not be able to properly search for attributes, but the only thing that matters in conditionals and actions is their position in the structs.

2021-05-30 07:17 UTC, WPDolan commented on src/action_management/examples/spring2021-demo.c
> +  dmgCap->attribute_key = strdup(name);
That is fine, seeing as the demo is not concerned with hashing attributes.

2021-05-30 07:20 UTC, WPDolan approved these changes
The custom-actions portion of the demo looks good, and my questions both here and in the slack have been answered to satisfaction. 

Because I wrote the player struct portion of the demo, the player struct portion should be reviewed by another developer before the PR is ready to be merged.

2021-05-30 12:52 UTC, jasulcaf commented on src/action_management/examples/spring2021-demo.c
> +    double change = atoi(tokens[1]) + 0.0;
I am curious if adding 0.0 is extremely necessary in this case.

2021-05-30 13:01 UTC, jasulcaf commented on src/action_management/examples/spring2021-demo.c
> +    strength = player_get_stat_current(player, "strength");
I am also curious how vital this line is, we never use strength after this afterall, and the change happened above with `player_change_stat`.

2021-05-30 13:02 UTC, jasulcaf reviewed
I have left two comments where I was curious about some bits of code, but the overall code for player struct portion looks good!

2021-05-30 22:47 UTC, WPDolan commented on src/action_management/examples/spring2021-demo.c
> +    double change = atoi(tokens[1]) + 0.0;
This is necessary to convert the output from atoi() (an integer) to a double.

2021-05-30 22:48 UTC, WPDolan commented on src/action_management/examples/spring2021-demo.c
> +    strength = player_get_stat_current(player, "strength");
Good catch, those lines are unused and have now been removed.

2021-05-31 00:33 UTC, jasulcaf approved these changes
Comments I left have been resolved, code looks good!

2021-06-01 16:18 UTC, MaxineK36 requested changes
Looking good overall! A couple of small things to make things clearer for future teams

2021-06-01 16:18 UTC, MaxineK36 commented on src/action_management/examples/CMakeLists.txt
> -add_executable(spring2020-demo
Is there a reason you're removing the old demo from the makefile? (Note that it is possible to include both executables; for example, see the[ UI examples cmakelists](https://github.com/uchicago-cs/chiventure/blob/dev/src/ui/examples/CMakeLists.txt))

2021-06-01 16:18 UTC, MaxineK36 commented on src/action_management/examples/spring2021-demo.c
> +  dmgIncrease->attribute_key = strdup(name);
Are there `attribute_new` (or similar) functions you can use instead of doing this manually?

2021-06-01 16:18 UTC, MaxineK36 commented on src/action_management/examples/spring2021-demo.c
> +  AST_block_t *branch = AST_branch_block_new(1, &cond, IFELSE, 2, actions);
Can you add a comment here describing the custom action this represents? This will be helpful for future teams to understand how custom actions should be used

2021-06-01 16:18 UTC, MaxineK36 commented on src/action_management/examples/spring2021-demo.c
> +  char *str;
`str` should be malloced

2021-06-01 16:18 UTC, MaxineK36 commented on src/action_management/examples/spring2021-demo.c
> +char *change_strength(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
How would strength be changed in an actual integration with chiventure?

2021-06-01 16:18 UTC, MaxineK36 commented on src/action_management/examples/spring2021-demo.c
> +    attribute_t *wepDmg = malloc(sizeof(attribute_t));
Is there an attribute_new function that can be used here?

2021-06-01 19:10 UTC, LapsededPacifist commented on src/action_management/examples/CMakeLists.txt
> -add_executable(spring2020-demo
Nope there is not. I hadn't seen any other examples of it multiple in one file, so I just changed the 0 to a 1 because I knew that would work. I will add the old executable back.

2021-06-01 19:23 UTC, LapsededPacifist commented on src/action_management/examples/CMakeLists.txt
> -add_executable(spring2020-demo
I added the executable back in the style of the UI example. It makes fine, but it segmentation faults when I try to run it. Should I try to fix this? I don't have any idea if I added dependencies wrong, or if it is just doesn't place nice with the new changes to chiventure.

2021-06-01 19:32 UTC, LapsededPacifist commented on src/action_management/examples/spring2021-demo.c
> +  dmgIncrease->attribute_key = strdup(name);
The custom-actions attribute_new function is still totally busted, but there are functions in item.c that I had kept getting errors before. They worked totally fine this time, so maybe I had a typo in the function call name or something.

2021-06-01 22:41 UTC, WPDolan commented on src/action_management/examples/spring2021-demo.c
> +char *change_strength(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
Stats in chiventure are designed to be changed through many venues. Common methods of changing stats would include equipping items, leveling up, or through moves in battle. The effects in `player_effects` field in the player struct is also unique in its ability to apply temporary or permanent modifiers to stats as long as the effect is present.

2021-06-01 23:48 UTC, MaxineK36 commented on src/action_management/examples/CMakeLists.txt
> -add_executable(spring2020-demo
@LapsededPacifist Which executable is seg-faulting; the 2020 one or the 2021 one?

2021-06-01 23:49 UTC, LapsededPacifist commented on src/action_management/examples/CMakeLists.txt
> -add_executable(spring2020-demo
The 2020 one. If ours was seg faulting it would be a much larger problem (At least a more pressing one).

2021-06-01 23:50 UTC, MaxineK36 commented on src/action_management/examples/spring2021-demo.c
> +char *change_strength(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
@WPDolan So ordinarily this would be as part of operations that come from other teams' functionality, yes? If so, worth noting it briefly here, and also mentioning as you do the demo.

2021-06-01 23:50 UTC, MaxineK36 commented on src/action_management/examples/spring2021-demo.c
> +char *change_strength(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
@WPDolan So ordinarily this would be as part of operations that come from other teams' functionality, yes? If so, worth noting it briefly here, and also mentioning as you do the demo.

2021-06-01 23:53 UTC, LapsededPacifist commented on src/action_management/examples/CMakeLists.txt
> -add_executable(spring2020-demo
OK. I can remove it. I didn't actually know it wasn't functional before. I thought it was.

2021-06-02 03:31 UTC, MaxineK36 requested changes
Due to changes in dev, `ctx->table` needs to be changed to `ctx->cli_ctx->table`

2021-06-02 04:12 UTC, MaxineK36 approved these changes
Looks good -- thanks for the quick fix!

2021-06-02 04:12 UTC, merged

2021-06-02 21:21 UTC, afranzese99 commented
Closing statement:

The pull-request has been merged, thus, the monkey-patched demo game for the action-management team is finished.
As mentioned in the opening statement, the demo game illustrates functionality for running of a custom-action IFELSE branch block and modifications made to the player struct and module specifically stats (which emulates how other components of the player struct would work such as skills and effects). These functionalities are demonstrated with the following commands:

- SEEDMG
- RAISEDMG
- MYSTRENGTH
- LEARNSTRENGTH
- CHANGESTRENGTH

2021-06-03 16:35 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Awesome work! Your title and summary are particularly well-written. 

<!-- {"score": "check-plus-plus"} -->