Npc/battle tests
uchicago-cs/chiventure pull request #1135
Opened 2021-05-28 22:35 UTC by northofsophia

We have added numerous tests for various npc_battle integration such as set functions, get functions, change functions, and functions for looting dead bodies.

2021-05-31 22:01 UTC, amymorrill requested changes
Looks good! I just saw a small bug in my tests (which I'll fix), and I also wonder if the test for a dead npc with multiple items should check that the correct number of items were transferred.

2021-06-01 14:16 UTC, northofsophia commented on tests/npc/test_npc_battle.c
> +    cr_assert_not_null(room->items,
I have added an additional check that sees if the correct items were transferred.

2021-06-01 17:17 UTC, amymorrill approved these changes

2021-06-01 20:53 UTC, lilyehsani requested changes
Looks really good! Added one comment, a style thing that needs to be changed in various places.

2021-06-01 20:53 UTC, lilyehsani commented on tests/npc/test_npc.c
> +stat_t* create_enemy_stats()
Move * over to be `stat_t *create_enemy_stats()` etc throughout this file

2021-06-02 03:16 UTC, lilyehsani requested changes
Missed 1 spot

2021-06-02 03:16 UTC, lilyehsani commented on tests/npc/test_npc.c
> +move_t* create_enemy_moves()
move *

2021-06-02 18:22 UTC, northofsophia commented on tests/npc/test_npc.c
> +move_t* create_enemy_moves()
I have fixed this style change

2021-06-02 19:08 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-06-02 20:43 UTC, merged

2021-06-02 22:07 UTC, amymorrill commented
The tests that we wrote for the npc_battle related functions that we created this quarter have now been merged into dev. We created a new file, tests/npc/test_npc_battle.c, that contains tests for functions in the npc_battle module and added to the file tests/npc/test_npc.c. This pr only included unit testing and did not include any integration testing with the battle module, which will have to be added by next year's class.

2021-06-07 03:15 UTC, lilyehsani commented
Issue Score: ✔️+

Comments:
Great work overall! I have two comments:
-  The title of a PR has to convey what the PR will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the PR (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.)
- The summary for this PR is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples).

<!-- {"score": "check-plus"} -->