Creation of Battle Mode for CLI Integration
uchicago-cs/chiventure pull request #1137
Opened 2021-05-29 01:37 UTC by jintae412

We modified the mode.c file to allow for a Battle Mode to run battles for the CLI, and then made an example of how this would work using a monkey-patched Fight command. This required us to modify the ctx struct to have a field for a battle context so that the CLI would have a way to access a given battle, and modify/create the relevant functions. In addition, modifications to the code were necessary so that actions produced the necessary strings that would be sent to the CLI to be printed through the CLI print functions. Battle_items and move structures must have their "name" and "info" fields respectively now in all-caps to ensure compatability with the parsed inputs from the CLI, which automatically makes all of the inputs all-caps.

2021-05-29 14:47 UTC, borjasotomayor requested changes
The changes to the game state code look good to me, but there is a small naming change that has to be made.

Additionally, someone should create a backlog item for moving "modes" out of Game State, since they make more sense inside CLI (however, that is a much larger task, and one that can simply be added to the backlog)

2021-05-29 14:47 UTC, borjasotomayor commented on include/game-state/game.h
> +    chiventure_ctx_battle_t *battle_ctx;
Rename `chiventure_ctx_battle_t` to `battle_ctx_t` for coherence with other struct names (note how no other struct in `game_t` -or in the entire code- uses the prefix `chiventure_ctx`).

2021-05-29 23:03 UTC, lczielinski approved these changes
Wow, this looks awesome! I think there's a typo on one of the header comments but that's about it

2021-05-30 03:28 UTC, jintae412 commented on include/battle/battle_print.h
> +int *print_battle_items(battle_t *b, char *string);
Yes, this has been fixed. Thanks!

2021-05-30 03:41 UTC, jintae412 commented on include/game-state/game.h
> +    chiventure_ctx_battle_t *battle_ctx;
All instances of the chiventure_ctx_battle_t struct should have been renamed to battle_ctx_t.

2021-05-30 15:14 UTC, borjasotomayor approved these changes

2021-05-31 04:31 UTC, Elsa-Athiley commented
Just pushed some minor changes, it seems like some code was refactored so that the `chiventure_ctx_t` struct now has a field for `cli_ctx_t` which now holds the lookup table so I changed the way we were accessing it so it no longer caused an error. I also added another case so if an invalid command is passed in for the 'list item/move' it returns a message saying ivalid command. Also fixed a small typo.

2021-05-31 18:24 UTC, firatciftci requested changes
I've requested some minor stylistic changes.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_flow.c
> +    if(battle_over(b) == BATTLE_IN_PROGRESS){
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of this line to a new line below.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_flow.c
> +    if (item == NULL){
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of this line to a new line below.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_flow.c
> +    if (item->quantity <= 0){
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of this line to a new line below.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_flow.c
> +    if(battle_over(b) == BATTLE_IN_PROGRESS){
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of this line to a new line below.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_flow.c
> +    if (strcmp(label, "ITEMS") == 0) {
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of this line to a new line below.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_flow.c
> +    } if (strcmp(label, "MOVES") == 0) {
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of this line to a new line below.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_flow.c
> +    } else {
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of this line to a new line below.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_logic.c
> +    {
GitHub shows extra white space being added to this line which I assume should not be there.

2021-05-31 18:24 UTC, firatciftci commented on src/battle/src/battle_print.c
> +    //print_moves(b,string);
Make sure to remove any unused commented out code.

2021-05-31 18:24 UTC, firatciftci commented on src/game-state/src/mode.c
> +    {
This file seems to be using the end-of-line approach for opening curly brackets, so I think you should move the `{` on this line to the end of the line just above.

2021-05-31 18:24 UTC, firatciftci commented on src/game-state/src/mode.c
> +        for(int i = 1; parsed_input[i] != NULL; i++) {
Make sure to place a single space character between `for` and `(`.

2021-06-02 04:37 UTC, firatciftci approved these changes
Looks good to me!

2021-06-02 04:37 UTC, merged

2021-06-02 21:43 UTC, jintae412 commented
To summarize this PR, a mode was created for conducting battles through the CLI. The run_battle_mode function uses if/else statements to go through the potential inputs given and so run the relevant battle_flow and battle_logic functions. This required liberal use of statements to print to the CLI as well as easy access to the required strings to output, so numerous changes to the battle_print functions as well as battle_flow and battle_logic were necessary. Similarly, keeping in line with how parsing of CLI input is conducted, as of right now items and moves work only should their names be in all lowercase letters.

The example created for the demo and to showcase this feature required a monkeypatched "FIGHT" command, given that the CLI team has not yet officially created one yet. Furthermore, there remains yet a bug in which one of the possible consumable items created by the default item creation function, the "elixir of life" occasionally causes a segfault while running the example. It is unknown why this is the case, but a backlog issue making note of it has been created.

2021-06-06 20:43 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Good work!

<!-- {"score": "check-plus-plus"} -->