Skill Trees Demo
uchicago-cs/chiventure pull request #1138
Opened 2021-05-29 01:40 UTC by tgao564

We have added the skilltrees_demo.c file in the src/skill/examples folder as our demo file for the final presentation. The file includes an implementation for a demo that showcases the new effects and leveling implementation done by the skill trees team this quarter. This PR relies on code in PR #1110 and therefore that PR needs to be approved before this one can.

2021-06-02 06:47 UTC, rohangupta2806 commented
PR 1110 has been merged.  This PR can now be reviewed.

2021-06-02 21:39 UTC, mariakravtsova approved these changes
Good demo!

2021-06-02 21:57 UTC, firatciftci requested changes
I have requested some stylistic changes.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(health_boost == NULL)
Make sure to add a space character between `if` and `(`. Also, make sure to always add curly brackets around if statements, with proper indentation for the code block inside the if statement.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(player->level<skill_node->prereq_level)
Make sure to add a space character between `if` and `(`.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(skill->sid != sid)
Make sure to add a space character between `if` and `(`.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(check == FAILURE)
Make sure to add a space character between `if` and `(`.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(dragon == NULL)
Make sure to add a space character between `if` and `(`.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(check == FAILURE)
Make sure to add a space character between `if` and `(`.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(dragon == NULL)
Make sure to add a space character between `if` and `(`. Also, make sure to always add curly brackets around if statements, with proper indentation for the code block inside the if statement.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    if(is_alive == true)
Make sure to add a space character between `if` and `(`. Also, make sure to always add curly brackets around if statements, with proper indentation for the code block inside the if statement.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +    }
This file seems to be using a new-line for opening curly brackets, so I think you should move the `{` at the end of the if, else, and for statements in this section to a new-line just below each one.

2021-06-02 21:57 UTC, firatciftci commented on src/skilltrees/examples/skilltrees_demo.c
> +void main(){
Make sure to add a space character between `)` and `{`.

2021-06-02 23:13 UTC, rohangupta2806 commented
I made all the required changes.  Should be good to merge now.

2021-06-02 23:16 UTC, firatciftci approved these changes
Everything looks good to me!

2021-06-02 23:16 UTC, merged

2021-06-04 20:36 UTC, rohangupta2806 commented
Closing comment:  The demo for skilltrees has been merged.  The demo can be built by going to the build/src/skilltrees/examples folder and doing make, and then running skilltrees_demo.  We have added a number of custom commands that let us showcase the functionality of skilltrees and the new effects, along with prerequisite levels.

2021-06-06 20:43 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Good work!

<!-- {"score": "check-plus-plus"} -->