sound/dev Initial Design and Implementation of Sound Module
uchicago-cs/chiventure pull request #1140
Opened 2021-05-29 02:18 UTC by gypark23

* Note: This pull request is based on #1129 which had been automatically closed due to the branch divergence. This pull request is created to succeed #1129 

This pull request has the initial design and implementation of sound structure and its functions. The sound structure had been designed, yet currently, the essential functions (including load and play sound) are only skeleton functions which are expected to be implemented throughout the Chiventure development. Initial readme.md that explains the roles of each functions are included. Finally, this branch also include demo files, which plays sound files using SDL Library.

2021-05-29 13:55 UTC, borjasotomayor requested changes

2021-05-29 13:55 UTC, borjasotomayor commented on .github/workflows/build-and-test.yml
> +          sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-gfx-dev
Add the packages in this line to the existing `apt install` command, instead of running `apt-get` a second time.

2021-05-29 19:17 UTC, gypark23 commented on .github/workflows/build-and-test.yml
> +          sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-gfx-dev
This has been updated. Now there is only one line of apt install command.

2021-05-29 22:36 UTC, borjasotomayor requested changes
The changes to the build files look good to me, but I've noticed you've commited binary files into the repository:

- src/sound/.DS_Store 
- src/sound/hash_functions/.DS_Store 

The .mp3 and .wav files should also be removed from the repository, and replaced with instructions on how to download those files from an alternate location. Alternatively, if you plan to use these files only for a demo, it is ok if these files just exist on your local computer. They do not need to be in `dev`.

In general please take into account that you should never commit binary files into a code repository, specially not large files that will increase the size of the repository (and will make push and pull operations slower for everyone)

2021-05-30 15:23 UTC, borjasotomayor requested changes
It looks like there's still a couple of binary files remaining in this pull request:

- src/sound/.DS_Store
- src/sound/hash_functions/.DS_Store
- src/sound/sandbox/sound_library/flute-alaert.wav
- src/sound/sandbox/sound_library/game-completed.wav
- src/sound/sandbox/sound_library/game-over.wav

Please make sure to remove these too.

2021-05-31 11:00 UTC, ecoble requested changes

2021-05-31 11:00 UTC, ecoble commented on src/sound/sandbox/sandbox
> +#include "sound/sound.h"
This file is missing an extension still.

2021-05-31 11:00 UTC, ecoble commented on src/sound/sandbox/main.cpp
> +#ifdef WIN32
The style in the file is still off, I would recommend using astyle to fix this.

2021-05-31 11:00 UTC, ecoble commented on include/sound/demo.h
> +typedef struct {
This struct is already defined in sound.h, instead of duplicating it for the demo file, just include both demo.h and sound.h and remove this definition of the sound struct.

2021-05-31 11:00 UTC, ecoble commented on include/sound/demo.h
> +#ifndef INCLUDE_DEMO_H_
Since this is only for the demo, please just move it directly into the examples folder.

2021-05-31 14:15 UTC, borjasotomayor approved these changes

2021-05-31 14:25 UTC, jiguba commented on src/sound/sandbox/main.cpp
> +#ifdef WIN32
Reformatted main.cpp to main.c as requested in a previous comment and astyle was used on main.c

2021-05-31 14:26 UTC, jiguba commented on include/sound/demo.h
> +typedef struct {
Removed sound struct and included sound.h into demo.h

2021-05-31 14:26 UTC, jiguba commented on include/sound/demo.h
> +#ifndef INCLUDE_DEMO_H_
created an examples folder where demo.h and demo.c were moved, and makefile was create to compile demo program

2021-05-31 17:36 UTC, ecoble requested changes

2021-05-31 17:36 UTC, ecoble commented on src/sound/sound.c
> +#include "../../include/common/uthash.h"
You should be able to just include common/uthash.h

2021-05-31 17:36 UTC, ecoble commented on src/sound/src/hashtable.c
> +#include "sound/sound.h"
What is the purpose of having a user hashtable?

2021-05-31 17:36 UTC, ecoble commented on src/sound/sandbox/main.c
> +#include "sound/sound.h"
Was this file adapted from the SDL documentation? If so I think it might be useful to make a note of that in a comment at the top of the file.

2021-05-31 18:30 UTC, jiguba commented on src/sound/sandbox/main.c
> +#include "sound/sound.h"
Reference to source code added to the top of the main.c file

2021-05-31 18:30 UTC, jiguba commented on src/sound/sound.c
> +#include "../../include/common/uthash.h"
Fixed uthash.h file pathway

2021-06-01 00:21 UTC, jiguba commented on src/sound/src/hashtable.c
> +#include "sound/sound.h"
The purpose of the user hashtable was to have a struct to store sound structs. It also served to test the functionalities of uthash. Comments were add to the hash variable and associated hash functions. However, the hashtable.c was moved to the sound/inprogress branch since it was a feature we could not implement.

2021-06-01 00:25 UTC, jiguba commented on src/sound/src/hashtable.c
> +#include "sound/sound.h"
hashtable.c was readded because it was needed in the CMakeLists file

2021-06-02 00:29 UTC, ecoble commented on src/sound/src/hashtable.c
> +#include "sound/sound.h"
If this was not implemented, I agree that it would be better to put it in the in progress branch. Can you remove the reference to it in CMakeLists?

2021-06-02 00:38 UTC, jiguba commented on src/sound/src/hashtable.c
> +#include "sound/sound.h"
hashtable.c was moved to inprogress branch and CMake dependency file on hashtable.c was removed

2021-06-02 04:44 UTC, ecoble requested changes

2021-06-02 04:44 UTC, ecoble commented on src/sound/src/sound.c
> +int main() {
You should not need a main function in this file, sorry for not catching that before.

2021-06-02 04:44 UTC, ecoble commented on src/sound/sandbox/sound.c
> +#include "common/uthash.h"
This file looks like a duplicate of the one in the src folder, it should be removed and referenced with include statements if necessary.

2021-06-02 17:51 UTC, ecoble approved these changes
LGTM! Great job!

2021-06-02 21:28 UTC, jiguba approved these changes

2021-06-02 21:29 UTC, jiguba approved these changes

2021-06-02 21:29 UTC, jiguba approved these changes

2021-06-02 21:30 UTC, jiguba approved these changes

2021-06-02 22:11 UTC, merged

2021-06-02 22:26 UTC, jiguba commented
Closing statement: The purpose of this pull request was to implement the audio module for chiventure. The sound header file is able to access the external SDL2 library and a demo audio program has been created in the examples directory that shows an example audio program using the SDL2 functions and data structures. Future sound teams will be able to modify and improve the foundation, by familiarizing themselves further with the SDL2 library and finding ways to incorporate sound into chiventure.

2021-06-07 20:13 UTC, ecoble commented
Issue Score: ✔️+

Comments:
Great work creating example programs and setting up the structure of the sound module! When reviewing pull requests, you should leave some kind of comment, even if it's just something like "looks good," so that others know you have looked over the changes. Also, it is better to have several smaller pull requests instead of one large one, in this case this pull request could have been split into one for the design of the modules and one for the example programs, or even several for the different example programs.

<!-- {"score": "check-plus"} -->