Update to help function
uchicago-cs/chiventure pull request #1144
Opened 2021-05-29 02:45 UTC by mjgoodman321

As several new functions have been added over the course of the quarter, there was a need to add entries for them to the help text that is displayed in Chiventure. There was a small issue with the branch being used to implement this (see linked Issue), but any problems from that should have been resolved by now.

Linked to Issue #1084

2021-05-30 00:16 UTC, Beza20 commented
I love it. Made important contributions to chiventure and really well commented code.

2021-05-30 00:16 UTC, Beza20 approved these changes

2021-05-31 10:53 UTC, ecoble requested changes

2021-05-31 10:53 UTC, ecoble commented on include/cli/operations.h
> +
Let's remove this line to avoid changing this file.

2021-05-31 10:53 UTC, ecoble commented on include/cli/parser.h
> +
Same here with removing this line.

2021-05-31 10:53 UTC, ecoble commented on include/game-state/game_state_common.h
> +
Same with removing these lines.

2021-05-31 10:53 UTC, ecoble commented on include/game-state/game_action.h
> -
Same with adding this line back.

2021-05-31 10:53 UTC, ecoble commented on src/cli/src/operations.c
> +                if(strcmp(tokens[0], "take") == 0 || strcmp(tokens[0], "pickup") == 0)
The work in this file looks like it was duplicated from the case insensitivity PR, watch out in case it causes conflicts.

2021-05-31 10:53 UTC, ecoble commented on src/game-state/src/game.c
> +{
Same about this line.

2021-05-31 10:53 UTC, ecoble commented on src/game-state/src/item.c
> +
Same for line.

2021-05-31 10:53 UTC, ecoble commented on src/game-state/src/path.c
> +
Same for line

2021-05-31 10:53 UTC, ecoble commented on src/game-state/src/room.c
> +
Same for line

2021-05-31 10:53 UTC, ecoble commented on src/wdl/src/load_item.c
> +    if(curr == NULL)
Space after if, and if there are no brackets please put a new line after return NULL.

2021-05-31 13:33 UTC, mjgoodman321 commented on src/game-state/src/game.c
> +{
I'm a little confused about what I'm supposed to change here, because my create_connection function is identical to what's currently in dev

2021-05-31 17:25 UTC, ecoble commented on src/game-state/src/game.c
> +{
There is an extra tab character, that is what the dark green block represents in the difference.

2021-05-31 17:25 UTC, ecoble commented on src/game-state/src/game.c
> +{
Looks like it has been fixed though.

2021-05-31 17:27 UTC, ecoble commented on src/cli/src/shell.c
> +        "LOAD [PATH]\n"
I think LOAD is still not implemented, the command that was fixed was LOAD_WDL, but I may be mistaken.

2021-05-31 18:27 UTC, mjgoodman321 commented on src/game-state/src/game.c
> +{
No it's still there, I see it now. I guess you just couldn't see it anymore because it was no longer different than the previous commit? Regardless, I fixed it now

2021-05-31 18:28 UTC, mjgoodman321 commented on src/cli/src/shell.c
> +        "LOAD [PATH]\n"
Thank you for catching that, those two refer to the same operation (because there ISN'T a pure LOAD function), but I'm going to change it so that LOAD_WDL is called with the LOAD command because I feel like that's more intuitive

2021-05-31 21:59 UTC, ecoble approved these changes
LGTM!

2021-06-01 13:29 UTC, merged

2021-06-07 20:06 UTC, ecoble commented
Issue Score: ✔️+

Comments:
Great job updating the help text! Even though it's a small issue, it is important to keep documentation up to date. Be sure to include a closing statement for PRs, even if they are small ones.

<!-- {"score": "check-plus"} -->

2021-06-07 20:19 UTC, mjgoodman321 commented
Closing statement: Help text has been updated and now displays information for the newly implemented features of HIST, TALK, QUIT, and ITEMS, as well as up to date information on the LOAD feature.