Added npc_one_move function and npcs_in_room_operation
uchicago-cs/chiventure pull request #1145
Opened 2021-05-29 04:03 UTC by mbutera17

This pull request contains steps towards our eventual goal of player action leading to an NPC with definite movement moving (we were unable to complete this goal). We did create a new function called `npc_one_move` which will handle the entirety of movement of one NPC. Previously, we had functions to add/remove an NPC from an `npcs_in_room` struct and we had a way to move an NPC down its path in its `npc_mov` struct (`movement` field in NPC struct), but we did not have one function to do both of these and thus completely "move" an NPC. 

Summary of major changes:
Added `npc_one_move` and `npc_one_move_helper` functions
Added npcs_in_room_operation function (CLI)
Added tests for `npc_one_move`

2021-05-31 03:33 UTC, torresszy commented on src/cli/src/operations.c
> +        return "Error! We need a loaded room to check items.\n";
It should be `We need a loaded room to check NPCs`

2021-05-31 03:34 UTC, torresszy commented on src/npc/src/npc_move.c
> +  room_list_t *elt;
indentation

2021-05-31 03:36 UTC, torresszy commented on include/npc/npc_move.h
> + * SUCCESS, OR FAILURE
It should return 0, 1, or 2 instead of just `SUCCESS` or `FAILURE`

2021-05-31 03:37 UTC, torresszy commented on tests/npc/test_npc_move.c
> +    room_t *test_room = room_new("test room", "test", "test test");
indentation

2021-05-31 03:39 UTC, torresszy commented on tests/npc/test_rooms_npc.c
> +	room_t *test_room2;
indentation

2021-05-31 03:42 UTC, torresszy requested changes
Looks good overall, I have made a few comments (mostly minor formatting issues) but don't see many problems with the implementation itself

2021-05-31 03:49 UTC, torresszy commented on src/cli/src/operations.c
> +        return "Error! We need a loaded room to check items.\n";
This function is updated now

2021-05-31 03:51 UTC, torresszy approved these changes
I think it's good to go now

2021-05-31 18:38 UTC, lilyehsani requested changes
Great job! Added a few comments.

2021-05-31 18:38 UTC, lilyehsani commented on include/npc/rooms-npc.h
> +int npc_one_move_helper(npc_t *npc, npcs_in_room_t *old_npc_room,
Should this function be in the interface, or should we just move the documentation to the implementation? It seems to me like this is only a helper that will be called by npc_one_mov. Correct me if there is a situation where it might be called somewhere else.

2021-05-31 18:38 UTC, lilyehsani commented on src/cli/src/operations.c
> +    if(game == NULL || game->curr_room == NULL) {
Be consistent with spacing/bracket placement. You mostly use Allman style, so you should be able to fix this with the command `astyle --style=allman src/cli/src/operations.c` in the chiventure directory. See more here: https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation

2021-05-31 18:38 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +        LL_FOREACH(npc_mov->npc_mov_type.npc_mov_definite->npc_path, elt) {
Be consistent with spacing/bracket placement. You mostly use Allman style, so you should be able to fix this with the command `astyle --style=allman src/npc/src/npc_move.c` in the chiventure directory. See more here: https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation

2021-05-31 18:38 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +            head->room = head->next->room; // not sure if this is correct
What about this is unsure?

2021-05-31 18:38 UTC, lilyehsani commented on src/npc/src/rooms-npc.c
> +int room_id_cmp2(room_list_t *room1, room_list_t *room2)
Add comment explaining why we have both this and `room_id_cmp`

2021-05-31 18:38 UTC, lilyehsani commented on tests/npc/test_npc_move.c
> +    LL_FOREACH(npc_mov->npc_mov_type.npc_mov_definite->npc_path, elt) {
Be consistent with spacing/bracket placement. You mostly use Allman style, so you should be able to fix this with the command `astyle --style=allman tests/npc/test_npc_move.c` in the chiventure directory. See more here: https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation

2021-05-31 18:38 UTC, lilyehsani commented on tests/npc/test_npc_move.c
> +    npc_mov_t* npc_mov = npc_mov_new(NPC_MOV_INDEFINITE, test_room);
Move * over

2021-05-31 18:38 UTC, lilyehsani commented on tests/npc/test_npc_move.c
> +    cr_assert_eq(delete_room_llist(npc_mov->npc_mov_type.npc_mov_indefinite->npc_path), SUCCESS, "delete llist failed");
Split lines in this file to keep them under 80 characters.

2021-05-31 18:41 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +        LL_FOREACH(npc_mov->npc_mov_type.npc_mov_definite->npc_path, elt) {
Edit: I think this will be resolved in a different PR.

2021-05-31 22:38 UTC, torresszy commented on include/npc/rooms-npc.h
> +int npc_one_move_helper(npc_t *npc, npcs_in_room_t *old_npc_room,
I have hidden this helper function from the interface, now only `npc_one_move` is in `rooms-npc.h`

2021-05-31 22:38 UTC, torresszy commented on src/cli/src/operations.c
> +    if(game == NULL || game->curr_room == NULL) {
Update has been made

2021-05-31 22:38 UTC, torresszy commented on src/npc/src/npc_move.c
> +        LL_FOREACH(npc_mov->npc_mov_type.npc_mov_definite->npc_path, elt) {
Update has been made

2021-05-31 22:41 UTC, torresszy commented on src/npc/src/rooms-npc.c
> +int room_id_cmp2(room_list_t *room1, room_list_t *room2)
`room_id_cmp` existed as another helper function under `npc_move.c`. However, since `room_id_cmp` and `room_id_cmp2` are identical, I have made`room_id_cmp` a public function under `npc_move.h`, and removed `room_id_cmp2`. Now `room_id_cmp` will be used in both `npc_move` and `rooms-npc`

2021-05-31 22:41 UTC, torresszy commented on tests/npc/test_npc_move.c
> +    LL_FOREACH(npc_mov->npc_mov_type.npc_mov_definite->npc_path, elt) {
Update has been made

2021-06-01 17:53 UTC, lilyehsani requested changes
Thanks for the changes! One last tiny style thing then we should be good.

2021-06-01 17:53 UTC, lilyehsani commented on src/npc/src/rooms-npc.c
> +int npc_one_move_helper(npc_t *npc, npcs_in_room_t *old_npc_room, npcs_in_room_t *new_npc_room)
This line and next should be under 80 chars

2021-06-02 03:26 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-06-02 03:26 UTC, merged

2021-06-02 22:30 UTC, torresszy commented
This is the closing comment for this pull request; it has been merged successfully and all goals have been achieved. There were a few minor updates for formatting and merge conflict issues, but no major change since the beginning of this pull request. 

As stated in the opening statement, the main feature of this pull request are:
- `npcs_in_room_operation`, which is a CLI command function in `operation.h` that prints out all the NPCs alive in the current to the CLI
- `npc_one_move` in `npc_move.h`, which moves an NPC in the current room to the next room in the list of (a `room_list_t` struct) it will visit.
- tests for `npc_one_move` in `test_npc_move.c`

In the future, we anticipate there could be another function, `npc_move_all`, which builds on top of `npc_one_move` and moves all the NPCs in the current room to each of their next rooms. This should not be hard to implement, as we imagine it to just iterate through all the NPCs in the current room and call `npc_one_move` for each of them.

2021-06-07 03:16 UTC, lilyehsani commented
Issue Score: ✔️++

Comments:
Great work overall! The summary and closing of this PR are very thorough.

<!-- {"score": "check-plus-plus"} -->