Adding a Player Class Demo to chiventure
uchicago-cs/chiventure pull request #1146
Opened 2021-05-29 04:16 UTC by ideclue

(Closes #1098)

In issue #1098, we sought to create a demo to demonstrate the work we have done so far this quarter.

2021-05-29 04:45 UTC, jackcasey067 commented
Update: The demo will no longer segfault when run in the wrong directory anymore.  Instead, the demo_WDL() function will print an error message and abort (allowing the other mini-demos to run).  It is critical that the program is run from the root of the build directory.  I use this command to build and run the file:

```make examples && src/playerclass/examples/2021-demo```

2021-05-30 02:19 UTC, himaanir reviewed
Looks good!

2021-05-30 02:22 UTC, jackcasey067 commented on src/playerclass/examples/2021-demo.c
> + *  - buffer: Pointer to memory to store the input, or NULL (in which case input is ignored).
Good catch.  I updated the comment.

2021-05-30 02:27 UTC, himaanir approved these changes

2021-05-31 18:15 UTC, firatciftci requested changes
I've requested minor stylistic changes, but other than that everything looks good to me!

2021-05-31 18:15 UTC, firatciftci commented on src/playerclass/examples/2021-demo.c
> +    else
Make sure to have curly brackets around one-line if/else, for, and while loop blocks as well. (This applies for all occurrences of this in the PR)

2021-05-31 18:15 UTC, firatciftci commented on src/playerclass/examples/2021-demo.c
> +     * it, it might be better to forgo user input (except for pauses) */
The `*/` at the end of this line should be put at the bottom, so the block comment would look like the following:
```c
    /* This was just code I had lying around. You don't necessarily need to use
     * it, it might be better to forgo user input (except for pauses)
     */
```

2021-05-31 18:15 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (base_tree == NULL && second_tree == NULL){
Make sure to leave a blank space between `)` and `{` at the end of this line.

2021-05-31 18:15 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (base_tree == NULL){
Make sure to leave a blank space between `)` and `{` at the end of this line.

2021-05-31 18:15 UTC, firatciftci commented on src/playerclass/src/class.c
> +    else if (second_tree == NULL){
Make sure to leave a blank space between `)` and `{` at the end of this line.

2021-05-31 18:15 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (base_tree != NULL){
Make sure to leave a blank space between `)` and `{` at the end of this line.

2021-05-31 18:48 UTC, jackcasey067 commented on src/playerclass/examples/2021-demo.c
> +     * it, it might be better to forgo user input (except for pauses) */
I ended up removing this comment, it no longer applies.

2021-05-31 19:00 UTC, jackcasey067 commented
I addressed the stylistic changes, so I am re-requesting @firatciftci for review.

2021-06-02 01:53 UTC, firatciftci approved these changes
Everything looks good to me!

2021-06-02 01:53 UTC, merged

2021-06-02 02:02 UTC, jackcasey067 commented
Closing comment:
After making some recommended stylistic changes, the branch was merged into dev.  The playerclass demo is now ready to be used in the presentation.

2021-06-06 20:44 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great work!

<!-- {"score": "check-plus-plus"} -->