Created an openworld demo game
uchicago-cs/chiventure pull request #1148
Opened 2021-05-29 14:35 UTC by wmingyan

This PR is related to issue #1039 for creating a monkey-patched demo game for openworld that showcases the following features we implemented this quarter:
- Level-oriented room generation, where a room is generated according to the player's level
- Recursive generation of rooms within a radius (n), where n layers of rooms are generated around the pivot room in the specified direction (north, south, east, and west in the demo game)

During the implementation of the demo game, a bug in roomspec_to_room that could cause segfault when calling game_free() is called was discovered and fixed.

2021-05-30 23:56 UTC, Justin08784 requested changes
Hardcoded gencontexts will enable us to preserve the current player_level between function calls. This means that implementing a "LEVELUP" CLI command to update player level (as we originally intended) should be possible. I will be making these changes.

2021-05-30 23:56 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +    roomspec_t *roomspec0 = roomspec_new("level_0_room", "A level-0 room.", "A room with difficulty level 0.", NULL);
roomspecs, gencontexts, speclists etc. can be hardcoded as global struct variables outside of the main function. level_gen and recursive_gen can simply use and update these variables instead of having to redefine them with every call. This prevents the addition of duplicate rooms and allows us to call level_gen and recursive_gen multiple times.

2021-05-31 13:17 UTC, Justin08784 approved these changes
I have addressed my own changes requested above. See [my comment](https://github.com/uchicago-cs/chiventure/issues/1039#issuecomment-851478701) on the issue to get a more detailed summary of changes (I also fixed a [bug](https://github.com/uchicago-cs/chiventure/issues/1039#issuecomment-851188026) for filter_speclist_with_difficulty()). 

Each CLI command can now be called arbitrarily many times. LEVELGEN now takes a num_rooms token/parameter.

2021-05-31 13:47 UTC, ahmed-sumaiya approved these changes
Looks good to me!

2021-05-31 15:35 UTC, MaxineK36 requested changes
This looks great! Just a couple of clarifications/things to change to make this example useful for future integration efforts

2021-05-31 15:35 UTC, MaxineK36 commented on src/openworld/examples/CMakeLists.txt
> +add_custom_target(openworld-examples
nit: might be better to call this something like `openworld-demo-2021`

2021-05-31 15:35 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    item_hash_t *items = random_items(roomspec);
Can you say more about the change being made here?

2021-05-31 15:35 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +            speclist_t *curr_copy = speclist_new(curr->spec);
& here?

2021-05-31 15:35 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +   Pre-declaring roomspecs like this is important as we need to preserve
In a full integration, would these go in the chiventure `ctx` struct?

2021-05-31 15:35 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +
Would these go in `ctx` as well?

2021-05-31 15:35 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
Are there existing functions for deleting rooms or does this need to be done manually?

2021-05-31 15:35 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +    add_room_to_game(ctx->game, orig_room);
Given that you're adding this one back, there may be some `free_rooms` or similar function; if so, please use that

2021-06-01 11:01 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +    item_hash_t *items = random_items(roomspec);
I don't think this change is necessary. Will undo.

2021-06-01 11:03 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +            speclist_t *curr_copy = speclist_new(curr->spec);
Creates a copy of the speclist node to be added to the filtered speclist (output). Previously it was just yoinking nodes out of the unfiltered speclist (input), which caused some problems.

2021-06-01 11:05 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +   Pre-declaring roomspecs like this is important as we need to preserve
I think so, but am not 100% sure.

2021-06-01 11:06 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +
Yes. But instead of having multiple fields for roomspecs, levelspecs etc. I think it would be best to wrap them under gencontext as a sort of neat package for all generation-related info.

2021-06-01 11:10 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
Yes, there is `delete_all_rooms(room_hash_t *rooms)`–– found [here](https://github.com/uchicago-cs/chiventure/blob/83f706a60e5d100082cb5438de4c4da4f0997631/src/game-state/src/room.c).

As you can see, this function's code is nearly identical to that of mine. However, if I just call `delete_all_rooms(ctx->game->all_rooms)` it crashes. 

Strangely, if I define an identical function `delete_all_rooms2(room_hash_t **rooms` <note the different parameter type>, it works just fine. Thoughts?

2021-06-01 11:27 UTC, Justin08784 commented on src/openworld/examples/CMakeLists.txt
> +add_custom_target(openworld-examples
Should I change the name of the .c file as well?

2021-06-01 16:25 UTC, MaxineK36 commented on src/openworld/examples/CMakeLists.txt
> +add_custom_target(openworld-examples
Yes

2021-06-01 16:26 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +
Ok, makes sense! Please note that in a comment in the demo file, and (if you're feeling up to it) it would be awesome to open up a backlog issue for this

2021-06-01 16:32 UTC, MaxineK36 reviewed
Responded to comments

2021-06-01 16:32 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
Hm, that's very odd. Have you figured out at all why it's happening/where the crash is coming from?

2021-06-01 16:32 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +            speclist_t *curr_copy = speclist_new(curr->spec);
Ok, sounds good

2021-06-01 16:32 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +   Pre-declaring roomspecs like this is important as we need to preserve
If they need to be declared before any open world functions are called, they'd need to be in the context struct, which you should note here.

2021-06-01 16:32 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +
Ok, makes sense! Please note that in a comment in the demo file, and (if you're feeling up to it) it would be awesome to open up a backlog issue for this

2021-06-01 17:14 UTC, Justin08784 commented on src/openworld/examples/CMakeLists.txt
> +add_custom_target(openworld-examples
UPDATE: 53d669f

Misc.:
While tinkering around, discovered that 'nuke' CLI command doesn't reset `game->curr_room` to original room. Fixed.

2021-06-01 17:28 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
Yes, it's `delete_all_rooms()`. See 868f13a.

To reproduce bug, 'make' debug2 in the openworld examples directory. The `debug2` program simply add 4 rooms to a hash and runs delete_all_rooms() to delete the rooms.

Running the core delete_all_rooms() results in segfault. Running my modified version frees all rooms without leaks (you can check using `valgrind ./debug2` as well).

In my experience, if we want to define a function that adds or deletes elements from a hash using standard uthash functions, the hash table parameter needs to be dereferenced by 1 (so taking a `struct_hash_t**` instead of `struct_hash_t*`). e.g.
```
add_roomlevel_to_hash(&roomlevels, lvl0_roomname, 0); // makes use of HASH_ADD_STR
int add_item_to_hash(item_hash_t **ht, item_t *new_item); // makes use of HASH_ADD_STR
```
In fact, if there are other functions like delete_all_rooms(), I don't how they are functioning properly.

2021-06-01 18:33 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +   Pre-declaring roomspecs like this is important as we need to preserve
Noted: 0edd6b4

2021-06-01 18:45 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +            speclist_t *curr_copy = speclist_new(curr->spec);
Noted: b4ca0d9

2021-06-02 04:19 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
@Justin08784 which other functions are you referring to?

2021-06-02 05:12 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
This is the only other example I am aware of so far. 
```
int delete_all_paths(path_hash_t *hash);
```
Every other function that uses uthash macros directly within its function scope always takes the hash table dereferenced by 1 (`struct_hash_t **`). I've added even more examples to prove my point in the above comment.

2021-06-02 05:34 UTC, MaxineK36 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
@Justin08784 Ok, thanks for tracking that down!
It looks like this function is only called one other place; if you can switch the `delete_all_rooms` function to match the `delete_all_rooms2` function you wrote, and it allows both your demo and the current chiventure to work without crashing, please go ahead and do that! 

If you encounter issues/it won't work with both, let me know, and in that case you'd leave what you have in your demo and we'd make a bug issue for the backlog so that this can be taken care of in future years.

2021-06-02 06:35 UTC, Justin08784 commented on src/openworld/examples/openworld_example.c
> +    HASH_DELETE(hh, ctx->game->all_rooms, orig_room);
UPDATE: 82afba1

Changes summarized [here](https://github.com/uchicago-cs/chiventure/issues/1039#issuecomment-852776759).

2021-06-02 15:54 UTC, MaxineK36 approved these changes
Looks great!

2021-06-02 15:58 UTC, merged

2021-06-02 19:51 UTC, Justin08784 commented
Closing statement:
Comments by reviewers have been addressed and branch `openworld/add-itemspec` is now merged into dev. The sample game `openworld-demo-spr21` can now be made and run in the `build/src/openworld/examples` directory. This demo game demonstrates level-oriented generation and recursive generation.

Misc Changes:
- filter_speclist_with_difficulty() no longer alters the unfiltered speclist – [(see post)](https://github.com/uchicago-cs/chiventure/issues/1039#issuecomment-851188026)
- delete_all_rooms() now takes a `room_hash_t**` parameter [(see post)](https://github.com/uchicago-cs/chiventure/issues/1039#issuecomment-852776759)–– similar changes should be made to other functions

2021-06-03 16:36 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Excellent work! Your links in the closing statement are particularly useful.

<!-- {"score": "check-plus-plus"} -->