NPC2 game demo bug fixes related to recent merges
uchicago-cs/chiventure pull request #1151
Opened 2021-05-31 23:43 UTC by jeyeong

Recent merges (specifically, case insensitivity) resulted in issues within the NPC and dialogue modules. This pull request fixes those issues. Specifically:
- The issue of items not being able to be found from game->all_items
- The issue of NPCs not being able to be talked to
- The issue of dialogue actions resulting in the game crashing
- Certain tests (Criterion assert_eq's) not passing due to remedies to the above issues

2021-06-01 00:49 UTC, matiasp-10 approved these changes
Looks good to me!

2021-06-01 03:33 UTC, pkasner requested changes
I was looking at the closed PR for the CLI's case insensitivity issue, and it looks like we made a lot of mistakes similar to what they did initially. Also it's possible that some of the functions that some of the calls to case_insensitize_string() would be better done if we make sure everything's lowercase right from when they're loaded from the WDL. For example if we insensitized the calls to get_item_from_game when loading the npc's inventory from wdl, then our hash find doesn't need to be insensitized every other time chiventure looks for an item.

2021-06-01 03:33 UTC, pkasner commented on src/game-state/src/game.c
> +    HASH_FIND(hh_all_items, game->all_items, case_insensitized_string(item_id),
The case_insensitized_string() function mallocs a new string and needs to be freed.

2021-06-01 03:33 UTC, pkasner commented on src/game-state/src/game.c
> +    HASH_FIND(hh, game->all_npcs, case_insensitized_string(npc_id),
Need to be able to free the case_insensitized_string. Alternatively, does this become redundant because we changed the npc's npc_id to be lowercase when we call npc_new?

2021-06-01 03:33 UTC, pkasner commented on src/npc/src/dialogue.c
> +    action_id = case_insensitized_string(action_id);
I don't think you're supposed to overwrite a parameter like this. I think it's best to make a new char *action_id_case. Additionally, the output of case_insensitized_string should probably be freed after it is strdup/strcpy'd into the struct

2021-06-01 03:33 UTC, pkasner commented on src/npc/src/npc.c
> +    npc_id = case_insensitized_string(npc_id);
See my comment about action_id

2021-06-01 03:33 UTC, pkasner commented on src/npc/src/npc.c
> +    HASH_FIND(hh, npc->inventory, case_insensitized_string(item_id),
Output of the case function needs to be freed.

2021-06-01 13:35 UTC, jeyeong commented on src/game-state/src/game.c
> +    HASH_FIND(hh_all_items, game->all_items, case_insensitized_string(item_id),
Changed!

2021-06-01 13:35 UTC, jeyeong commented on src/game-state/src/game.c
> +    HASH_FIND(hh, game->all_npcs, case_insensitized_string(npc_id),
Changed!

2021-06-01 13:40 UTC, jeyeong commented on src/game-state/src/game.c
> +    HASH_FIND(hh, game->all_npcs, case_insensitized_string(npc_id),
The npc_id provided here may not always be lower-case (this was causing a certain test to fail), unless we convert everything to lower-case at the WDL-to-game translation stage (which I think is good to do for the long term), I thought it would be a good safeguard to convert all strings passed into this function into lower-case.

2021-06-01 13:41 UTC, jeyeong commented on src/npc/src/dialogue.c
> +    action_id = case_insensitized_string(action_id);
Changed!

2021-06-01 13:41 UTC, jeyeong commented on src/npc/src/npc.c
> +    npc_id = case_insensitized_string(npc_id);
Changed!

2021-06-01 13:41 UTC, jeyeong commented on src/npc/src/npc.c
> +    HASH_FIND(hh, npc->inventory, case_insensitized_string(item_id),
Changed!

2021-06-01 13:44 UTC, jeyeong commented
I definitely agree. A more efficient implementation would be to convert everything to lower-case right from the start, i.e. the WDL-to-game translation stage. If you have the time to work on that, please go ahead!

2021-06-01 15:50 UTC, MaDDylan requested changes
Great job tracking down the source of the errors! Everything looks good to me, just did a complete run-through of the demo again. Although there was one thing I was wondering, in the mom's dialogue do we want the second quip "Finding wild pokemon!" to be conditional on talking to oak/ after receiving a pokeball?

2021-06-01 17:01 UTC, pkasner approved these changes
Everything looks good now!

2021-06-01 20:49 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-06-02 03:48 UTC, MaDDylan approved these changes

2021-06-02 15:44 UTC, merged

2021-06-07 03:19 UTC, lilyehsani commented
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- Like issues, PRs require closing comments. When an PR is done, you should include a final comment summarizing what was merged to `dev` and what work remains to be done, if any.

<!-- {"score": "check-plus"} -->