Quests/change id format
uchicago-cs/chiventure pull request #1237
Opened 2022-05-01 14:42 UTC by Castel-Jaloux

Changed the type of quest_id from long int to char* to improve usability. Changed the appropriate values in all functions and function calls, as well as tests, to reflect this alteration.

2022-05-01 18:28 UTC, JSerf02 approved these changes
Changes look good and passes all tests, so not really much else to say. We should take note, though, that when we eventually improve our tests [(Issue #1165)](https://github.com/uchicago-cs/chiventure/issues/1165), we should add tests for multiple different ids instead of using the same id for every quest.

2022-05-02 21:12 UTC, philipchenaux requested changes
Generally looks good, one very minor comment. But if we can get that fixed quickly, then it should likely be good to merge and will count for the second sprint.

2022-05-02 21:12 UTC, philipchenaux commented on src/quests/src/quests_state.c
> +    q->quest_id = strdup(quest_id);
It is good practice to use the string-safe version of strdup which is strndup.

2022-05-02 23:18 UTC, Castel-Jaloux commented on src/quests/src/quests_state.c
> +    q->quest_id = strdup(quest_id);
The suggested edit has been updated on the branch and pushed. Additionally, some of the edits to quest-example.c that ended up being made in the other pull request were moved here as well for consistency (since this is the pull request that those changes are related to).

2022-05-03 01:17 UTC, philipchenaux approved these changes
Looks good to me, happy to merge this into the code base.

2022-05-03 01:49 UTC, JSerf02 approved these changes
Looks good. Nice job using a #define to store the max number of characters in the id!

2022-05-03 01:59 UTC, merged

2022-05-18 16:22 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Another great pull request, good job!

<!-- {"score": "excellent", "minor": true} -->