Refactoring the legacy custom-scripts source code
uchicago-cs/chiventure pull request #1248
Opened 2022-05-02 17:27 UTC by tatmaca

The custom-scripts team decided to refactor the legacy source code, as it was previously all stored in one large, difficult to read source file. After reviewing the code, we decided that we could refactor the source code into four modules: the arguments (arg) module, the object_type (obj) module, the lua module, and the implement into game (get) module. 

We decided that the "arg" and "obj" modules would be necessary as it stored the creation and initialization of the two main structs used in the custom-scripts source code. We decided that the "lua" module was necessary as it included all of the unique functions that allowed our code to interact with Lua. We decided that the "get" module was necessary as it stores all the code that members of other developments teams would be interested in looking at in order to get their object_types to interact with their unique custom scripts.

2022-05-02 18:13 UTC, RamarkoB commented
It seems that the includes are not loading properly. Looking them over now

2022-05-04 20:32 UTC, jackjackkimkim approved these changes
The refactoring of the code looks good! The original document was also left untouched so it can be compared

2022-05-08 22:05 UTC, ecoble requested changes
Nice work! I think a lot these functions can be combined through use of the union data structure. Also the C library UTLIST should be used for making linked lists, we do not need to recreate this data structure ourselves. Also, please delete the old files, we will still have reference to them through the Git history.

2022-05-08 22:05 UTC, ecoble commented on include/custom-scripts/arg_custom_type.h
> +    struct arg_t *prev;
Is this meant to be a linked list? If so, the library UTLIST should be used. 

Here are resources on UTLIST: https://troydhanson.github.io/uthash/utlist.html

2022-05-08 22:05 UTC, ecoble commented on include/custom-scripts/arg_custom_type.h
> +arg_t *arg_t_bool(bool b);
For these next four functions, I think they can be consolidated into one. You can pull out the union type in the arg_t struct, and then just pass a union type to these functions.

2022-05-08 22:05 UTC, ecoble commented on include/custom-scripts/get_custom_type.h
> +/**
Similarly, these functions can be consolidated.

2022-05-08 22:05 UTC, ecoble commented on include/custom-scripts/obj_custom_type.h
> +object_t *obj_t_bool(bool b, char *lua);
Similar comment about consolidating these 4 functions.

2022-05-08 22:05 UTC, ecoble commented on include/custom-scripts/obj_custom_type.h
> +object_t *obj_add_arg_bool(object_t *obj, bool b);
Here are well

2022-05-08 22:05 UTC, ecoble commented on src/custom-scripts/src/arg_custom_type.c
> +arg_t *arg_t_bool(bool b) {
To consolidate these 4 functions, you will also need to add an arg with the enum for type that you can assign to arg->type. You can also use this enum to create a switch statement for assigning data.

2022-05-08 22:05 UTC, ecoble commented on src/custom-scripts/src/arg_custom_type.c
> +arg_t *arg_t_add(arg_t *head, arg_t *add) {
UTLIST should be used instead of implementing this logic by hand.

2022-05-08 22:05 UTC, ecoble commented on src/custom-scripts/src/get_custom_type.c
> +
You can use the type here too for creating a switch statement to combine these functions

2022-05-08 22:05 UTC, ecoble commented on src/custom-scripts/src/lua_custom_type.c
> +    while (head != NULL) {
This iteration can be done using UTLIST as well.

2022-05-08 22:05 UTC, ecoble commented on src/custom-scripts/src/obj_custom_type.c
> +object_t *obj_t_bool(bool b, char *lua)
Similar comments here about combining.

2022-05-08 22:05 UTC, ecoble commented on src/custom-scripts/src/obj_custom_type.c
> +object_t *obj_add_arg_bool(object_t *ot, bool b) {
Here as well.

2022-05-24 18:48 UTC, ecoble commented on .gitmodules
> +[submodule "include/custom-scripts/--foorce"]
UTLIST and UTHASH are already included in this project, you don't need to git submodules. You can just include UTLIST or UTHASH by adding `#include "common/utlist.h"` at the top of the file.

2022-05-24 19:02 UTC, ecoble requested changes
Nice job on with consolidating these functions! Just a couple things on style on UTLIST.

2022-05-24 19:02 UTC, ecoble commented on include/custom-scripts/arg_custom_type.h
> +#include "utlist.h"
So here, do `#include common/utlist.h`

2022-05-24 19:02 UTC, ecoble commented on src/custom-scripts/src/arg_custom_type.c
> +arg_t *arg_t_add(arg_t *head, arg_t *add) {
This could still use utlist, please take a look at the documentation [here](https://troydhanson.github.io/uthash/utlist.html#_list_operations). You can use the DL_APPEND method.

2022-05-24 19:02 UTC, ecoble commented on src/custom-scripts/src/get_custom_type.c
> +    case BOOL_TYPE:
Indentation is off in this switch statement.

2022-05-24 19:02 UTC, ecoble commented on src/custom-scripts/src/get_custom_type.c
> +        if (ot->is_lua) {
These lines (10-12), are the same through all the switch statements, can this part be moved out to the front of the switch statement and then within the switch statement just start with returning the result?

2022-05-24 19:02 UTC, ecoble commented on src/custom-scripts/src/lua_custom_type.c
> +    while (head != NULL) {
Same comment here about UTLIST, look at DL_FOREACH

2022-05-24 21:05 UTC, tatmaca commented on src/custom-scripts/src/get_custom_type.c
> +        if (ot->is_lua) {
i tried this earlier, but it really breaks down the program for some reason :( im not entirely sure why but i think its helpful that its defined locally in the scope of the switch statements? [Here](https://github.com/uchicago-cs/chiventure/runs/6581567977?check_suite_focus=true) is the error report it gave me. I tried debugging, but I think all the additions that would come with fixing this offsets the benefit of moving this statement outside of the switch. Let me know your thoughts!

2022-05-25 19:10 UTC, ecoble requested changes
Nice work using the utlist modules! A couple more changes, mostly fixing header comments.

2022-05-25 19:10 UTC, ecoble commented on .gitmodules
> +[submodule "include/custom-scripts/--foorce"]
Please remove the submodules and utlist.h

2022-05-25 19:10 UTC, ecoble commented on include/custom-scripts/obj_custom_type.h
> + * - the boolean to be added
data_type_t is missing from header comment

2022-05-25 19:10 UTC, ecoble commented on include/custom-scripts/get_custom_type.h
> + * - d: operating data type
d is no longer a parameter

2022-05-25 19:10 UTC, ecoble commented on include/custom-scripts/get_custom_type.h
> + * - bool from ot
"data from ot"

2022-05-25 19:10 UTC, ecoble commented on include/custom-scripts/obj_custom_type.h
> + * - pointer to an object struct containing the bool
Update header comment

2022-05-25 19:10 UTC, ecoble commented on include/custom-scripts/obj_custom_type.h
> + * obj_add_arg_bool adds a bool to the argument linked list of the object_t
Update header comment name

2022-05-25 19:10 UTC, ecoble commented on src/custom-scripts/src/get_custom_type.c
> +            if (ot->is_lua) {
Lines 10-12, 17-19, are repeated throughout the switch statement. Can you move this out of the switch statement and then just have the data type dependent code each case?

2022-05-25 19:10 UTC, ecoble commented on tests/custom-scripts/get_custom_typ.h
> + * bool_t_get() returns a bool from an object_t struct
Update header comment

2022-05-25 19:10 UTC, ecoble commented on tests/custom-scripts/obj_custom_typ.h
> + * obj_t_bool() creates an object_t struct containing a boolean
update header comment

2022-05-25 19:10 UTC, ecoble commented on tests/custom-scripts/obj_custom_typ.h
> + * obj_add_arg_bool adds a bool to the argument linked list of the object_t
update header comment

2022-05-26 18:46 UTC, jackjackkimkim approved these changes

2022-05-26 18:46 UTC, jackjackkimkim commented on tests/custom-scripts/test_types.c
> +#include "get_custom_typ.h"
I looked through the test cases and they all seem to reflect the refactoring of data quite well. Thanks Togay!

2022-05-26 18:46 UTC, jackjackkimkim commented on tests/custom-scripts/utlist.h
> +/*
Nice, this reflects the change that Elizabeth asked for earlier with the addition of utlist.

2022-05-26 19:33 UTC, ecoble requested changes
Almost there! Some of the header comments still need to be updated to reflect the new data types. Also utlist.h still needs to be removed.

2022-05-26 19:33 UTC, ecoble commented on include/custom-scripts/arg_custom_type.h
> +/**
Header comment

2022-05-26 19:33 UTC, ecoble commented on tests/custom-scripts/arg_custom_typ.h
> + * Creates an argument structure with the specified boolean
Header comment

2022-05-26 19:33 UTC, ecoble commented on tests/custom-scripts/get_custom_typ.h
> + * bool_t_get() returns a bool from an object_t struct
Header comment

2022-05-26 19:33 UTC, ecoble commented on tests/custom-scripts/obj_custom_typ.h
> + * obj_t_bool() creates an object_t struct containing a boolean
Header comment

2022-05-26 19:33 UTC, ecoble commented on tests/custom-scripts/obj_custom_typ.h
> + * obj_add_arg_bool adds a bool to the argument linked list of the object_t
Header comment

2022-05-27 21:27 UTC, ecoble approved these changes
Great job!

2022-05-27 21:30 UTC, merged

2022-05-27 21:45 UTC, tatmaca commented
This issue is now closed! With the refactored code in place, the custom-scripts team is now able to merge our numerous demos which demonstrate the capabilities of Lua scripting as well as our final Demo which runs Lua in a sample Chiventure game!

2022-06-07 02:30 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice job making change requests on this PR, I know it was difficult at times! Ideally please try to finish tasks in the sprint they are assigned to.

<!-- {"score": "excellent", "minor": false} -->