Npc/1240 repeat room in movement path bug
uchicago-cs/chiventure pull request #1268
Opened 2022-05-02 23:48 UTC by bvvill

2022-05-04 00:44 UTC, bvvill commented
> changed reverse_path so that it supports NPCs with both a definite and indefinite movement path. I also edited move_npc_indefinite so that the movement path is reversed once the end is reached, but the move backward is not followed through, staying true to the original documentation of the function in npc_move.h

I decided to to commit these changes to this branch because they are changes I would've made with more time with this issue

2022-05-05 02:57 UTC, bvvill commented
summary of changes:

- addition of `unsigned int npc_path_pos` into the `npc_mov_t` struct, which keeps track of the current location of the NPC within its movement path

- a function to get this value, `track_npc_path_pos`, has also been implemented
- addition of `uint8_t npc_path_reversed` into the `npc_mov_t` struct, which is 0 if the movement path is in the original order/direction, or 1 if the path is in the reverse/opposite order/direction
   
- a function to get this value, `track_npc_path_reversed`, has also been implemented
- for NPCs with definite paths, the `reverse_path` function was edited to flip this member between 0 and 1 whenever called.
- `npc_mov_init` was edited to assign the initial values of the newly added members to be 0
- To fix the bug described earlier, functions using the `char *room_id` to search through the movement path (which is in a linked list), such as `mov_npc_definite` and `mov_npc_indefinite`, were edited to go through the linked list using the values of the `npc_path_pos` and `npc_path_reversed` members, and to (in/de)crement an NPC's `npc_path_pos` accordingly.
- `get_npc_num_rooms` now uses the efficient `LL_COUNT` macro instead of using `LL_FOREACH` and explicitly defining the counting

2022-05-06 22:37 UTC, emilybae1705 reviewed
npc_path_reversed is tracking whether an NPC is moving along its path in the original or reversed direction where 0 indicates original and 1 indicates reversed direction. To make this idea more concrete, maybe you could make the struct into an enum where ORIGINAL=0, REVERSED=1. This could possibly help avoid confusion down the line for future developers of the NPC movement module as well.

2022-05-06 22:44 UTC, emilybae1705 reviewed
Additionally, in `npc_move.c` _lines 176-180_, `head` is assigned to different `npc_path` values depending on whether the `mov_type` is DEFINITE or INDEFINITE. The original implementation only accounted for the DEFINITE case as an input to the LL_FOREACH_SAFE function. I wasn't sure whether this was intentional, but after talking to @bvvill I've confirmed that he intentionally made this change because the previous implementation did not account for the INDEFINITE case (npcs move to a different room after a certain time interval passes). Accounting for the indefinite case resolves any bug in npc movement where an npc should move to a different location despite having no definite choice of movement made by a player in the CLI.

2022-05-07 05:06 UTC, emilybae1705 reviewed
`LL_COUNT()`'s implementation uses `LL_FOREACH()` and not `LL_FOREACH_SAFE()`, which to my knowledge is a safer version of `LL_FOREACH()` as it accounts for the case when the number of elements in a list changes. Would this be a problem for your `LL_COUNT()` implementation in _line 223_ of `npc_move.c`? I don't know the details of the npc movement module so I'm not entirely sure, but it might be a consideration you need to make?

2022-05-07 18:03 UTC, bvvill commented
> `LL_COUNT()`'s implementation uses `LL_FOREACH()` and not `LL_FOREACH_SAFE()`, which to my knowledge is a safer version of `LL_FOREACH()` as it accounts for the case when the number of elements in a list changes. Would this be a problem for your `LL_COUNT()` implementation in _line 223_ of `npc_move.c`? I don't know the details of the npc movement module so I'm not entirely sure, but it might be a consideration you need to make?

`LL_FOREACH_SAFE` is the same as `LL_FOREACH`, it just has an extra parameter in case the pointer to the next step in the linked list step is named something other than `*next`, which is not the case here, so `LL_COUNT` is fine.

2022-05-07 18:07 UTC, bvvill commented
> npc_path_reversed is tracking whether an NPC is moving along its path in the original or reversed direction where 0 indicates original and 1 indicates reversed direction. To make this idea more concrete, maybe you could make the struct into an enum where ORIGINAL=0, REVERSED=1. This could possibly help avoid confusion down the line for future developers of the NPC movement module as well.

I think I agree with using an enum here to avoid confusion in the future. I know other teams in chiventure have a defined range of enums they use so that everyone's not using enums that equal zero or one, but I don't think our team has a defined range yet, I'll ask Lily and then I'll implement an enum for this.

2022-05-09 00:44 UTC, bvvill commented
> I know other teams in chiventure have a defined range of enums they use so that everyone's not using enums that equal zero or one, but I don't think our team has a defined range yet, I'll ask Lily and then I'll implement an enum for this.
To correct/clarify myself, other teams making enums for use within the `tid_t`` struct were given a range of values to work with so there wasn't any overlap, but that is not a concern here. Also, an enum (`npc_path_direction_t`) for npc path direction has been implemented, as discussed above.

2022-05-09 22:22 UTC, emilybae1705 approved these changes
I have reviewed the pull request and it looks good! @bvvill has incorporated the feedback I gave previously and all the necessary changes have been made. Overall, I see no errors in the code and changing the npc_path_direction_t struct into an enum has made it easier to follow the implementation details. Looks like the request is ready to go!

2022-05-10 03:03 UTC, lilyehsani requested changes
Looks really good! Just a few comments, mostly stylistic.

2022-05-10 03:03 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +unsigned int track_npc_path_pos(npc_mov_t *npc_mov)
I think it would fit chiventure conventions more if these were named `get_npc_path_pos` and `get_npc_path_direction`.

2022-05-10 03:03 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +    if (npc_mov->mov_type == NPC_MOV_DEFINITE) {
Need to be consistent with bracket placement: chiventure uses [Allman style](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation).

2022-05-10 03:03 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +        LL_COUNT(npc_mov->npc_mov_type.npc_mov_definite->npc_path, elt, count);
Nice use of this macro!

2022-05-10 03:03 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +        (direction)? npc_mov->npc_path_pos-- : npc_mov->npc_path_pos++;
The question mark operator is cool, but for readability, I think we should expand this to a case or if statement checking the enum.

2022-05-10 03:03 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +        (direction)? npc_mov->npc_path_pos-- : npc_mov->npc_path_pos++;
Same as above.

2022-05-10 03:56 UTC, bvvill commented on src/npc/src/npc_move.c
> +unsigned int track_npc_path_pos(npc_mov_t *npc_mov)
Yes I agree

2022-05-10 03:57 UTC, bvvill commented on src/npc/src/npc_move.c
> +    if (npc_mov->mov_type == NPC_MOV_DEFINITE) {
I used the astyle command for this lol I didn't realize it would change so many files, sorry

2022-05-10 03:57 UTC, bvvill commented on src/npc/src/npc_move.c
> +        LL_COUNT(npc_mov->npc_mov_type.npc_mov_definite->npc_path, elt, count);
thank u !

2022-05-10 03:58 UTC, bvvill commented on src/npc/src/npc_move.c
> +        (direction)? npc_mov->npc_path_pos-- : npc_mov->npc_path_pos++;
Yes I agree

2022-05-10 20:50 UTC, lilyehsani approved these changes
Looks good to me! Approved.

2022-05-10 20:50 UTC, merged

2022-05-18 03:10 UTC, bvvill commented
summary of changes:

* addition of `unsigned int npc_path_pos` into the `npc_mov_t` struct, which keeps track of the current location of the NPC within its movement path
* a function to get this value, `get_npc_path_pos`, has also been implemented
* addition of `uint8_t npc_path_direction` into the `npc_mov_t` struct, which is `enum NPC_MOV_ORIGINAL` if the movement path is in the original order/direction, or `enum NPC_MOV_REVERSED` if the path is in the reverse/opposite order/direction
* a function to get this value, `get_npc_path_direction`, has also been implemented
* for NPCs with definite paths, the `flip_npc_path_direction` function was edited to flip this member between 0 and 1 whenever called.
* `npc_mov_init` was edited to assign the initial values of the newly added members to be 0
* To fix the bug described earlier, functions using the `char *room_id` to search through the movement path (which is in a linked list), such as `mov_npc_definite` and `mov_npc_indefinite`, were edited to go through the linked list using the values of the `npc_path_pos` and `npc_path_direction` members, and to (in/de)crement an NPC's `npc_path_pos` accordingly.
* `get_npc_num_rooms` now uses the efficient `LL_COUNT` macro instead of using `LL_FOREACH` and explicitly defining the counting

Commentary made during the progress leading to these changes can be found in #1240 and in this PR

2022-05-18 21:33 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! The summary and updates are very clear and thorough. When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests.

<!-- {"score": "excellent", "minor": false} -->