RPG Battles stat_t changes
uchicago-cs/chiventure pull request #1304
Opened 2022-05-06 18:40 UTC by nicholaswlee

We have created this pull request to create our new struct, stat_t. We have added a couple of new fields for this data structure:
`typedef struct stat {`

     int speed; //The combatant's speed. Used to determine who goes first in battle.

     int defense; //The defense value of the player. Used in damage calculations.

     int strength; //No description given; presumably the offensive value of the player used for damage calculation.

     int dexterity; //The dexterity of the player. Not implemented yet.

     int hp; //The current HP of the combatant.

     int max_hp; //The max HP of the combatant.
}
We have also edited our damage function to accommodate for critical rate in battle_ai.c and also made sure that all of the code in the code base is now aligned with stat_t.c. Additionally we have temporarily commented out all of the battle examples as we will refine them once move_t and battle_items_t have been made. To add on, we have changed our tests to work with the new stat_t.c struct. A couple of the NPC tests/examples had to be changed to work with stat_t. A new issue will have to be created to create further testing, but that should be done once move_t has become better. Information about our [implementation](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Stat-Changes-Design-Document) and [work](https://github.com/uchicago-cs/chiventure/issues/1275) can be found with these links.

2022-05-09 03:16 UTC, aliu65803 commented on include/battle/battle_flow.h
> +
I am a bit confused about this function. Is it calculating the accuracy or is it calculating whether the move will hit based on the accuracy of the user? If the second one, perhaps a better-suited description and name would be "Determines whether a move hits based on accuracy stat" and "hits_target".

2022-05-09 03:20 UTC, aliu65803 commented on include/battle/battle_structs.h
>      int xp;
I noticed that this does not include the int level that was written in the stat changes design document. What motivated this change?

2022-05-09 03:22 UTC, aliu65803 commented on src/battle/examples/battle_cli_example.c
>  }
Is it necessary to code all this out for the example to run?

2022-05-09 03:35 UTC, nicholaswlee commented on include/battle/battle_structs.h
>      int xp;
It is still in it you just need to scroll down. It is on line 55.

2022-05-09 03:36 UTC, nicholaswlee commented on src/battle/examples/battle_cli_example.c
>  }
Yes it is because we will be making a new example at the very end of the sprints anyway.

2022-05-09 03:39 UTC, nicholaswlee commented on include/battle/battle_flow.h
> +
Given the user's accuracy this function will return 1 or 0 indicating if the move hits or misses. This can be changed later when move_t makes changes to accuracy.

2022-05-09 03:51 UTC, aliu65803 commented on include/battle/battle_structs.h
>      int xp;
I see, thank you. It was not shown until I pressed something.

2022-05-09 04:02 UTC, aliu65803 commented on src/battle/src/battle_ai.c
> +}
Will the critical damage always be 1.5 times the normal damage? Perhaps there should be a way to allow the game designer to choose how much damage a critical attack does/a way for them to change this percentage each time a move is critical.

2022-05-09 04:02 UTC, aliu65803 commented on src/battle/src/battle_ai.c
> +    if(1){
Wouldn't this make it so that this is always true?

2022-05-09 04:08 UTC, aliu65803 commented on src/battle/src/battle_flow.c
> +            string = print_battle_move(b, b->turn, enemy_move);
A minor suggestion, but perhaps you can create a helper function for this that will take in who's turn it is and do this calculation based on that. This way, you don't need two blocks of code that are pretty similar.

2022-05-09 04:11 UTC, aliu65803 commented on src/battle/src/battle_print.c
> +    char* combatant_name;
This is a super small detail but I believe these two should be char *

2022-05-09 04:13 UTC, aliu65803 commented on src/npc/examples/battle_move_example_2021.c
> +    test_stats->crit = 0;
Indentation needed.

2022-05-09 04:22 UTC, aliu65803 commented on tests/battle/test_battle_print.c
> +}
Since the only difference between this test and the previous is that the second one has a move that is critical, would it be easier to make a helper that runs through a test of print battle move and make two tests, one with a player with an extremely low crit rate and one with a player with an extremely high crit rate? This would make it a bit like the homework, where we used a helper to test the functions such as on_segment and created various tests that just passed in different values.

2022-05-09 04:28 UTC, aliu65803 approved these changes
Overall, I believe that the code looks great. My comments are only to help the clarity of the code in parts that I felt were confusing or to point out small typos. There were no mistakes that I found that I thought would hinder whether the code would run, and the code is implemented in a way that is easy to follow. One small comment I have that is not in the other comments is for the design document for the stat changes, which says that the battle ends when the hp hits 0; however, there are ways for enemies to surrender once their hp is low enough, so it might be helpful to clarify this in the design document. Overall, I will approve this pull request because I think it runs well and is mostly easy to follow.

2022-05-10 04:17 UTC, lilyehsani requested changes
Looks good so far! I left handful of comments, mostly stylistic. I also agree with all of Angela's points, so please address them.

2022-05-10 04:17 UTC, lilyehsani commented on src/battle/src/battle_ai.c
> +    if(chance <= crit_chance){
Need to add some [spaces](https://www.target.com/p/women-s-essential-racerback-tank-top-all-in-motion/-/A-81503757?preselect=80881430#lnk=sametab) here, and switch to [Allman style](https://www.target.com/p/women-s-essential-racerback-tank-top-all-in-motion/-/A-81503757?preselect=80881430#lnk=sametab) for the braces (throughout).

2022-05-10 04:17 UTC, lilyehsani commented on src/battle/src/battle_default_objects.c
> +/*  --BATTLE ITEM TEST CHANGES TO BE IMPLEMENTED WITH BATTLE ITEM CHANGES
Sounds good. Make sure you've written the issue for this and placed it in the backlog. Same goes for the other examples.

2022-05-10 04:17 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +    if(!calculate_accuracy(b->player->stats->accuracy)){
Add spaces for style (guide linked previously).

2022-05-10 04:17 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +        enemy->stats->hp -= dmg;
This line should not be necessary since `dmg` is set to 0 just before. In fact, it looks like that line is likely not necessary either.

2022-05-10 04:17 UTC, lilyehsani commented on src/battle/src/battle_logic.c
> +    if((c->stats->hp + item->hp) > c->stats->max_hp){
Add spaces for style (guide linked previously).

2022-05-10 04:17 UTC, lilyehsani commented on src/battle/src/battle_print.c
> +    } else
`else` should be on its own line.

2022-05-10 04:17 UTC, lilyehsani commented on src/battle/src/battle_print.c
> +    snprintf(string, BATTLE_BUFFER_SIZE, "%s used %s! It missed!\n",
This is nit-picky but the phrasing here could potentially be better. How about `"%s used %s, but it missed!\n"` or `"%s tried to use %s, but it missed!\n"`?

2022-05-10 07:54 UTC, emilybae1705 commented on include/battle/battle_structs.h
>  typedef struct stat {
In our most recent meeting, we agreed to include the npc `surrender_level` in the stat_t struct instead of having it as a separate attribute in `npc_battle_t`. Since currently normal players don't have a surrender_level attribute, how would we incorporate surrender_level in stat_t? We could 1) set surrender_level to 0 for players; 2) implement a surrender_level for players, which would require another set of design documentation; 3) have a separate `stat_t` struct for npcs, `npc_stat_t`. I think (1) would be the easiest to adopt but what do you think? We could also just talk this over a really quick meeting if that's better.

2022-05-10 08:06 UTC, emilybae1705 approved these changes
The changes made in `stat_t` looks good and I approve of the pull request! I left a comment about incorporating surrender_level in stat_t so take a look and let me know what you think. On a side note, I think the `battle_over` function would be a suitable place to incorporate surrender_level so if an NPC's health level goes below the surrender_level, the battle ends in favor of the player. We can discuss this in more detail in a future meeting.

2022-05-10 17:09 UTC, nicholaswlee commented on src/battle/src/battle_ai.c
> +    if(chance <= crit_chance){
Hi Lily, I think you provided the wrong style link.

2022-05-10 17:11 UTC, nicholaswlee commented on src/battle/src/battle_ai.c
> +    if(1){
Yes the point of this is because there is no current "magical" moves.

2022-05-10 18:57 UTC, lilyehsani commented on src/battle/src/battle_ai.c
> +    if(1){
Could you add a comment to the code explaining this/what needs to be done when there are magical moves?

2022-05-10 19:11 UTC, lilyehsani commented on src/battle/src/battle_ai.c
> +    if(chance <= crit_chance){
Oops, updated.

2022-05-10 19:22 UTC, nicholaswlee commented on src/battle/src/battle_ai.c
> +}
Right now we have left it as 1.5, but we can discuss this in a later implementation.

2022-05-10 19:24 UTC, nicholaswlee commented on tests/battle/test_battle_print.c
> +}
Having seperate tests makes it clear if there is an issue with a Crit or not a crit.

2022-05-10 19:24 UTC, nicholaswlee commented on src/battle/src/battle_ai.c
> +    if(chance <= crit_chance){
I have fixed the spacing issue and {}

2022-05-10 19:25 UTC, nicholaswlee commented on src/battle/src/battle_flow.c
> +        enemy->stats->hp -= dmg;
I have removed both lines and just called the print statement in this if block.

2022-05-10 19:25 UTC, nicholaswlee commented on src/battle/src/battle_flow.c
> +    if(!calculate_accuracy(b->player->stats->accuracy)){
I have fixed the spacing issue and {}

2022-05-10 19:25 UTC, nicholaswlee commented on src/battle/src/battle_print.c
> +    snprintf(string, BATTLE_BUFFER_SIZE, "%s used %s! It missed!\n",
I have changed the message to ", but it missed!"

2022-05-10 19:26 UTC, nicholaswlee commented on src/battle/src/battle_flow.c
> +            string = print_battle_move(b, b->turn, enemy_move);
This will be changed anyway because of move_t, so we can resolve this then.

2022-05-10 19:26 UTC, nicholaswlee commented on src/battle/src/battle_ai.c
> +    if(1){
Yes will do now

2022-05-10 20:43 UTC, lilyehsani approved these changes
Looks good to me! Approved.

2022-05-10 20:43 UTC, merged

2022-05-28 02:55 UTC, nicholaswlee commented
We have successfully merged this PR. We have implemented tests and commented out all of our examples and have closed this issue. These changes have allowed battles to become more customizable, including have magical attack/defense, critical damage, accuracy, and skill points! Our current branch passes all the [checks](https://github.com/uchicago-cs/chiventure/actions/runs/2283397844)! We did have to change some NPC tests and examples, but those were only 2-4 lines that is just a field rename. The full outline of this implementation is in this [doc](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Stat-Changes-Design-Document).

2022-06-02 02:09 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR! One comment:
1. The title of an issue (or PR) has to convey what the issue (or PR) will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the issue (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.)

<!-- {"score": "excellent", "minor": false} -->