Openworld/room autogenerate
uchicago-cs/chiventure pull request #1358
Opened 2022-05-11 00:07 UTC by williamhu314

I have created 2 new functions in this pull requests:

1. roomspec_autogenerate, which uses an algorithm and the provided adjacency matrix to output a new roomspec given a current roomspec.
2. room_autogenerate, which given a starting room and a direction, generates a new room in the specified direction from the current room, with the associated roomspec being created by room_autogenerate.

Additionally, included in this pull request is the new specgraph struct, which provides an adjacency matrix showing relationships between roomspecs rather than just a list of roomspecs, which was the functionality of the former speclist struct.

Due to the modification of speclist into specgraph, lots of functions associated with specgraph and lots of tests associated with specgraph or functions using specgraphs do not compile and will need to be completely redesigned and reimplemented. Those functions and tests are temporarily commented out in this pull request. We will uncomment them gradually as we update them to accommodate specgraph. This task will be time consuming so we don’t want to wait for that to be completed before working on other functions.

The demo and demo makefile were also causing issues since they are using the speclist struct. The makefile for the demo was deleted (its contents were moved into the demo in case we need it for reference later).

2022-05-15 14:17 UTC, rohandeme commented
Looks good to me!

2022-05-15 14:20 UTC, rohandeme reviewed
All looks good! (part 2)

2022-05-15 14:21 UTC, rohandeme approved these changes

2022-05-16 00:49 UTC, philipchenaux requested changes
I have added a few questions/comments about this PR, although you noted that a lot of the tests break. Ideally you should have a few tests for what you have implemented so far. Especially for the basic functions.

2022-05-16 00:49 UTC, philipchenaux commented on src/openworld/src/gen_structs.c
> +/*specgraph_t* specgraph_new(roomspec_t *spec)
why have you commented out specgraph_new and specgraph_free functions?

2022-05-16 00:49 UTC, philipchenaux commented on include/openworld/gen_structs.h
> + *                the higher the number, the more likely rooms of this roomspec appear
It might be worth explaining this further. It is not initially clear why a higher number indicates this.

2022-05-16 00:49 UTC, philipchenaux commented on src/openworld/src/autogenerate.c
> +            return roomspecs[i];
Using a list like this is fine, but in some ways you are re-inventing the wheel when you can just use existing list implementations.

2022-05-16 00:53 UTC, philipchenaux commented
I just saw that your new PR addresses some of the issues above. I will review your most recent PR instead.

2022-05-16 01:58 UTC, philipchenaux commented
This PR will be closed since all edits are part of https://github.com/uchicago-cs/chiventure/pull/1384

2022-05-16 01:58 UTC, closed without merging