Addition of class_t and battle_item_t to the npc_battle struct
uchicago-cs/chiventure pull request #1361
Opened 2022-05-11 15:32 UTC by srydbergcox

To make battles with NPCs more robust, I added a `class_t` struct and a `battle_item_t` struct to the `npc_battle_t` struct. This then required me to update each call of the `npc_battle_new` & `npc_battle_init` functions throughout Chiventure to reflect the updated parameters. Also, documentation was updated to reflect these changes.

2022-05-11 15:34 UTC, srydbergcox commented
This PR caused past years examples to break. Since this is a new addition to the struct that wasn't relevant then, I will go through and add NULL pointers to the npc_battle_new, add_npc_battle functions in these examples.

2022-05-11 18:00 UTC, srydbergcox commented
Now, all examples have been fixed. But, tests for `npc_battle_free` fail. Currently working to debug this function. As of now, everything else builds so hopefully this is the last roadblock.

2022-05-11 18:54 UTC, srydbergcox commented
Bug in npc_battle_free() is now fixed, I will go through the conflicts and then it should be ready for review.

2022-05-12 05:45 UTC, srydbergcox commented
I have found that two tests in `test_battle_print.c` fail due to an inconsistency between the npc struct and the combatant struct. The `build_moves` function expects a `combatant_t` struct as a parameter which it then expects to have a place to store moves. However, in these test cases the npc struct is passed in leading to a bug where there is nowhere to store the moves causing a seg fault. To resolve this, either a function needs to be created that can turn an npc struct into a combatant struct or the `build_moves` function needs to be updated to reflect the npc organization.

2022-05-13 16:52 UTC, srydbergcox commented
Fixed the tests that broke after merging branch and fixing conflicts. PR is ready for review now.

2022-05-13 18:40 UTC, nicholaswlee approved these changes
This pull request looks great! There are a couple minor tab errors but beyond that for this Sprint, it is approved. In the future a couple things may have to change:

int surrender_level
We have talked with Emily about taking this and putting it in stat_t. This will make it so that surrender levels actually exist and that the battle will stop when it reaches that level.

battle_item_t
I want to clarify that currently battle_item_t only supports stat changing items like potions. In Sprint 4, we hope to expand battle_item_t to accommodate for more stat_t changes. We will let you know when this occurs. Additionally, we will be adding equipment and weapons that will most likely be added during Sprint 4 as well. We will contact you when these changes are made and keep you all updated.

Overall, great work! I am glad that NPC's can use items now in battle.

2022-05-13 18:40 UTC, nicholaswlee commented on include/npc/npc.h
> +                      int surrender_level, class_t *class_type,
For the int surrender_level, this is the minimum HP that will trigger the battle to end correct? I believe we had a conversation with Emily about taking this and putting it into the combatant_t struct or the stat_t struct. Is that still the case?

2022-05-13 18:40 UTC, nicholaswlee commented on include/npc/npc_battle.h
> +                            battle_item_t *items);
This is really minor, but the indentation here seems to be kinda off.

2022-05-13 18:40 UTC, nicholaswlee commented on src/npc/src/npc_battle.c
> +                            battle_item_t *items)
Same here for the indentation.

2022-05-13 18:40 UTC, nicholaswlee commented on tests/battle/test_battle_flow.c
> +    true, 20, 5, 0);
Currently battle_item_t only supports items that can augment stat i.e. potions, medicine, etc. Since this test is made just for testing start_battle this is fine, but just FYI this kind of "item" would be classified as a weapon or equipment, which has not been implemented in battles yet.

2022-05-13 19:32 UTC, srydbergcox commented on include/npc/npc.h
> +                      int surrender_level, class_t *class_type,
yes, we have discussed this. I think that we plan on working on this soon.

2022-05-13 19:42 UTC, srydbergcox commented on include/npc/npc_battle.h
> +                            battle_item_t *items);
Yeah I agree. But, when I look at it on my VSCode the indentation looks normal so I am not sure what is causing that.

2022-05-15 19:18 UTC, emilybae1705 commented on include/npc/npc.h
> +                      int surrender_level, class_t *class_type,
@nicholaswlee Yes, we're incorporating that in a pull request I'm currently working on. I'll let you know once that gets done.

2022-05-15 20:48 UTC, emilybae1705 requested changes
Overall, I don't see any issues with your pull request! I just have a few minor changes to request. Because we're going to replace bool will_fight with the hostility_t enum, for the new functions you made in the test files (`create_npc_battle_item`, `npc_create_battle_item`, `generate_test_battle_item`, and `generate_npc_test_battleitem`) could you take bool out and replace it with hostility_t? For the functions that are already in the chiventure repo I can go ahead and fix them. It's just for the new functions, I don't have access to them right now since they haven't been merged to dev branch so I don't want to create errors when my PR gets merged with yours.

2022-05-15 20:48 UTC, emilybae1705 commented on include/npc/npc.h
>   */
I suggest you add a comment about the class_t and battle_item_t structs you added as parameters. Just maybe one line documenting what those structs represent and why you're adding them to the add_battle_to_npc function.

2022-05-15 20:48 UTC, emilybae1705 commented on include/npc/npc.h
>   */
I noticed you wrote comments for those structs in the npc_battle_init function. You could just copy and paste those comments here.

2022-05-15 20:48 UTC, emilybae1705 commented on src/battle/examples/battle_cli_example.c
> +                                        BATTLE_AI_GREEDY, HOSTILE, 0, NULL, NULL);
Not sure if this matters too much, but since this is an example file, instead of initializing `class_t `and `battle_item_t `to NULL, you could use either the `make_bard2()` or `make_wizard2()` functions as an input for class_t and a battle item init function as input for battle_item_t. I don't see any battle_item_init function on the example file or battle_logic.c so this might be something to talk with Battles about.

2022-05-15 20:48 UTC, emilybae1705 commented on tests/battle/test_battle_flow.c
> + * Testing if the battle_player is determiend as the winner if the enemy
minor typo here for determined

2022-05-15 20:48 UTC, emilybae1705 commented on src/battle/examples/battle_cli_example.c
> +                                        BATTLE_AI_GREEDY, HOSTILE, 0, NULL, NULL);
I noticed you made a `npc_create_battle_item` function in `test_battle_print.c`. You could use that function to initialize a list of battle items.

2022-05-15 20:48 UTC, emilybae1705 commented on src/battle/examples/battle_cli_example.c
> +                                        BATTLE_AI_GREEDY, HOSTILE, 0, NULL, NULL);
Same for the example files below

2022-05-15 20:48 UTC, emilybae1705 commented on tests/battle/test_battle_print.c
> +                            char* description, bool battle, int attack,
I noticed this is the same exact function as `create_npc_battle_item` in `test_battle_flow.c`. Not sure if this is an issue but maybe you can just use one function?

2022-05-17 20:13 UTC, srydbergcox commented on tests/battle/test_battle_print.c
> +                            char* description, bool battle, int attack,
Yeah, I had issues using the functions across multiple files because there was no header file with the declaration to include in each file where I wanted to use these functions. Maybe this can be created? Or, maybe Lily has suggestions/input.

2022-05-17 20:13 UTC, srydbergcox commented on tests/battle/test_battle_flow.c
> + * Testing if the battle_player is determiend as the winner if the enemy
Fixed

2022-05-17 20:16 UTC, srydbergcox commented on include/npc/npc.h
>   */
Yeah I missed that one, good catch! Now fixed.

2022-05-17 20:25 UTC, srydbergcox commented on src/battle/examples/battle_cli_example.c
> +                                        BATTLE_AI_GREEDY, HOSTILE, 0, NULL, NULL);
I discussed this earlier with Lily and since this is a past year's example it has no dependency on the class or items being initialized since those weren't a thing then. So, we made them NULL for simplicity.

2022-05-17 22:19 UTC, srydbergcox commented
> Overall, I don't see any issues with your pull request! I just have a few minor changes to request. Because we're going to replace bool will_fight with the hostility_t enum, for the new functions you made in the test files (`create_npc_battle_item`, `npc_create_battle_item`, `generate_test_battle_item`, and `generate_npc_test_battleitem`) could you take bool out and replace it with hostility_t? For the functions that are already in the chiventure repo I can go ahead and fix them. It's just for the new functions, I don't have access to them right now since they haven't been merged to dev branch so I don't want to create errors when my PR gets merged with yours.

For this, those functions return `battle_item_t` which does not have a hostility_t field. The `bool battle` parameter of `battle_item_t` represents whether the item that is being created/used inflicts stat changes onto the player or npc.

2022-05-18 00:35 UTC, lilyehsani commented on tests/battle/test_battle_print.c
> +                            char* description, bool battle, int attack,
This is fine for now. I would recommend writing a backlog issue about creating some sort of battle_test_utility.c/.h that can be used across the many battle test files.

2022-05-18 01:29 UTC, lilyehsani requested changes
Looks really good! Just two minor comments, and you need to fix the merge conflicts.

2022-05-18 01:29 UTC, lilyehsani commented on src/npc/examples/dialogue_example_2020.c
> +    while (rc != 1) {
Bracket should be on next line since chiventure uses Allman Style.

2022-05-18 01:29 UTC, lilyehsani commented on src/npc/src/npc_battle.c
> +    while(curr) {
Bracket should be on next line for Allman Style.

2022-05-18 01:47 UTC, srydbergcox commented on src/npc/examples/dialogue_example_2020.c
> +    while (rc != 1) {
Fixed

2022-05-18 01:47 UTC, srydbergcox commented on src/npc/src/npc_battle.c
> +    while(curr) {
Fixed

2022-05-18 18:05 UTC, srydbergcox commented on tests/battle/test_battle_print.c
> +                            char* description, bool battle, int attack,
A backlog issue has been created.

2022-05-19 02:55 UTC, emilybae1705 commented
> For this, those functions return `battle_item_t` which does not have a hostility_t field. The `bool battle` parameter of `battle_item_t` represents whether the item that is being created/used inflicts stat changes onto the player or npc.

I see. Sorry for the confusion!

2022-05-19 02:57 UTC, emilybae1705 approved these changes
Looks great! Great job! I approve of the pull request as the previous changes I requested resulted from confusing bool attack and bool will_fight. So I don't see any issues with your code.

2022-05-19 03:17 UTC, lilyehsani approved these changes
LGTM! Approved

2022-05-19 03:17 UTC, merged

2022-05-19 03:26 UTC, srydbergcox commented
Closing statement: This PR is now finished. After review, I made a couple of stylistic changes, completed some documentation, and we added an issue to fix my problems with creating test classes, etc. in battles test files. Overall, the PR now adds functinality to have class types and items in the npc_battle_t struct.

2022-06-05 02:01 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR! When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests.

<!-- {"score": "excellent", "minor": false} -->