Quests/player update 2
uchicago-cs/chiventure pull request #1362
Opened 2022-05-11 19:03 UTC by JSerf02

Updates quest-structs.h, quest-state.h, quest-state.c, and the quest tests to work with the player module and with the new player_quest and player_task structs. Contributes to the same redesign as Pull Request #1337.

2022-05-11 19:09 UTC, JSerf02 commented
Some of these changes are the same as Pull Request #1337 but I'm not sure why it's showing up as new changes. If there are any differences, the changes from the previous PR should be accepted.

2022-05-11 20:00 UTC, jakeziqiwei approved these changes
Everything looks. Some concerns were already addressed in slack!

2022-05-13 20:16 UTC, philipchenaux requested changes
Added a few minor comments to change, but once theses are addressed you should be good to go!

2022-05-13 20:16 UTC, philipchenaux commented on include/quests/quests_structs.h
> +typedef struct mission {
Does this imply that a mission must be both an active and passive mission?

2022-05-13 20:16 UTC, philipchenaux commented on src/quests/src/quests_state.c
> +            return 1;
You should stick to the convention of returning either SUCCESS or FAILURE instead of 1 or 0.

2022-05-13 20:16 UTC, philipchenaux commented on include/quests/quests_structs.h
>  } quest_t;
Make sure that you update the appropriate documentation if you change the structs (i.e remove the explanation of status if you remove it from the struct).

2022-05-13 20:16 UTC, philipchenaux commented on include/quests/quests_structs.h
>      reward_t *reward;
Make sure that you remove the `completed` explanation in the comment explaining the task struct.

2022-05-13 20:16 UTC, philipchenaux commented on include/quests/quests_structs.h
>  } quest_t;
One additional note, make sure that you update the new player_quest_t and player_struct_t structs that you have created in the player.h file to include the documentation about the `completed` field as it is currently not clear as to why quests have a `completion` of type int, while tasks have `completed` of type bool.

2022-05-13 20:38 UTC, JSerf02 commented on include/quests/quests_structs.h
> +typedef struct mission {
We had to change it from a union to a struct to get it to pass the tests, since it was originally passing only by unknowingly resetting the mission pointer to NULL so the mission wouldn't actually get checked. This is really just a temporary change though since we already created an entire redesign of the mission system that addresses this issue better and we plan to implement that in the next couple of days.

2022-05-13 21:09 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +            return 1;
Just switched it to bools. Chose bools instead of SUCCESS/FAILURE because SUCCESS and FAILURE typically correspond to whether or not a function actually did what it was supposed to while here, the function is not returning whether or not it succeeded.

2022-05-13 21:11 UTC, philipchenaux commented on include/quests/quests_structs.h
> +typedef struct mission {
Okay this makes sense.

2022-05-13 21:14 UTC, philipchenaux approved these changes
I am happy with how this looks. Well done guys.

2022-05-13 21:15 UTC, merged

2022-06-04 15:37 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Great job on this PR!

<!-- {"score": "excellent", "minor": false} -->