Quest/delete quest
uchicago-cs/chiventure pull request #1363
Opened 2022-05-11 20:18 UTC by elizabethli31

We used uthash macros to write two functions to remove quests from a hash table. One of the functions allows the user to remove a single quest and the other removes all quests from the hash table. This pull request incorporates the working add_quest_to_hash and get_quest_from_hash functions as well as the change of quest_ids from long int to char.

2022-05-12 17:28 UTC, charlieweiler requested changes
Looks good, I'd just add an error check in remove_quest_all before merging (unless there's a reason for its absence)

2022-05-12 17:28 UTC, charlieweiler commented on src/quests/src/quests_state.c
> +int remove_quest_all(quest_hash_t *hash_table)
Is there any particular reason you guys don't have an error check line in remove_quest_in_hash? If not, I think it should be in remove_quest_all.

2022-05-13 01:19 UTC, charlieweiler commented on src/quests/src/quests_state.c
> +int remove_quest_all(quest_hash_t *hash_table)
Elizabeth informed me that an error check isn't necessary because it is not present in other team's modules, and also because of how this function links with hash_iter.

2022-05-13 01:22 UTC, charlieweiler approved these changes
Functions look good and there are reasons for excluding the error check, so it's good by me.

2022-05-13 19:59 UTC, philipchenaux requested changes
You have included all CMake files, please recommit only the files that are relevant to this PR.

2022-05-15 19:00 UTC, elizabethli31 commented
I removed the cmake files and merged the new code from dev

2022-05-16 00:18 UTC, philipchenaux approved these changes
Looks good, great work!

2022-05-16 00:18 UTC, merged

2022-06-04 15:38 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Great job on this PR!

<!-- {"score": "excellent", "minor": false} -->