Custom actions/1291 teleportation as a custom action
uchicago-cs/chiventure pull request #1373
Opened 2022-05-13 16:02 UTC by jbrouwer5

We implemented TELEPORTATION as a custom action. A developer can now create a custom action that moves a player to a specified destination room. This involved creating a parameter struct that the action_new family of functions takes. This allows for more types of parameters rather than just attributes. We also implemented the applicable tests in the tests directory.

2022-05-14 01:53 UTC, sabinecodes15 commented on src/custom-actions/include/action_block.h
> + * - action block. Must point to already allocated memory.
```suggestion
 * - action block. Must already be allocated in memory.
```

2022-05-14 02:02 UTC, sabinecodes15 commented on src/custom-actions/src/action_block.c
>      ast = malloc(sizeof(AST_block_t));
You check if `action` was properly malloced in the if statement below. Should you not also check if `ast` was properly allocated?

2022-05-14 02:08 UTC, sabinecodes15 commented on src/custom-actions/src/action_block.c
> +    block_t *block = malloc(sizeof(block));
Check if malloc is successful

2022-05-14 02:52 UTC, sabinecodes15 commented on src/custom-actions/include/custom-actions-effect.h
>   *
Update the comment so it properly reflects the new move_player function. Make sure it's distinct from the comments for `say_phrase`, and update the parameter list.

2022-05-14 03:01 UTC, sabinecodes15 commented on src/custom-actions/src/custom-actions-effect.c
>   *
If `move_player(player_t *p, room_t *r)` is being replaced with `move_player(game_t *game, room_t *new_room)`, remove it from the TO BE IMPLEMENTED section below.

2022-05-14 03:21 UTC, sabinecodes15 commented on src/custom-actions/src/custom-actions-effect.c
> +// already implemented in game.h
I don't see a `move_player` function implemented in game.h, but I do see `move_room` function. Is this what you're referring to?

2022-05-14 03:23 UTC, sabinecodes15 commented on src/custom-actions/include/custom-actions-effect.h
> +int move_player(game_t *game, room_t *r);
Where exactly is this implemented? (See also my comment [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872921347).)

2022-05-14 04:54 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +                                                                        "new_action->action_params->args");
```suggestion
                                                                       "new_action->action_params->args");
```

2022-05-14 14:47 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args1 = (attribute_t **)malloc(sizeof(attribute_t *) * 2);
```suggestion
    args1 = (attribute_t**)malloc(sizeof(attribute_t*) * 2);
```

2022-05-14 14:49 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args1 = (attribute_t **)malloc(sizeof(attribute_t *) * 2);
[Style guide](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872921347) says no space between variable and dereference operator; I think that applies here

2022-05-14 14:50 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args2 = (attribute_t **)malloc(sizeof(attribute_t *) * 2);
```suggestion
    args2 = (attribute_t**)malloc(sizeof(attribute_t*) * 2);
```

2022-05-14 14:50 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args2 = (attribute_t **)malloc(sizeof(attribute_t *) * 2);
See [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077)

2022-05-14 14:51 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args1 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
```suggestion
    args1 = (attribute_t**)malloc(sizeof(attribute_t*) * 3);
```

2022-05-14 14:51 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args1 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
Spaces (see [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077))

2022-05-14 14:52 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args2 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
```suggestion
    args2 = (attribute_t**)malloc(sizeof(attribute_t*) * 3);
```

2022-05-14 14:52 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args2 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
Spaces (see [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077))

2022-05-14 14:53 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    action_params2 = (action_param_t *)malloc(sizeof(action_param_t));
```suggestion
    action_params2 = (action_param_t*)malloc(sizeof(action_param_t));
```

2022-05-14 14:53 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    action_params2 = (action_param_t *)malloc(sizeof(action_param_t));
Spaces for lines 852 and 853 (see [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077))

2022-05-14 14:54 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    action_params2 = (action_param_t *)malloc(sizeof(action_param_t));
```suggestion
    action_params2 = (action_param_t*)malloc(sizeof(action_param_t));
```

2022-05-14 14:54 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    action_params2 = (action_param_t *)malloc(sizeof(action_param_t));
Spaces for lines 923 and 924 (see [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077))

2022-05-14 14:55 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args1 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
```suggestion
    args1 = (attribute_t**)malloc(sizeof(attribute_t*) * 3);
```

2022-05-14 14:56 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args1 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
Spaces (see [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077))

2022-05-14 14:56 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args2 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
```suggestion
    args2 = (attribute_t**)malloc(sizeof(attribute_t*) * 3);
```

2022-05-14 14:57 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    args2 = (attribute_t **)malloc(sizeof(attribute_t *) * 3);
Spaces (see [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077))

2022-05-14 14:57 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +    action_params2 = (action_param_t *)malloc(sizeof(action_param_t));
```suggestion
    action_params2 = (action_param_t*)malloc(sizeof(action_param_t));
```
Spaces for lines 1027 and 1028 (see [here](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872989077))

2022-05-14 14:59 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +                               "returned FAILURE with action type GEN");
```suggestion
                               "returned FAILURE with action type TELEPORT");
```

2022-05-14 15:00 UTC, sabinecodes15 commented on tests/custom-actions/test_action_block.c
> +                               "returned FAILURE with action type GEN");
```suggestion
                               "returned FAILURE with action type TELEPORT");
```

2022-05-14 15:04 UTC, sabinecodes15 requested changes
[This comment](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872921516) (with this [related comment](https://github.com/uchicago-cs/chiventure/pull/1373/files#r872921347)) is the main issue I noticed; if this feature is working as intended, consider making clearer comments

2022-05-14 21:48 UTC, ecoble approved these changes
Great job on this! Also great job @sabinecodes15 for such a thorough first review! Approving this pull request, as a next step consider writing a small example using teleportation (which could be useful for the demo), or adding teleportation specific tests.

2022-05-15 04:05 UTC, sabinecodes15 approved these changes
Looks good to merge!

2022-05-17 19:03 UTC, closed without merging