cli: associate words in quotes into a single item (token)
uchicago-cs/chiventure pull request #1378
Opened 2022-05-13 19:26 UTC by mrestuccia1

Currently, there is a limit of four tokens per input, which limits the possible inputs. While there is no need for it right now, we want to be able to say, for example, go to "ring of fire", and have that be counted as three tokens instead of five. This will allow for more tokens, but also for games to have special names beyond north, south etc... We edited the current parsing framework such that if the command line input contains something in quotes, whatever is inside is considered its own token, no matter how many words are inside.

2022-05-13 19:29 UTC, fkbad commented on src/cli/src/parser.c
> +    char *token2 = strtok(input, "\"");
tokenizing on quotation mark

2022-05-13 19:31 UTC, fkbad commented on src/cli/src/parser.c
> +    for(int i = 0; i < 4; i++)
why change this from being the constant to 4? Should this not be linked?

2022-05-13 19:33 UTC, fkbad commented on src/cli/src/parser.c
> +    if (input[0] != '\"')
should add some kind of description here about what the loop is doing.

2022-05-13 19:35 UTC, fkbad requested changes
Please add some description within your code (particularly at the commented portions) so that it is more clear what you code is meant to be doing.

I already know it is supposed to parse for text within a quote, but it is not obvious when you are looking.

2022-05-13 19:35 UTC, fkbad commented on src/cli/src/parser.c
> +        for(int i = 0; i < 4; i++)
Again, why 4? It is not clear to me. 
If this is meant to be the word limit constant, then keep it as such

2022-05-13 19:52 UTC, mrestuccia1 commented
As suggested by Faruk in his review, we added comments and changed the number 4 back to the pre-defined variable TOKEN_LIST_SIZE. The code still passes all the tests and added the functionality described above. We will check with Faruk one more time, but the next step will be to get the code looked over by the TA

2022-05-15 18:29 UTC, jacknugent1529 reviewed
The main thing to change is the descriptiveness of the names. Everything else looks good, although I'll do a more thorough review once this is done. Also, since this is an integral part of chiventure, testing is especially important. So, how have you tested this code and can we be confident that it interpreting the quotes in this manner won't break something elsewhere?

2022-05-15 18:29 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +    char **temp2;
More descriptive names (rather than `temp` and `temp2`) would make this code much easier to read. Also, if names are not enough, give a brief comment explaining why there needs to be 3 of these arrays.

2022-05-15 18:29 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +        return NULL;
style: indentation

2022-05-15 18:29 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +        for(int i = 0; i < 4; i++)
@fkbad Is correct. Avoid using "[magic numbers](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#avoid-magic-numbers)" because it is often unclear what the number mean (especially if someone changes them in the future. Instead use descriptive constants

2022-05-16 19:06 UTC, milesgardner commented
General functionality has been completed.  Unit tests have been implemented, and we believe that tokens surrounded by quotations is ready to be merged into the main branch.

2022-05-17 02:31 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +    for(int i = 0; i < 4; i++)
This is correct, we switched it initially to test the function inside a sandbox, and never switched it back. This change has been made, and all the for loops now have dynamic variables.

2022-05-17 02:32 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +    if (input[0] != '\"')
We have added descriptive comments for everything we added, so this change should be fixed now.

2022-05-17 02:35 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +        for(int i = 0; i < 4; i++)
This change has been made, there are descriptions for all our new added code, and we changed the "magic numbers" back to the dynamic variables they had been set to in the previous version.

2022-05-17 02:36 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +        return NULL;
The indentation has been added.

2022-05-17 02:38 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +    char **temp2;
We reverted the code to only need two arrays, one named words, which is the array of tokens tokenized by spaces, and one named words_quotes, which is the array of tokens tokenized by quotes.

2022-05-17 03:11 UTC, mrestuccia1 commented
> Please add some description within your code (particularly at the commented portions) so that it is more clear what you code is meant to be doing.
> 
> I already know it is supposed to parse for text within a quote, but it is not obvious when you are looking.

2022-05-17 03:55 UTC, fkbad approved these changes

2022-05-18 00:51 UTC, milesgardner commented
Added unit tests as requested through slack.

2022-05-18 01:57 UTC, jacknugent1529 reviewed
It looks mostly good and the tests are a nice addition. There's just a few style issues remaining

2022-05-18 01:57 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +    char *token2 = strtok(input, "\"");
I still think this naming scheme is a bit confusing. What does "token2" mean in this context?

2022-05-18 01:57 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +        for(int i = 0; i < 4; i++)
style: space between `for` and `(` (`for (...`). Also, replace 4 with a constant

2022-05-18 01:57 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +        return NULL;
I mean that the `return NULL` line should be indented once more based on its location in the curly braces. And the space between `if` and `(` doesn't seem to have been added.

2022-05-18 01:57 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +    }else{
style: spaces around `else`

2022-05-18 02:52 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +    char *token2 = strtok(input, "\"");
Just changed token2 to token_quotes, since it is the token separated by quotes.

2022-05-18 02:56 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +    }else{
Added the spaces around else, as suggested.

2022-05-18 02:56 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +        for(int i = 0; i < 4; i++)
Added the spaced between for and ( in a ll instances, and changed 4 to dynamic variable it was previously set to.

2022-05-18 02:59 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +        return NULL;
The indentation should now be added for all instances of return NULL, and spaces between all instances of if and "(" have been added.

2022-05-18 02:59 UTC, mrestuccia1 commented
All requested edits have been made, we believe the pull request should now be good to go.

2022-05-19 18:11 UTC, jacknugent1529 reviewed
Nice job making the changes! It looks good to me

2022-05-19 18:11 UTC, jacknugent1529 approved these changes

2022-05-19 18:12 UTC, merged

2022-06-03 02:14 UTC, jacknugent1529 commented
PR Score: Excellent

Comments: Excellent work on this PR! The description is good, and you addressed each of the suggestions well. This is not a rubric item, but the commit "discipline" could be improved to give insightful yet concise commit messages and commits in places that logically make sense. 

<!-- {"score": "excellent", "minor": false} -->