Created a Sample Game with Chiventure Structs
uchicago-cs/chiventure pull request #1379
Opened 2022-05-13 20:28 UTC by sangerr

In this pull request, we created a sample game with chiventure structs. This is an initial step before we add in the sound modules, in order to familiarize ourselves with the chiventure structs and make sure that we are able to integrate the sound once the sample game can compile. We commented in where the sound structures will go, and we are now moving on to writing those implementations.

2022-05-15 18:58 UTC, JaStarbuck approved these changes
This looks good to me. I'm only concerned about line 38 and 39 since on the debugging hw I didn't do the part right where something was free'd before it was initialized and the only way I got it to run was by removing the free(). However, I did get it wrong so if it works for this I'm all for it.

2022-05-16 17:33 UTC, ecoble requested changes
This looks like a good start!

2022-05-16 17:33 UTC, ecoble commented on src/sound/examples/sound_example.c
> +    game_free(ctx->game);
Agree with Jason's concerns, why are you freeing the game here?

2022-05-17 06:01 UTC, ecoble approved these changes

2022-05-17 06:03 UTC, merged

2022-05-24 03:23 UTC, jwschroeder21 commented
Closing statement:

In this pull request, we created a sample game with chiventure structs. This is an initial step before we add in the sound modules, in order to familiarize ourselves with the chiventure structs and make sure that we are able to integrate the sound once the sample game can compile. We commented in where the sound structures will go, and we are now moving on to writing those implementations. We have written those implementations, and submitted a PR for them on issue #1320!

2022-06-06 22:06 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice job on this sample game, and great job catching hard to notice issues on the review!

<!-- {"score": "excellent", "minor": false} -->