We have implemented a new move_t struct!
uchicago-cs/chiventure pull request #1381
Opened 2022-05-14 03:25 UTC by nicholaswlee

With this move_t struct we have implemented these changes as described in this [document](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Move-Changes-Design-Document). Further tests will have to be created in order to fully test out all of our functions. The goal of this was to add moves that can do physical/magical attacks, and change a user's, opponents, or both combatants stats using a move. Tests were also changed, including three files the skilltree's tests and npc's tests.

2022-05-15 18:51 UTC, srydbergcox commented on src/battle/src/battle_default_objects.c
> +    //bool attack = true;
Just want to verify that this should be commented out.

2022-05-15 18:52 UTC, srydbergcox commented on src/battle/src/battle_default_objects.c
> +    //int defense = rand * 10 + 5;
Again, just want to verify that this should be commented out.

2022-05-15 19:10 UTC, srydbergcox approved these changes
Great job! The changes look good to me, specifically the changes to the test files for NPCs. A couple small notes with lines that were commented out which I just want to be sure was intentional. Also, in the future it may be helpful to leave updates on your Pull Request github page as well to make it a little easier to see what you did/how it progressed. But, other than those relatively minor things, great work!

2022-05-15 22:11 UTC, nicholaswlee commented on src/battle/src/battle_default_objects.c
> +    //bool attack = true;
Oh yes, this should be deleted thank you!

2022-05-15 22:11 UTC, nicholaswlee commented on src/battle/src/battle_default_objects.c
> +    //int defense = rand * 10 + 5;
Oh yes, this should be deleted thank you!

2022-05-16 06:05 UTC, emiliolevinspage commented on include/battle/battle_flow.h
> +int use_stat_change_move(combatant_t* target, move_t* move, combatant_t* source);
should this be in battle_logic.h? will it be called by battle_flow_move()?

2022-05-16 06:08 UTC, nicholaswlee commented on include/battle/battle_flow.h
> +int use_stat_change_move(combatant_t* target, move_t* move, combatant_t* source);
Yes this is called in battle_flow_move()

2022-05-16 06:26 UTC, emiliolevinspage approved these changes

2022-05-16 06:26 UTC, emiliolevinspage commented on include/battle/battle_print.h
> +int print_stat_changes_move(battle_t *b, turn_t turn, move_t *move, char *string);
how will this function be called? will the turn loop need to check what kind of move is being used to call the right print function?

2022-05-16 06:26 UTC, emiliolevinspage commented on src/battle/src/battle_ai.c
> +double crit_modifier(int crit_chance)
why is crit modifier a double if damage is now an int?

2022-05-16 06:26 UTC, emiliolevinspage commented on src/battle/src/battle_ai.c
> +double crit_modifier(int crit_chance)
is this to avoid compounding rounding?

2022-05-16 06:26 UTC, emiliolevinspage commented on src/battle/src/battle_flow.c
> +        if (move->stat_mods != NO_TARGET)
in what cases would there be no target?

2022-05-16 06:26 UTC, emiliolevinspage commented on src/battle/src/battle_moves.c
> +    strncpy(move->info, "Fireball", MAX_MOVE_INFO_LEN);
excellent choice

2022-05-16 06:26 UTC, emiliolevinspage commented on src/battle/src/battle_print.c
> +/* see battle_print.h */
if stat changes are temporary, shouldnt the report say how long it will last? are they temporary?

2022-05-16 06:26 UTC, emiliolevinspage commented on tests/battle/test_battle_print.c
> -
this will conflict with some changes we made to print_battle_move but i agree that this is good- we will take your version

2022-05-16 06:28 UTC, emiliolevinspage commented on include/battle/battle_flow.h
> +int use_stat_change_move(combatant_t* target, move_t* move, combatant_t* source);
i think it would make sense to move it to battle logic to keep the battle_flow module full of higher level functions. not a strong feeling but that is my thought

2022-05-16 06:29 UTC, emiliolevinspage commented
looks good! im excited to have this feature. My comments are mostly suggestions for clarity- not major issues!

2022-05-16 07:02 UTC, nicholaswlee commented on src/battle/src/battle_flow.c
> +        if (move->stat_mods != NO_TARGET)
This applies when the move does not change stats, thus there are no targets in terms of stat changes.

2022-05-16 07:03 UTC, nicholaswlee commented on src/battle/src/battle_print.c
> +/* see battle_print.h */
Currently, they are temporary within the battle and not within a certain number of turns within the battle.

2022-05-17 02:37 UTC, lilyehsani requested changes
Really great work! Added a few comments.

2022-05-17 02:37 UTC, lilyehsani commented on include/battle/battle_moves.h
>   * - defense: amount of defense the move provides
Update parameters in comment.

2022-05-17 02:37 UTC, lilyehsani commented on include/battle/battle_moves.h
>    * - SUCCESS for successful init
Update parameters in comment.

2022-05-17 02:37 UTC, lilyehsani commented on include/battle/battle_structs.h
> +typedef struct move_t {
Can you add the comments you have in the design document here? Either in-line with the fields or above, explaining the struct and its fields.

2022-05-17 02:37 UTC, lilyehsani commented on include/battle/battle_structs.h
> +typedef struct stat {
Can you add the comments you have in the (stat changes) design document here? Either in-line with the fields or above, explaining the struct and its fields.

2022-05-17 02:37 UTC, lilyehsani commented on src/battle/src/battle_default_objects.c
> +/* PROSPECTIVE CHANGES
When would these changes be considered? Is there a reason we are holding off on them now?

2022-05-17 02:37 UTC, lilyehsani commented on include/battle/battle_structs.h
> +    struct move_t* prev;
I'm a bit confused as to why move is now a doubly-linked list. Could you explain the reasoning behind this change?

2022-05-17 02:37 UTC, lilyehsani commented on src/npc/examples/battle_move_example_2021.c
> +/* This is no longer used, has been replaced by move_new() */
You can just delete this then.

2022-05-17 02:37 UTC, lilyehsani commented on tests/npc/test_npc.c
> +/* This is no longer used, has been replaced by move_new() from battles */
You can just delete this then.

2022-05-17 02:58 UTC, nicholaswlee commented on include/battle/battle_structs.h
> +    struct move_t* prev;
Move has always been a doubly linked list so we are maintaining that structure

2022-05-17 03:02 UTC, nicholaswlee commented on src/battle/src/battle_default_objects.c
> +/* PROSPECTIVE CHANGES
These currently cannot be tested and we ill be used for when further testing is added. This will be crucial to testing accuracy,  physical and magic damage, sp_cost, and stat changes.

2022-05-17 03:10 UTC, nicholaswlee commented on include/battle/battle_structs.h
> +typedef struct move_t {
I have added them

2022-05-17 03:11 UTC, nicholaswlee commented on include/battle/battle_structs.h
> +typedef struct stat {
I have added them in this pull request

2022-05-17 03:12 UTC, nicholaswlee commented on src/battle/src/battle_ai.c
> +double crit_modifier(int crit_chance)
Our crit modifier multiples damage by 1.5 since we thought 2 was too much of an increase.

2022-05-17 03:12 UTC, nicholaswlee commented on src/npc/examples/battle_move_example_2021.c
> +/* This is no longer used, has been replaced by move_new() */
I have removed them in this pull request

2022-05-17 04:02 UTC, lilyehsani approved these changes
Looks great! Approved.

2022-05-18 00:36 UTC, merged

2022-05-28 01:33 UTC, nmkhan100 commented
We have completed our implementation and have submitted a pull request. We have made a couple new functions as outlined in our doc and above. The biggest change is that there are different types of moves that allow for more customizable battles. All of our tests have passed, and we have implemented our code as laid out in the [design document](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Move-Changes-Design-Document). Here is the [PR](https://github.com/uchicago-cs/chiventure/pull/1381).

2022-06-05 01:44 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->