Action management/1290 make view stats actions
uchicago-cs/chiventure pull request #1389
Opened 2022-05-15 17:44 UTC by HarrisonD123

Implemented a new do_self_action function that currently only handles the "view stats" function. Details in issue #1290.

2022-05-16 03:02 UTC, sabinecodes15 commented on include/action_management/action_structs.h
> +    /* KIND 4 ACTIONS - ACTION <self> */
Something to consider: the NPC team plans to implement actions of kind 4, 5, and 6 (same as 1, 2, and 3, but involving npcs). That being said, it's not in the dev branch (currently in progress in npc/actions)...
 
This may just be something you want to communicate with them if you haven't already, or you can change this to kind 7 action.

2022-05-16 03:06 UTC, sabinecodes15 commented on include/action_management/actionmanagement.h
> + * - obj: An enum describing what
Describing what?

2022-05-16 03:07 UTC, sabinecodes15 commented on src/action_management/src/actionmanagement.c
> +        string = display_stats(p->player_stats);
```suggestion
            string = display_stats(p->player_stats);
```
Indentation

2022-05-16 03:13 UTC, sabinecodes15 requested changes
Just a few things, but otherwise looks great! Please respond to [this](https://github.com/uchicago-cs/chiventure/pull/1389/files#r873291479) comment before you mark it as resolved so I know what you did to address it.

2022-05-16 17:39 UTC, ecoble requested changes
Nice job! Just a minor change, and like Sabine said communicate with the NPC team about the action kind number, either way you choose to go is fine.

2022-05-16 17:39 UTC, ecoble commented on include/action_management/action_structs.h
> +    /* KIND 4 ACTIONS - ACTION <self> */
Good catch!

2022-05-16 17:39 UTC, ecoble commented on src/action_management/src/actionmanagement.c
> +        if(obj == STATS) {
Space after "if"

2022-05-17 04:38 UTC, ecoble approved these changes
Looks good to me!

2022-05-17 04:44 UTC, sabinecodes15 approved these changes
Looks good to merge!

2022-05-17 04:45 UTC, merged

2022-05-24 03:41 UTC, HarrisonD123 commented
### Closing Statement
We were able to get our code from this issue successfully merged into the dev branch. Several minor changes were made in before this PR was approved. This included some if-statement formatting issues, as well as some missing/incomplete descriptions in the comments of our `do_self_action` function in `actionmanagement.h.`

As for unknowns, it is possible that the parameters of this function don't entirely make sense for all parties involved with calling/using `do_self_actions.` Currently, our function takes in an enum called `self_action_obj` that determines what the user wants viewed. Further communication with the CLI team might be needed to determine what kinds of parameters would be most efficient.

2022-06-07 01:29 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job updating and reviewing this code!

<!-- {"score": "excellent", "minor": false} -->