1375 editing item_t struct
uchicago-cs/chiventure pull request #1394
Opened 2022-05-15 22:30 UTC by KendrickXie

Three new elements have been added to the ```item_t``` struct.

```char* item_image``` is to store a file path to an image of an item.
```unsigned int* inventory_x_pos``` and ```unsigned int* inventory_y_pos``` are to store x and y coordinates of an item within an inventory.

2022-05-15 22:49 UTC, HarrisonD123 approved these changes
These changes are pretty straightforward and don't look like they'd create any conflicts in the code. Any assignment of these members to values should most likely be left up to the graphics module.

Looks good to merge!

2022-05-16 17:43 UTC, ecoble requested changes
Looks good! I would also recommend getting a review from a member of the GUI team to confirm that these changes work for their interface.

2022-05-16 17:43 UTC, ecoble commented on include/game-state/item.h
> +    char* item_image; // a file path to an image of an item
Please put the asterisk on the other side to be consistent with style, i.e. `char *item_image`, for this line and the next two lines.

2022-05-16 18:00 UTC, ecoble approved these changes

2022-05-16 19:36 UTC, imadejski approved these changes

2022-05-16 22:27 UTC, merged