Openworld/coords tests
uchicago-cs/chiventure pull request #1395
Opened 2022-05-16 01:11 UTC by helenastc

Wrote tests for new coords struct functions and updated the tests for room_new to include coords.

2022-05-17 15:46 UTC, rohandeme commented on src/game-state/src/room.c
> +    free(room->coords);
May want to consider using the free function you wrote for coords_t.

2022-05-17 15:50 UTC, rohandeme commented on tests/game-state/test_rooms.c
> +}
In the future, for either new or init, you may want to consider adding asserts that check that the right value for x and y is passed into the struct.

2022-05-17 15:51 UTC, rohandeme approved these changes
I left a few comments for future considerations, but overall theses tests look good to me!

2022-05-20 19:35 UTC, philipchenaux requested changes
Looking at this PR, it doesn't look like it actually changes anything in the code base. If it is okay with you, I will close this PR

2022-05-20 20:21 UTC, philipchenaux commented
This pull request does not actually modify any part of the code as all modifications seem to have been addressed by past pull requests. Therefore this PR will be closed.

2022-05-20 20:21 UTC, closed without merging