Remove health and surrender_level from npc_battle_t and replace will_fight with hostility_t in npc_t
uchicago-cs/chiventure pull request #1400
Opened 2022-05-16 02:21 UTC by emilybae1705

Creating a pull request for changes made to `npc_battle_t` and `npc_t` and all functions that use those structs. After consulting with RPG-Battles, we have decided to incorporate `surrender_level` into `stat_t`. The original health point of an NPC is equivalent to `max_hp` in `stat_t` and the current health point is equivalent to `hp` in `stat_t`. Additionally, to make the game more interesting and nuanced, @srydbergcox and I decided to replace bool `will_fight` with the `hostility_t` struct. That way, we can increase compatibility between `npc_t` and `npc_battle_t` and can do a simple check of whether an NPC's `hostility_level` is `HOSTILE` to test if they can fight.

2022-05-17 00:35 UTC, emilybae1705 commented
All checks have passed but because `transfer_all_npc_items()` has moved to `src/game-state/src/room.c` from `src/npc/src/npc_battle.c` by @bvvill and there are tests in test_npc_battle.c that test that function, I will consult him about what to do with those tests as well as whether to move the function back to its original place.

2022-05-17 02:13 UTC, bvvill commented
> All checks have passed but because `transfer_all_npc_items()` has been moved to `src/game-state/src/room.c` from `src/npc/src/npc_battle.c` and there are tests in test_npc_battle.c that test that function, I will consult @bvvill about what to do with those tests as well as whether to move the function back to its original place.

the tests for `transfer_all_npc_items` in `transfer_all_npc_items_dead` are failing because the NPC created in those tests hasn't been 'defeated' aka died aka has 0 hp, which is a condition of the function

2022-05-17 17:09 UTC, nicholaswlee requested changes
This looks really great and I like how you have implemented hostility level and integrated health with stat_t. I just have a couple comments on changing fields/setting them that might need to be added in order for everything to work properly. Overall, I think this is a great improvement to the current state and I am excited to implement the surrender_level soon.

2022-05-17 17:09 UTC, nicholaswlee commented on src/battle/examples/battle_command_example.c
> +    printf("Accuracy: %d\n", e_stats->accuracy);
What was the reason for adding a print statement for accuracy but not for crit, or mag_def, or mag_atk?

2022-05-17 17:09 UTC, nicholaswlee commented on src/battle/examples/battle_flow_example.c
> +    p_stats->phys_def = 3;
You should probably set phys_atk to some value here if since battle_flow_move() needs an attack stat to work. I would also set crit as well to some random value, probably 0 if we do not want crits. Both crit and phys_atk/mag_atk need to be set in order for damage to be calculated properly in battle_flow_move().

2022-05-17 17:09 UTC, nicholaswlee commented on src/battle/examples/battle_flow_example.c
> +    e_stats->phys_def = 2;
You should probably set phys_atk to some value here if since battle_flow_move() needs an attack stat to work. I would also set crit as well to some random value, probably 0 if we do not want crits. Both crit and phys_atk/mag_atk need to be set in order for damage to be calculated properly in battle_flow_move().

2022-05-17 17:09 UTC, nicholaswlee commented on tests/game-state/test_rooms.c
> +move_t *create_move(int id, battle_item_t* item, bool attack, int damage, int defense)
Just as an FYI, the move_t data type has changed and this might cause a merge conflict which I can help with when the time comes.

2022-05-17 17:32 UTC, emilybae1705 commented on src/npc/examples/battle_move_example_2021.c
> +            /* Battles can uncomment this once surrender_level gets incorporated into stat_t */
@nicholaswlee this is where battles should uncomment once surrender_level gets incorporated into stat_t

2022-05-17 22:10 UTC, srydbergcox commented on src/battle/examples/battle_command_example.c
> +    printf("Accuracy: %d\n", e_stats->accuracy);
In general, what are these changes for? I do not see anything about them in the PR and am a little bit confused.

2022-05-17 22:13 UTC, srydbergcox commented on src/npc/examples/battle_move_example_2021.c
> +            if (npc_elt->npc_battle->stats->hp == 0) {
Just formatting here, indentation of the conditional statement is a little off.

2022-05-17 22:23 UTC, srydbergcox commented on src/npc/src/npc.c
> +    if (npc->hostility_level == HOSTILE && npc->npc_battle == NULL)
Does this need to also check if `npc->hostility_level` is conditional_friendly?

2022-05-17 22:41 UTC, srydbergcox approved these changes
I think that overall the PR looks good, I just have a couple of clarifying comments/questions to make sure that we're on the same page. But, I am going to approve the PR given that I do not have specific changes that I think need to be completed. Good work!

2022-05-19 03:41 UTC, lilyehsani requested changes
Looks really good overall! Added a few comments, and you will need to resolve the merge conflicts.

2022-05-19 03:41 UTC, lilyehsani commented on src/battle/examples/battle_cli_example.c
> -/*
I believe the battle team commented this example out, and you should probably leave it that way.

2022-05-19 03:41 UTC, lilyehsani commented on src/battle/examples/battle_command_example.c
> -/*
Same here, that this should be commented out. This might be fixed by resolving merge conflicts though.

2022-05-19 03:41 UTC, lilyehsani commented on src/npc/examples/battle_move_example_2021.c
> +            if (npc_elt->npc_battle->stats->hp == 0) {
Adding to this, chiventure uses [Allman Style](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation) brackets and indentation. Please change to this everywhere.

2022-05-19 03:41 UTC, lilyehsani commented on src/playerclass/src/class_prefabs.c
> +    strncpy(temp_name, name, MAX_NAME_LEN + 1);
Good find!

2022-05-20 09:03 UTC, emilybae1705 commented on src/battle/examples/battle_cli_example.c
> -/*
Did they comment out the entire file?
On my end I don't see anything commented out.

2022-05-20 09:12 UTC, nicholaswlee commented on src/battle/examples/battle_cli_example.c
> -/*
Here is what the current [code](https://github.com/uchicago-cs/chiventure/blob/dev/src/battle/examples/battle_command_example.c) looks like in the code base

2022-05-20 09:16 UTC, nicholaswlee commented on src/battle/examples/battle_cli_example.c
> -/*
This was commented out previously, but a recent PR changed it so it is no longer commented [out](https://github.com/uchicago-cs/chiventure/blob/dev/src/battle/examples/battle_cli_example.c), so this should be fine now.

2022-05-20 21:34 UTC, nicholaswlee approved these changes

2022-05-20 21:35 UTC, nicholaswlee commented
I have approved these changes after talking with Emily a bit more about the examples and how they will be managed.

2022-05-21 18:43 UTC, emilybae1705 commented on src/npc/src/npc.c
> +    if (npc->hostility_level == HOSTILE && npc->npc_battle == NULL)
I've purposely just tested for HOSTILE because in a future PR I'm going to implement a function converting hostility_level from CONDITIONAL_FRIENDLY to HOSTILE if an NPC has been provoked. I just think it's more simple to have all battlers be HOSTILE instead of checking whether they're HOSTILE or CONDITIONAL_FRIENDLY.

2022-05-21 18:45 UTC, emilybae1705 commented on src/battle/examples/battle_flow_example.c
> +    p_stats->phys_def = 3;
I've talked to Nicholas and confirmed that the entire `battle_flow_example.c` is commented out for now as the Battles team is making changes to the stats and move structs.

2022-05-21 18:45 UTC, emilybae1705 commented on src/battle/examples/battle_command_example.c
> +    printf("Accuracy: %d\n", e_stats->accuracy);
I've talked to Nicholas and confirmed that the entire `battle_command_example.c` is commented out for now as the Battles team is making changes to the stats and move structs.

2022-05-21 20:24 UTC, lilyehsani commented on src/battle/examples/battle_cli_example.c
> -/*
Oh ok, my bad!

2022-05-22 00:19 UTC, lilyehsani requested changes
Looking good! Just two small changes.

2022-05-22 00:19 UTC, lilyehsani commented on include/game-state/room.h
> +#include "npc/npc_battle.h"
I think Will removed this in his circular dependencies PR, could you remove it as well?

2022-05-22 00:19 UTC, lilyehsani commented on tests/battle/test_battle_flow.c
> -#include <stdlib.h>
Please un-comment this file.

2022-05-23 19:51 UTC, lilyehsani approved these changes
Looks great! Approved.

2022-05-23 19:57 UTC, merged

2022-05-23 21:11 UTC, emilybae1705 commented
This PR is now finished and merged into dev branch. Please see #1283 for details on what changes have been made.

2022-06-05 01:36 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR! When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests.

<!-- {"score": "excellent", "minor": false} -->