Prefab a default NPC Class
uchicago-cs/chiventure pull request #1401
Opened 2022-05-16 09:01 UTC by wellingtj

This PR has used the preexisting models in class_prefabs.c and repurposed them into making a 7th prefab that functions as a base class and is intended for integration with NPC's. This class is called "basic". At the moment it is just a class that is intended to be initialized with no skill trees, items, or anything that is optional. It does have some pretty basic stats, but they are the lowest of any possible

2022-05-16 15:59 UTC, Vincent-Zhang4135 reviewed
It looks good so far! However, I do want to mention that I noticed that you arbitrarily set the basic stats to be 1 for everything. This is an arbitrary decision, and so it is not a big deal, but what do you think if we change it to 5 instead? I think that it would make more sense in the context of all the other classes, because all the other classes have starting stats of factors of 5. 

Additionally, there is a function called check_and_add_stat in class_prefab.c, and I noticed in this function it makes all stats to be 100, which is what it originally was. I think that implies that it is also initializing the originally game stat to be based off of the basic class. Do you think it would make sense to also make sure to change all these to the basic stats you changed for basic class?

2022-05-22 20:34 UTC, wellingtj commented
I have fixed this according to your suggestions vincent

2022-05-23 19:52 UTC, lilyehsani requested changes
Looks good so far! One comment.

2022-05-23 19:52 UTC, lilyehsani commented on src/playerclass/src/class_prefabs.c
> +    else if (!strncmp(temp_name, "basic", MAX_NAME_LEN)) {
Now that this prefab exists, would it also be possible to set this to be the default class for an NPC in npc_new()/npc_init()? Something along the lines of, if NULL is pass to those functions for the NPC class, set it to be this.

2022-05-24 02:48 UTC, wellingtj commented
Hi @lilyehsani, I added some code to to npc new and npc init but for some reason no matter what I did there was no way to get npc.h to recognize the chiventure_ctx_t struct. I asked multiple other people (including a 4th year cs major) and nobody could figure out why that was the case

2022-05-25 03:19 UTC, wellingtj commented
I have gotten everything back to its original state. That was agony but I've fixed EVERYTHING

2022-05-25 19:46 UTC, wellingtj commented on src/playerclass/src/class_prefabs.c
> +    else if (!strncmp(temp_name, "basic", MAX_NAME_LEN)) {
I have fixed this

2022-05-26 00:48 UTC, wellingtj commented
this PR ultimately creates a new prefab for NPC's to use as a default class. It also fixes a few minor bugs in the codebase

2022-05-26 19:13 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-27 16:46 UTC, Vincent-Zhang4135 approved these changes
Hi Jake, good job with the NPC prefab basic class. I noticed that you also created a separate test for the basic class prefab and i appreciate that as it will make debugging easier for future developers if there is an issue. I am approving this and looking forward to having this get merged!

2022-05-27 17:00 UTC, merged

2022-05-27 19:44 UTC, wellingtj commented
A basic class has been completely implemented into the codebase with this PR

2022-06-05 18:16 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->