Sound/background music
uchicago-cs/chiventure pull request #1407
Opened 2022-05-16 17:03 UTC by JaStarbuck

I'm having trouble with compilation because of include statement errors and building chiventure in the workflow. However, the functions I wrote don't look like theres anything glaringly wrong with them. Maybe we could pull it into dev so others can look and we can debug.

2022-05-16 21:58 UTC, JaStarbuck commented
Debugged based off of workflow, got all tests to pass #1319

2022-05-16 22:18 UTC, parkerbroz approved these changes
Great documentation with the comments - made code easy to understand and review. Your implementation seems intuitive and functional. I think our team and other teams will have an easy time working with this module in the future.

2022-05-17 05:50 UTC, ecoble requested changes
This looks good besides some minor style issues!

2022-05-17 05:50 UTC, ecoble commented on src/sound/src/sound.c
> +    if (sound == NULL){ // error check, nothing passed into function
Please add a space between ){, you can check the [style guide](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#style-guide-c) and run a style to automatically fix style issues.

2022-05-17 05:50 UTC, ecoble commented on src/sound/src/sound.c
> +    } else if (sound->type == SOUND_EFFECT){
Same here with style.

2022-05-17 05:50 UTC, ecoble commented on src/sound/src/sound.c
> +        if (!wav){ // error check
Same here with style.

2022-05-17 05:50 UTC, ecoble commented on src/sound/src/sound.c
> +    if (sound == NULL){ // error check, nothing passed into function
Style

2022-05-17 05:50 UTC, ecoble commented on src/sound/src/sound.c
> +    }else if (sound->type == BACKGROUND) {
Style

2022-05-17 05:50 UTC, ecoble commented on src/sound/src/sound.c
> +    else if (sound->type == SOUND_EFFECT){
Style

2022-05-23 07:08 UTC, ecoble approved these changes
Great job!

2022-05-23 07:08 UTC, ecoble commented on src/sound/sandbox/README
> +## Major Drawbacks
This is really useful, great documentation!

2022-05-23 07:09 UTC, merged

2022-05-24 03:40 UTC, JaStarbuck commented
Closing statement: the three functions, load and play and free, have been created and are not giving any errors during the building process. Also, the file now adheres to the style guide. There are some warnings, however, and they will be updated in a new issue.

2022-06-06 22:08 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice job finishing the sound module, and also great documentation!

<!-- {"score": "excellent", "minor": false} -->