Playerclass/Add prefab skill trees and create testing for them
uchicago-cs/chiventure pull request #1408
Opened 2022-05-16 17:11 UTC by vanolson

We filled in missing prefab skill trees in class_prefabs.c, notably, Bard, Mage, Ranger, Rogue, and Wizard, and wrote tests for them in test_class_prefabs.c. In addition, we deleted several obsolete classes that are no longer part of the prefabs.

2022-05-16 20:14 UTC, wellingtj commented
Hi a few comments for my review. Overall this is solid code but I have a few suggestions for how to improve. The third skill for wizard only has the warrior description. The rogue skills have some of the descriptions for bard. You're also missing spaces on the end of the line for the monk class and a few others. Otherwise the prefabs look good and the tests look perfect too. This is great!

Here is more of an idea for where to go next, but definitely not for this code request. It looks like you have 3 skills with one being significantly better than the next. It may be smart to implement some kind of mana cost mechanism. This is more of just a recommendation that should probably be taken up with skill trees or battles, but it's more of where to go next with this. I think some effects should also be added. For example, the wizard can paralyze you, but the paralyze effect isn't implemented in the skill. This would likely require consulting with the skill team so this also is probably not feasible for this pull request, but again it's an idea worth pursuing if possible.

2022-05-16 20:20 UTC, wellingtj approved these changes
I found the review button. Not sure why that was so hard to find. I left my comments on the feed above

2022-05-17 03:02 UTC, lilyehsani requested changes
Looks great! Just one minor note. Love the skill choices too!

2022-05-17 03:02 UTC, lilyehsani commented on src/playerclass/src/class_prefabs.c
> +                                     "A powerful spell that causes a massive explosion with high area damage!", 1, 200,
Split this line at 80 characters to be consistent with the rest of the file.

2022-05-17 03:12 UTC, vanolson commented on src/playerclass/src/class_prefabs.c
> +                                     "A powerful spell that causes a massive explosion with high area damage!", 1, 200,
Made the change!

2022-05-19 00:37 UTC, KabirDubey approved these changes
Looks great to me! The skilltrees team will use this same design if we implement more skilltrees for prefabricated classes.

2022-05-20 21:09 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-20 21:37 UTC, merged

2022-05-23 23:29 UTC, vanolson commented
Katie and I filled the `TODO`-commented skill trees in `class_prefabs.c`. Katie added Rogue, Wizard, and Monk, and I added Bard and Wizard. We also wrote tests for these classes for them in `test_class_prefabs.c`, where I did Bard, Monk, and Ranger, and Katie did Wizard and Rogue. There weren't any major changes that we made after the review, mainly some style changes and error fixes suggested by Jake and Lily. Jake did suggest a few possible additions, but those are larger-scale and are something that could be a new issue in the future. This issue became related to another one from the skill trees team, #1066, which we coordinated with their team.

2022-06-05 01:32 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->