Battle/run battle
uchicago-cs/chiventure pull request #1422
Opened 2022-05-16 22:21 UTC by emiliolevinspage

This pr includes the implementation of the run_turn_component() function in battle_flow.c, including dependencies in battle_logic and battle_print. Note that the changes to the print_battle_move function might conflict with those made by the battle_move team's pull request. We will defer to their changes whenever they conflict with ours.

2022-05-17 04:45 UTC, corian-jal approved these changes
Overall, this looks really good to me! The charts you made when making this obviously helped and I feel like I still have a good idea of how it all works together just from the documentation. I had some minor issues, but nothing that makes the code unrunnable--just some things that might produce wonky results if they don't work out the way you intended.

2022-05-17 04:45 UTC, corian-jal commented on include/battle/battle_flow_structs.h
> + *  - move: determines whether a move can be used or not. Will be 1 or 0.
So for turn_component, will each field (move, item, pass) exclusively be zero or one to say whether they can do something in a turn or not? If it will always be 0 or 1, why have it as an int rather than a bool?
Or is it an int to include functionality for a developer wanting maybe 2 moves (etc) in a turn? If so, that's a smart implementation for it.

2022-05-17 04:45 UTC, corian-jal commented on src/battle/src/battle_flow.c
> +        callback_func(ctx, movestr, callback_args);
Just to be clear, a turn component starts with an enemy, has them take a turn, and then transitions to taking player input to execute their turn all as one function, right? This seems fine, but my only question is then what would happen if the player has a higher speed than the enemy and was meant to move first?

2022-05-17 04:45 UTC, corian-jal commented on src/battle/src/battle_flow.c
> +        int index = (int) input[1];
Will this return the char value stored in input[1] or the ASCII value of that character cast to an int?

2022-05-17 04:45 UTC, corian-jal commented on src/battle/src/battle_print.c
> +                                          mover_name, move_name, target_name, dmg,
move_name is set to equal move->info instead of move->name; is that right?

2022-05-17 04:45 UTC, corian-jal commented on src/battle/src/battle_print.c
> + *  - moves: a linked list of available items
Did you mean to put available moves here?

2022-05-17 04:45 UTC, corian-jal commented on src/battle/src/battle_print.c
> +                                          "%s has %d hp remaining.\n",
Would it be possible to check whether target_name == "you" and have an if statement that has the same function but swaps "has" for "have" so it's not "you has x hp remaining"? However, this is a super minor issue.

2022-05-18 22:41 UTC, emiliolevinspage commented on include/battle/battle_flow_structs.h
> + *  - move: determines whether a move can be used or not. Will be 1 or 0.
for now they are intended as booleans but yeah we want to allow for implementation of multiple actions in a turn component later

2022-05-18 22:44 UTC, emiliolevinspage commented on src/battle/src/battle_flow.c
> +        callback_func(ctx, movestr, callback_args);
a turn component is a part of a single combatant's turn, so it doesnt specify an order of play. for example, a turn could be composed of 3 turn components linked together. that whole linked list would represent a single turn (either the player's or the opponent's).

2022-05-19 01:36 UTC, lilyehsani requested changes
Really great work on this! Just a few comments, let me know if you have questions.

2022-05-19 01:36 UTC, lilyehsani commented on include/battle/battle_flow.h
> +int run_turn_component(chiventure_ctx_t *ctx, turn_component_t component, void *callback_args, cli_callback callback_func);
Split line at 80 characters.

2022-05-19 01:36 UTC, lilyehsani commented on include/battle/battle_flow.h
> + * - component: the turn component being run
Add explanation for other arguments. From `mode.h`:
```
* callback_func: pointer to a callback function
* callback_args: additional arguments to callback function
```

2022-05-19 01:36 UTC, lilyehsani commented on include/battle/battle_flow_structs.h
> + * a certain point of the turn
Explain a bit more here. What does each int represent?

2022-05-19 01:36 UTC, lilyehsani commented on include/battle/battle_flow_structs.h
> +turn_component_list_t *init_turn_component_list(turn_component_list_t *turn, turn_component_list_t *r, turn_component_t c);
Split line at 80 characters.

2022-05-19 01:36 UTC, lilyehsani commented on include/battle/battle_logic.h
> + * - moves an initially empty (NULL) linked list of battle_item_ts that can be used
Did you mean move_t's here?

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +        //print_to_cli(ctx, movestr);
Please delete commented out code.

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +                        void *callback_args, cli_callback callback_func){
Chiventure uses [Allman Style](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation) brackets and indentation. Please change this function and its if statements to that.

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +    callback_func(ctx, strg, callback_args);
This is how I instructed you guys to write the function, and I am pretty sure it will work, but I just want to point out that we should ensure, in testing, the we can call the callback_func multiple times like this. Just keep it in mind.

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_flow_structs.c
> +turn_component_t *init_turn_component(turn_component_t tc, int m, int i, int p){
Change to Allman Style brackets.

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_flow_structs.c
> +      free(tcl->rest);
I think you will have to free the list iteratively. Check out how other linked lists are freed in chiventure.

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_logic.c
> +  // add the combatant's items to the return value for possible items
Nice commenting!

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_print.c
> +        mover_name = "You";
Good change

2022-05-19 01:36 UTC, lilyehsani commented on src/battle/src/battle_print.c
> +  for(i=1; i<=moves_count; i++)
Please [add spaces](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#places-to-use-spaces).

2022-05-19 01:36 UTC, lilyehsani commented on tests/battle/test_battle_print.c
> +/*Test(battle_print, print_player_move)
Why were these tests commented out? Do we have plans to update them? If so, please add a comment about it, and open a backlog issue for updating them.

2022-05-19 02:43 UTC, emiliolevinspage commented on tests/battle/test_battle_print.c
> +/*Test(battle_print, print_player_move)
These tests have been changed by the other battle team in their stat changes pull request- we will be accepting their version, making these ones obsolete - I left a comment to this affect above the commented-out tests.

2022-05-19 02:44 UTC, emiliolevinspage commented on src/battle/src/battle_print.c
> +  for(i=1; i<=moves_count; i++)
Done

2022-05-19 03:21 UTC, aliu65803 commented on src/battle/src/battle_flow.c
> +        int index = (int) input[1];
Thanks for the catch! I will add a -48 so it will return the char value stored in input[1].

2022-05-19 04:44 UTC, aliu65803 commented on src/battle/src/battle_print.c
> + *  - moves: a linked list of available items
Yes we did. I have made the change to reflect this. Thanks!

2022-05-19 04:46 UTC, aliu65803 commented on src/battle/src/battle_print.c
> +                                          mover_name, move_name, target_name, dmg,
Yes, that is what it was before, and we will leave it as it is for now.

2022-05-19 05:35 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-20 21:57 UTC, merged

2022-05-25 03:15 UTC, aliu65803 commented
We are now done with implementing run_turn_component. For this pull request, we created new structs called turn_component_t and turn_component_list_t and implemented a function called run_turn_component which will run the action that the user chooses. We are closing this pull request because our code successfully compiles and passes the tests. Moreover, it has been approved and merged to dev.

2022-05-25 16:25 UTC, emiliolevinspage commented
We have merged successfully, accepting the changes to print functions given by the stats update and fixing some style inconsistencies: run_turn_component is done.

2022-05-27 21:44 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR! Two comments:
1. When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests.
2. Make sure to link the PR to its related issue.

<!-- {"score": "excellent", "minor": false} -->