Sound/tts jason
uchicago-cs/chiventure pull request #1423
Opened 2022-05-16 22:29 UTC by JaStarbuck

Added the test-espeak.c file from https://github.com/espeak-ng/espeak-ng/blob/master/docs/integration.md and cloned the espeak repo so that running ./test-espeak will output sound from the VBox. There is an accidental minor change to sound.c that can be ignored.

2022-05-17 01:04 UTC, jiaoboxuan approved these changes
Looks good. That said, the comment looks like it belongs to a `README.md` file perfectly, so I suggest you do so. Especially considering it's a sandbox, future groups could pick them up easily if they can locate a `README.md`.

2022-05-17 05:58 UTC, ecoble requested changes
This looks good besides some style issues! You can leave the comment in this file for now, but a README containing this as well as installation instructions is a good idea.

2022-05-17 05:58 UTC, ecoble commented on src/sound/sandbox/test-espeak.c
> +// in order to run this, in the chiventure/src/sound/sandbox directory run
Please make this a block comment like this 
/*
 *
 */

2022-05-17 05:58 UTC, ecoble commented on src/sound/sandbox/test-espeak.c
> + void* user_data;
Please switch asterisk to the other side for consistent style, you can fix style automatically using astyle, more documentation [here](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#style-guide-c).

2022-05-17 05:58 UTC, ecoble commented on src/sound/sandbox/test-espeak.c
> + int main(int argc, char* argv[]) {
Asterisk style

2022-05-18 20:44 UTC, jiaoboxuan approved these changes
Looks about okay.

2022-05-18 21:04 UTC, ecoble approved these changes
Nice work! Excited to see the demo!

2022-05-18 21:04 UTC, merged

2022-05-24 03:55 UTC, jwschroeder21 commented
closing statement: 

We first successfully cloned the espeak repo into the VM.  We then followed the demo to create the test-espeak.c file in the sandbox folder of the sound directory. Then, after getting driver warnings from computers that don't have speakers, we ran it on a PC that had speakers (no errors!). 

Our goal is to generalize the process in the demo to create functions to use text to speech during a chiventure game.

With Elizabeth and Victor's approval, this PR has been successfully merged!

2022-06-06 22:11 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice job with e-speak, integrating a new library can be really challenging and you did a great job!

<!-- {"score": "excellent", "minor": false} -->