Quests/implement mission redesign
uchicago-cs/chiventure pull request #1438
Opened 2022-05-17 01:58 UTC by JSerf02

Reworked missions so they actually work. Also added new tests that actually test mission functionality unlike before.

2022-05-17 03:27 UTC, elizabethli31 commented on tests/quests/test_quests_state.c
> +	task_t* task_to_complete = task_new(NULL, id, rewards, prereq);
unnecessary indentation?

2022-05-17 03:34 UTC, elizabethli31 commented on tests/quests/test_quests_state.c
> +	int check = task_init(task, mission, id, rewards, NULL);
count have another task init test that initializes the task with prereqs instead of mission

2022-05-17 03:36 UTC, elizabethli31 approved these changes
Everything looks good, and I like that the passive mission is just the prereqs now. I left two very minor comments about an indentation and writing another test that initializes the task with prereqs, or another test that tries to initialize with both a task and prereq but returns failure.

2022-05-20 18:32 UTC, philipchenaux requested changes
As Elizabeth noted a few minor indentation issues, but this is a very well constructed PR. It is clear what you have implemented and I think this simplifies the code very nicely. Try to quickly fix up the indentations, and then I'll merge this.

2022-05-20 18:43 UTC, philipchenaux requested changes

2022-05-20 18:43 UTC, philipchenaux commented on tests/quests/test_quests_state.c
>  	task_t* task_to_complete = task_new(NULL, id, rewards, prereq);
I was referring to the line indentation on line 539, not the fact that you had extra spaces between lines!

2022-05-20 18:47 UTC, JSerf02 commented on tests/quests/test_quests_state.c
>  	task_t* task_to_complete = task_new(NULL, id, rewards, prereq);
Sorry, didn't notice that. It was actually caused by there being a tab instead of spaces which didn't appear different in my IDE but just pushed a change that fixes it

2022-05-20 18:53 UTC, philipchenaux approved these changes
Great work, looks good to merge!

2022-05-20 18:54 UTC, merged

2022-06-04 16:21 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Great PR, and a very through review!

<!-- {"score": "excellent", "minor": false} -->