Npc class speed
uchicago-cs/chiventure pull request #1458
Opened 2022-05-18 07:35 UTC by jroven

Vincent and I finally got a successful build after trying to incorporate speed stat multiplier into auto_gen_movement() in npc_move.c for issue #1306.

We used this stats hash table function found in stats.h in game-state to change the speed multipliers, and implemented this into auto_gen_movement(). However, because the Test case for Test(npc_mov, auto_gen_movement_indefinite was not written for this change, it crashed. We decided that this can be a separate task of adjusting the test to work for our new implementation/feature, and will close this issue now.

Note: We attempted to create a pull request of this in #1406 but unfortunately the branch that was selected was incorrect. We couldn't figure out a way to change it so this pull request should take the place of the old one.

2022-05-18 22:54 UTC, katie-gao commented on src/npc/src/npc_move.c
>  	      }
This is a small comment, but I would suggest lining up the brackets with the corresponding if/else if statements. So, in this case I would move the brackets back a few spaces to line with the else if statement.

2022-05-18 22:54 UTC, katie-gao commented on src/npc/src/npc_move.c
>              int time_in_room = (rand() % (maxtime_in_room - mintime_in_room + 1)) + mintime_in_room;
Can you guys check if this is in the 80 character line?

2022-05-18 22:54 UTC, katie-gao commented on src/npc/src/npc_move.c
>          if(rc == FAILURE) {
Maybe I am not understanding the code correctly, but if it returns rc in both the if statement and right after, then is the if statement necessary? It might be redundant if it always returns rc.

2022-05-18 22:54 UTC, katie-gao commented on src/npc/src/npc_move.c
> +}
Overall, nice job adding the multiplier and updating the variables to match the changes. I think it is really cool you guys learned the hash table and random functions. I just made a few comments on formatting and had a few questions on the code, but it looks really good. Next, I would just think about how to test it. Also, I like how succinct you guys made the code.

2022-05-20 19:02 UTC, bvvill commented on src/npc/src/npc_move.c
>          if(rc == FAILURE) {
i wondered the same thing too, but then i realized it's part of the loop, so if `rc` is ever `FAILURE` then it'll return and break out of the for-loop

2022-05-23 19:57 UTC, lilyehsani requested changes
Looks good so far! One comment.

2022-05-23 19:57 UTC, lilyehsani commented on src/playerclass/src/class.c
> + *  - succ: an out parameter that is set to SUCCESS if the length of the new
The changes in this file seem to be unrelated to NPC speed. Please remove them.

2022-05-23 20:02 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +	if(npc->movement == NULL || head == NULL) {
Chiventure uses [Allman Style](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation) brackets, please change to this (manually, NOT with the astyle command as that will change all chiventure files).

2022-05-24 21:03 UTC, Vincent-Zhang4135 commented on src/npc/src/npc_move.c
>  	      }
got it! appreciate the minor suggestions!

2022-05-24 21:06 UTC, Vincent-Zhang4135 commented on src/npc/src/npc_move.c
>              int time_in_room = (rand() % (maxtime_in_room - mintime_in_room + 1)) + mintime_in_room;
thanks! I fixed the comments to match the 80 character line convention

2022-05-25 09:11 UTC, bvvill approved these changes
Everything looks good to me now, I went ahead and changed the type of the time being used from int to double, to make future merges easier.

2022-05-25 16:40 UTC, Vincent-Zhang4135 commented
Thank you William helping resolve the tests for us!

2022-05-25 19:23 UTC, katie-gao approved these changes

2022-05-25 19:24 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-25 19:24 UTC, merged

2022-06-05 20:44 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! Like issues, PRs should have closing statements.

<!-- {"score": "excellent", "minor": false} -->