Cli/remove fillers
uchicago-cs/chiventure pull request #1476
Opened 2022-05-19 18:43 UTC by milesgardner

On the cli/remove-fillers branch, we've implemented a function called `remove_fillers()`.  We've unit tested it, and believe it is ready to be merged onto the dev branch.

2022-05-20 18:41 UTC, katyashchukina requested changes
Looks really good! The documentation is very clear and the functions are well structured

2022-05-20 18:41 UTC, katyashchukina commented on src/cli/src/parser.c
> +    //loooping through the four words in the parsed input
Just a typo

2022-05-20 18:41 UTC, katyashchukina commented on tests/cli/test_parser.c
> +}
Should you also include tests asserting the parsing is equal? Like that parse("go to the south") is the same as parse("go south")? It would be a more accurate test than just asserting the presence/absence of a token

2022-05-20 18:41 UTC, katyashchukina commented on tests/cli/test_parser.c
>  }
Again, it might be worth checking for the specific token rather than just his presence?

2022-05-20 22:34 UTC, jacknugent1529 reviewed
It looks good and it's very well documented! I just have a few minor issues and points of clarification

2022-05-20 22:34 UTC, jacknugent1529 commented on include/cli/parser.h
> +//char **remove_fillers(char **parsed_input);
If this doesn't need to be here, it should be deleted. The function documentation can then be moved to the `.c` file

2022-05-20 22:34 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +        if(parsed_input[i] == NULL){ break; }
I'm a bit confused on the purpose of `null_count`. It seems as if that issues is handled here

2022-05-20 22:34 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +            || strcmp("into", parsed_input[i]) == 0){
For clarity, it would be best to have a constant `FILLER_WORDS` and then loop over that. This will make it easier to expand on in the future, and will make the functionality more obvious.

2022-05-21 19:04 UTC, milesgardner commented
Requested changes have been implemented.  I created an array of strings called filler_words, which is looped over when comparing the tokens.  It will make it much easier for future teams to develop.

2022-05-22 20:38 UTC, katyashchukina approved these changes
Nice!

2022-05-23 03:20 UTC, mrestuccia1 commented on include/cli/parser.h
> +//char **remove_fillers(char **parsed_input);
As requested, we moved the documentation of the remove_fillers function to the .c file, and removed it from the header file

2022-05-23 03:21 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +            || strcmp("into", parsed_input[i]) == 0){
As requested, we have implement this change

2022-05-23 03:34 UTC, mrestuccia1 commented on tests/cli/test_parser.c
> +}
As per request, we added a test that does this, comparing two different inputs, which should be the same considering they are filler words

2022-05-23 03:41 UTC, mrestuccia1 commented on src/cli/src/parser.c
> +        if(parsed_input[i] == NULL){ break; }
We remove the null_count part, as requested

2022-05-23 19:47 UTC, jacknugent1529 reviewed
Just a few minor notes. Be sure to follow the style guide. When the style is consistently followed it makes the code much easier to read.

2022-05-23 19:47 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +        if(parsed_input[i] == NULL){ break; }
style: spaces (elsewhere in the function as well)
See the c style guide for a full explanation https://uchicago-cs.github.io/dev-guide/style_guide_c.html#whitespace-in-expressions-and-statements

2022-05-23 19:47 UTC, jacknugent1529 commented on src/cli/src/parser.c
> +    int is_filler = 0;
From what I can tell, this appears to be a boolean value. Declaring it as a bool will make its purpose more clear

2022-05-24 14:13 UTC, jacknugent1529 approved these changes
Looks good to me!

2022-05-24 14:13 UTC, merged

2022-06-06 17:03 UTC, jacknugent1529 commented
PR Score: Excellent

Comments: Great job on this PR! The code was well structured and you responded to the feedback quickly and very well. When writing code or reviewing, always try to follow the style guide so that it's easier to focus on the content of the code itself during reviews.

<!-- {"score": "excellent", "minor": false} -->