Created a new battle_item_t fields and a new battle_equipment_t data structure in battles
uchicago-cs/chiventure pull request #1478
Opened 2022-05-19 21:34 UTC by nicholaswlee

The goal of this pull request was to revamp the battle_item_t data structure to account for more stat changes, and to add battle_equipment_t as outlined in this design [doc](https://github.com/uchicago-cs/chiventure/wiki/Items-~-Equipment-~-Design-Document). A big change with this PR is that we have an entirely new data type battle_equipment, which enhances a player's stats when they enter a battle. Other changes include having stat changes in our battle_item_t data structure as well as allowing combatants to have three different types of equipment: weapon, armor, and accessory. With these new additions, battles are even more customizable battles.

2022-05-20 03:11 UTC, junasano reviewed
Great job! The files related to NPCs look good overall except for a few minor styling issues I outlined below. All are small changes and should be a quick fix. Other than those issues, the PR is ready to go for NPC related things.

2022-05-20 03:11 UTC, junasano commented on src/npc/src/npc_battle.c
> +    npc_battle->armor = armor;
Very minor styling issue: npc_battle->armor = armor should come before the accessory line, since all other orders are armor, then accessory, then weapon.

2022-05-20 03:11 UTC, junasano commented on tests/npc/test_npc.c
> + battle_item_t *npc_create_battle_item_new(int id, int quantity, char* description,
Once again another minor styling issue, I think it would be easier to follow if the order of the parameters followed the actual battle_item_t order. (ie. id, name, description, attributes (and also change "*changes" to "*attributes"), quantity, then attack)
And also change the parameter order for rest of this file as well as test_npc_battle.c whenever this function is called

2022-05-20 03:11 UTC, junasano commented on tests/npc/test_npc.c
> +     item->attributes = changes;
Same thing as above, change order here to match the actual order in struct, and change "changes" to "attributes".

2022-05-20 03:11 UTC, junasano commented on tests/npc/test_npc_battle.c
> + battle_item_t *npc_create_battle_item(int id, int quantity, char* description,
Same thing with order applies here

2022-05-20 04:35 UTC, nicholaswlee commented on src/npc/src/npc_battle.c
> +    npc_battle->armor = armor;
These have been changed to address this issue.

2022-05-20 04:51 UTC, junasano approved these changes
The changes were made accordingly and the PR for the NPC related files are ready to go!

2022-05-20 06:12 UTC, emiliolevinspage approved these changes
after looking over the changes to tests and examples, i feel pretty strongly that all equipment should be wrapped in an equipment arsenal struct to not bloat the combatant structs and to make initialization easier and more updatable in the future. But i think that is a project for a future pull request tbh- this is a lot already. maybe add to the backlog?

2022-05-20 06:12 UTC, emiliolevinspage commented on include/battle/battle_common.h
> +    battle_equipment_t *armor;
if more equipment types are added in the future, might it make sense to wrap the equipment in a struct so the combatant struct doesn't get too bloated?

2022-05-20 06:12 UTC, emiliolevinspage commented on include/battle/battle_flow.h
> -
assuming this was moved to logic or something

2022-05-20 06:12 UTC, emiliolevinspage commented on include/battle/battle_flow.h
> -
indeed it was

2022-05-20 06:12 UTC, emiliolevinspage commented on include/battle/battle_flow_structs.h
> +    battle_equipment_t *armor; // the armor the user holds
same comment as for combatant strut

2022-05-20 20:58 UTC, lilyehsani requested changes
Very thorough PR and cool addition to battles! Just a couple comments, mostly just some missing comments. Great work!

2022-05-20 20:58 UTC, lilyehsani commented on include/battle/battle_flow_structs.h
> +                                battle_equipment_t *weapon,
Update parameters in comment.

2022-05-20 20:58 UTC, lilyehsani commented on include/battle/battle_state.h
> +            stat_t *stats, move_t *moves, battle_item_t *items, battle_equipment_t *weapon,
Update parameters in comment.

2022-05-20 20:58 UTC, lilyehsani commented on include/battle/battle_state.h
> +     stat_t *stats, move_t *moves, battle_item_t *items, battle_equipment_t *weapon,
Update parameters in comment.

2022-05-20 20:58 UTC, lilyehsani commented on include/npc/npc_battle.h
> +                    battle_item_t *items, battle_equipment_t *armor,
Update parameters in comment.

2022-05-20 20:58 UTC, lilyehsani commented on include/npc/npc_battle.h
> +                            battle_item_t *items, battle_equipment_t *armor,
Update parameters in comment.

2022-05-20 20:58 UTC, lilyehsani commented on src/battle/src/battle_default_objects.c
> +    char* description_array[] = {"Reduces enemy's HP by 20",
Nice styling!!

2022-05-20 20:58 UTC, lilyehsani commented on src/battle/src/battle_default_objects.c
> +    char* name_array[]= {"elixir of life ", "healing potion ",
Could you capitalize these and delete the trailing spaces to be consistent with the other functions?

2022-05-20 20:58 UTC, lilyehsani commented on src/battle/src/battle_default_objects.c
> +    rv_item->id = rand ;
Remove extraneous space.

2022-05-20 20:58 UTC, lilyehsani commented on src/battle/src/battle_default_objects.c
> +                                 "Adds 5 to your defense!",
Change these strings to be consistent as well: above you used "Adds 15 to Magical Defense." so, "Adds 5 to Defense." Especially since enemies can probably use these as well.

2022-05-20 20:58 UTC, lilyehsani commented on src/battle/src/battle_default_objects.c
> +    if(rand == 1)
Change to a switch-case to be consistent with previous functions.

2022-05-20 20:58 UTC, lilyehsani commented on src/battle/src/battle_logic.c
> +    }else
else should be on its own line, below here as well.

2022-05-21 20:23 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-21 21:32 UTC, merged

2022-05-28 02:58 UTC, nicholaswlee commented
We have fixed all the comments on the pull request and resolved all the merge conflicts, closing this PR. Since we have completed implementing all of the changes outlined in our design document such as adding/updating structs and updating functions, we are now done. The pull request has been approved by Emilio, Lily, and Jun. This PR allowed for more battle_items_t stat changes as well as new equipment that enhances a users stats. The full breakdown of the doc is [here](https://github.com/uchicago-cs/chiventure/wiki/Items-~-Equipment-~-Design-Document).

2022-06-05 21:09 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->