Refactoring NPC movement by getting rid of separate definite movement and indefinite movement structs
uchicago-cs/chiventure pull request #1483
Opened 2022-05-20 02:31 UTC by bvvill

As detailed in #1475

2022-05-22 13:04 UTC, sglenn-uchi commented on include/npc/npc_move.h
>   */
Incomplete function header

2022-05-22 13:05 UTC, sglenn-uchi commented on include/npc/npc_move.h
>   * Returns the room that the npc is currently in
Incomplete function header (missing parameters)

2022-05-22 13:05 UTC, sglenn-uchi commented on include/npc/npc_move.h
>   * Gets the number of rooms in an NPC's path
Incomplete function header (missing parameters)

2022-05-22 13:05 UTC, sglenn-uchi commented on include/npc/npc_move.h
> +npc_mov_t *npc_mov_new(npc_mov_enum_t mov_type, char *room_id, double room_time);
Return type of should be int if returning SUCCESS/FAILURE or npc_mov_t if returning the struct (contradiction between function description and return value in header comment)

2022-05-22 13:06 UTC, sglenn-uchi commented on include/npc/npc_move.h
> + * and the number of SECONDS that phenomenon is supposed to last,
why is seconds all caps?

2022-05-22 13:06 UTC, sglenn-uchi commented on include/npc/npc_move.h
> +/* Doubly-Linked List of an NPCs path Struct
really minor but "path" can be capitalized

2022-05-22 13:07 UTC, sglenn-uchi commented on include/npc/npc_move.h
> + * 1: if npc has reached the end of the path, reverse_path is called
Maybe change redistribute return values such that 1 is the success case and 2 and 3 are the other cases? just thought it might be more intuitive for future programmers to see 0 as failure case and 1 as success case (unless this would result in a lot of other changes to be made)

2022-05-22 13:08 UTC, sglenn-uchi commented on include/npc/rooms_npc.h
>   */
Incomplete function headers

2022-05-22 13:08 UTC, bvvill commented on include/npc/npc_move.h
>   * Returns the room that the npc is currently in
I don't think you're clicking on the arrow to expand the header descriptions

2022-05-22 13:10 UTC, bvvill commented on include/npc/npc_move.h
> +npc_mov_t *npc_mov_new(npc_mov_enum_t mov_type, char *room_id, double room_time);
Ahhh yes thank you, it's been changed to "Pointer to the new npc_mov_t struct"

2022-05-22 13:11 UTC, bvvill commented on include/npc/npc_move.h
> + * and the number of SECONDS that phenomenon is supposed to last,
to emphasize the change from milliseconds to seconds

2022-05-22 13:13 UTC, sglenn-uchi commented on include/npc/rooms_npc.h
>   */
I think the UT_hash_handle component hh was removed so you can remove it from the struct comment

2022-05-22 13:13 UTC, sglenn-uchi commented on include/npc/rooms_npc.h
>   * Deletes npc_list hashtable, but does not free npcs in hash table
Same as earlier since hashtable was removed

2022-05-22 13:15 UTC, bvvill commented on include/npc/rooms_npc.h
>   */
wym
`/* 
 * Struct for adding and handling npcs in rooms 
 * 
 * Components:
 *  room_id: The name of the room
 *  npc_list: Hash table storing the npcs in the room
 *  num_of_npcs: Number of npcs in the room
 */
typedef struct npcs_in_room {
    UT_hash_handle hh;
    char* room_id;
    npc_hash_t *npc_list;
    int num_of_npcs;
} npcs_in_room_t;`

2022-05-22 13:16 UTC, bvvill commented on include/npc/npc_move.h
> + * 1: if npc has reached the end of the path, reverse_path is called
I agree, the change will be pushed in a few minutes

2022-05-22 13:26 UTC, sglenn-uchi commented on src/game-state/src/room.c
>  int npc_one_move(npc_t *npc, room_hash_t *all_rooms)
was this defined in a header file? im expanding the code in header files and can't find a definition

2022-05-22 13:31 UTC, bvvill commented on src/game-state/src/room.c
>  int npc_one_move(npc_t *npc, room_hash_t *all_rooms)
no , it isn’t ! very weird , i’ll add that when i wakeup later today , nice catch  
!

2022-05-22 16:12 UTC, sglenn-uchi commented on src/npc/src/npc_move.c
> +        return 2;
should 0 be returned here if npc is definite?

2022-05-22 16:20 UTC, sglenn-uchi commented on tests/npc/test_npc.c
> +    earthquake = move_new(1, "earthquake", "", PHYS, NO_TARGET, NO_TARGET,
move_new is defined in battle_moves.h which isn't included in test_npc.c (it is included in test_battle_ai.c though where create_enemy_moves is defined)

2022-05-22 16:39 UTC, sglenn-uchi commented on tests/npc/test_npc_move.c
> +                 SUCCESS, "delete npc_path_dll failed");
think "delete" was kept because of old function name
could change to free just for consistency's sake with new function name

2022-05-22 16:39 UTC, sglenn-uchi commented on tests/npc/test_npc_move.c
> +                 SUCCESS, "delete npc_path_dll failed");
same as above

2022-05-22 16:42 UTC, sglenn-uchi commented on include/npc/npc_move.h
>   */
oh i just expanded it and saw

2022-05-22 22:35 UTC, bvvill commented on include/npc/rooms_npc.h
>   */
for which functions ?

2022-05-22 22:36 UTC, bvvill commented on include/npc/rooms_npc.h
>   * Deletes npc_list hashtable, but does not free npcs in hash table
where was the hashtable removed ?

2022-05-22 22:39 UTC, bvvill commented on src/game-state/src/room.c
>  int npc_one_move(npc_t *npc, room_hash_t *all_rooms)
oh nvm , it's actually already defined in `rooms_npc.h`

2022-05-22 23:58 UTC, bvvill commented on src/npc/src/npc_move.c
> +        return 2;
great observation , and while keeping the return value as 2 for both cases was intentional on my part , I'm convinced that it should be considered an unsuccessful move . Considering the multiple discussions about the outputs of this function , i think it's appropriate to just simplify it to return `SUCCESS` or `FAILURE` . I believe the use of numbers to match specific cases of NPC movement was implemented for easier debugging , and i preserved that style of implementation in my own iterations of the functions , but now i think it's more important to reduce complexity . In order to keep debugging this function relatively easy , I'm going to assign the local variable `path_pos` to be a unique value before every possible return call , to help with tracing .

2022-05-23 00:24 UTC, bvvill commented on tests/npc/test_npc_move.c
> +                 SUCCESS, "delete npc_path_dll failed");
ah yes , i definitely forgot to change that in this branch, thank u!

2022-05-23 00:30 UTC, bvvill commented on tests/npc/test_npc.c
> +    earthquake = move_new(1, "earthquake", "", PHYS, NO_TARGET, NO_TARGET,
tests_npc.c includes npc.h, which includes npc_battle.h, which includes battle_moves.h, so i don't think anything is wrong with this

2022-05-23 01:46 UTC, sglenn-uchi commented on include/npc/rooms_npc.h
>   */
oh my bad i think this was before i realized i could expand the function headers

2022-05-23 01:49 UTC, sglenn-uchi commented on include/npc/rooms_npc.h
>   */
just looked at this again and i have no idea why i thought that... my bad

2022-05-23 01:54 UTC, sglenn-uchi commented on tests/npc/test_npc.c
> +    earthquake = move_new(1, "earthquake", "", PHYS, NO_TARGET, NO_TARGET,
i just noticed it was included in test_npc_battle.c but not in tests_npc.c but you're right, it won't matter since it's functionally the same

2022-05-23 02:23 UTC, sglenn-uchi commented on tests/npc/test_npc_move.c
> +    cr_assert_eq(check2, SUCCESS, "move_npc_def() failed");
I think "move_npc_def()" is the outdated function name. It should be just move_npc_mov, I believe?

2022-05-23 03:12 UTC, sglenn-uchi approved these changes
Aside from the final stylistic comments I made here, I think this PR is complete. I think consolidating the definitive and indefinite movement structs streamlines a lot of the implementation and understanding of the design. This PR looks good and is ready for Lily's final review!

2022-05-23 04:47 UTC, bvvill commented on tests/npc/test_npc_move.c
> +    cr_assert_eq(check2, SUCCESS, "move_npc_def() failed");
yes you're right , updating that now , thank u !

2022-05-24 03:30 UTC, lilyehsani requested changes
Excellent refactor; this design is much cleaner! Just a couple clarification comments.

2022-05-24 03:30 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +    npc_path_dll_t *head = NULL; // these next few lines are VERY important
Add a comment explaining why/what they do

2022-05-24 03:30 UTC, lilyehsani commented on src/npc/src/npc_move.c
> +        path_pos += 1; // For debugging use
What do you mean by "For debugging use"? Should these be removed?

2022-05-24 06:48 UTC, bvvill commented on src/npc/src/npc_move.c
> +        path_pos += 1; // For debugging use
> great observation , and while keeping the return value as 2 for both cases was intentional on my part , I'm convinced that it should be considered an unsuccessful move . Considering the multiple discussions about the outputs of this function , i think it's appropriate to just simplify it to return `SUCCESS` or `FAILURE` . I believe the use of numbers to match specific cases of NPC movement was implemented for easier debugging , and i preserved that style of implementation in my own iterations of the functions , but now i think it's more important to reduce complexity . In order to keep debugging this function relatively easy , I'm going to assign the local variable `path_pos` to be a unique value before every possible return call , to help with tracing .

so I added those lines in order to aid developers (although I'm probably the only one who will ever have to at this point) who are debugging this function by stepping through it. Since there's only 2 possible return values, but many different ways of reaching then, I figured i could just uniquely change a certain local variable (in this case, path_pos) in order to give something debuggers could set a watchpoint on or something, but yeah thinking about it now these should definitely be deleted, thx !

2022-05-25 19:55 UTC, lilyehsani approved these changes
Excellent job! Approved.

2022-05-25 19:55 UTC, merged

2022-05-31 21:38 UTC, bvvill commented
comments from #1475:

Currently, the only difference between the `npc_mov_definite` and `npc_mov_indefinite` structs is that the indefinite one has a hash table of "room times", `npc_room_time_hash_t`, which is just has the room IDs and an integer value for the amount of milliseconds an indefinite NPC is supposed to be in that room. Although a hash_table is technically a doubly-linked list (per uthash's documentation), mapping these time values in the hash table to the steps in the movement path has some problems:
1. If an NPC has a particular room in its path multiple times, it will always stay in that room for the exact same amount of time as before (as opposed to spending 15000 ms in it the first time and 20000 ms the second time, for example), because all values in the hash table must be unique
2. Is unnecessarily complex, and serves as a speed bump in further development of NPC movement

My current plan to alleviate this is to add a time field to the existing `room_id_dll` struct, so that it isn't necessary to have separate structs for definite and indefinite moving NPCs and taking the `mov_type` enum into consideration (where appropriate) will be sufficient, and considerably less complex.

The time field I mentioned in the previous comment will come in the form of the `time_ray_t` struct, which have `time_t start` and `double assigned_time` fields, representing the start time of when an (indefinite) NPC enters a room and the number of seconds that NPC has been assigned to be in that room

This `time_ray_t` struct will be a new member of the `npc_path_dll_t` struct, which I am renaming from `room_id_dll_t`

Definite NPCs will have this `time_ray_t` field to be `NULL`, whereas it will actually be initialized for indefinite NPCs. `init()`, `new`, and `free` functions for the `time_ray_t` struct have been implemented, and they have been abstracted to solely live in npc_move.c, as helper functions.

removed the `move_npc_indefinite` and `move_npc_definite` functions as it's no longer necessary to have separate functions, `move_npc_mov` takes care of both types perfectly

Ran into a little bit of a change amplification problem from going from `int room_time` to `double room_time` in reference to the amount of seconds (which used to be milliseconds, and is being switched in order to be similar to the output of `difftime()` in the standard `time.h` header, which will soon be utilized to its full extent) an indefinite NPC spends in each room along its path, mainly in npc_move.c and room.c

Removed the `register_npc_room_time` function and its test, as `npc_mov_init` now accomplishes the same purpose.

updated `extend_npc_path_indefinite()` and `extend_npc_path_definite()` (and their tests) to reflect changes in the `npc_mov` struct. I've decided to let these functions stay separate because they get called upon often and there's an extra parameter used in `extend_npc_path_indefinite` that would often be unused if the functions were generalized. This makes me really wish there was a good way to do optional arguments in C lol

also, forgot to mention that I've implemented init(), new(), and free() functions for the `npc_path_dll_t` struct, although I've decided to abstract them away to solely reside in `npc_move.c`, since they're basically helper functions

Finally, did some rearranging of the functions in the `npc_move` module so that the functions are sorted by their type of operation, like struct, "get", compare, and "do something" (I could think of no better name, even update didn't totally apply lol) functions


``` strcpy(npc_mov->track, room_id);
    npc_mov->npc_path_pos = 0;
    npc_mov->npc_path_direction = NPC_MOV_ORIGINAL;
    npc_mov->path = NULL;
    npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time);
    DL_APPEND(npc_mov->path, elt);
    return SUCCESS;
```

basically all of the failed builds on this branch are because I had set up `npc_mov_init` like the above code, instead of the below. Letting this serve as a painful reminder that initializing the head of a utlist is essential, as sussing this out took me 2 excruciatingly-long hours

```
int npc_mov_init(npc_mov_t *npc_mov, npc_mov_enum_t mov_type, char *room_id,
                 double room_time)
{
    assert(npc_mov != NULL);
    npc_mov->mov_type = mov_type;
    strcpy(npc_mov->track, room_id);
    npc_mov->npc_path_pos = 0;
    npc_mov->npc_path_direction = NPC_MOV_ORIGINAL;
    npc_path_dll_t *head = NULL; // these next few lines are VERY important
    npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time);
    DL_APPEND(head, elt);
    npc_mov->path = head;
    return SUCCESS;
}
```

2022-06-05 21:15 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this issue! The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples).

<!-- {"score": "excellent", "minor": false} -->