Quest/free
uchicago-cs/chiventure pull request #1484
Opened 2022-05-20 06:13 UTC by jakeziqiwei

Previously task tree wasn't free properly which was causing tests in other branches to fail. We have fixed the free function and revisited how trees are supposed to work.

2022-05-22 16:52 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +task_t *find_task_tree_of_task_in_tree(task_tree_t *tree, char *id)
Something funky is going on with the typing here. This function is supposed to return a task_tree_t while find_task_in_tree is supposed to return a task_t. Also, it doesn't appear that find_task_in_tree is called anywhere as far as I can tell so that function can probably just be deleted.

2022-05-22 16:57 UTC, JSerf02 requested changes
The freeing changes from this push look really good, but I'm concerned that the merge conflicts were resolved a little bit weird and may cause issues with other branches. It seems like this branch is really behind many of the other branches and some of the merges didn't work 100% (in fact, I have no idea how it's compiling considering there are some clear type issues, such as on line 418). Is it possible to scrap this branch and copy paste the free changes into an offshoot of the refactor or status enum branches so both the newer branches and then afterward these free changes can be pushed with less merge conflict issues? The refactor branch should already be up to date with all of the most recent changes.

If you do opt to keep this branch, find_task_tree_of_task_in_tree needs to return a task tree and find_task_in_tree needs to be defined after that function and needs to return a task. All calls to both functions (I think only the first one is called even though the second one should be called at some point too) need to be updated as well to have the correct types

2022-05-22 17:07 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +int task_tree_free(task_tree_t *task_tree)
Looks good! Nice job catching this error and adding in this function!

2022-05-22 17:07 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +task_tree_t *find_task_in_tree(task_tree_t *tree, char *id)
This function shouldn't exist anymore as far as I can tell and it also has the wrong type

2022-05-22 17:08 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +    tree = find_task_tree_of_task_in_tree(quest->task_tree, parent_id);
This line doesn't type check and shouldn't compile

2022-05-22 17:10 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +        task = find_task_tree_of_task_in_tree(cur->task_tree, id);
Also doesn't type check. Will work if the find_task_tree_of_task_in_tree is fixed

2022-05-23 14:35 UTC, jakeziqiwei commented on src/quests/src/quests_state.c
> +        task = find_task_tree_of_task_in_tree(cur->task_tree, id);
This is now PR #1531

2022-05-23 14:35 UTC, jakeziqiwei commented
This is now #1531

2022-05-23 14:35 UTC, closed without merging