Implemented mechanism to specify inventory conditions in a WDL file
uchicago-cs/chiventure pull request #1492
Opened 2022-05-20 18:20 UTC by sabinecodes15

Resolves issue #786 .

This pull request allows game authors to optionally specify a list of condition objects for an object. The function `load_conditions()`, added to load_items.c, checks for a "conditions" attribute in an action object in a WDL file, then adds the listed conditions to the action if they exist.
Additionally, the file "inventory-cond.wdl" in the tests/wdl/examples/wdl/ directory was added to test that conditions are properly applied.

2022-05-21 17:52 UTC, KendrickXie requested changes
Everything looks good. I would just recommend adding a few more comments describing what is happening in the load_conditions function so it is easier to follow for people in the future.

2022-05-21 19:25 UTC, KendrickXie approved these changes
Looks good to me.

2022-05-23 07:26 UTC, ecoble requested changes
This is really great!! Nice job using figuring out how to use the obj library and finishing a task that has been in the back log for a long time! One very small style issue here and a suggestion for the WDL text, otherwise looks good to go!

2022-05-23 07:26 UTC, ecoble commented on src/wdl/src/load_item.c
> +        if(load_conditions(curr, g, item) == FAILURE)
Space after if here, easy fix with astyle.

2022-05-23 07:26 UTC, ecoble commented on tests/wdl/examples/wdl/inventory-cond.wdl
> +                    "text_fail": "You cannot push this table",
For the purposes of demoing, I think it might be worth changing the failure text to be more descriptive like "You cannot push this table. Try taking the chair first." And similarly with the "TAKE" action for the table.

2022-05-23 17:08 UTC, ecoble approved these changes

2022-05-23 17:09 UTC, merged

2022-06-07 01:21 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job! This is a tough issue to solve and your implementation is excellent! Please include closing statements on PRs

<!-- {"score": "excellent", "minor": false} -->