Scene Graphics pullrequest  part1
uchicago-cs/chiventure pull request #1494
Opened 2022-05-20 18:58 UTC by Cyrus-Zhou2302

We have written scene graphics struct to contain information required for scene display. This is to bridge parser and individual draw functions in each module. We have also written new and free functions. We tested these functions and they both passed. We will be adding the drawing function part soon!

2022-05-23 16:35 UTC, imadejski approved these changes

2022-05-23 18:49 UTC, philipchenaux requested changes
Some minor syntax comments, but I am happy with how the code looks. One additional change you have to make is make sure to not include the executable file in the PR and also you should not include the ".DS_Store" files as well.

2022-05-23 18:49 UTC, philipchenaux commented on graphics_sandbox/scene_graphics/scene_graphics.h
> + *      1 on success
Refer to most of the other functions in chiventure, you'll see that they return the macros SUCCESS or FAILURE instead of 1 or 0. Modify your code so that it follows this convention.

2022-05-23 18:49 UTC, philipchenaux commented on graphics_sandbox/scene_graphics/test_scene_graphics.c
> +Test(scene_graphics, new)
Make sure you add a comment that describes what exactly you are testing.

2022-05-23 19:25 UTC, Cyrus-Zhou2302 commented on graphics_sandbox/scene_graphics/scene_graphics.h
> + *      1 on success
This has just been solved! Thanks Philip

2022-05-23 19:25 UTC, Cyrus-Zhou2302 commented on graphics_sandbox/scene_graphics/test_scene_graphics.c
> +Test(scene_graphics, new)
Yup, just added

2022-05-24 02:23 UTC, philipchenaux requested changes
Please address the comments that I have made, and make sure to delete the top-level .DS_Store file before committing again.

2022-05-24 02:23 UTC, philipchenaux commented on graphics_sandbox/scene_graphics/scene_graphics.c
> +    return 1;
As mentioned you should be returning SUCCESS instead of 1.

2022-05-24 02:23 UTC, philipchenaux commented on graphics_sandbox/scene_graphics/scene_graphics.h
> + *      1 on success
change this to return SUCCESS instead of 1. Look at the rest of the code base for guidance.

2022-05-24 02:23 UTC, philipchenaux commented on graphics_sandbox/scene_graphics/test_scene_graphics.c
> +Test(scene_graphics, new)
Please add function comments describing the tests.

2022-05-24 12:52 UTC, Cyrus-Zhou2302 commented on graphics_sandbox/scene_graphics/test_scene_graphics.c
> +Test(scene_graphics, new)
Just added!

2022-05-24 12:53 UTC, cyruszzhou commented on graphics_sandbox/scene_graphics/scene_graphics.c
> +    return 1;
Yup I found that would be a push issue, just pushed again

2022-05-24 12:53 UTC, Cyrus-Zhou2302 commented on graphics_sandbox/scene_graphics/scene_graphics.h
> + *      1 on success
yes this is  a push issue. Just pushed again!

2022-05-24 13:51 UTC, philipchenaux requested changes
Almost there, just remove the top-leave .DS_Store file! You can see that it's still there if you click on "Files changed" tab on GitHub!

2022-05-24 19:21 UTC, philipchenaux approved these changes
Great looks good to merge!

2022-05-24 19:26 UTC, merged

2022-06-04 19:24 UTC, philipchenaux commented
Issue Score: Satisfactory

Comments:
Great work! However, I have one comment: The reviewer for this PR approved the PR without comment. Please make sure that you always do a full review of the code, even if the senior developer has already provided their review. In the rare cases where there truly isn't anything to improve in the PR, make sure to leave a comment confirming that you reviewed the code and don't have any changes to suggest. If the senior dev has left their review, it can also be useful to indicate whether you agree with it or not. Note that this is considered a major issue.

<!-- {"score": "satisfactory", "minor": false} -->