Dsl/dsl-parser module refactor
uchicago-cs/chiventure pull request #1504
Opened 2022-05-20 22:41 UTC by awliu2

We first created a new subdirectory, 'src/dsl_parser'. In this subdirectory, we have created three new files, 'dsl_to_dict.py', 'transformers.py', and 'simple_modifiers.py'. 

'dsl_to_dict.py' specifically focuses on the outward facing export_dict function that is used by the to_wdl module to convert a dictionary/tree into JSON format. 

We moved all of the logical transformers into separate files in order to keep our main outward facing 'dsl_to_dict.py' module clean and concise.

'transformers.py' contains all definitions and functions to transform rooms, actions, items, and the game. For now, we put everything in this file, but as DSL support for Chiventure features grow, it would make sense to split up this file in the future.

'simple_modifiers.py' simply contains all of the one line functions that run simple transformations, i.e labeling items with their id.

Everything compiles and runs as expected.

We have moved each class definition to each file so that in the future, when DSL implements supports features such as NPCs, Battles, etc, they will be placed in separate files. The goal of this is to separate the high-level parsing/conversion function, 'parsed_dict_to_json()', from the rest of the code (which can be hidden at a lower level). Everything has been tested with the example dsl files and works as expected.

2022-05-23 02:45 UTC, baigh1 commented on src/dsl/src/dsl_parser/dsl_to_dict.py
> +class TreeToDict(Transformer):
These have become super concise and readable! Nice job.

2022-05-23 02:57 UTC, baigh1 requested changes

2022-05-23 02:57 UTC, baigh1 commented on src/dsl/src/dsl_parser/dsl_to_dict.py
> +
These have become super concise and readable. Very helpful in abstracting information for other users. (Lines 42-52 in dsl_to_dict.py)

2022-05-23 02:57 UTC, baigh1 commented on src/dsl/src/dsl_parser/dsl_to_dict.py
> +        return ' '.join(s)
For lines 55-87, I am confused why they are still included indsl_to_dict.py, especially when they are followed by what seems like their counterparts in transfoormations.

2022-05-23 02:57 UTC, baigh1 commented on src/dsl/src/dsl_parser/transformers.py
> +    raise Exception('"property FOR object" syntax is not yet supported')
I like overall how you all have split up lower level structures into one file and higher-level structures (player classes, rooms, items, etc) into another. Overall, I think the refactoring was done nicely, just address the redundancy in the dsl_to_dict.py file.

2022-05-23 03:22 UTC, alexlee0422 commented
Fixed the redundancy error in dsl_to_dict.py

2022-05-23 03:32 UTC, baigh1 approved these changes

2022-05-23 19:54 UTC, jacknugent1529 commented
Running the standard commands yields an error for me, so something seems to have gone wrong with refactoring
```
python src/parse.py examples/dsl/demo.dsl
 src/parse.py:82	UserWarning: No output file provided. Default to '/Users/jacknugent/Desktop/220CS/chiventure/src/dsl/examples/wdl/demo.wdl' 
Traceback (most recent call last):
  File "/Users/jacknugent/.pyenv/versions/3.9.0/lib/python3.9/site-packages/lark/visitors.py", line 93, in _call_userfunc
    return f(children)
  File "/Users/jacknugent/Desktop/220CS/chiventure/src/dsl/src/dsl_parser/transformers.py", line 22, in transform_game
    game_dictionary = dict((k, v) for k, v in s if k != "ROOM")
  File "/Users/jacknugent/Desktop/220CS/chiventure/src/dsl/src/dsl_parser/transformers.py", line 22, in <genexpr>
    game_dictionary = dict((k, v) for k, v in s if k != "ROOM")
TypeError: cannot unpack non-iterable Tree object
```

2022-05-23 22:09 UTC, awliu2 commented
Fixed a small typo on line 59 of 'dsl_to_dict.py' (that made it so that the game method was not defined). Code works as expected now, and generates wdl files.

2022-05-25 19:02 UTC, jacknugent1529 approved these changes
Looks good to me! The structure is much clearer than previously

2022-05-25 19:02 UTC, merged

2022-06-06 17:29 UTC, jacknugent1529 commented
Issue Score: E

Comments: Nice work on this PR! The opening summary was very detailed and well-written. When making refactoring changes, be sure to test the code as rigorously as possible (better tests help with this) to ensure you don't accidentally break it.

<!-- {"score": "excellent", "minor": false} -->