Edges_new, init, and free functions
uchicago-cs/chiventure pull request #1506
Opened 2022-05-21 00:53 UTC by williamhu314

In this pull request, we have created new functions that provide functionality for creating a new pointer to an adjacency matrix (i.e. create the edges field in a specgraph, which is a heap-allocated 2D array), initializing the matrix, and freeing the matrix. We also made tests for each of these functions to ensure that they are working correctly.

The edges_new function simplifies the creation of an adjacency matrix for the game author. Rather than having them make a for loop to malloc each row of the matrix, they can just make a heap-allocated 1D array and then pass that into our edges_new function to get a heap-allocated 2D array.

The edges_free function simplifies freeing a heap-allocated 2D array as one would no longer need to use a for loop to free each individual row of the 2D array.

2022-05-21 01:22 UTC, helenastc approved these changes
This looks good, good job adding tests too. I would suggest maybe making a new issue to clear up the differences between edges and specgraph structs.

2022-05-23 18:42 UTC, philipchenaux requested changes
A few minor syntax issues, but besides that I am happy with how the functions and tests look!

2022-05-23 18:42 UTC, philipchenaux commented on include/openworld/gen_structs.h
> +int edges_init(int** edges, int* inp_array, int num_rows, int num_cols);
You must include proper function comments within the .h file. Please refer to other functions for a template to follow.

2022-05-23 18:42 UTC, philipchenaux commented on src/openworld/src/gen_structs.c
> +int edges_init(int** edges, int* inp_array, int num_rows, int num_cols)
Again refer to other functions to see that you need to include a function comment. Specifically you should write /* see gen_structs.h */

2022-05-23 19:15 UTC, rohandeme commented on include/openworld/gen_structs.h
> +int edges_init(int** edges, int* inp_array, int num_rows, int num_cols);
Thanks for the reminder! Just added the comments.

2022-05-23 19:16 UTC, rohandeme commented on src/openworld/src/gen_structs.c
> +int edges_init(int** edges, int* inp_array, int num_rows, int num_cols)
Just added those to the functions to the c files.

2022-05-24 00:58 UTC, philipchenaux approved these changes
Great job, looks good to merge!

2022-05-24 01:05 UTC, merged

2022-06-04 19:31 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR!

<!-- {"score": "excellent", "minor": false} -->