Quests/add status enum
uchicago-cs/chiventure pull request #1523
Opened 2022-05-22 04:45 UTC by JSerf02

This PR adds a quest status enum so quest status values are easier to interpret (before, they were just ints from -1 to 2), adds a new `update_task()` function that calls `accept_reward(complete_task())` with the proper arguments, and modifies the `complete_task()` function to remove tasks from sibling paths to the completed quest from the player's task list so the player becomes committed to their current path on the quest.

2022-05-22 19:58 UTC, elizabethli31 approved these changes
Everything looks good. The enums are descriptive and concise and all the quest functions were updated accordingly. I also like the new create sample functions - makes testing a lot easier.

2022-05-22 20:01 UTC, elizabethli31 commented on include/quests/quests_state.h
> +/* Checks a task for completion and accepts th reward if it is
minor typo

2022-05-23 19:15 UTC, philipchenaux requested changes
As Elizabeth mentioned, I agree that the new enum is very helpful. I commented about a minor issue with return values, and also please address Elizabeth's comment about the typo.

2022-05-23 19:15 UTC, philipchenaux commented on include/quests/quests_state.h
> + * - 0 if the removal was failure, 1 if successful
This and the function above should ideally stick to the convention of returning the macros FAILURE or SUCCESS instead of 1 and 0.

2022-05-23 19:39 UTC, Castel-Jaloux commented on include/quests/quests_state.h
> + * - 0 if the removal was failure, 1 if successful
I just made the edits, and it turns out that the actual functions were already returning SUCCESS or FAILURE - for some reason the header comments indicated differently. At any rate, both that issue and the typo are fixed now.

2022-05-23 20:52 UTC, philipchenaux approved these changes
Looks good to merge, great job!

2022-05-23 20:53 UTC, merged

2022-06-04 19:33 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR!

<!-- {"score": "excellent", "minor": false} -->