Quest/refactor
uchicago-cs/chiventure pull request #1527
Opened 2022-05-22 20:11 UTC by elizabethli31

Previously, the quest feature was divided into two modules: quests_structs and quests_state making it very unorganized and lengthy. We refactored the code into prereqs, tasks, quest, quests_hash, and quests_state. Prereqs, tasks, and quest deal with the structs and initialization functions while quests_hash handles anything related to changing the quest or player hash table. Quests_state holds all the quest functionality functions. There is also a samples module which is used for testing (shared across all the test modules). All tests were refactored accordingly and this branch is merged with add_status_enum.

2022-05-23 04:07 UTC, JSerf02 commented on src/quests/CMakeLists.txt
> -target_include_directories(quests PRIVATE src/)
I don't really understand what most of this does and why some of these lines were replaced, but everything seems to work and build correctly so it's all good with me

2022-05-23 04:15 UTC, JSerf02 approved these changes
This is a spectacular pull request that fixes many of the problems we've been dealing with this quarter! Looking through the changes, everything appears to be fine, since this push mainly restructures existing code instead of adding new functionality (though it is DEFINITELY a necessary restructure). My one comment is that the test suite names and test names are a little bit odd, particularly in test_quests_hash.c, but this is extremely minor and doesn't really matter.

2022-05-24 19:32 UTC, philipchenaux requested changes
This is an excellent PR, very well written and must have taken a lot of work. I added one minor comment that should be resolved, but besides that I am happy with how this looks.

2022-05-24 19:32 UTC, philipchenaux commented on include/quests/quests_hash.h
> + * - 0 if the removal was failure, 1 if successful
Is there any reason why the return values here are 1 or 0 instead of FAILURE and SUCCESS?

2022-05-24 20:33 UTC, jakeziqiwei commented on include/quests/quests_hash.h
> + * - 0 if the removal was failure, 1 if successful
Fixed!

2022-05-25 01:00 UTC, philipchenaux approved these changes
Great work!

2022-05-25 01:01 UTC, merged

2022-06-04 19:35 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR!

<!-- {"score": "excellent", "minor": false} -->