Adding an agent struct to accommodate for the upcoming npc/action implementation
uchicago-cs/chiventure pull request #1536
Opened 2022-05-23 01:53 UTC by junasano

The goal of this PR is to introduce the new agent struct (agent_t) into Chiventure. agent_t can hold an item or npc, meaning that a new layer above items and npcs is added. 
Many helper functions that will be used in the future implementation of npc/actions overlap with the item functions, and thus agent_t was created. 
agent_t is in npc.h, however, there were many files that were affected due to this new struct: 
**npc.h**
Added a new union called agent which has either an item_t or npc_t.
An enum agent_tag was also introduced to differenciate between the two.
game_action_effect_t, action_effect_list_t, and game_action_t were moved from item.h to npc.h to eliminate circular dependency (removed include for item.h)
Changed new_value of game_action_effect to a pointer
Added a new pointer in npc struct

**item.h**
game_action_effect_t was modified to account for the new agent union. 
game_action_effect_t, action_effect_list_t, and game_action_t were moved from item.h to npc.h to eliminate circular dependency (added include for npc.h)
Added forward declaration for game_action_t

**player.h** 
     Added a forward declaration for item.h
**condition.h**
     Added a forward declaration for structs and unions in item.h
     Changed expected_value of attribute_condition_t to a pointer
**game_action.h**
     Added include for npc.h
**condition.h**
     Added forward declartion for player_t
**action_structs.h**
     Added forward declarations of structs and unions in item.h and for      condition_list_t ****check for comment*****
**game.h**
     There were two npc.h includes so removed one and added dialogue.h
**game_action.c**
     Changed few lines to account for agent. And for new_value being      changed to a pointer in npc.h
**condition.c**
     Changed few lines to account for new_value being changed to pointer in npc.h
**sample_game.c**
     Changed few lines to account for attribute_condition_t to a pointer in condition.h
**test_item_actions.c**
     Changed few lines to account for attribute_condition_t to a pointer in condition.h
**test_item_item_actions.c**
     Changed few lines to account for attribute_condition_t to a pointer in condition.h
**test_game.c**
     Changed few lines to account for attribute_condition_t to a pointer in condition.h     
**test_condition.c**
     Changed few lines to account for attribute_condition_t to a pointer in condition.h
**test files**
     There many changes in test files as well. 

Closes #1339

2022-05-23 03:20 UTC, KendrickXie requested changes
Looks good. There are some leftover comments that just look like you forgot to take them out. There are also a lot of style inconsistencies that were probably there before, but they are easy changes.

2022-05-23 03:20 UTC, KendrickXie commented on include/action_management/action_structs.h
> +//typedef struct attribute_wrapped_for_llist attribute_list_t;
remove comment (I'm assuming you are not using it and forgot about this)

2022-05-23 03:20 UTC, KendrickXie commented on include/action_management/action_structs.h
> +//typedef struct attribute attribute_hash_t;
here too

2022-05-23 03:20 UTC, KendrickXie commented on include/game-state/game_action.h
> +//typedef struct attribute attribute_t;
remove comments

2022-05-23 03:20 UTC, KendrickXie commented on include/npc/npc.h
> +    attribute_t* attribute_to_modify;
move the asterisk to the right to be consistent ```attribute_t *attribute_to_modify```

2022-05-23 03:20 UTC, KendrickXie commented on include/game-state/game.h
> +           char* item_modify_name, char* attribute_name, attribute_value_t *new_value);
move the asterisk to the right to be consistent

2022-05-23 03:20 UTC, KendrickXie commented on include/game-state/game_action.h
> +game_action_t *get_action(agent_t *agent, char* action_name);
move asterisk

2022-05-23 03:20 UTC, KendrickXie commented on include/game-state/game_action.h
> +int add_action(agent_t* agent, char *action_name, char* success_str, char* fail_str);
move asterisk

2022-05-23 03:20 UTC, KendrickXie commented on include/game-state/game_action.h
> +int possible_action(agent_t* agent, char* action_name);
asterisk

2022-05-23 03:20 UTC, KendrickXie commented on include/game-state/game_action.h
> +int do_all_effects(agent_t* agent, char* action_name);
asterisk

2022-05-23 03:20 UTC, KendrickXie commented on include/npc/npc.h
> +typedef struct game_action {
move 3 asterisks here

2022-05-23 03:20 UTC, KendrickXie commented on src/game-state/src/game.c
> +               char* item_modify_name, char* attribute_name, attribute_value_t *new_value)
asterisks

2022-05-23 03:20 UTC, KendrickXie commented on tests/action_management/test_item_actions.c
> +    //game_action_free(ga);
remove comment if not needed

2022-05-23 03:20 UTC, KendrickXie commented on tests/action_management/test_item_item_actions.c
> +    //game_action_free(ga);
remove comment if not needed

2022-05-23 05:39 UTC, junasano commented
> Looks good. There are some leftover comments that just look like you forgot to take them out. There are also a lot of style inconsistencies that were probably there before, but they are easy changes.

Thanks! I fixed most of your suggestions but kept a few comments that I felt were useful.

2022-05-24 14:49 UTC, KendrickXie approved these changes
Looks good on the action management side. I'm less sure about the CLI and WDL parts put the logic makes sense to me

2022-05-25 22:24 UTC, sglenn-uchi commented on include/npc/npc.h
> +typedef struct agent
just curious, how did you decide to put the agent struct here vs like item? does it have anything to do with how npcs and items are both agents, but there is still a hierarchy in the sense that npcs can possess items? or is this just the only viable location?

2022-05-25 22:34 UTC, sglenn-uchi commented on src/action_management/src/actionmanagement.c
> +    agent_t *agentdir = malloc(sizeof(agent_t));
where are agentdir and agentindir freed? i don't see those statements in this file

2022-05-25 22:43 UTC, sglenn-uchi commented on include/game-state/game_action.h
> +/* do_all_effects() sets all effects of an agent
think this is a typo– the function is still setting the effects of an action, right?

2022-05-25 23:11 UTC, sglenn-uchi commented on src/cli/examples/extra-command.c
> +    agent_t *agent = malloc(sizeof(agent_t));
like before, is this freed? i don't see a free statement

2022-05-25 23:12 UTC, sglenn-uchi commented on src/common/src/sample_game.c
> +    agent_t *agent_orb = malloc(sizeof(agent_t));
same thing about freeing malloc-ed agend_t structs here and at line 52 but i'll just leave 1 comment in case i'm missing something

2022-05-26 03:08 UTC, sglenn-uchi commented on tests/game-state/test_condition.c
> -    attribute_value_t value;
yeah, so the malloced structs in this file seem to be freed, unlike the other ones. that's my main question

2022-05-26 03:26 UTC, sglenn-uchi commented on include/game-state/item.h
> +// Forward declarations. Full typedef can be found in actionmanagement.h
Very small style issue– should be block comment rather than signature inline "//"

2022-05-26 03:35 UTC, sglenn-uchi commented on src/game-state/examples/stats_example.c
> +    agent_t *agent = malloc(sizeof(agent_t));
Maybe for clarity's sake you could name this poison_agent? As of now, the add_effect_to_item and add_action calls are a little less clear than the original because the item_t struct was just called "poison." With this addition, the calls would read add_effect_to_item(poison_agent->item, poisoned) and add_action(poison_agent...) which could retain the clarity of the original.

This goes for the other malloc calls throughout the examples.

2022-05-26 03:38 UTC, sglenn-uchi commented on src/game-state/src/condition.c
>              return true;
i think you're following K&R style (ex: line 196-197), so this conditional should be written without brackets. this also goes for the ones on 218, 225, 232, 239, and any others in the files.

2022-05-26 03:46 UTC, sglenn-uchi reviewed
All in all this looks good. Other than questions about the implementation, I just had a couple styling suggestions, either for consistency in formatting/syntax or in improving readability for future programmers. All in all it looks good though, I'll just wait to approve until I hear your responses to my comments in the code.

2022-05-26 04:28 UTC, junasano commented on include/npc/npc.h
> +typedef struct agent
Not necessary a hierarchy but more of a dependency issue. The agent struct is used in game_action_effect_t and if I remember correctly, that made it hard to eliminate circular dependencies if agent_t was put in item.h instead. I'm sure it could be done but there would be a lot of moving around things.

2022-05-26 07:02 UTC, junasano commented
> All in all this looks good. Other than questions about the implementation, I just had a couple styling suggestions, either for consistency in formatting/syntax or in improving readability for future programmers. All in all it looks good though, I'll just wait to approve until I hear your responses to my comments in the code.

Thanks for the review! I fixed up all the syntax errors and the freeing things as well.

2022-05-26 10:58 UTC, sglenn-uchi approved these changes

2022-05-26 19:59 UTC, lilyehsani requested changes
Really impressive work here! Just a few comments.

2022-05-26 19:59 UTC, lilyehsani commented on include/action_management/action_structs.h
> +typedef struct attribute attribute_t;
I don't think these are necessary. The build succeeds for me without them.

2022-05-26 19:59 UTC, lilyehsani commented on include/game-state/condition.h
> +typedef struct attribute attribute_t;
These also seem to not be necessary (the game_t above is though).

2022-05-26 19:59 UTC, lilyehsani commented on include/game-state/game_action.h
> +typedef struct game_action game_action_t;
Also don't think these are necessary.

2022-05-26 19:59 UTC, lilyehsani commented on include/game-state/player.h
> +typedef struct item item_t;
Also don't think these are necessary.

2022-05-26 19:59 UTC, lilyehsani commented on src/game-state/src/game_action.c
> +    game_action_t *action = malloc(sizeof(game_action_t));
This is a minor point but I actually think this is not supposed to be malloc'd, because of the way that HASH_FIND works.

2022-05-26 20:34 UTC, junasano commented
> Really impressive work here! Just a few comments.

Thank you! Just finished making the changes.

2022-05-26 21:27 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-26 21:28 UTC, merged

2022-06-05 21:59 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! Like issues, PRs should have closing statements.

<!-- {"score": "excellent", "minor": false} -->