Cli/levenshtein suggestions
uchicago-cs/chiventure pull request #1539
Opened 2022-05-23 03:16 UTC by mrestuccia1

Currently, when a command is not found in Chiventure a function is called to give suggestions. These suggestions are calculated simply by comparing characters. However, this is not a very accurate method, as length can also play a part in similarity. As such, we aim to implement a fuzzy search system (specifically Levenshtein's Distance) in order to better predict what word a user might have been trying to input and suggest it.

2022-05-23 12:54 UTC, fkbad requested changes
Overall, great job! I like the idea and implementation of using the Levenshtein distance since it's a pretty easy algorithim to use when it comes to string similarity. 

All you need now is stellar documentation for this function and I think it can hit the books. 

One thing to note, according to the linked wiki page, there is a more efficient way to calculate the distance involving pre-loading a matrix of distances, that would be a neat thing to mention in some kind of write-up or suggestions for future years doc.

2022-05-23 12:54 UTC, fkbad commented on src/cli/src/operations.c
> +    }else if (tolower(action_input[0]) == tolower(action[0])) {
Add a comment here about the tolower function. 
I had not heard of it before and had to look up what it was since I thought it was your own function that somehow wasn't documented.

2022-05-23 12:54 UTC, fkbad commented on src/cli/src/operations.c
> +    }
simple implementation, good job sticking with the definition of the Levenshtien distance.

2022-05-23 12:54 UTC, fkbad commented on src/cli/src/operations.c
> + * https://en.wikipedia.org/wiki/Levenshtein_distance
good inclusion of the link to make it easy for people to find your source.

2022-05-23 12:54 UTC, fkbad commented on src/cli/src/operations.c
>  char* suggestions(char *action_input, char** actions)
add note about what is actually going to be in this inputted array, I personally know that we will be passing the global `actions_for_sug` array, but make it clear for other teams to easily know what is happening.

This is a byproduct of this function not actually being included in the `operations.h` file.

To be a little more formal, write a full `.h`esque header comment to detail your function. Specifically:
* Brief statement of what the `suggestions` function does
* Brief statement on HOW it does it (computing Levenshtien distance)
  * include small note about what the Levenshtien distance is, something as simple as "the distance is a metric to compare string similarity"
* List of your inputs, and please be specific to how suggestions is actually called in the `actions_error_operation` function in `operations.c`
* List of your outputs 

This is because it the function is already not well documented before this, so adding another layer of complexity warrants proper documentation.

2022-05-23 12:54 UTC, fkbad commented on src/cli/src/operations.c
>      }
Very clean for loop!
Either add a note about how the for loop works inline, or add it to the previously mentioend `.h`esque header comment. 
It is _pretty_ obvious, however I would much rather it be clear to the reader.

2022-05-23 12:54 UTC, fkbad commented on tests/cli/test_cmd.c
> +#include "cli/operations.h"
why include operations.h here?

2022-05-23 14:57 UTC, mrestuccia1 commented on src/cli/src/operations.c
> +    }else if (tolower(action_input[0]) == tolower(action[0])) {
I agree, I have added this change now.

2022-05-23 15:06 UTC, mrestuccia1 commented on tests/cli/test_cmd.c
> +#include "cli/operations.h"
It was included before (in the dev branch) and I accidentally deleted it, so I readded it.

2022-05-23 15:07 UTC, mrestuccia1 commented on src/cli/src/operations.c
>      }
This change has been made as requested, a detailed header has been added.

2022-05-23 16:04 UTC, mrestuccia1 commented on src/cli/src/operations.c
>  char* suggestions(char *action_input, char** actions)
This header has now been added, and clearly explains what the function is.

2022-05-23 16:05 UTC, mrestuccia1 commented on tests/cli/test_cmd.c
> +#include "cli/operations.h"
Added by mistake, is now removed

2022-05-23 19:41 UTC, jacknugent1529 reviewed
It looks good! The documentation is very thorough and the implementation looks solid. Are there any tests written for this function, or, if not, how can you verify that it works?

2022-05-23 19:41 UTC, jacknugent1529 commented on src/cli/src/operations.c
> +    }else if (b < a && b < c) {
style: space after curly brace (fix this throughout the code)

2022-05-23 19:41 UTC, jacknugent1529 commented on src/cli/src/operations.c
> +    if (action_len == 0) {
Minor style issue, but this check should probably be moved to before you define `tail_inp`. The reason is that if `action_input` is length 0, then `tail_inp` will not be well defined. You obviously don't reference it here, but in case someone adds something in the future, it's better to guarantee that invalid pointers won't be created.

2022-05-23 20:21 UTC, mrestuccia1 commented on src/cli/src/operations.c
> +    if (action_len == 0) {
I agree, and have just implemented this change

2022-05-23 20:21 UTC, mrestuccia1 commented on src/cli/src/operations.c
> +    }else if (b < a && b < c) {
Fixed all of these style mistakes

2022-05-23 20:24 UTC, mrestuccia1 commented
I have added tests, and they all pass. To check my answer, I used this Levenshtein Calculator tool online (https://planetcalc.com/1721/)

2022-05-24 14:26 UTC, fkbad approved these changes
Thank you for adjusting your documentation! Makes the code super readable :)

2022-05-24 14:26 UTC, majorsylvie commented on tests/cli/test_cmd.c
Change this to `extern char** actions_for_sug;` and do the same for the `NUM_ACTIONS` constant which are both contained in `operations.c`

This way you don't have to update these separately as you test.

https://stackoverflow.com/questions/6792930/how-do-i-share-a-global-variable-between-c-files

2022-05-26 01:39 UTC, jacknugent1529 approved these changes
Looks good to me!

2022-05-26 01:48 UTC, merged

2022-06-06 22:15 UTC, jacknugent1529 commented
Issue Score: Excellent

Comments: Excellent work on this PR! Everything is documented in a detailed and well-organized fashion. One thing to note is to be careful with using force push, since it can overwrite the git history. Methods such as "revert" can often be used instead.

<!-- {"score": "excellent", "minor": false} -->