pullrequesting input_box_graphics
uchicago-cs/chiventure pull request #1541
Opened 2022-05-23 04:02 UTC by Cyrus-Zhou2302

We have come up with a graphical input box that allows customization on the game developer side. This may very well replace the command line (terminal) input. The input from the user side will be stored in a buffer to be read by the main program, which cleans/restores it after the corresponding implementation. We have written dynamic struct and new/init/free functions for this, and all tests have passed. We wish to pull-request this feature to our graphics sandbox.

2022-05-23 17:18 UTC, csraffaga approved these changes
Works fantastic! Complies, runs, builds, and looks exactly like what we want!

2022-05-24 19:44 UTC, philipchenaux requested changes
Great job! Here are some comments that must be resolved before this can be merged.

2022-05-24 19:44 UTC, philipchenaux commented on graphics_sandbox/input_box_graphics/input_box_graphics.c
> +    return 1;
Remember to return SUCCESS or FAILURE, it might be worth doing some error checking and returning FAILURE if there is a situation to do so. Make sure you also change the .h file to reflect this change in the return value.

2022-05-24 19:44 UTC, philipchenaux commented on graphics_sandbox/input_box_graphics/input_box_graphics.c
> +    return 1;
The same applies here, return SUCCESS or FAILURE (depending on the situation).

2022-05-24 19:44 UTC, philipchenaux commented on graphics_sandbox/input_box_graphics/input_box_graphics.h
> +typedef struct input_box_graphics{
You should be documenting what each of these fields are. Look at other struct definitions for guidance.

2022-05-24 19:44 UTC, philipchenaux commented on graphics_sandbox/input_box_graphics/test_input_box_graphics.c
> +Test(input_box_graphics, new)
Please explain what you are testing.

2022-05-25 01:59 UTC, philipchenaux approved these changes
Great job, looks good to merge!

2022-05-25 02:40 UTC, merged

2022-06-05 09:50 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Great work, but please make sure that you do a thorough code review and, in the future, make sure to look out for the kind of issues the senior developer pointed out.

<!-- {"score": "excellent", "minor": false} -->