Creating a function to change hostility_level of npc based on the tone of their conversation
uchicago-cs/chiventure pull request #1548
Opened 2022-05-23 17:18 UTC by srydbergcox

This pull request will have the implementation of a new function that changes a conditional_friendly npc's hostility_level to hostile, thus allowing it to participate in a battle. To determine when this change will occur, we will also implement a `tone_t` struct that is determined by the conversation which then, if the tone is negative (i.e. angry, annoyed, etc.) the hostility_level will be changed. This will allow for more variety in battles and a greater number of potential paths through a single game.

2022-05-23 17:29 UTC, srydbergcox commented
Now, the declaration and implementation of `make_npc_hostile()` have been completed.

2022-05-23 19:24 UTC, emilybae1705 commented
Because a HOSTILE NPC can become CONDITIONAL_FRIENDLY again once the battle ends, we decided to have the `make_npc_hostile()` function consider both conversion cases and renamed it to `convert_hostility()`.

2022-05-23 20:34 UTC, emilybae1705 commented
Currently considering the case where NPCs can turn CONDITIONAL_FRIENDLY back again after they finish a battle

2022-05-24 14:40 UTC, srydbergcox commented
I made a mistake in opening this PR, we will open a new one when the code for this issue is fully ready for review.

2022-05-30 01:35 UTC, emilybae1705 commented
The npc/dialogue-provocation branch was closed for a while because I `reset --hard dev` which cleared all commits on this branch and reset commit history to dev HEAD. Now I have pushed the same set of changes I've made before but now on this "resetted" branch.

2022-05-30 16:19 UTC, junasano requested changes
Overall it looks goods! I left a few comments but they should be quick fixes.

2022-05-30 16:19 UTC, junasano commented on include/npc/npc.h
> + *  SUCCESS if successful, FAILURE if an error occurred.
It only returns an error if npc is NULL so maybe mention that here

2022-05-30 16:19 UTC, junasano commented on include/npc/npc.h
> + *  SUCCESS if successful, FAILURE if an error occurred.
Same thing with npc being NULL here

2022-05-30 16:19 UTC, junasano commented on include/npc/npc.h
> + *  SUCCESS if successful, FAILURE if an error occurred.
Same thing with npc being NULL here

2022-05-30 16:19 UTC, junasano commented on include/npc/npc.h
> + *  SUCCESS if successful, FAILURE if an error occurred.
And in this case, when npc or edge is NULL, an error is returned

2022-05-30 16:19 UTC, junasano commented on include/npc/npc.h
> + *  SUCCESS if successful, FAILURE if an error occurred.
And in this case, when npc or edge is NULL, an error is returned

2022-05-30 16:19 UTC, junasano commented on src/npc/examples/npc_example.c
> +             "or else I'm gonna force you to.", NEUTRAL);
Although I think leaving the previous year's examples as NEUTRAL is fine, I feel like this is a general example file where people actually might take a look at so change this to HOSTILE to show some variety.

2022-05-30 16:19 UTC, junasano commented on src/npc/examples/npc_example.c
> +             "or else I'm gonna force you to.", NEUTRAL);
Although I think leaving the previous year's examples as NEUTRAL is fine, I feel like this file is a general example file where people actually might take a look at so change this to NEGATIVE to show some variety. And also the npc changing to hostile would be easier to showcase should anyone decide to do it in the future.

2022-05-30 16:19 UTC, junasano commented on src/wdl/src/load_npc.c
> +                      npc_t *npc, tone_t tone)
Add tone in the parameters right above this.

2022-05-30 16:19 UTC, junasano commented on src/wdl/src/load_npc.c
> +                      npc_t *npc, tone_t tone)
Add tone in the parameters right above this.
Also, is there a reason why you added tone here? This function doesn't seem to use tone anywhere.

2022-05-30 16:19 UTC, junasano commented on src/wdl/src/load_npc.c
> +            if (load_node_actions(actions_obj, convo, id, npc, tone) != SUCCESS) {
Same as above, the tone doesn't seem to be doing any work here?

2022-05-30 16:19 UTC, junasano commented on src/wdl/src/load_npc.c
> +            if (load_node_actions(actions_obj, convo, id, npc, tone) != SUCCESS) {
Same as above, the tone doesn't seem to be doing any work here?

2022-05-30 16:19 UTC, junasano commented on tests/npc/test_dialogue.c
> +    tone_t tone = NEUTRAL;
The example files explicitly had NEUTRAL as a parameter rather (had something like add_node(c, "N2", "D2", NEUTRAL);) than having it previously defined, but in this file, the tone is pre-defined and the variable is used as parameters. Might be better to stick to one method for all the files.

2022-05-30 16:19 UTC, junasano commented on tests/npc/test_dialogue.c
> +    tone_t tone = NEUTRAL;
The example files explicitly had NEUTRAL as a parameter rather (had something like add_node(c, "N2", "D2", NEUTRAL);) than having it previously defined, but in this file, the tone is pre-defined and the variable is used as parameters. Might be better to stick to one method for all the files.

2022-05-30 16:19 UTC, junasano commented on src/npc/src/npc.c
> +        case POSITIVE:
Just a quick thought but maybe make it so that if the tone is POSITIVE, make the npc friendly?

2022-05-30 16:19 UTC, junasano commented on src/npc/src/npc.c
> +        case POSITIVE:
Just a quick thought but maybe make it so that if the tone is POSITIVE, make the npc friendly?

2022-05-30 17:29 UTC, emilybae1705 commented on tests/npc/test_dialogue.c
> +    tone_t tone = NEUTRAL;
I just left it as a variable with tone parameters because this is a testing file unlike the previous examples files which explicitly had dialogue to which I could add tones.

2022-05-30 18:26 UTC, junasano approved these changes
Looks good to go

2022-05-30 18:26 UTC, junasano commented on include/npc/npc.h
> + *  SUCCESS if successful, FAILURE if an error occurred.
It only returns an error if npc is NULL so maybe mention that here

2022-05-31 05:26 UTC, lilyehsani reviewed
Looks great so far! Just one question.

2022-05-31 05:26 UTC, lilyehsani commented on src/npc/src/npc.c
> +int change_npc_hostility(npc_t *npc, edge_t *edge)
Is this function called anywhere? If not, should it be?

2022-05-31 15:06 UTC, emilybae1705 commented on src/npc/src/npc.c
> +int change_npc_hostility(npc_t *npc, edge_t *edge)
We were intending to call it with `add_start_battle()` in `dialogue.c` but the function hasn't been implemented yet. I added a note under that function in `dialogue.h` as a TODO list.

2022-05-31 15:30 UTC, lilyehsani commented on src/npc/src/npc.c
> +int change_npc_hostility(npc_t *npc, edge_t *edge)
Sounds good

2022-05-31 15:30 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-31 15:33 UTC, merged

2022-05-31 17:24 UTC, emilybae1705 commented
This PR implemented a new `tone_t` enum in `dialogue.h` which identifies a dialogue as POSITIVE, NEUTRAL, or NEGATIVE, and new functions `make_npc_hostile()`, `make_npc_cond_friendly()`, and `change_npc_hostility()`. A NEGATIVE tone in a player's edge can trigger a CONDITIONAL_FRIENDLY NPC to become HOSTILE in `change_npc_hostility()`. A POSITIVE tone can make them CONDITIONAL_FRIENDLY again. Because our design states that FRIENDLY NPCs stay FRIENDLY throughout the game, `change_npc_hostility()` only converts hostility_level for non-FRIENDLY NPCs. A note for future implementation is to call `change_npc_hostility()` with `add_start_battle()` in `dialogue.c` such that if an NPC's hostility_level has become HOSTILE due to `change_npc_hostility()`, a `START_BATTLE` action flag is added to the NPC's node, triggering the `start_battle()` function in the battle team's module.

2022-06-05 22:07 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! The closing statement is very thorough. When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests.

<!-- {"score": "excellent", "minor": false} -->