Quest graphics struct new/init/free and tests
uchicago-cs/chiventure pull request #1549
Opened 2022-05-23 18:04 UTC by Cyrus-Zhou2302

We have written structs for quest graphics display. We also provided new init free functions for the struct. All tests written with criterion have passed. We want to merge it to the dev branch.

2022-05-23 18:59 UTC, philipchenaux requested changes
I'm happy with how this looks, again a minor comment on return values from functions. By the way it is good that you have included the .gitignore file as part of your PR now, that way the .DS_Store files no longer are included.

2022-05-23 18:59 UTC, philipchenaux commented on graphics_sandbox/quest_graphics/quest_graphics.h
> + *      1 on success
Please refer to my comment on https://github.com/uchicago-cs/chiventure/pull/1494#pullrequestreview-982216190 about returning 1 from functions. You should implement functions that return either SUCCESS or FAILURE.

2022-05-23 19:01 UTC, csraffaga approved these changes
tests run and build perfectly! all pass

2022-05-23 19:44 UTC, Cyrus-Zhou2302 commented on graphics_sandbox/quest_graphics/quest_graphics.h
> + *      1 on success
Thanks! Just resolved!

2022-05-24 19:24 UTC, philipchenaux approved these changes
Great job, looks good to merge!

2022-05-24 19:34 UTC, merged

2022-06-05 09:54 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR!

<!-- {"score": "excellent", "minor": false} -->