Quests/wdl
uchicago-cs/chiventure pull request #1552
Opened 2022-05-23 20:27 UTC by JSerf02

Added a WDL parsing function for quests and fixed a ton of bugs in quest functions. The function is also tested extensively. One note, though, is that many aspects of quests objects that can be in a WDL file are not required in order for quests to function, but if they are not included, parsing treats it as an error and prints it into stderr. This doesn't prevent the program from running (you can see from the tests that everything works 100% correctly) so it shouldn't really be a problem, but it just means stderr will have a ton of error messages. You can see this from the test output as well.

2022-05-24 01:30 UTC, elizabethli31 commented on src/wdl/src/load_quests.c
> +task_t *load_task(obj_t *task_obj, game_t *game) {
load_task should have a header like the other functions

2022-05-24 01:33 UTC, elizabethli31 requested changes
WDL is very comprehensive and includes all the objects which are thoroughly included step by step in load_quests.c. This needs to be updated with dev so it doesn't have any merge conflicts. Also load_task should have a header.

2022-05-25 18:33 UTC, philipchenaux requested changes
Minor comment on return values again, but once that is addressed this looks good to merge! Also please address Elizabeth's comment.

2022-05-25 18:33 UTC, philipchenaux commented on include/quests/quests_hash.h
> + * - 0 if the removal was failure, 1 if successful
Fix return values for this function and the one below to SUCCESS or FAILURE

2022-05-25 21:26 UTC, elizabethli31 approved these changes
Changed made and looks good to me!

2022-05-26 01:37 UTC, philipchenaux approved these changes
Looks good to merge!

2022-05-26 01:39 UTC, merged

2022-06-05 09:55 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR!

<!-- {"score": "excellent", "minor": false} -->