added sound into example
uchicago-cs/chiventure pull request #1559
Opened 2022-05-23 21:15 UTC by sangerr

In this pull request, we added the load sound feature into an example game. The implementation for the load sound was created by referencing the previous demos.

Assignees: Jake, Rhea

2022-05-24 03:43 UTC, jwschroeder21 commented
closing statement:

In this pull request, we created a sample game that implements sound with chiventure structs. We replaced the comments where the sound structures were meant to go with their actual implementations. This pull request contains the implementations with inspiration from the demo that incorporates the sound modules in the example.

2022-05-25 20:29 UTC, parkerbroz approved these changes

2022-05-26 19:37 UTC, ecoble requested changes
Great job! Just a couple small changes.

2022-05-26 19:37 UTC, ecoble commented on src/sound/examples/sound_example.c
> +    Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT,2, 2048);
Please have consistent spacing between the commas, one is missing here. Also please 2048 a macro or const variable with a descriptive name at the top of this file so that it is not a "magic number".

2022-05-26 19:37 UTC, ecoble commented on src/sound/examples/sound_example.c
> +    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
Same thing about variables or macros for 255 number.

2022-05-26 20:03 UTC, parkerbroz reviewed
I'll echo Elizabeth's notes about the comma spacing and giving some meaning for the large constants you included in those function calls.

2022-05-28 02:34 UTC, sangerr commented
I converted the arbitrary numbers into macro variables, so that the code is more readable and future teams can mess around with the numbers.

2022-05-29 22:14 UTC, ecoble approved these changes
Nice job!

2022-05-29 22:16 UTC, merged

2022-05-31 14:00 UTC, jwschroeder21 commented
Closing statement: In this pull request, we added the load sound feature into an example game. The implementation for the load sound was created by referencing the previous demos. We incorporated these functions into the previously existing sample game we implemented from the issue sound: research and create chiventure structs needed for the sound example.

2022-06-07 00:15 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job getting this example up and running!

<!-- {"score": "excellent", "minor": false} -->