Action management/1290 make view stats actions
uchicago-cs/chiventure pull request #1578
Opened 2022-05-24 04:31 UTC by HarrisonD123

We made several changes to our new `do_self_actions` function to make it easier for the CLI team to call and to make it easier to have our function support many new viewing actions.

Our do_self_actions function now only contains the parameters `chiventure_ctx_t *c`, `action_type_t *a`,
`char* target`, and `char **ret_string`
The target parameter decides what the user wants to view. We were able to remove the previous version's `player_t` parameter because we realized that the `chiventure_ctx_t` struct already contains a player.
We also implemented a deeper if-else statement structure to allow for viewing of other interfaces (i.e. skills, quests, inventory, etc.) in the future.

2022-05-24 05:50 UTC, sabinecodes15 commented on include/action_management/actionmanagement.h
> +                  char* target, char **ret_string);
```suggestion
                  char *target, char **ret_string);
```

2022-05-24 05:52 UTC, sabinecodes15 commented on include/action_management/actionmanagement.h
> + * - target: An enum describing what self-related object (STATS, etc)
```suggestion
 * - target: A string describing what self-related object (STATS, etc)
```

2022-05-24 05:53 UTC, sabinecodes15 commented on src/action_management/src/actionmanagement.c
> +                   char* target, char **ret_string)
```suggestion
                   char *target, char **ret_string)
```

2022-05-24 05:55 UTC, sabinecodes15 requested changes
A few cosmetic changes, but otherwise looks good!

2022-05-24 14:29 UTC, merged

2022-06-07 01:14 UTC, ecoble commented
I am removing the milestone and this PR will remain ungraded since it was mistakenly merged and a new graded PR was opened in its place.