Action management/do self action errors
uchicago-cs/chiventure pull request #1580
Opened 2022-05-24 04:54 UTC by HarrisonD123

Given that our do_self_action function now has an if-else logic chain to test what the user wants to view (based on strcmp's), we now have a way to error check the item that the user wants to view. This means that if the user types view porta-potty into the command line, we will be able to return an error message. We also have an error message to check for the action itself in the rare case in which CLI passes us an invalid action (currently anything other than "view").

We've also added a new nested if-statement under the conditional that checks for "view", that supports the statement view effects. Upon this command, the do_self_action function will now call the do_stat_effect function from the game-state/stats module. For this specific command, we did not need to collaborate with any other teams. We currently have plans to support even more view actions in the near future in collaboration with other teams.

2022-05-24 16:45 UTC, jbrouwer5 requested changes
Once the target parameter is changed in the function header and the other comments are checked over this code is good to go!

2022-05-24 16:45 UTC, jbrouwer5 commented on include/action_management/actionmanagement.h
> +                  char* target, char **ret_string);
In the function description you have that target is an enum, but then you give it a char* type instead. If it is supposed to be an enum, make sure the function actually takes a value from a defined enum. If it is supposed to take a string just make sure the description aligns with that.

2022-05-24 16:45 UTC, jbrouwer5 commented on src/action_management/src/actionmanagement.c
> +                   char* target, char **ret_string)
Make sure to apply any changes to the function header relating to the enum here as well.

2022-05-24 16:45 UTC, jbrouwer5 commented on src/action_management/src/actionmanagement.c
> +        if (strcmp(target, "stats") == 0) {
Just checking that CLI will always pass an all lowercase string to target. If not you should let them know that it needs to be lowercase or add the string adjustments in here.

2022-05-24 16:45 UTC, jbrouwer5 commented on include/action_management/actionmanagement.h
>   * - 6 if conditions for the action haven't been met, failure string as an out parameter
I don't see the return value of 6 being used in the function.

2022-05-24 21:23 UTC, ecoble approved these changes
Once Jackson's changes are addressed, this looks good to me!

2022-05-25 04:25 UTC, HarrisonD123 commented on src/action_management/src/actionmanagement.c
> +        if (strcmp(target, "stats") == 0) {
Yep! CLI changes all strings to lowercase

2022-05-25 04:26 UTC, HarrisonD123 commented on src/action_management/src/actionmanagement.c
> +                   char* target, char **ret_string)
Fixed

2022-05-25 04:26 UTC, HarrisonD123 commented on include/action_management/actionmanagement.h
>   * - 6 if conditions for the action haven't been met, failure string as an out parameter
That was left over from a previous function's comments. Just removed that line!

2022-05-25 04:33 UTC, jbrouwer5 approved these changes
Looks good!

2022-05-26 16:44 UTC, merged

2022-06-07 01:14 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice job adding error checking and reviewing this PR! Please include closing statements.

<!-- {"score": "excellent", "minor": false} -->