Sound/warnings
uchicago-cs/chiventure pull request #1583
Opened 2022-05-24 07:09 UTC by JaStarbuck

Summary: after merging the load/free/play functions for sounds, it turns out there were warnings in the code. To get rid of these warnings, we needed to create a new union so that different sound types could be returned from and passed between functions. This was very involved and required another deep dive into the demo.c code. This work was necessary, however, because it will allow us to more accurately create new functionality for the sound module and will also be accurate and reliable for other groups that intend to use the sound module. #1551

2022-05-24 18:49 UTC, sangerr approved these changes
Given that there are no more warnings or errors occurring, it seems like this pull request is good to be merged. The commit names are very funny but I think that adding a comment to the PR that details how/why you made the changes you did to fix the warnings would be great, as it is difficult to understand that from the commits. After that, I think that it is good to merge!

2022-05-24 22:34 UTC, JaStarbuck commented
As Rhea said, this comment will be about what was changed that helped with the error: Originally, we were passing in the string name of the music to the function to play the music. This was incorrect as it needed the music struct to be passed into it. Then, the problem we experienced was that we needed to distinguish between the music struct and sound effect struct being passed into the built in SDL functions. This is why we created the union so that either the music or sound effect struct was contained and could thus be conditionally passed into the SDL functions. Then any other changes were just fixing the functions so that they were returning/taking in the correct structs and unions.

2022-05-24 22:42 UTC, ecoble requested changes
Great job fixing the warning and creating the union type! One small syntax issue with using the union, otherwise looks good to me.

2022-05-24 22:42 UTC, ecoble commented on src/sound/src/sound.c
> +        loaded->backgroundSound = mus;
Union types are accessed with the following syntax: `loaded.backgroundSound`

2022-05-24 22:42 UTC, ecoble commented on src/sound/src/sound.c
> +        loaded->soundEffect = wav;
Same syntax here.

2022-05-24 22:42 UTC, ecoble commented on src/sound/src/sound.c
> +        Mix_FreeMusic(soundType->backgroundSound); // frees resources assocateed with the music
Here as well, and line 59.

2022-05-24 22:42 UTC, ecoble commented on src/sound/src/sound.c
> +        Mix_PlayMusic(music->backgroundSound, -1); // play the music
Syntax

2022-05-24 23:19 UTC, ecoble approved these changes

2022-05-24 23:19 UTC, merged

2022-05-24 23:21 UTC, JaStarbuck commented
Closing statement: In this pull request the union and slight function restructuring around the union was a success. We accidentally made a change to the union syntax which was changed back during the pull request. Now, these functions will be able to be used in the demo and by future groups integrating sound into chiventure!

2022-06-07 00:33 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job debugging this and creating the new union struct! 

<!-- {"score": "excellent", "minor": false} -->