Battle test utility
uchicago-cs/chiventure pull request #1584
Opened 2022-05-24 07:29 UTC by nmkhan100

I am creating this pull request in order to add the battle_test_utility.c file to our collection of battle test files for the other battle test files to import and use functions from. This file contains all the functions that are in the battle test files and used in tests, except this time it won't be necessary to copy paste the functions into each file whenever needed. We would simply import the battle_test_utility.c file into the test file for it to use the functions it needs.

2022-05-24 18:04 UTC, lilyehsani commented
@srydbergcox has been added as a reviewer for this PR because he originally identified the issue.

2022-05-24 18:10 UTC, lilyehsani requested changes
This looks good so far, but the idea of creating this file is also to use it. Could you also remove these functions from the test files and #include this file in those files? You should also do this in test_npc_battle.c (https://github.com/uchicago-cs/chiventure/blob/dev/tests/npc/test_npc_battle.c)

2022-05-25 19:33 UTC, lilyehsani requested changes
Just a couple more comments, this is almost ready for student review.

2022-05-25 19:33 UTC, lilyehsani commented on src/battle/src/battle_test_utility.c
> +class_t *make_new_warrior_class()
Great job renaming these!

2022-05-25 19:33 UTC, lilyehsani commented on src/battle/src/battle_test_utility.c
> +void check_add_node(int num_nodes)
Could you actually put this one and the following one back in test_dialogue.c? They are not actually related to battles at all and are only related to dialogue. (check_add_node and check_add_edge).

2022-05-25 19:33 UTC, lilyehsani commented on tests/npc/test_npc_move.c
> +#include "../../include/battle/battle_test_utility.h"
Since this file is not related to battles, I think we should leave the include statements how they were, to avoid circular dependencies in the future.

2022-05-25 19:33 UTC, lilyehsani commented on tests/npc/test_rooms_npc.c
> +#include "../../include/battle/battle_test_utility.h"
Since this file is not related to battles, I think we should leave the include statements how they were, to avoid circular dependencies in the future.

2022-05-25 19:36 UTC, emiliolevinspage approved these changes
minor changes- i think the versions of stat-giving functions should be made more descriptive, but otherwise this looks good to me!

2022-05-25 19:36 UTC, emiliolevinspage commented on tests/battle/test_battle_utility.c
> +move_t* create_enemy_moves()
i think some of these function names should be more detailed to explain what they are used for, or have more documentation in the comments

2022-05-25 19:36 UTC, emiliolevinspage commented on tests/battle/test_battle_utility.c
> +void check_give_move(combatant_t* player, combatant_t* enemy, difficulty_t difficulty, move_t* expected)
does this belong here even tho it is so specific?

2022-05-25 19:36 UTC, emiliolevinspage commented on tests/npc/test_npc.c
> +    move_t *moves = create_enemy_moves_v1();
what are the other versions of this?

2022-05-25 19:36 UTC, emiliolevinspage commented on tests/npc/test_npc.c
> +    move_t *moves = create_enemy_moves_v1();
/ can they be combined or renamed more descriptively?

2022-05-25 19:36 UTC, emiliolevinspage commented on tests/npc/test_npc_battle.c
> +    move_t *moves = create_enemy_moves_v1();
i think these could be renamed to describe why they are different

2022-05-25 22:15 UTC, srydbergcox approved these changes
Good work! This all looks good to me. I know that this will be super helpful in the future since making all of your own classes, etc. gets super tedious. I will approve the PR.

2022-05-26 00:42 UTC, lilyehsani approved these changes
Looks good! Great job on the refactor! Approved.

2022-05-26 00:42 UTC, merged

2022-05-28 01:18 UTC, nmkhan100 commented
I have created a battle_test_utility.c/.h file for both the battle and NPC tests to import and use functions from. This has been implemented to prevent teams from having to copy paste functions into every test file for the tests to use the functions and pass. The files have also been made more readable through the renaming of different functions, removal of duplicate functions found in multiple test files as a result of copy pasting, and the grouping of similar functions (and labeling). I have also both added and modified comments describing all the functions. Now it will be very easy for these teams to use functions in their tests, and in the future, if they want to add more functions for the tests to use, they can simply add it to these files I have created.

2022-06-05 22:29 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->