Create a script in the sandbox testing the boolean data type with Lua
uchicago-cs/chiventure pull request #1585
Opened 2022-05-24 11:35 UTC by tatmaca

Merge request to resolve Issue #1561:

"The custom-scripts team has decided that, along with the documentation we've written up this quarter, we wanted to leave a substantial code base through which future teams can clearly see how they can implement Lua with the different data types described in our arg_custom_type module.

This issue is complete when a successful merge request is made which incorporates a Lua function which can accurately update a boolean data type ingrained in a unique game struct."

2022-05-26 04:07 UTC, RamarkoB approved these changes
Looks Great! I already worked with Maggie to finish up the files, and It looks like everything compiles correctly, so the demos and the updated boolean system is working correctly. We can still only compile one file at a time, but that doesn’t seem to be an actual problem! Good work on the new booleans!

2022-05-27 22:24 UTC, ecoble requested changes
Looks great overall! A few small changes, also it looks like there are still some cache files. Please refer to the message Borja sent about removing them, if you are having trouble with it let me know.

2022-05-27 22:24 UTC, ecoble commented on src/custom-scripts/CMakeCache.txt
> +# This is the CMakeCache file.
Please remove this cache file

2022-05-27 22:24 UTC, ecoble commented on src/custom-scripts/examples/CMakeCache.txt
> +# This is the CMakeCache file.
Please remove this cache file

2022-05-27 22:24 UTC, ecoble commented on src/custom-scripts/examples/Makefile
> +# CMAKE generated file: DO NOT EDIT!
This should also be removed

2022-05-27 22:24 UTC, ecoble commented on src/custom-scripts/examples/demonstration.c
> +    // make key something that can be taken
Maybe start this comment with a TODO so it is clear you are planning to implement this.

2022-05-27 22:24 UTC, ecoble commented on src/custom-scripts/examples/flip.lua
> +function foo(st)
You can instead just do `return !st`

2022-05-27 22:24 UTC, ecoble commented on src/custom-scripts/examples/gold.h
> +int coins;
Indentation

2022-05-27 22:28 UTC, ecoble requested changes
Also please remove the Lua submodule, it should get included by the build

2022-05-29 22:26 UTC, ecoble requested changes
Please remove the Lua submodule, it should already be installed on the CSIL machines. Let me know if you are having trouble doing this.

2022-05-31 18:51 UTC, ecoble approved these changes

2022-05-31 18:51 UTC, merged

2022-05-31 23:12 UTC, tatmaca commented
This issue is now closed! In preparation for our final demo, we've merged a branch that runs a chiventure game and experiments with using Lua to manipulate boolean values. This simple function is critical as it can add easy game manipulation through the use of ON/OFF, ACTIVE/INACTIVE, etc. to implement logic on the players end as they progress through a game.

2022-06-07 02:19 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job on this example, and nice work making the requested changes!

<!-- {"score": "excellent", "minor": false} -->