Create a demo where two arguments are passed into Lua script
uchicago-cs/chiventure pull request #1586
Opened 2022-05-24 13:11 UTC by tatmaca

In an effort to increase our familiarity with Lua as well as build a greater volume of scripts in our sandbox for future developers, our team decided to create a more advanced script compared to what already exists at present. All of our previous samples in the sandbox were isolated pieces of code which passed one argument into a static Lua script. The goal is to create a demonstration that runs in Chiventure which dynamically responds to the user's input (i.e. their name) as well as the specific item which they are holding.

This issue is completed when a successful merge request occurs. This merge request should include the demonstration .c file as well as its corresponding .lua file which contains the customized script.

2022-05-25 19:40 UTC, calvinytcheong2020 approved these changes

2022-05-25 22:03 UTC, calvinytcheong2020 approved these changes
Gold demo runs without issue on my computer! Possible minor addition: another line or two of documentation at calls of obj_add_arg (in gold.c) just to make things as clear as possible!

2022-05-26 20:04 UTC, ecoble requested changes
Nice job on these examples! A couple of things regarding uthash, also it looks like a lot of these changes are duplicated from the other pull request so I won't merge this one until the first one is in dev, and then this branch can be updated.

2022-05-26 20:04 UTC, ecoble commented on .gitmodules
> +[submodule "include/custom-scripts/--foorce"]
Remove submodules for uthash, this library has already been included in this project.

2022-05-26 20:04 UTC, ecoble commented on src/custom-scripts/examples/CMakeLists.txt
> -set(CS_EXAMPLES demonstration)
Why was demonstration removed? You can have multiple files in the CMakeLists.txt. Or did you rename it?

2022-05-26 20:04 UTC, ecoble commented on src/custom-scripts/examples/dark_room.h
> +bool state; // on or off?
Indentation, you can fix this by running a style.

2022-05-26 20:04 UTC, ecoble commented on .gitmodules
> +[submodule "include/custom-scripts/--foorce"]
Also please remove uthash.h

2022-05-26 21:45 UTC, tatmaca commented on src/custom-scripts/examples/CMakeLists.txt
> -set(CS_EXAMPLES demonstration)
@ecoble Oh we weren't aware that we could have multiple files in CMakeLists.txt! When we tried doing that it didn't seem to work. Is there a preferred way we can add multiple files?

2022-05-31 18:06 UTC, ecoble commented on tests/custom-scripts/arg_custom_type.h
>  #include "lauxlib.h"
Do we still need this file? Or can we use the one from the include folder instead of making a new one just for tests?

2022-05-31 18:29 UTC, ecoble approved these changes

2022-05-31 18:38 UTC, merged

2022-05-31 21:36 UTC, RamarkoB commented
A new demo has been added to the custom-scripts folder which can take in multiple arguments and then pass it to Lua. The demo file is called gold.c and is in the examples folder of custom-scripts.

2022-06-07 02:18 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great work on this demo!

<!-- {"score": "excellent", "minor": false} -->