sound: created a demo with dialogue prior to integrating text to speech
uchicago-cs/chiventure pull request #1591
Opened 2022-05-24 20:25 UTC by sangerr

In this pull request, we created a sample game with a conversation between an npc and the player. In order to understand this, we had to research the different structs necessary to create an npc and a conversation between an npc and player, which was mostly from previous npc examples and looking through their header file. After doing so, we created a demo example with a conversation that can be built upon to integrate the text to speech. 

Assignees: Rhea, Jake, Victor

2022-05-24 22:40 UTC, JaStarbuck approved these changes
This looks good! This will be good for the demo, maybe we can add some text to speech to this sample game for the main DEMO issue. It looks like the change in the README below is redundant to another issue and wasn't needed in this pull request, but afaik, it doesn't hurt anything. Good job!

2022-05-24 22:46 UTC, ecoble requested changes
Small style change, otherwise looks great! This will be really exciting to demo!

2022-05-24 22:46 UTC, ecoble commented on src/sound/examples/tts_dialogue_example.c
> +        if (rc < 0) ret_str = start_conversation(c1, &rc, game);
Please use if {...} else {...} for consistent style

2022-05-25 01:41 UTC, sangerr commented on src/sound/examples/tts_dialogue_example.c
> +        if (rc < 0) ret_str = start_conversation(c1, &rc, game);
I just pushed an updated version where I fixed this issue, I had an issue in that I didn't git pull on this branch before uploading, but I was able to merge the two versions and the changes can be viewed under "fixed if else formatting and other typos" commit.

2022-05-25 19:18 UTC, ecoble approved these changes
Looks good!

2022-05-25 19:21 UTC, merged

2022-05-26 02:50 UTC, jwschroeder21 commented
Summary: 

we created a sample game with a conversation between an npc and the player. We researched the different structs necessary to create an npc and a conversation between an npc and player. We then created a demo example with a conversation that can be built upon to integrate the text to speech. After pushing an updated version where we fixed this issue, we merged the two versions and the changes can be viewed under "fixed if else formatting and other typos" commit. With Emily and Jason's approval, this pull request was successfully merged!

2022-06-07 00:55 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job creating this demo, and also incorporating integration with NPCs!

<!-- {"score": "excellent", "minor": false} -->