1490 - Add NPC-specifc prefabs into class_prefab.c inside Playerclass
uchicago-cs/chiventure pull request #1594
Opened 2022-05-24 22:02 UTC by jroven

Vincent, Katie, and I have added in friendly NPC's into the playerclass module in class_prefabs.c. Before, all the playerclass prefabs were very combat and skill heavy, and there weren't many supportive classes. Therefore, we added some classes into the code with the stats of these new classes, alongside a short and long description. Katie added lord and healer, Vincent added alchemist and chef, and I added fisherman and shopkeeper. We made a space change in wdl/test_class.c to match monk, and changed some spacing/if else statements to have the code compile and past the tests currently written.

2022-05-25 03:19 UTC, vanolson approved these changes
Looks good! I was wondering about the comments deleted at line 42 of class_prefabs.h, before the `class_prefab_add_skills()` function—it might be useful to keep parts of what was deleted, since we are still waiting for the skill effects to be developed further, I believe. But that's a small change, just something I was unsure about. Besides that, this looks great! I really like the added NPC classes, and I think the variation in stats between them is good.

2022-05-25 03:19 UTC, vanolson commented on include/playerclass/class_prefabs.h
> - *
Was wondering about this deletion - we're still waiting on the developed skill effects, right? So might want to keep that part of the comment.

2022-05-26 20:12 UTC, lilyehsani requested changes
Looking good! 1 minor comment, and Van also made a good point about the comment in class_prefabs.h.

2022-05-26 20:12 UTC, lilyehsani commented on src/playerclass/src/class_prefabs.c
> +        short_desc = "a skillfull alchemist.";
Capitalize sentence

2022-05-26 22:52 UTC, katie-gao commented on src/playerclass/src/class_prefabs.c
> +        short_desc = "a skillfull alchemist.";
Made the change!

2022-05-26 22:58 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-27 19:04 UTC, merged

2022-06-05 22:39 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! Like issues, PRs should have closing statements.

<!-- {"score": "excellent", "minor": false} -->