Update Legacy Demonstration with Refactored Code
uchicago-cs/chiventure pull request #1611
Opened 2022-05-25 16:44 UTC by tatmaca

Pull request to resolve Issue #1610 : 

"With the newly refactored code in place, the custom-scripts team has decided to update our team's demonstration from two years ago so that it is usable with our new codebase. This includes renaming our include modules and updating both the name of function calls and inputting the correct parameters.

This issue is completed when we are able to run the demonstration.c such that a game of chiventure is loaded and playable."

2022-05-25 20:53 UTC, mxu24 approved these changes

2022-05-25 23:31 UTC, mxu24 approved these changes
All code and files appear appropriate, demo runs accurately

2022-05-26 20:12 UTC, ecoble reviewed
Is this a duplication of PR #1586?

2022-05-26 21:51 UTC, tatmaca commented
> 

@ecoble This pull request updates the demonstration.c file from two years ago so that it runs with the new refactored code! PR #1586 creates a new demo from scratch which plays around with more in-depth lua scripting! I think what may have happened is that when we created the branch seen in PR #1586, we merged it with one of our other branches awaiting a pull request because the refactored code wasn't yet available in the dev branch. In that merge, it looks like some code from this branch was also copied over. Rest assured however, the PRs are unique and address their own respective issues [🙂](https://emojipedia.org/slightly-smiling-face/)👍 This PR is us reworking the original demo so that it works with the refactored code, and the other PR is us experimenting with Lua and creating a new demo from scratch!

2022-05-30 14:31 UTC, ecoble requested changes
The header files in tests/custom-scripts seem like a duplication of the header files that already were merged in include, why not reference those instead of creating new header files?

2022-05-30 14:31 UTC, ecoble commented on .gitmodules
> +[submodule "include/custom-scripts/--foorce"]
Please remove submodules

2022-05-31 01:51 UTC, ecoble approved these changes
Nice job cleaning things up!

2022-05-31 01:54 UTC, merged

2022-05-31 02:24 UTC, jackjackkimkim commented
We were able to make updates to the legacy demonstrations to function correctly with the refactored code. The old demonstration can now make with the new refactored code design.

2022-06-07 02:12 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job updating the code and responded to changes on this PR!

<!-- {"score": "excellent", "minor": false} -->