Scenes_Graphics: "Draw_Scenes_Graphics " Pull Request
uchicago-cs/chiventure pull request #1616
Opened 2022-05-25 19:35 UTC by ukanyanwu

With the important structs of scenes_graphics pulled into the main branch, the dev branch is ready to merge the actual function that draws scenes in chiventure. Draw_Scenes implements the structs from the first scenes_graphics pullrequest, and allows a developer to visualize environments that players would be experiencing when playing a chiventure game.

2022-05-25 19:48 UTC, dhirpalshah approved these changes
code has thorough tests and adds a lot to the scenes module - looks good to me!

2022-05-26 01:23 UTC, philipchenaux requested changes
One minor issue, but once that is resolved it looks good to merge!

2022-05-26 01:23 UTC, philipchenaux commented on graphics_sandbox/scene_graphics/main.c
> +/* See scene_graphics.h */
I cannot see the proper function header of this function in scene_graphics.h, please add the relevant function comment header.

2022-05-26 01:36 UTC, ukanyanwu commented
Mistake had been made in accidentally not including proper header file in scenes_graphics.h, with a new commit it has been added!

2022-05-26 01:39 UTC, philipchenaux requested changes
Refer to my comment about return values.

2022-05-26 01:39 UTC, philipchenaux commented on graphics_sandbox/scene_graphics/scene_graphics.h
> + * - 1 on success
You should adhere to the convention of returning the macros SUCCESS or FAILURE instead of 1 or 0.

2022-05-26 01:55 UTC, ukanyanwu commented
Change about returning SUCCESS has been made to the draw_scenes function in the header file.

2022-05-26 02:51 UTC, philipchenaux approved these changes
Great job, looks good to merge!

2022-05-26 02:51 UTC, merged

2022-06-05 10:04 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR!

<!-- {"score": "excellent", "minor": false} -->