Map_Graphics Pt. 2 "Draw_Map_Graphics" Pullrequest
uchicago-cs/chiventure pull request #1617
Opened 2022-05-25 19:47 UTC by ukanyanwu

With important structs for map_graphics pulled into the dev branch, the draw function for maps is ready to be added as well. Draw_map_graphics implements previously pulled structs from the maps module that allow developers to visualize the maps of the environment that players would go through in a chiventure game.

2022-05-26 02:06 UTC, imadejski approved these changes
Looks great!

2022-05-26 03:00 UTC, philipchenaux requested changes
A few minor comments that need to be resolved.

2022-05-26 03:00 UTC, philipchenaux commented on graphics_sandbox/map_graphics/main.c
> +/* See map_graphics.h for documentation */
The draw_map_graphics documentation in map_graphics.h is not added and is not complete (at least based on what I can see at the repo for the moment).

2022-05-26 03:00 UTC, philipchenaux commented on graphics_sandbox/map_graphics/main.c
> +            ClearBackground(RAYWHITE);
Try to keep you indentation consistent throughout the code.

2022-05-26 16:46 UTC, ukanyanwu commented on graphics_sandbox/map_graphics/main.c
> +/* See map_graphics.h for documentation */
We've adjusted the header for our draw function to properly include the inputs and a SUCCESS when the function completes.

2022-05-27 00:06 UTC, philipchenaux approved these changes
Looks good to merge!

2022-05-27 03:12 UTC, merged

2022-06-05 10:05 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR!

<!-- {"score": "excellent", "minor": false} -->