Battle/battle mode update
uchicago-cs/chiventure pull request #1619
Opened 2022-05-25 20:47 UTC by aliu65803

For this pull request, Emilio, Nafis and I implemented a way to run a battle with CLI integration. During this process, we had to completely restructure run_turn_component, which was created in a previous pull request. Instead, the function is now split into two—the input comparison happens in the run_battle_mode function in mode.c while running the actual action happens in a function called run_action in the battle_flow.c file. Moreover, we have merged our code with CLI's battle_operation code, meaning we can start a fight with typing in "FIGHT" and also accept user input through the CLI.

2022-05-26 01:16 UTC, corian-jal approved these changes
Most of this looks really good! The logic is easy to follow and the documentation, especially in the cli and game-state files, makes it easy to see how it works together with the changes to how battles are run. I made two comments, but neither inhibit the functionality of the code at all, so I approve this request.

2022-05-26 01:16 UTC, corian-jal commented on src/game-state/src/mode.c
> +            }
This battle_over clause for buffer = NULL seems to be the same as the battle_over clause for buffer != NULL, so this section could be simplified to check if the battle is in progress (and then check the buffer to print the correct player/enemy output) and then just have one battle_over clause as the else to that.

2022-05-26 01:16 UTC, corian-jal commented on include/battle/battle_flow_structs.h
> +
Is there any reason for not including a battle_ctx_free function?

2022-05-26 17:39 UTC, aliu65803 commented on include/battle/battle_flow_structs.h
> +
Actually, these battle ctx functions were created by the previous classes, so we didn't add to them. We can add it if necessary or update the battle wishlist to include this.

2022-05-26 17:43 UTC, aliu65803 commented on src/game-state/src/mode.c
> +            }
I'm not sure if I know exactly what you're referencing, but I believe your comment addresses the fact that there are two battle-over checks. If that is the case, this is how I would like to structure it, because one of the battle over checks if the battle is over at the end of a turn, and the other checks if it is over at the end of each turn components.

2022-05-26 19:12 UTC, lilyehsani requested changes
Really impressive work so far! Left a few comments.

2022-05-26 19:12 UTC, lilyehsani commented on include/battle/battle_common.h
>   * - turn: a turn_t enum storing the current turn
Add a comment here with the new parameter.

2022-05-26 19:12 UTC, lilyehsani commented on include/battle/battle_flow_structs.h
> + *     - tcl: turn component list that makes up a turn
Add tcl_len

2022-05-26 19:12 UTC, lilyehsani commented on include/battle/battle_flow_structs.h
> + *     - tcl: turn component list that makes up a turn
Add tcl_len

2022-05-26 19:12 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +            //strncat(string, enemy_move_report);
Delete commented out code. While you're here, i think it would be better to give `string` a clearer name as well like `res_string` or something.

2022-05-26 19:12 UTC, lilyehsani commented on include/battle/battle_flow_structs.h
> +
Were they in the code already? I think it would be best to write a free function in any case.

2022-05-26 19:12 UTC, lilyehsani commented on src/battle/src/battle_logic.c
> +#include "game-state/player.h"
Since this is included in battle_logic.h, we shouldn't need to include it here.

2022-05-26 19:12 UTC, lilyehsani commented on src/cli/src/operations.c
> +    // char *output_and_menu = strcat(output, menu); // replace calls to print_to_cli
Delete commented out code.

2022-05-26 19:12 UTC, lilyehsani commented on src/game-state/src/mode.c
> +    // will implement without turn component list length right now,
This is a lot of commented out code, would it be possible to remove this or document it in another way? Maybe put it in a Wiki page and link to that here?

2022-05-26 19:12 UTC, lilyehsani commented on src/game-state/src/mode.c
> +        buffer = tcl_buffer->next;//->current; // wait... will this be moved down??? Emilio: No???
Comments lol, please remove as they won't make sense to future developers.

2022-05-26 19:12 UTC, lilyehsani commented on src/game-state/src/mode.c
> +                ctx->game->battle_ctx->game->battle->current_tc = buffer->current; //check to make sure this is the correct tc now
This comment likely exceeds 80 chars, either move or delete it

2022-05-26 22:28 UTC, lilyehsani commented on include/battle/battle_flow_structs.h
> +
Because this would also involve writing free functions for each stub inside the struct, the team has decided to hold off on this.

2022-05-26 22:42 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-26 22:43 UTC, merged

2022-05-26 22:45 UTC, aliu65803 commented
While we did not change much from the beginning of the PR, we deleted commented out code, decided to take out the turn component list length from the battle context struct, and also wrote some missing free functions. Now that the PR has been merged, we are done with the PR and the implementation issue.

2022-06-05 23:12 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->