Added sound_new and sound_init functions
uchicago-cs/chiventure pull request #1623
Opened 2022-05-25 21:25 UTC by jiaoboxuan

Summary: Existent functions such as `load_wav` and `sound_free` require already allocated `sound_t` structs, and while writing tests, I would have to allocate the structs in separate lines of code, and repeat the process per new test. Therefore, I added two functions, `sound_init` and `sound_new`, descriptions of which are added in `sound.h` file. The code compiles successfully in the workflow run, and these two simple functions could significantly ease the test writing process, as well as improve the readability of the module.

2022-05-26 16:38 UTC, JaStarbuck commented on include/sound/sound.h
> +
I like your documentation here!

2022-05-26 16:39 UTC, JaStarbuck commented on src/sound/src/sound.c
> +    sound->wavBuffer = (uint8_t*)malloc(sizeof(uint8_t));
not sure if this needs to be malloced

2022-05-26 16:41 UTC, JaStarbuck approved these changes
This looks really good! I've gone through and left comments on some things. I wonder if once you malloc the struct, you actually have to malloc the things inside the struct. Other than that, it looks good!

2022-05-26 17:04 UTC, JaStarbuck approved these changes
Oops think I accidentally re-review--approving again

2022-05-26 20:15 UTC, ecoble requested changes
Nice work! Just a quick change on the header comment.

2022-05-26 20:15 UTC, ecoble commented on include/sound/sound.h
> +/* Initializes the
Initializes the what? Also it looks like function does have parameters, and it is returning an int.

2022-05-26 20:15 UTC, ecoble commented on src/sound/src/sound.c
> +    sound->wavBuffer = (uint8_t*)malloc(sizeof(uint8_t));
Mallocing this is correct since wavBuffer is a pointer.

2022-05-27 01:54 UTC, jiaoboxuan commented
Update: changed the `char` structure from pointer form to stack form, and updated the documentation.

2022-05-29 22:31 UTC, ecoble approved these changes

2022-05-29 22:31 UTC, merged

2022-05-31 13:57 UTC, jwschroeder21 commented
Closing statement: sound_init and sound_new were added with descriptions of them in the sound.h file. These functions ease the test writing process and allow  for no re-allocation of the sound_t structs in each process of a repeated test.

2022-06-07 00:44 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great work! Nice job identifying the need for new and init functions!

<!-- {"score": "excellent", "minor": false} -->