Adding and Updating Functions dealing with Items in Rooms and held by NPCs so that Duplicate Items Cannot Exist within a Singular Hash Table
uchicago-cs/chiventure pull request #1626
Opened 2022-05-25 21:37 UTC by bvvill

As described in #1614

2022-05-26 04:16 UTC, junasano requested changes
Overall, the logic seems good. I left some comments here and there but I'm not 100% sure for some of them so feel free to correct me if you had a different intention.

2022-05-26 04:16 UTC, junasano commented on include/npc/npc.h
> + *  npc: the npc whose inventory we're freeing
add deleting as well, so becomes "... inventory we're deleting and freeing"
To make your intentions stated in the issue more explicit.

2022-05-26 04:16 UTC, junasano commented on src/game-state/src/game.c
> +    room_hash_t *rooms = NULL;
Im not sure if it works like this but is there a reason why you stated each variable before hand and set that to NULL?  If not, maybe just go straight into game->all_rooms = NULL; and etc.

2022-05-26 04:16 UTC, junasano commented on src/game-state/src/item.c
> +    game_action_hash_t *actions = NULL;
Same thing here with declaring the NULL beforehand.

2022-05-26 04:16 UTC, junasano commented on tests/npc/test_npc.c
> +    cr_assert_eq(rc, FAILURE, "add_item_to_npc added duplicate item to npc");
I feel like testing for duplicate items on the remove_item_from_npc test is redundant. Since it's already being tested in add_item_to_npc and this test is specifically for removing the item rather than adding.

2022-05-26 04:16 UTC, junasano commented on tests/game-state/test_rooms.c
> +    cr_assert_eq(check, FAILURE, "duplicate item added to room incorrectly");
isn't this check and the check right below this pretty much doing the same thing?

2022-05-26 04:16 UTC, junasano commented on tests/game-state/test_rooms.c
> +    cr_assert_eq(rc, FAILURE, "add_item_to_room added duplicate item");
Same thing as comment from the other test file. No need to test for duplicate again and since the test is for the remove item test.

2022-05-26 04:16 UTC, junasano commented on src/game-state/src/room.c
> +    assert(move_npc(npc) != 0);
change the 0 to SUCCESS so that it is more explicit

2022-05-26 04:16 UTC, junasano commented on include/npc/npc.h
> +int move_npc(npc_t *npc);
I'm not really sure what the point of this function is except that it is in the npc.h/npc.c module rather than npc_move.h/npc_move.c. Especially since they are pretty much identical and is only used once so far (and in that place, move_npc_mov can be used).

2022-05-26 04:16 UTC, junasano commented on src/game-state/src/room.c
> +    item_hash_t *head = NULL;
same thing will NULL here

2022-05-26 04:16 UTC, junasano commented on src/npc/src/npc.c
> +    item_hash_t *items = NULL;
NULL once again

2022-05-26 04:16 UTC, junasano commented on src/npc/src/npc_battle.c
> +    if (npc_battle == NULL || check != SUCCESS)
Is there a reason why you deleted the NULL checks for the other stuff? Because I feel like a battle can't start if those are NULL and just checking to see if npc_battle == NULL isn't enough to check for everything

2022-05-26 04:16 UTC, junasano commented on src/npc/src/rooms_npc.c
> +    npc_hash_t *npcs = NULL;
NULL here too

2022-05-26 18:52 UTC, bvvill commented on include/npc/npc.h
> + *  npc: the npc whose inventory we're freeing
i agree, will do

2022-05-26 19:05 UTC, bvvill commented on src/game-state/src/room.c
> +    assert(move_npc(npc) != 0);
omg this is actually a major bug lol thank you for pointing this out, since the refactoring of `move_npc_mov()` to simply out `FAILURE` or `SUCCESS`, this statement was not updated to say `assert(move_npc(npc) != FAILURE);`, so I will change that now

2022-05-26 19:11 UTC, bvvill commented on src/npc/src/npc_battle.c
> +    if (npc_battle == NULL || check != SUCCESS)
checking npc_battle for being NULL is checking if the memory allocation of the struct worked, and then checking if `check` equals `SUCCESS` makes sure that the initialization of the struct went okay. In some of the examples/tests, there are many parameters that `NULL` is being passed into, and because of that, the return value for `npc_battle_new()` is NULL, which obviously wasn't the intention of whoever was creating those battle structs in those cases. It's also to stay consistent with the other struct creation implementations throughout chiventure, as I haven't come across any other `..._new()` function that expects every single struct member to not be `NULL` and returns `NULL` if not.

2022-05-26 19:12 UTC, bvvill commented on tests/game-state/test_rooms.c
> +    cr_assert_eq(check, FAILURE, "duplicate item added to room incorrectly");
Yup you're right, didn't think about that, the second one shall be removed

2022-05-26 19:13 UTC, bvvill commented on tests/game-state/test_rooms.c
> +    cr_assert_eq(rc, FAILURE, "add_item_to_room added duplicate item");
Yeah I agree, I will remove it now

2022-05-26 19:15 UTC, bvvill commented on tests/npc/test_npc.c
> +    cr_assert_eq(rc, FAILURE, "add_item_to_npc added duplicate item to npc");
Yeah I agree, removing this as well

2022-05-26 19:16 UTC, bvvill commented on include/npc/npc.h
> +int move_npc(npc_t *npc);
Yeah this function is purely for minimizing complexity where possible. I think people are going to more often use functions dealing with higher-level structs such as an `npc_t` (as opposed to its movement struct/member) and a function for moving an NPC given solely it's `npc_t` didn't exist yet, so I figured I'd quickly implement it. It's also a lot easier to read/decipher when used in other functions, and I don't think performance loss is an issue. Also, while right now the function only makes changes to an NPC's movement member, perhaps developers in the future could add more functions inside this one that change something else related to the NPC if they move rooms, such as dialogue or appearance, but this honestly had nothing to do with why I decided to implement `move_npc()`.

2022-05-26 19:17 UTC, bvvill commented on src/game-state/src/game.c
> +    room_hash_t *rooms = NULL;
https://github.com/uchicago-cs/chiventure/issues/1614#issuecomment-1137860606

2022-05-26 19:18 UTC, bvvill commented on src/game-state/src/item.c
> +    game_action_hash_t *actions = NULL;
https://github.com/uchicago-cs/chiventure/issues/1614#issuecomment-1137860606

2022-05-26 19:18 UTC, bvvill commented on src/game-state/src/room.c
> +    item_hash_t *head = NULL;
https://github.com/uchicago-cs/chiventure/issues/1614#issuecomment-1137860606

2022-05-26 19:18 UTC, bvvill commented on src/npc/src/npc.c
> +    item_hash_t *items = NULL;
https://github.com/uchicago-cs/chiventure/issues/1614#issuecomment-1137860606

2022-05-26 19:18 UTC, bvvill commented on src/npc/src/rooms_npc.c
> +    npc_hash_t *npcs = NULL;
https://github.com/uchicago-cs/chiventure/issues/1614#issuecomment-1137860606

2022-05-26 21:16 UTC, junasano commented
The changes look good. Just make sure to merge with the dev branch since there seems to have been new PRs approved.

2022-05-26 21:16 UTC, junasano approved these changes

2022-05-27 16:26 UTC, lilyehsani requested changes
Looks really good! One comment.

2022-05-27 16:26 UTC, lilyehsani commented on src/game-state/src/room.c
> -    rc = add_item_to_hash(&(room->items), item);
What is the reason you moved away from using this helper function? I notice that the implementation here is very similar to the implementation for add_item_to_npc, so a helper function makes sense to me.

2022-05-27 19:42 UTC, bvvill commented on src/game-state/src/room.c
> -    rc = add_item_to_hash(&(room->items), item);
While the helper function is correctly used here, I think that it's worth noting that it assumes the hash handle being used is `hh`, and because there are two possible hash handles for items, I thought it was better to be explicit as to which one was being used. That being said, I think I've become overly paranoid about hash table errors, so if you feel this was an unnecessary change, I will swiftly undo it.

2022-05-30 00:18 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-30 00:21 UTC, merged

2022-05-31 21:59 UTC, bvvill commented
comments from #1614:

There are currently a few bugs involving items within rooms or held by NPCs, one being that duplicate items are allowed to be added to a room's or NPC's `item_hash_t`, which is an error according to UTHash's documentation. There are also a couple of useful functionalities that have yet to be implemented, such as "getting" an item from an NPC's inventory given the `item_id`. There are also a couple hash implementations regarding items that could use optimization

As I said I would do in my opening comment, I've implemented `item_t *get_item_from_npc(npc_t *npc, char *item_id)` in npc.h/.c, which returns an item in an NPC's inventory given the `item_id`, if it exists.

I've also implemented `delete_all_items_from_npc` and `free_all_items_from_npc`, which delete and (delete, but also) free the given NPC's inventory, respectively. The difference in the use of these functions is that solely deleting an NPC's inventory doesn't free the items that were in it, so that the items can still be used in other places or conveniently added to other hash tables, as is done in `transfer_all_npc_items()` (found in room.h/.c)

in `game.c` and `item.c`, I've also went ahead and explicitly initialized every hash table member of the `game_t` and `item_t` structs to be `NULL` when either of those two structs is created. Doing so is incredibly important for ut_hash table maintenance and stability, and can lead to mysterious seg faults if not done properly. The new lines added to `game_new()` are:
```
    room_hash_t *rooms = NULL;
    item_hash_t *items = NULL;
    quest_hash_t *quests = NULL;
    npc_hash_t *npcs = NULL;
    stats_global_hash_t *stats = NULL;
    effects_global_hash_t *effects = NULL;
    class_hash_t *classes = NULL;

    game->all_rooms = rooms;
    game->all_items = items;
    game->all_quests = quests;
    game->all_npcs = npcs;
    game->curr_stats = stats;
    game->all_effects = effects;
    game->all_classes = classes;
```
And the new lines in `item_init()` are:
```
    game_action_hash_t *actions = NULL;
    attribute_hash_t *attributes = NULL;
    effects_hash_t *stat_effects = NULL;

    new_item->actions = actions;
    new_item->attributes = attributes;
    new_item->stat_effects = stat_effects;
```


in `add_item_to_npc()` (in npc.h/.c), I've also explicitly implemented the function instead of using `add_item_to_hash()`, since it assumes the hash handle to be hh and doesn't check that the input parameters aren't NULL.

in `game-state/test_rooms.c` and `npc/test_npc.c`, I've updated the tests regarding adding duplicate items to rooms and NPCs, such that the functions now appropriately return `FAILURE` if a duplicate item is attempted to be added

2022-06-07 00:35 UTC, lilyehsani commented
Issue Score: Satisfactory

Comments:
Great work on this PR! The closing statement is very thorough. Two comments:
1. The summary for this PR is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples).
2. When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests. Merging dev is acceptable, but there are other commits after the creation of the PR and before the review.

<!-- {"score": "satisfactory", "minor": false} -->