Create an Advanced Lua Demo with 3+ Args passed through Lua Script
uchicago-cs/chiventure pull request #1629
Opened 2022-05-25 22:27 UTC by tatmaca

As the custom-scripts team works towards its final demo for the quarter, we wanted to practice writing more advanced scripts that could interact with more game items and player inputs. Our goal is to create a demo that passes at least 3 parameters through at least 3 Lua scripts. This way, we can have our scripts interact with one another and perform more complex actions.

This issue is complete when we have a completed pull request which features a demonstration contained in a .c file and its corresponding .lua files. The demo should successfully run in Chiventure and pass 3+ variables through Lua scripts.

2022-05-26 00:10 UTC, jackjackkimkim commented on include/custom-scripts/arg_custom_type.h
> +typedef union data {
i like that you created a central data struct that will be able to take any type of data

2022-05-26 00:12 UTC, jackjackkimkim commented on src/custom-scripts/CMakeLists.txt
> +            src/arg_custom_type.c
good now the library has all the c files that resulted from the refactoring

2022-05-26 00:18 UTC, jackjackkimkim approved these changes
looks good! i'm not sure when we might use more than 3 arguments for LUA but if we do, now we're covered!

2022-05-31 18:08 UTC, ecoble requested changes

2022-05-31 18:08 UTC, ecoble commented on src/custom-scripts/examples/lost_order2.lua
> +  if order == "Wingstop" then
Please add parenthesis to these if statements.

2022-05-31 18:08 UTC, ecoble commented on tests/custom-scripts/arg_custom_type.h
>  #include "lauxlib.h"
Same comment here about removing this file and using the existing ones in the include folder.

2022-05-31 18:33 UTC, RamarkoB commented on src/custom-scripts/examples/lost_order2.lua
> +  if order == "Wingstop" then
This is a lua file, so I don't know if we can add parenthesis and still have the file work

2022-05-31 18:56 UTC, ecoble commented on src/custom-scripts/examples/lost_order2.lua
> +  if order == "Wingstop" then
There are parenthesis in the other Lua file lost_order.lua

2022-05-31 18:56 UTC, ecoble commented on src/custom-scripts/examples/lost_order2.lua
> +  if order == "Wingstop" then
You can remove the other parenthesis if you would rather do that, please just be consistent

2022-05-31 18:57 UTC, ecoble requested changes
Small style fixes

2022-05-31 19:06 UTC, ecoble approved these changes

2022-05-31 19:09 UTC, merged

2022-05-31 21:43 UTC, RamarkoB commented
We have a completed pull request which features a demonstration contained in a .c file and its corresponding .lua files. The demo should successfully run in Chiventure and pass 3+ variables through Lua scripts. The file is lost_order.c and the corresponding lua files are lost_order.lua, lost_order2.lua and lost_order3.lua. Marking this issue as closed

2022-06-07 02:11 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice work on this demo, and great job reviewing!

<!-- {"score": "excellent", "minor": false} -->