Implement testing for Multiclass_longdesc and Multiclass_shortdesc
uchicago-cs/chiventure pull request #1633
Opened 2022-05-26 00:43 UTC by wellingtj

The new multiclass has several functions, and they all need to be tested. This pull request implements multiclass_longdesc, multiclass_shortdesc and their tests. Currently, the tests account for grammar, string overflow, and overall functionality within the two functions. Additionally, it debugs the multiclass function and a few of the other functions in the multiclass module. This pull request is the first step in finishing issue #1608.

2022-05-26 19:13 UTC, vanolson requested changes
This looks great! In multiclass.c there are a number of lines past 80 characters, which I understand due to all the struct calling, but some of them could be broken up between function arguments and put on new lines to limit the length of the lines. There's also a function definition with a lot of parameters that goes over 80 lines, but I'm not sure if that's something that should be split up. I also noticed a few typos in the file, which I commented. But the tests look very comprehensive, they cover a lot of scenarios. And the functions in multiclass.c look well written. Aside from the few formatting things I commented, this seems to be in great shape!

2022-05-26 19:13 UTC, vanolson commented on src/playerclass/src/multiclass.c
>   * Returns:
Okay I don't know why it won't let me comment on the line itself but line 108 has a typo in "Parameters"

2022-05-26 19:13 UTC, vanolson commented on tests/playerclass/test_multiclass.c
> +//testing here is modeled after test_class_prefabs.c
I'm not sure what our policies are on `//` vs `/* */`, but that might be worth changing, and maybe also capitalize testing and put a space before the comment starts

2022-05-26 19:13 UTC, vanolson commented on tests/playerclass/test_multiclass.c
> +/* Initializes a chicventure context */
typo in chiventure

2022-05-27 21:29 UTC, lilyehsani requested changes
Great job! Just a few comments.

2022-05-27 21:29 UTC, lilyehsani commented on src/playerclass/src/multiclass.c
> +      len += 14;
Where did these constants come from? These are called [magic numbers](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#avoid-magic-numbers) and they are generally to be avoided. If you can explain in a comment what their purpose is, we can probably allow it. (The numbers I see are 14, 2, 5, and 15).

2022-05-27 21:29 UTC, lilyehsani commented on src/playerclass/src/multiclass.c
> +        strncat(new_shortdesc, ", ", 3);
(The purpose of 3 and 6 is obvious enough that you do not need to add a comment to these).

2022-05-27 21:29 UTC, lilyehsani commented on src/playerclass/src/multiclass.c
> +char* multiclass_shortdesc(class_t* base_class, class_t* second_class, int *succ) {
Add "succ" as a parameter in the above comment.

2022-05-27 21:29 UTC, lilyehsani commented on src/playerclass/src/multiclass.c
> +char* multiclass_longdesc(class_t* base_class, class_t* second_class, int *succ) {
Add "succ" as a parameter in the above comment.

2022-05-27 21:29 UTC, lilyehsani commented on src/playerclass/src/multiclass.c
> +      len += 14;
I see now that they are likely the lengths of strings you are concatenating. Please still add comments to make it clear (for example, `/* 15 = strlen("Multiclass of ") + 1 for the null terminator */`.

2022-05-27 21:29 UTC, lilyehsani commented on tests/playerclass/test_class_prefabs.c
> +void check_field_pressence(class_t* c)
The word "presence" has one s. Please leave this named how it was before to avoid the typo.

2022-05-27 21:43 UTC, wellingtj commented on tests/playerclass/test_class_prefabs.c
> +void check_field_pressence(class_t* c)
it was actually named along the typo before. It was when we fixed it that we got an error

2022-05-27 21:47 UTC, vanolson approved these changes
All my suggestions are fixed, looks great!

2022-05-27 21:50 UTC, wellingtj commented
In this PR, we have done some major debugging and performance fixing in the multiclass_shortdesc and multiclass_longdesc functions. We have also implemented complete tests for them

2022-05-27 22:03 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-27 22:26 UTC, merged

2022-05-27 22:27 UTC, wellingtj commented
> In this PR, we have done some major debugging and performance fixing in the multiclass_shortdesc and multiclass_longdesc functions. We have also implemented complete tests for them

this is the closing statement, jumped the gun on it a bit there

2022-06-05 23:25 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->