Graphics GDL module PR #1
uchicago-cs/chiventure pull request #1634
Opened 2022-05-26 01:54 UTC by imadejski

This is the first pull request for the GDL module, which read in a json file to set the graphics information for the game. In this pull request, we designed the module and created the read_gdl.h and read_gdl.c which outline the desired functions and implement the new, init, and free functions for the module. We also created tests for the camera and display_dimensions structs that exist within the read_gdl files. The tests build successfully and pass.

2022-05-28 02:32 UTC, dhirpalshah approved these changes
looks good to me!

2022-05-28 18:46 UTC, philipchenaux requested changes
Minor revisions need to be made.

2022-05-28 18:46 UTC, philipchenaux commented on graphics_sandbox/gdl/read_gdl.h
> +>>>>>>> d26175b898a004f623b54b54f8c67cdae0ce0265
Please clean up this header comment.

2022-05-28 18:46 UTC, philipchenaux commented on graphics_sandbox/gdl/read_gdl.c
> +graphics_t* new_graphics(display_dimensions_t *dimensions, camera_t *camera,
Make sure to add "see read_gdl.h" as a header comment for each of these functions.

2022-05-29 21:33 UTC, imadejski commented
Minor revisions completed. See read_gdl.h header comment added and formatting of specified header comment cleaned up. No other changes requested.

2022-05-30 01:39 UTC, philipchenaux approved these changes
Looks good to merge!

2022-05-30 01:41 UTC, merged

2022-06-05 10:10 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Great work, but please make sure that you do a thorough code review and, in the future, make sure to look out for the kind of issues the senior developer pointed out.

<!-- {"score": "excellent", "minor": false} -->