Custom scripts/sandbox2
uchicago-cs/chiventure pull request #1637
Opened 2022-05-26 02:55 UTC by jackjackkimkim

There are two WDL files and each is associated with a player class. There is one for the wizard class and one for the warrior class.

2022-05-27 03:02 UTC, RamarkoB approved these changes
Looks Good! All the Demos are compiling for me, and the it passes all the tests! Good work on expanding the demo to be more dynamic!

2022-05-31 18:10 UTC, ecoble requested changes

2022-05-31 18:10 UTC, ecoble commented on src/custom-scripts/examples/loadwdl2.c
> +    if(strcmp(wizard,custom_string)== 0){
Please follow the style guide for adding spaces like this: `if (` and this `) {`

2022-05-31 18:22 UTC, RamarkoB commented on src/custom-scripts/examples/loadwdl2.c
> +    if(strcmp(wizard,custom_string)== 0){
Fixed!

2022-05-31 18:28 UTC, ecoble approved these changes

2022-05-31 18:30 UTC, merged

2022-05-31 23:20 UTC, tatmaca commented
This issue is now closed! Both WDL files are read correctly by the Chiventure game and in both demonstrations the correct items are being loaded in with the proper associated actions. Since everything runs as it should, all tests have passed, and the merge request went through, this pull request is closed!

2022-06-07 02:09 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job on getting this working for your demo, it was really effective!

<!-- {"score": "excellent", "minor": false} -->