sound: add functionality for pausing/stopping sound pull request
uchicago-cs/chiventure pull request #1639
Opened 2022-05-26 03:25 UTC by JaStarbuck

Summary: For this pull request, we've made 3 simple functions using functions from the SDL library. It may seem redundant to make these functions since they're so small, it makes it so that other groups and future teams don't have to do their own research and find these SDL functions themselves--they will already be in the sound module. We've also made small edits to the play_sound function to get rid of potentially function breaking code. We realized that freeing the sound in the play function could lead to the sound not playing. Like other pull requests this sprint, these functions haven't been tested and will need to be in the future. The goal of this pull request is so that, like mentioned before, increase ease of use for future groups and other teams.

2022-05-26 03:34 UTC, jwschroeder21 approved these changes

2022-05-26 03:34 UTC, jwschroeder21 commented on src/sound/src/sound.c
> +    int x = Mix_HaltMusic();
Looks good

2022-05-26 03:34 UTC, jwschroeder21 commented on src/sound/src/sound.c
> +    Mix_PauseMusic();
Looks good

2022-05-26 03:34 UTC, jwschroeder21 commented on src/sound/src/sound.c
> +    Mix_ResumeMusic();
Brilliant work!

2022-05-26 20:19 UTC, ecoble requested changes
Small change!

2022-05-26 20:19 UTC, ecoble commented on src/sound/src/sound.c
> +    int x = Mix_HaltMusic();
If you're not doing anything with the int, do you need to save it? Or maybe you can return it as a signal for success/failure?

2022-05-27 21:29 UTC, ecoble approved these changes
Nice job!

2022-05-27 21:33 UTC, merged

2022-05-27 22:49 UTC, JaStarbuck commented
Closing statement: In this pull request we were able to get the function headers for pause/stop/resume in sound.h and the functions in sound.c working. The only edit that was requested was to get rid of an unused variable. We will need to test these functions so that future groups and other teams can use them when they access the sound module.

2022-06-07 00:42 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job researching the SDL library and implementing this!

<!-- {"score": "excellent", "minor": false} -->