Sound/tts
uchicago-cs/chiventure pull request #1647
Opened 2022-05-26 04:16 UTC by parkerbroz

Created a tts struct which enables easier and simpler use of text to speech. We think long-term this struct will be useful for integrating the tts functionality into chiventure, as it is an effective middleman which takes on all the strain of interfacing with the espeak libraries. There is definitely room for expansion of the struct. Espeak has many fields and options which can be set, most of which were left as default here. Adding support for these would be fairly simple, essentially just modifying the data that tts_t stores and adjusting a few function calls in speak().

2022-05-26 16:56 UTC, jwschroeder21 requested changes
This all looks really great. I think some of the commenting on the code could be cleaned up and I'm happy to help with that. Otherwise great job!

2022-05-26 16:56 UTC, jwschroeder21 commented on include/sound/tts.h
> +// malloc and fill a tts_t struct with the necessary data
This looks really good. I think it may be cleaner to have the comments all be in the same style. Maybe we should choose either /* */ style comments or // ?

2022-05-26 16:56 UTC, jwschroeder21 commented on src/sound/examples/CMakeLists.txt
> +    # Link with chiventure libraries
Nicely done

2022-05-26 18:00 UTC, parkerbroz commented on include/sound/tts.h
> +// malloc and fill a tts_t struct with the necessary data
I generally tried to use /**/ for multiline comments or important headers. I think it gives a nice distinction that it's more significant than //. If you'd like, I can go through and change them but I think it just comes down to stylistic preference.

2022-05-26 18:05 UTC, jwschroeder21 commented on include/sound/tts.h
> +// malloc and fill a tts_t struct with the necessary data
Okay, I'm convinced. Sounds good.

2022-05-26 18:05 UTC, jwschroeder21 approved these changes

2022-05-26 20:30 UTC, ecoble requested changes
Looks good! Small changes!

2022-05-26 20:30 UTC, ecoble commented on src/sound/src/tts.c
> +void* user_data;
Move asterisk over

2022-05-26 20:30 UTC, ecoble commented on include/sound/tts.h
> +// malloc and fill a tts_t struct with the necessary data
With header comments, please follow the format of:

Brief description of functions
Parameters:
- param1: description
- param2: description
- ...

Returns:
- brief description description of what is returned

2022-05-27 22:02 UTC, ecoble approved these changes
Nice job!

2022-05-27 22:02 UTC, merged

2022-05-31 13:55 UTC, jwschroeder21 commented
Closing statement: we created a tts struct which enables easier and simpler use of text to speech. In the long term, this struct will be useful for integrating the tts functionality into chiventure. It is an effective intermediary which takes on all the hard work of interfacing with the e-speak libraries. 

There is still room for improvement. Adding support would be fairly simple, essentially just modifying the data that tts_t stores and adjusting a few function calls in speak().

2022-06-07 00:41 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job on these e-speak structs! This is great foundation for future use in Chiventure.

<!-- {"score": "excellent", "minor": false} -->