Action management/1624 implement a new action view inventory
uchicago-cs/chiventure pull request #1649
Opened 2022-05-26 04:46 UTC by HarrisonD123

We have changed ```do_self_action``` to be able to perform ```display_inventory``` and ```display_inventory_item```. ```display_inventory``` is called if the target parameter (a list of strings)  in  ```do_self_action``` is a list of length 1. Otherwise, ```display_inventory_item``` is called to search for the second string in the target parameter.

```display_inventory``` and ```display_inventory_item``` are both implemented within the `game-state/player` module `(player.h` and `player.c`). `display_inventory` simply accepts a player struct as a parameter and iterates through a list representation of the inventory. `display_inventory_item` accepts a player and an item name and uses `HASH_FIND_STR` to grab the corresponding item from the inventory and print its long description.

2022-05-26 21:41 UTC, jbrouwer5 requested changes
Two minor documentation comments. After they're resolved good to go!

2022-05-26 21:41 UTC, jbrouwer5 commented on include/game-state/player.h
> + * Returns a string that represents the player's entire inventory
Maybe a more abstract description since it says the same thing later in the function description. "Displays the items in a player's inventory" for instance. Not a necessity.

2022-05-26 21:41 UTC, jbrouwer5 commented on include/action_management/actionmanagement.h
> +                  char **target, char **ret_string);
Update the description to reflect the parameter change

2022-05-27 22:38 UTC, ecoble requested changes
This looks good overall, but please note that there is already a CLI function `inv` that prints out a list of what is in the player's inventory. Have you talked to the CLI team about this overlap? Is your implementation replacing theirs?

2022-05-27 22:38 UTC, ecoble commented on src/game-state/src/player.c
> +    if(find != NULL){
Space after "if"

2022-05-29 21:55 UTC, HarrisonD123 commented on src/game-state/src/player.c
> +    if(find != NULL){
Fixed!

2022-05-29 21:55 UTC, HarrisonD123 commented on include/action_management/actionmanagement.h
> +                  char **target, char **ret_string);
Fixed!

2022-05-29 21:55 UTC, HarrisonD123 commented on include/game-state/player.h
> + * Returns a string that represents the player's entire inventory
Changed!

2022-05-29 21:59 UTC, HarrisonD123 commented
> This looks good overall, but please note that there is already a CLI function `inv` that prints out a list of what is in the player's inventory. Have you talked to the CLI team about this overlap? Is your implementation replacing theirs?

Thanks for pointing that out, we didn't notice that. Our function does a little more by trying to print the inventory items in a grid format. It's not yet perfect (doesn't account for different length item names), so we think it can be touched up in a backlog issue. We think our function is an improvement on theirs and is used in different cases.

2022-05-30 03:28 UTC, jbrouwer5 approved these changes
Good to go!

2022-05-30 14:02 UTC, ecoble commented on include/game-state/player.h
> +
Are these documentation changes for player quests meant to be here?

2022-05-31 06:42 UTC, HarrisonD123 commented on include/game-state/player.h
> +
Sorry, accidentally did that when fixing a merge conflict. It has been returned to normal!

2022-05-31 18:12 UTC, ecoble approved these changes

2022-05-31 18:25 UTC, merged

2022-06-07 01:05 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job implementing and reviewing this view inventory functionality! Please include closing statements on PRs

<!-- {"score": "excellent", "minor": false} -->