Custom scripts/demo sandbox
uchicago-cs/chiventure pull request #1651
Opened 2022-05-26 06:57 UTC by RamarkoB

This is a working demo with Conditionals, Multiple WDL files, and the Torch. In short, It comprises of nearly everything custom scripts has accomplished this quarter.  The one thing issue this pull request still has is that the Lua Functions are not compiling correctly. Once Togay takes a look at this to correct the Luad functions to match the Refactoring, it should be good to go!

2022-05-26 14:12 UTC, RamarkoB commented
For some reason, [8ff23d6](https://github.com/uchicago-cs/chiventure/pull/1651/commits/8ff23d62acf46fbd5abb30bc46ffc4c552e531a9) broke the build, but i removed one line and added it back, and suddenly, it all compiled correctly. Github is crazy

2022-05-31 03:47 UTC, mxu24 approved these changes
Past issues all fixed, demonstration functions correctly with all new custom actions, integrated Lua and WDL content.

2022-05-31 19:00 UTC, ecoble requested changes
Small style changes

2022-05-31 19:00 UTC, ecoble commented on src/custom-scripts/examples/demo_2022.c
> +    if(strcmp(wizard,custom_string)== 0){
Spacing between ( and {

2022-05-31 19:00 UTC, ecoble commented on src/custom-scripts/examples/loadwdl2.c
> +    if(strcmp(wizard,custom_string)== 0){
Style spacing

2022-05-31 19:41 UTC, ecoble approved these changes

2022-05-31 19:51 UTC, merged

2022-05-31 21:48 UTC, RamarkoB commented
We were able to both integrate the dark_room.c demo with the torch, and add custom actions for fireball and slash into a single demo, solving two issues with a single pull request. Moving forward, we want to integrate more small demos into a single, larger demo that we can present

2022-06-07 02:03 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job creating this demo and debugging the issues! Please try to make sure the PR is ready to go before submitting it. 

<!-- {"score": "excellent", "minor": false} -->