Adding and Updating Battle Tests for Moves, Equipment, and Items changes
uchicago-cs/chiventure pull request #1661
Opened 2022-05-27 08:54 UTC by nmkhan100

For this PR, we are both updating and creating battle tests to accommodate the changes and additions we have made to structures such as battle_equipment_t, battle_item_t, move_t, etc., throughout the entire quarter. We have prioritized the files battle_flow.c, battle_ai.c, battle_print.c, and battle_logic.c.

Here is a link to the issue associated with this PR:(https://github.com/uchicago-cs/chiventure/issues/1529)

2022-05-29 03:16 UTC, aliu65803 commented on include/battle/battle_ai.h
> + * Outputs:
Just to clarify, is this crit_modifier function specific to NPCs or is it for both the player and npc? I ask if it is specific to NPCs because the function is in battle_ai but I am unsure after reading the description. If it is for both players and NPCs, perhaps it would be best to move this function to battle logic.

2022-05-29 03:18 UTC, aliu65803 commented on src/battle/src/battle_ai.c
> +    }
What is the benefit in changing the target's defense to 1 if it is 0? Is it not allowed for a target to have 0 defense?

2022-05-29 03:20 UTC, aliu65803 commented on tests/battle/test_battle_flow.c
> +Test(battle_flow_move, do_physdamage_battle_flow_move)
Small comment, but I think it should be do_phys_damage_battle_flow_move.

2022-05-29 03:23 UTC, aliu65803 commented on tests/battle/test_battle_logic.c
>  {
This is a large chunk of commented-out code—is there a specific reason this hasn't been deleted? If not, perhaps it would be best to delete it.

2022-05-29 03:24 UTC, aliu65803 commented on tests/battle/test_battle_print.c
> -/*Test(battle_print, print_enemy_move)
delete this

2022-05-29 03:26 UTC, aliu65803 approved these changes
Great work! It seems that you all did a very thorough job in testing what needed to be tested. I have some very minor comments, but I do not think they affect the functionality of the code so I am approving this change. Good job!

2022-05-29 03:29 UTC, aliu65803 requested changes
Actually, I am requesting changes due to the battle_crit function being in the battle_ai module. If it stays there, it may affect the understanding of future teams. Overall, great work!

2022-05-30 01:11 UTC, nicholaswlee commented on include/battle/battle_ai.h
> + * Outputs:
This should have been moved to battle_flow.c

2022-05-30 01:12 UTC, nicholaswlee commented on src/battle/src/battle_ai.c
> +    }
This needs to be done otherwise we divide by zero in our damage calculations.

2022-05-31 00:19 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-31 00:38 UTC, aliu65803 approved these changes
I am approving this PR since it seems like my concerns were addressed.

2022-05-31 15:37 UTC, merged

2022-05-31 17:29 UTC, nicholaswlee commented
We have closed the PR and some of the tests have been updated! We unfortunately were not able to complete all the battles test because of time, but we were able to test these files: battle_flow.c, battle_ai.c, battle_print.c, and battle_logic.c. These tests have not been updated to accommodate things like magical/physical moves, different types of battle items, critical damage, stat changing moves, and many more things!. We have outlined the [doc](https://github.com/uchicago-cs/chiventure/wiki/Battle-~-Test-~-Moves-~-Items-~-Equipment-~-Design-Document) to clarify what future teams will need to do in order to finish testing.

2022-06-06 01:46 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->