1625/am view skills
uchicago-cs/chiventure pull request #1662
Opened 2022-05-27 09:17 UTC by HarrisonD123

We modified our `do_self_action` function to first take in multiple string inputs by converting `string *target` to an array of strings, `string **target`. We then modified our if-statement logic:

If the first string in the array is `"skills"` and the second element is null, we call the skilltree modules function `display_tree,` which prints all skill names out.

If the first string in the array is `"skills"` and the second element is a string, we call the skilltree function `display_skill_description,` passing in the second string as the skill name. This displays the description of the skill and will be used by the player to see what a particular skill does/means.

Harrison changed the parameters of the `do_self_action` function. Jackson and Sabine coded up the if-statement logic and called the skilltree team's functions.

2022-05-27 16:48 UTC, chelseaegbarin commented on include/action_management/actionmanagement.h
>   * - 0 upon success, success string as an out parameter
By "out parameter" do you mean what is printed to the terminal? Not a suggestion just trying to understand !

2022-05-27 16:48 UTC, chelseaegbarin commented on include/action_management/actionmanagement.h
> + * - 6 if conditions for the action haven't been met, failure string as an out parameter
Why does it return 6? Do you mean 1 or am I misunderstanding

2022-05-27 16:54 UTC, chelseaegbarin commented on include/action_management/actionmanagement.h
> + * - 6 if conditions for the action haven't been met, failure string as an out parameter
Okay wait I see why now! I would make these descriptions more uniform though because you specified WRONG_KIND in the previous return option but in this one you just used the number, and it wasn't until I went to the source file that I understood what that meant

2022-05-27 16:56 UTC, chelseaegbarin approved these changes
See comments :) Other than those it looks great. I think your changes were warranted and well-executed. I also appreciate how you left comments throughout your code, it made it easier to follow. My only suggestions/points of confusion were in the header file and are easy fixes :)

2022-05-27 18:29 UTC, KendrickXie approved these changes
Looks good to me.

2022-05-27 22:45 UTC, ecoble requested changes
Looks great overall, Chelsea brought up great points about making the header comments more clear.

2022-05-27 22:45 UTC, ecoble commented on include/action_management/actionmanagement.h
> + * - 6 if conditions for the action haven't been met, failure string as an out parameter
Great point!

2022-05-29 21:29 UTC, HarrisonD123 commented on include/action_management/actionmanagement.h
>   * - 0 upon success, success string as an out parameter
Just that the string is passed in by reference by the CLI team! They have a string whose address they pass in as a parameter. We assign the string, which allows CLI to use the value without our having to actually return it.

2022-05-29 21:29 UTC, HarrisonD123 commented on include/action_management/actionmanagement.h
> + * - 6 if conditions for the action haven't been met, failure string as an out parameter
Just got rid of that comment line. This function never returns 6.

2022-05-30 13:59 UTC, ecoble approved these changes
Great job!

2022-05-31 13:21 UTC, merged

2022-06-07 01:03 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job reviewing and updating this PR! Be sure to include closing statements.

<!-- {"score": "excellent", "minor": false} -->