Adding action functions for NPCs (KIND 5, KIND 6, KIND 7)
uchicago-cs/chiventure pull request #1664
Opened 2022-05-27 16:33 UTC by junasano

Actions is an aspect of the NPC module which allows the player to interact with the NPCs by talking to and trading with them. The current actions can be split into three larger groups, called KIND 5, KIND 6, and KIND 7 actions. 

The purpose of this PR is to implement three functions which allow these KIND actions to be processed. Also, a new variable called price was added to the item_t struct (which is necessary for the KIND 7 function)

KIND 5 and KIND 6 are fully complete. However, with KIND 7, the BUY part cannot be implemented yet since there needs to be a currency-like feature first. Additionally, for TRADE for KIND 7 the player can’t choose which item to give away and it just takes the first item on the list which has a higher price than the wanted item. These two issues will be documented and issues will be created on the backlog later.

2022-05-28 20:12 UTC, srydbergcox commented on src/action_management/src/actionmanagement.c
> +            int switch_mode; // check in examples if this is how a convo is initiated
Was this checked? I am not familiar with this mechanism so want to be sure.

2022-05-28 20:15 UTC, srydbergcox commented on src/action_management/src/actionmanagement.c
> +        if(add_item_to_npc(agent->npc, item) != SUCCESS)
Does this function call and the function call on line 588 remove and add the item too? Or, do we need to directly call the functions too in order to update the inventories?

2022-05-28 20:16 UTC, srydbergcox commented on src/action_management/src/actionmanagement.c
> +        if(add_item_to_player(c->game->curr_player, item, c->game) != SUCCESS)
Same question as above for lines 612 & lines 608.

2022-05-28 20:19 UTC, srydbergcox requested changes
These changes look good and I think it is a really great addition to Chiventure! My only comments are in the main function that you wrote where you call functions that add items, etc. in a conditional check statement and I just want to be sure that that actually updates the player's inventories. Just for now, I am going to hold off on approving the PR until we can discuss that real quick since if they didn't update the inventories the functions wouldn't work. Other than that though, great work!

2022-05-28 20:49 UTC, sglenn-uchi commented on src/action_management/src/actionmanagement.c
> +        if(add_item_to_npc(agent->npc, item) != SUCCESS)
I don't think any direct calls are necessary– add_item_to_npc adds the given item to the hash table representing the npc's inventory and then just returns whether it was able to complete successfully or not. So I don't think direct calls are necessary, if that's what you're talking about.

2022-05-28 21:01 UTC, srydbergcox commented on src/action_management/src/actionmanagement.c
> +        if(add_item_to_npc(agent->npc, item) != SUCCESS)
Yes, that is what I was wondering about. Sounds good then, I just wanted to be sure since I wasn't sure how the functions worked under-the-hood.

2022-05-28 21:02 UTC, srydbergcox approved these changes
Looks good!

2022-05-28 21:03 UTC, sglenn-uchi commented on src/action_management/src/actionmanagement.c
> +            int switch_mode; // check in examples if this is how a convo is initiated
Hmm I checked but might be worth looking at again. Jun have you by chance looked at it?

2022-05-28 22:06 UTC, junasano commented on src/action_management/src/actionmanagement.c
> +            int switch_mode; // check in examples if this is how a convo is initiated
Just checked again. And this was correct so I removed the comment. 
But when the mode is switched to NORMAL, the third parameter was NULL for the examples so I changed it to NULL on line 525

2022-05-29 18:50 UTC, sglenn-uchi commented on src/action_management/src/actionmanagement.c
> +            int switch_mode; // check in examples if this is how a convo is initiated
Thank you for catching that!

2022-05-30 16:05 UTC, Don-Osipov commented on include/action_management/action_structs.h
> +typedef enum {
As someone from the action management team I am a bit confused on what this does and how it is used. Perhaps update the documentation to make it more clear or give a more concrete example?

2022-05-30 16:08 UTC, Don-Osipov commented on src/action_management/src/actionmanagement.c
> +                    if(add_item_to_player(c->game->curr_player, item, c->game) != SUCCESS)
the "c->game->curr_player" object is used many times in the functions you wrote. I think assigning it to a variable would make the code more readable. In general, just try to utilize named variables more often across your functions.

2022-05-30 16:10 UTC, Don-Osipov reviewed
Overall the code you guys wrote looks great. It is well documented and structured. I just had some minor nitpicks with documentation for self_action_object and also the repeated use of c->game->curr_player without assigning it to a variable.

2022-05-30 16:31 UTC, junasano commented on include/action_management/action_structs.h
> +typedef enum {
Thanks for pointing this out. I actually don't know what this is and deleting it doesn't seem to cause any issues so I have removed it. I'm assuming I accidentally copied this from the old branch when I was moving stuff around.

2022-05-30 16:40 UTC, junasano commented
> Overall the code you guys wrote looks great. It is well documented and structured. I just had some minor nitpicks with documentation for self_action_object and also the repeated use of c->game->curr_player without assigning it to a variable.

Thanks for the review! I deleted the sefl_action_object and implemented your second suggestion.

2022-05-30 18:31 UTC, Don-Osipov approved these changes
All feedback that I gave before was addressed. Nice work!

2022-05-31 20:25 UTC, lilyehsani approved these changes
LGTM! Thanks to the other thorough reviews I have no notes.

2022-05-31 20:33 UTC, merged

2022-06-06 21:10 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! Like issues, PRs should have closing statements.

<!-- {"score": "excellent", "minor": false} -->