Quests/cli
uchicago-cs/chiventure pull request #1666
Opened 2022-05-27 17:20 UTC by elizabethli31

We wanted to have quests displayable through the command line, so we worked with action management and cli for this. They needed us to write functions that stored what we wanted displayed into a string, so we wrote functions that would display all the quests a player has, the task tree associated with a quest, and all the elements associated with a particular task. We created a new file for this (quests_cli) and tested using print statements in pre-existing tests. Once this PR goes through, action management and cli will be able to open theirs which both depend on our functions.

2022-05-27 17:43 UTC, Castel-Jaloux approved these changes
Everything looks good, should be ready for merging. Nice comments above the helper functions explaining elements of the methodology!

2022-05-27 19:43 UTC, philipchenaux requested changes
One minor stylistic comment, but besides that looks good to go!

2022-05-27 19:43 UTC, philipchenaux commented on include/game-state/player.h
> +    completion_status_t completion;
Well done changing this to a completion_status_t struct, but please change the documentation of the struct right above.

2022-05-27 19:55 UTC, philipchenaux approved these changes
Looks good to merge!

2022-05-27 19:55 UTC, merged

2022-06-05 10:15 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Excellent job on this PR, note that next time having a more descriptive title that explains your goal would be more useful.

<!-- {"score": "excellent", "minor": false} -->