Battle demo branch
uchicago-cs/chiventure pull request #1674
Opened 2022-05-27 22:39 UTC by nicholaswlee

We are making this Pull Request in order to showcase the changes we have made to battles. This include moves, equipment, and items as outlined in the [doc](https://github.com/uchicago-cs/chiventure/wiki/Battle-~-Demo-~-Design-Document). Additionally we get to showcase "battle mode" which our team has worked with CLI to get working. We have updated all the examples as well in order to have back up plans for the demo and to provide a strong foundation for future coders to know how battles works.

2022-05-28 23:46 UTC, corian-jal approved these changes
Just looking over all of this work, I can tell how much thought and effort you put into this demo update, especially with regard to integration with CLI. Though they are still a bit wonky, I think the demos do a fairly good job of showcasing everything we did this quarter with run_battle and the mei updates. As such, I approve this request to be merged as-is. However, I also know that you guys want to clean everything up a bit more, so I have left comments about my thoughts on and experiences with the demos and hope they help as you all improve it further!

2022-05-28 23:46 UTC, corian-jal commented on src/battle/examples/battle_cli_example.c
> +int main(int argc, char **argv)
To comment on my experience with this demo rather than the code specifically, I struggled to figure out how to start to demo and has to make various guesses and look through the code to figure out that the commands were "fight ninja" and "fight minion". I know this is mainly a problem with CLI since the help menu should have listed them as options, but it could have been explained in the README or the Demo Design Doc. 

Battling the minion was actually pretty fun and mostly everything seemed to work there! As for the ninja, maybe I was just unlucky, but he kept getting crit damage on the first turn, doing insane damage (177 dmg one time and 234 dmg another), and ending the battle really quickly; perhaps his crit stat could be made lower to showcase more of the battle. In another case, I used life drain on my first turn and somehow ended up with -7 hp on the player and -44 hp on the ninja, and I have no idea what happened there. I also had a situation where I used all of I1 so it removed itself from the list and the previous I2 became listed as I1, but when I tried to use the new I2 (the previous I3), the previous I2 was used instead of the new one. Despite all this, the demo seemed to work most of the time and shows off a lot of the work we did this quarter, so good job!

2022-05-28 23:46 UTC, corian-jal commented on src/battle/examples/battle_command_example.c
> +        fprintf(stderr, "SUCCESS: battle flow loop exited and enemy won\n");
There have been a lot of changes to this file specifically, which is why I'm wondering if it is supposed to work? When I ran the executable, the enemy moves and "What will you do?" printed just fine, the normal damage + number of crits + crit damage were reasonable and resulted in a short but not immediately over battle, and the loop successfully exited with an enemy victory. However, I could not do anything: all of the commands I typed (M1, LifeDrain, Move List, List Moves, Help, etc) did not return anything and the enemy just took their next turn until I died. Was this example meant to be used? If there were instructions printed in that first block of text, I could not see them because that block of text was long enough to go off-screen and I could not scroll up to see what it said; perhaps it could print in stages (with waits or as the parts process)?

2022-05-28 23:46 UTC, corian-jal commented on src/battle/examples/battle_flow_example.c
> +    }
I think the executable just prints an example battle that doesn't take inputs, and from the code here and the fraction I saw, it seems like a good example, but again, I ran into the problem where it all printed as one block and I could not scroll up to see what was off-screen. Maybe it's just a problem with the program I'm using, but printing each turn and separating them with waits or requesting a simple command like "next" or "n" in-between turns might make it easier to see and digest.

2022-05-28 23:46 UTC, corian-jal commented on src/battle/examples/demo_items_and_equipment.c
> +
All of the pieces of equipment you came up with are very fun! I just wanted to comment that I loved the creativity here.

2022-05-28 23:46 UTC, corian-jal commented on src/battle/src/battle_flow_structs.c
> +      new_equip->type = type;
Is there any reason for copying this block of code instead of calling init_battle_equipment?

2022-05-28 23:46 UTC, corian-jal commented on src/battle/src/battle_flow_structs.c
> +      new_item->prev = prev;
Same thing: why not call init_battle_item?

2022-05-28 23:46 UTC, corian-jal commented on src/battle/src/battle_logic.c
> +
I think the above changes of setting a field to 0 when it returns a value under 0 should be added to hp and sp as well.

2022-05-29 00:13 UTC, corian-jal requested changes
The points made in my previous review still stand, but I am changing my decision to "Request Changes" to facilitate further code work.

2022-05-30 00:03 UTC, nicholaswlee commented on src/battle/examples/battle_cli_example.c
> +int main(int argc, char **argv)
Yeah we gave the ninja an item called razor claw that doubles his crit rate. We'll play around with his stats to make it a little more fair.

2022-05-30 00:04 UTC, nicholaswlee commented on src/battle/examples/battle_command_example.c
> +        fprintf(stderr, "SUCCESS: battle flow loop exited and enemy won\n");
I think LIST MOVES is the correct command and HELP. We will double check this to make sure, but this example is mainly a back up plan.

2022-05-30 00:23 UTC, nicholaswlee commented on src/battle/examples/battle_flow_example.c
> +    }
This one is supposed to print a very very long text that really just showcases battle flow.

2022-05-30 00:33 UTC, nicholaswlee commented on src/battle/src/battle_logic.c
> +
We have just change it so that this works.

2022-05-30 01:36 UTC, nicholaswlee commented on src/battle/src/battle_flow_structs.c
> +      new_item->prev = prev;
This has been resolved

2022-05-30 07:42 UTC, corian-jal requested changes
Everything looks good to me: I couldn't get the command example to progress my turn, but the cli demo works perfectly with minion and ninja and the flow example works as a back-up, so I think we're good on that front. The only change I'm requesting is for the one failing check to be fixed so the code can be merged later.

2022-05-30 16:47 UTC, corian-jal approved these changes
After all of the fixes in response to previous requests for changes, I think this code us good to be merged!

2022-05-31 02:37 UTC, lilyehsani requested changes
Really work here! You did a great job explaining everything with comments. I left some notes, mostly about commented-out code. Remember that if you want to leave in commented-out code, you should also leave a comment explaining why.

2022-05-31 02:37 UTC, lilyehsani commented on include/battle/battle_logic.h
> +void get_legal_actions(battle_item_t **items,
Is this now an array of linked lists? Could you update the comment with an explanation?

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/examples/battle_command_example.c
> +    /*
Delete commented out code.

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/examples/battle_command_example.c
> +        printf("Determined command as MOVE USE, and it using the %s move\n\n",
I'm not sure I understand this output, particularly the "and it" part.

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/examples/battle_command_example.c
> +        printf("calling check_target...\n");
Perhaps capitalize this?

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/examples/battle_command_example.c
> +    /*
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +    /*if(battle_over(b) == BATTLE_IN_PROGRESS)
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +    char *string = calloc(BATTLE_BUFFER_SIZE + 1, sizeof(char));
Good change!

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +    /*char *item_name = calloc(150, sizeof(char));
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +    // char *ret_string = (char*)calloc(1,BATTLE_BUFFER_SIZE*sizeof(char));
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_flow.c
> +            //if (ctx->game->battle_ctx->game->player->moves == NULL)
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_logic.c
> +    //printf("place 1\n");
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_logic.c
> +        /*for(int i = 0; temp->name[i] != '\0'; i++)
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_logic.c
> +    //battle_item_t *item = find_battle_item(c->items, name);
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/battle/src/battle_print.c
> +/*char *print_battle_action_menu(battle_item_t *items, move_t *moves)
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/cli/src/operations.c
> +    /*stat_t *p1_stats = (stat_t*) calloc(1, sizeof(stat_t));
Delete or uncomment

2022-05-31 02:37 UTC, lilyehsani commented on src/game-state/src/mode.c
> +        //output = strcat(output, enemy_turn);
Delete or uncomment

2022-05-31 17:03 UTC, nicholaswlee commented on include/battle/battle_logic.h
> +void get_legal_actions(battle_item_t **items,
This has been updated.

2022-05-31 17:03 UTC, nicholaswlee commented on src/battle/examples/battle_command_example.c
> +        printf("Determined command as MOVE USE, and it using the %s move\n\n",
This has been updated.

2022-05-31 17:11 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-31 19:00 UTC, merged

2022-05-31 20:15 UTC, aliu65803 commented
Now that the PR has been merged to dev, we are done with implementing the 2022 battle demo. We had to make several changes based on the comments given to us by Lily and Fatimah, which include fixing some bugs regarding user input, deleting commented-out code, and more. We look forward to presenting our demo to the rest of the class and showing them the updated battle module.

2022-06-06 23:32 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR! My review contained a lot of comments regarding commented-out code, which likely should have been caught by the student reviewer. Please make sure that you do a thorough code review and, in the future, make sure to look out for the kind of issues the senior developer pointed out.

<!-- {"score": "excellent", "minor": false} -->