1628/am view quests
uchicago-cs/chiventure pull request #1675
Opened 2022-05-27 22:57 UTC by HarrisonD123

We modified our do_self_action function to first take in multiple string inputs by converting string *target to an array of strings, string **target. We then modified our if-statement logic:

If the first string in the array is "quests" and the second element is null, we call the quests module's function show_quests, which prints all quest names out.

If the first string in the array is "quests" and the second element is a string, we call the quests function show_task_tree, passing in the second string as the quest name. This displays the tree of tasks that completing the specified quest entails.

If the first string in the array is "task" and the second element is a string, we call the quests function show_task, passing in the second string as the task name. This displays one specific task's of a particular quest and its description, so that the player knows what it entails.

2022-05-28 20:02 UTC, Don-Osipov commented on include/action_management/actionmanagement.h
> + *           (quests, etc), and secondary-level object ("quest-id", etc)
Maybe a bit more clarification on what a secondary-level object is?

2022-05-28 20:06 UTC, Don-Osipov commented on src/action_management/src/actionmanagement.c
> +                string = show_quests(c->game->curr_player);
You use c->game->curr_player very often, maybe make it a variable that you reuse

2022-05-28 20:08 UTC, Don-Osipov commented on src/action_management/src/actionmanagement.c
> +                string = show_quests(c->game->curr_player);
You also have this line: game_t *game = c->game;
which goes unused as far as I see

2022-05-28 20:10 UTC, Don-Osipov reviewed
Looks pretty good other than some minor documentation and code style changes. Nice job documenting what the code you added does - it's very clear.

2022-05-29 03:18 UTC, ecoble reviewed
Just a quick question, otherwise looks good!

2022-05-29 03:18 UTC, ecoble commented on src/action_management/src/actionmanagement.c
> -    target = case_insensitized_string(target);
do you still need to case desensitize target?

2022-05-29 15:11 UTC, JSerf02 commented on src/action_management/src/actionmanagement.c
> -    target = case_insensitized_string(target);
Hi, I'm from the quest team and I was messing around with the changes from this PR in another branch to test our final demo. 

So I'm 90% sure you don't need to make it lowercase again since the strings in target are already lowercase. In fact, I'm pretty sure this line is actually a mistake that needs to get removed since target is a char ** while case_insensitized_string takes a char * as input (this causes segfaults in-game). Another issue with this happens later in the function as well. I posted fixes in your Slack channel yesterday if anyone can take a look.

2022-05-29 15:32 UTC, sabinecodes15 commented on src/action_management/src/actionmanagement.c
> -    target = case_insensitized_string(target);
Thanks for pointing this out! Just updated the code to reflect those changes.

2022-05-29 21:37 UTC, HarrisonD123 commented on src/action_management/src/actionmanagement.c
> -    target = case_insensitized_string(target);
Those issues have all been fixed!

2022-05-29 21:39 UTC, HarrisonD123 commented on src/action_management/src/actionmanagement.c
> -    target = case_insensitized_string(target);
CLI already lowercases all strings

2022-05-30 00:35 UTC, JSerf02 requested changes
Changes look good! I commented 2 changes. The bottom one is far more important since it causes segfaults if not fixed, but it would be nice if you can get to the top one as well.
Will approve once the mistyping error on line 425 is fixed.

2022-05-30 00:35 UTC, JSerf02 commented on src/action_management/src/actionmanagement.c
>              sprintf(string, "%s cannot be viewed", target);
This is the other line with incorrect typing (char ** instead of char *). Should be target[0] I think

2022-05-30 00:35 UTC, JSerf02 commented on src/action_management/src/actionmanagement.c
> +            else {
It would likely make more sense in terms of quest interface if this were its own condition for when the user enters "quest" to distinguish more between printing multiple quests and an individual quest (so add another if statement just for this, print an error message if there is no second input in that statement, and call the first statement in the current "quests" if statement with no other checks). 
This is not the biggest deal though and it is definitely more important to get this PR in than to fix this if there's no time.

2022-05-30 00:48 UTC, HarrisonD123 commented on src/action_management/src/actionmanagement.c
>              sprintf(string, "%s cannot be viewed", target);
Ah thanks for catching that. It was fixed in another branch, but we have a lot of branches working on the same function, so it's hard to keep track of what was changed where. Fixed!

2022-05-30 00:50 UTC, HarrisonD123 commented on src/action_management/src/actionmanagement.c
> +            else {
I think for now, it'd be simpler to keep the current implementation. We can make it a backlog issue to make it more robust, but generally we don't want to clutter the if-statement logic if at all possible. If things go well, there will be many more things to view along with more self_actions in the future, making the logic even more complex.

2022-05-30 00:56 UTC, JSerf02 approved these changes

2022-05-30 00:56 UTC, JSerf02 commented on src/action_management/src/actionmanagement.c
> +            else {
Thank you!

2022-05-30 00:56 UTC, HarrisonD123 commented on src/action_management/src/actionmanagement.c
> +            else {
Done!

2022-05-30 01:08 UTC, Don-Osipov approved these changes
All changes that were commented on by me earlier have been addressed. Looks good!

2022-05-30 13:59 UTC, ecoble approved these changes
Great job reviewing and updating this PR!

2022-05-30 14:03 UTC, merged

2022-06-07 01:01 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job on this issue, and especially with reviewing the updating a cross-team PR! Please be sure to include closing statements for PRs as well as issues.

<!-- {"score": "excellent", "minor": false} -->