rpg-battles/sound integration & Wiki
uchicago-cs/chiventure pull request #1682
Opened 2022-05-28 01:31 UTC by jiaoboxuan

In this issue, we attempted to integrate sound modules into `rpg-battle` modules. We changed the `CMakeFiles.txt` of both `sound` and `rpg-battle` folders, and added `#include` statements to the `rpg_battle_flow.h` header file. The code compiles successfully, yet the issue is that when we put actual `sound_new`, `play_sound`, and `sound_free` functions, there are some extremely unexpected errors that occur outside of the function where the codes are inserted. We are going to deal with the actual function implementation over the weekend, yet with the successful compilation post addition of header files, we might as well put this pull request in.

Additionally, we wrote a Wiki page on our progress, The link is attached [here](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Sound-integration-with-battle-(design-document)).

Not sure why this branch cannot automatically merge into `dev`, however. A possibility is that when I created this branch, I copied the files off some branch other than `dev`, so there would be some merging conflicts, but I hope it's not a big issue. Please let us know ASAP if it is indeed a source of concern.

2022-05-28 03:07 UTC, nicholaswlee requested changes
This pull request looks good. Everything has been defined well and given good header comments. I've left a couple comments for things that are just minor styling issues. You've also done a good job freeing these structs as well. I am excited for sound to get implemented, especially within the scope of battles!

2022-05-28 03:07 UTC, nicholaswlee commented on src/sound/src/sound.c
> +    if (sound->name == NULL) {
Make sure to follow the style guidelines, use
if ()
{
}

2022-05-28 03:07 UTC, nicholaswlee commented on include/sound/sound.h
> +/* Initializes the
I'm assuming this is initializing sound?

2022-05-29 17:03 UTC, jwschroeder21 approved these changes
Aside from Nicholas' style suggestions, everything looks good to me!

2022-05-29 17:03 UTC, jwschroeder21 commented on include/sound/sound.h
> +/* Initializes the
yep

2022-05-30 14:15 UTC, ecoble reviewed
I believe a lot of these changes from the sound team have already been merged into dev, so we will see them removed once this PR gets updated. Looks good overall, you might want to update on this PR that the compilation errors were fixed. Additionally, please fix the merge conflicts.

2022-05-30 14:15 UTC, ecoble commented on include/sound/sound.h
> +/* Initializes the
Please update this header comment with the full sentence, also I believe these changes have already been made in a previous PR.

2022-05-31 21:12 UTC, ecoble approved these changes

2022-05-31 21:26 UTC, nicholaswlee approved these changes

2022-05-31 22:04 UTC, merged

2022-05-31 22:41 UTC, emiliolevinspage commented
We are closing this issue because the merge is complete! The integration has been completed so that in the future it will be easy to add sounds to any aspect of battles. The process for doing this is documented in the wiki page referenced above.

2022-06-07 00:35 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice job laying the groundwork for integration, and great job reviewing the PR!

<!-- {"score": "excellent", "minor": false} -->