sound: create a final demo with text to speech
uchicago-cs/chiventure pull request #1683
Opened 2022-05-28 02:07 UTC by sangerr

This pull requests contains a final demo in tts_dialogue_example.c that demonstrates the text to speech feature we have been working on all quarter. This is built upon the previous example we created that contained a dialogue between an npc and character in a game. Based off the tts structs that were created, we added those into the portions of the conversation where the program was printing the responses from the npc. In this game, we have both printed and vocal responses using text to speech.

2022-05-28 02:11 UTC, sangerr commented
There were some issues with the test_sound file I had in my repository, however those were solved by the commits "fixed test sound issue" and "fixed test_sound". To see the actual changes made for the final demo, please look at the "added text to speech to dialogue demo" commit.

2022-05-30 20:06 UTC, jwschroeder21 commented
Update: we are getting an error that doesn’t allow for the text to speech to run beyond the first line of text. The message popping up in response is “error: entity exists,” and we are further investigating. It is probably the error message of some other module.

2022-05-31 20:03 UTC, parkerbroz approved these changes
Great job! I think this is a promising proof of concept for the application of text-to-speech and the utility of sound in chiventure overall.

2022-05-31 21:05 UTC, ecoble requested changes

2022-05-31 21:05 UTC, ecoble commented on include/sound/sound.h
> +<<<<<<< HEAD
Remove line 46 and 48, thesis is text created from the merge conflict

2022-05-31 21:05 UTC, ecoble commented on src/sound/examples/Makefile
> -CC=gcc
This file is auto generated by CMake, please remove it

2022-05-31 21:05 UTC, ecoble commented on src/sound/examples/examples/Makefile
> +# CMAKE generated file: DO NOT EDIT!
Please remove this as well

2022-05-31 21:14 UTC, ecoble requested changes
Please also remove all the compiled binary executables, otherwise looks good

2022-05-31 21:30 UTC, ecoble approved these changes

2022-05-31 21:32 UTC, merged

2022-06-01 03:18 UTC, sangerr commented
Closing Summary: In this PR we developed a demo that demonstrates the text to speech feature we have been working on all quarter. We did this by adding on to the dialogue between an npc and player using the tts structs to be able to have audio for the conversation. We initially tried to integrate it directly into a game, but had to monkey patch it due to some errors. In addition, we have to restructure the from the example without tts because of errors in printing to cli and speaking in the actual game. Lastly, we had to edit the cmake to make sure that the file would compile and run. We are looking forward to presenting this at the demo on Wednesday!

2022-06-07 00:27 UTC, ecoble commented
Issue Score: Excellent

Comments:
Nice job with the demo! I know there were a lot of difficult issues to fix and you did a great job debugging them. Ideally the demo would be debugged before the pull request was created, but otherwise excellent work!

<!-- {"score": "excellent", "minor": false} -->