npc/dialogue and quests: quest implementation in dialogue and wdl integration
uchicago-cs/chiventure pull request #1685
Opened 2022-05-28 03:31 UTC by sglenn-uchi

This pull request includes the additions of quests and their associated tasks within the npc struct, found in the form of npc_quest_list_t and npc_task_list_t pointers. These pointers hold linked lists of npc_quests and npc_tasks, representing the quests and tasks an npc has. Each one of these quests and tasks has unique dialogue that will be activated if the player satisfies the stat prerequisites of the quest. If they satisfy these prerequisites, they will get the quest and participate in unique dialogue with the NPC, including for each of the individual tasks, until the tasks and their quest are complete and the NPC returns to its default dialogue. This PR also includes complete implementation of NPC quests and tasks in WDLs, allowing previous WDLs to be run as well as new ones representing NPCs with the new quest and task lists in JSON. The full design is included in this [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Incorporating-Quests-into-NPC).

2022-05-28 21:43 UTC, bvvill commented on docs/actions.md
> +                - :
Is something else meant to go here?

2022-05-29 00:45 UTC, bvvill requested changes
Overall, I'm very impressed with the work you guys have done. I'd be lying if I said I completely understand the design of this new feature, but I trust y'all know what you're doing, and I must say I'm very glad I reviewed this, I've learned a few things along the way. I can't wait to approve this once the changes are made.

2022-05-29 00:45 UTC, bvvill commented on docs/actions.md
> +                - :
is something else meant to go here?

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +   npc_quest_t *next;
you should be able to avoid using a forward declaration by doing this
```suggestion
   struct npc_quest *next;
```

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +    class_t *npc_class;
there's already a `class_t` member on line 81, what's the purpose of `npc_class_t`?

2022-05-29 00:45 UTC, bvvill commented on include/npc/dialogue.h
> +//#include "quests/quests_state.h"
I'm not sure if this should either be uncommented or just deleted entirely

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +npc_quest_t *get_npc_quest(npc_t *npc, char *id);
maybe a slight nit-pick but because there are so many different types of `id`s I think it's be best if they were specified in the function declarations
```suggestion
npc_quest_t *get_npc_quest(npc_t *npc, char *quest_id);
```

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +npc_task_t *get_npc_task(npc_t *npc, char *id);
and here as well
```suggestion
npc_task_t *get_npc_task(npc_t *npc, char *task_id);
```

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +
Considering the addition of ~150 lines of functions solely dealing with `npc_quest` and `npc_task` structs, I think you guys should create a separate module and have it included in this one

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +
Going back to my suggestion for making a new `npc_quest` module, I would include these in there as well

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +                                 char *quest_id, char *task_id);
parameters need updated

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +                   char *quest_id, char *task_idk);
parameters need updated. Also, this function should be moved to the game file since it involves the `game_t` struct, not doing so will lead to circular dependency issues.

2022-05-29 00:45 UTC, bvvill commented on include/npc/npc.h
> +bool npc_can_give_task(quest_ctx_t *qctx, char *task_id);
why do these need to be forward declared?

2022-05-29 00:45 UTC, bvvill commented on include/quests/quests_state.h
> +bool npc_can_complete_task(quest_ctx_t *qctx, char *task_id);
I think these functions should have more accurate names, such as
```
can_player_start_quest()
can_player_start_task()
```
also, it seems `npc_can_give_quest()` is declared twice (the first in lines 192-202), and that `npc_can_give_task()` (declared in lines 204-214) is obselete.

2022-05-29 00:45 UTC, bvvill commented on src/cli/src/operations.c
> +
you've got an added empty line here, not sure if this was intentional

2022-05-29 00:45 UTC, bvvill commented on tests/npc/test_wdl_plus.c
> +}
I would add a newline here just so the file is null-terminated
```suggestion
}

```

2022-05-29 00:45 UTC, bvvill commented on src/wdl/src/validate.c
> +}*/
I'd either uncomment these or delete them entirely, and if they're going to be deleted please remove them from validate.h as well

2022-05-29 00:45 UTC, bvvill commented on src/quests/src/task.c
> +    }
this seems to be some sort of copy and paste situation but a couple of things: make sure you're following the style guidelines (https://uchicago-cs.github.io/dev-guide/style_guide_c.html) (indentation and spaces being of concern), and to make the string lowercase I would just use the `case_insensitize()` function to reduce complexity and keep string manipulation consistent throughout chiventure.
```suggestion
    if (type == MEET_NPC || type == KILL_NPC) 
    {
        case_insensitize(mission->target_name);
    }
```
and honestly it might be better to just case_insensitize the `char *target_name` input from the get-go before even assigning `mission->target_name` to it

2022-05-29 00:45 UTC, bvvill commented on src/quests/src/quests_state.c
> +    return false;
i notice there's no case for `KILL_NPC` (which i recommend you make), i'm assuming this was intentional and meant to always be false, but why?

2022-05-29 00:45 UTC, bvvill commented on src/quests/src/quests_state.c
> +    if(pquest != NULL) {
yeah this is going to be my second and also my last styling comment lol sorry @lilyehsani

2022-05-29 00:45 UTC, bvvill commented on src/quests/src/quests_state.c
> +    if(!ptask) {
i know that this works but for the sake of clarity:
```suggestion
    if(ptask == NULL) {
```

2022-05-29 00:45 UTC, bvvill commented on tests/npc/test_npc.c
> +
when you make the separate module please remember to make another test file for these as well

2022-05-29 00:45 UTC, bvvill commented on tests/quests/test_quests_state.c
>      cr_assert_eq(check, true, "npc_can_give_task() failed");
ik i suggested you guys change the name of this function so just make sure that change is reflected in the test-failure messages as well
```suggestion
    cr_assert_eq(check, true, "npc_can_complete_task() failed");
```

2022-05-29 00:45 UTC, bvvill commented on src/wdl/src/load_npc.c
> +            fprintf(stderr, "Quests were not loaded properly. NPC: %s\n",
```suggestion
            fprintf(stderr, "Tasks were not loaded properly. NPC: %s\n",
```

2022-05-29 00:45 UTC, bvvill commented on src/npc/examples/pokemon_plus.wdl
> +}
no newline at EOF

2022-05-29 00:45 UTC, bvvill commented on src/npc/src/npc.c
> +
ik i've already said this but... new module plz

2022-05-29 00:45 UTC, bvvill commented on src/npc/src/npc.c
> +    task->dialogue = c;
and then don't forget to move these to the new module as well

2022-05-29 00:45 UTC, bvvill commented on src/cli/src/operations.c
> +    quest_ctx_init(&qctx, ctx->game->curr_player, ctx->game->all_quests);
this is going to immediately fail the `assert(quest_ctx != NULL);` statement in the first line of `quest_ctx_init()` since `quest_ctx_t qctx;` is NULL-initialized by default, i think you meant to do this:
```suggestion
    quest_ctx_t qctx = quest_ctx_new(ctx->game->curr_player,  ctx->game->all_quests);
```
and then free this `qctx` at some later point in this function ofc

2022-05-29 00:47 UTC, bvvill commented on include/npc/npc.h
> +typedef struct npc_quest npc_quest_t; // forward declaration
neither of these forward declarations should be needed

2022-05-29 00:49 UTC, bvvill commented on include/npc/dialogue.h
> +//#include "quests/quests_state.h"
def deleted entirely

2022-05-29 01:12 UTC, sglenn-uchi commented on include/npc/npc.h
> +   npc_quest_t *next;
Thank you!

2022-05-29 01:14 UTC, sglenn-uchi commented on include/npc/dialogue.h
> +//#include "quests/quests_state.h"
Oops, I forgot to delete this. Thanks for catching!

2022-05-29 01:14 UTC, sglenn-uchi commented on include/npc/npc.h
> +npc_quest_t *get_npc_quest(npc_t *npc, char *id);
Yeah, I agree. That would improve readability/reduce confusion a lot.

2022-05-29 01:23 UTC, sglenn-uchi commented on include/npc/npc.h
> +   npc_quest_t *next;
Actually I tried this, and it causes compiler warnings (incompatible pointer type) in the npc_task/quest_list_add and npc_task/quest_list_free functions and other functions that involve traversing the list.

2022-05-29 01:23 UTC, sglenn-uchi commented on include/npc/npc.h
> +    class_t *npc_class;
To be honest, I'm not sure. I don't think it's used anywhere else in the code.

2022-05-29 01:24 UTC, sglenn-uchi commented on src/wdl/src/load_npc.c
> +            fprintf(stderr, "Quests were not loaded properly. NPC: %s\n",
Nice catch, thank you!

2022-05-29 01:31 UTC, bvvill commented on include/npc/npc.h
> +   npc_quest_t *next;
ahhh, makes sense.

2022-05-29 01:32 UTC, bvvill commented on include/npc/npc.h
> +typedef struct npc_quest npc_quest_t; // forward declaration
actually, the second one seems to be needed

2022-05-29 04:27 UTC, sglenn-uchi commented on src/npc/examples/pokemon_plus.wdl
> +}
fixed!

2022-05-29 05:00 UTC, sglenn-uchi commented on src/cli/src/operations.c
> +    quest_ctx_init(&qctx, ctx->game->curr_player, ctx->game->all_quests);
Yes, nice catch!

2022-05-29 05:11 UTC, sglenn-uchi commented on include/npc/npc.h
> +                   char *quest_id, char *task_idk);
That's right, thank you for catching that!

2022-05-29 05:14 UTC, JSerf02 commented on src/quests/src/task.c
> +    }
Can we leave this here for now? It is fixed in a later branch already

2022-05-29 05:18 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +    return false;
KILL_NPC is not implemented into chiventure yet, it is just in the enum for legacy support for some of the older quest module tests that relied on it. Changed this to false to make sure quests with invalid missions or unsupported missions don't automatically complete, as that makes bug testing games really difficult.

Also sorry for obscuring so much info about these changes, I am going to write up a design doc detailing everything that happened here in a couple days once my finals are done. Just haven't had the time :(

2022-05-29 05:21 UTC, JSerf02 commented on docs/actions.md
> +                - :
I don't think we are the ones who made these changes. There were a ton of merge conflicts with this branch, so I think some of the changes from prior pushes to dev are showing up again here as new changes.

2022-05-29 05:23 UTC, JSerf02 commented on include/npc/npc.h
> +
Can this please be a backlog issue? It seems like it's going to take a lot of work to move this into its own module bc of resolving dependencies and time is really of the essence right now

2022-05-29 05:32 UTC, JSerf02 commented on include/npc/npc.h
> +                                 char *quest_id, char *task_id);
Nice catch! Turns out this function and the one from the next comment are not actually needed anymore! They were replaced by the set_proper_dialogue() function, we just forgot to remove their headers from this file. Just fixed

2022-05-29 05:32 UTC, JSerf02 commented on include/npc/npc.h
> +                   char *quest_id, char *task_idk);
See prev

2022-05-29 05:32 UTC, JSerf02 commented on include/npc/npc.h
> +bool npc_can_give_task(quest_ctx_t *qctx, char *task_id);
Removed

2022-05-29 05:33 UTC, sglenn-uchi commented on include/npc/npc.h
> +                   char *quest_id, char *task_idk);
Just saw, ty for reminding me we needed to remove

2022-05-29 05:39 UTC, JSerf02 commented on include/quests/quests_state.h
> +bool npc_can_complete_task(quest_ctx_t *qctx, char *task_id);
Renamed to can_player_start_quest() and can_player_complete_task(). Also deleted the repetitions, which were caused by merging issues.

2022-05-29 05:40 UTC, bvvill commented on docs/actions.md
> +                - :
makes sense

2022-05-29 05:41 UTC, bvvill commented on include/npc/npc.h
> +
why would this take long?

2022-05-29 05:43 UTC, JSerf02 commented on src/cli/src/operations.c
> +
Fixed, since start_conversation() was actually called in the wrong place anyways (discovered in a later branch), so I just moved it up here and deleted the lines

2022-05-29 05:47 UTC, bvvill commented on src/quests/src/task.c
> +    }
I mean i would just go ahead and fix it rq, you can just click on the suggestion to commit it if you'd like.

2022-05-29 06:05 UTC, JSerf02 commented on include/npc/npc.h
> +
Did it, hopefully didn't break anything here or in future branches

2022-05-29 06:07 UTC, bvvill commented on src/cli/src/operations.c
> +    quest_ctx_init(&qctx, ctx->game->curr_player, ctx->game->all_quests);
in my suggested change, I forgot to make the new `quest_ctx_t *qctx` a pointer, so I just wanted to make another comment to make sure you didn't make the same mistake

2022-05-29 06:08 UTC, JSerf02 commented on src/quests/src/task.c
> +    }
There are more changes than just that need to go into fixing the actual issues with this function though. Changing this here will create a merge conflict for future branches that already fixed them all (see quests/wdl_file_branch for the fixes). LIke the entire other branch already has everything fixed and will get pulled in once this and an action management pr is done, so changing it here will only cause harm.

2022-05-29 06:19 UTC, JSerf02 commented on include/npc/npc.h
> +typedef struct npc_quest npc_quest_t; // forward declaration
Fixed

2022-05-29 06:20 UTC, JSerf02 commented on src/cli/src/operations.c
> +    quest_ctx_init(&qctx, ctx->game->curr_player, ctx->game->all_quests);
Fixed I think

2022-05-29 06:21 UTC, JSerf02 commented
I think I resolved all of the suggestions. Lmk if there is anything else that needs to be addressed!

2022-05-29 07:03 UTC, bvvill commented on src/quests/src/task.c
> +    }
if you're trying to avoid merge conflicts wouldn't you want this to be the same as dev?

2022-05-29 07:08 UTC, JSerf02 commented on src/quests/src/task.c
> +    }
I can't make the other changes in this branch because they involve changing all mission names to lowercase and not just the ones provided which is going to crash a bunch of quest tests, which would be even more to fix in this 1700 line pr.

2022-05-29 07:09 UTC, JSerf02 commented on src/quests/src/task.c
> +    }
Please I fixed everything else, just let this one thing remain, I promise it will be better in dev once everything else is sorted out with action management. We've had way too many problems with merge conflicts already and I don't want to cause any more pain with that.

2022-05-29 07:31 UTC, bvvill commented on src/quests/src/task.c
> +    }
> We've had way too many problems with merge conflicts already and I don't want to cause any more pain with that.

I'm pretty sure this is going to become a merge conflict

2022-05-29 07:40 UTC, JSerf02 commented on src/quests/src/task.c
> +    }
Fiiinneee, fixed but please approve now :)

2022-05-29 07:40 UTC, JSerf02 commented on src/quests/src/quests_state.c
> +    if(!ptask) {
Fixed I think

2022-05-29 07:45 UTC, JSerf02 commented on tests/npc/test_npc.c
> +
Just remembered

2022-05-29 07:45 UTC, JSerf02 commented on tests/npc/test_npc.c
> +
(fixed btw)

2022-05-29 08:04 UTC, bvvill requested changes
Looks great ! Just a couple more things and you'll have my stamp of approval

2022-05-29 08:04 UTC, bvvill commented on include/npc/npc.h
> +
Can this be deleted?

2022-05-29 08:04 UTC, bvvill commented on src/cli/src/operations.c
> +    quest_ctx_free(qctx);
what do you mean by this comment lmao

2022-05-29 08:04 UTC, bvvill commented on src/npc/src/npc.c
> +    npc->tasks = NULL;
please explain what you're trying to do here

2022-05-29 08:04 UTC, bvvill commented on src/npc/src/npc.c
> +}
no newline at EOF

2022-05-29 08:04 UTC, bvvill commented on src/npc/src/npc_quests.c
> +}
no newline at EOF

2022-05-29 08:04 UTC, bvvill commented on tests/npc/test_npc_quest.c
> +}
no newline at EOF

2022-05-29 08:08 UTC, bvvill commented on include/npc/npc.h
> +
this change is for the best, if future branches are broken by this then they'll be changed for the better as well

2022-05-29 08:08 UTC, bvvill commented on src/quests/src/task.c
> +    }
nah

2022-05-29 08:09 UTC, JSerf02 commented on include/npc/npc.h
> +
I think that was there before we made these changes, so gonna have to defer to the quest team on this one

2022-05-29 08:10 UTC, JSerf02 commented on tests/npc/test_npc_quest.c
> +}
fixed

2022-05-29 08:10 UTC, JSerf02 commented on src/npc/src/npc_quests.c
> +}
fixed

2022-05-29 08:11 UTC, JSerf02 commented on src/npc/src/npc.c
> +}
fixed

2022-05-29 08:12 UTC, JSerf02 commented on src/npc/src/npc.c
> +    npc->tasks = NULL;
Idk what happened there (probably more merge problems given this branch's history lol). Removed the 2 NULL lines

2022-05-29 08:12 UTC, JSerf02 commented on src/cli/src/operations.c
> +    quest_ctx_free(qctx);
Lol removed

2022-05-29 08:15 UTC, bvvill requested changes
one last ting ?

2022-05-29 08:15 UTC, bvvill commented on src/npc/src/npc.c
> +
now that you have lines 21 & 22 you can delete these

2022-05-29 08:17 UTC, bvvill commented on include/npc/npc.h
> +
on behalf of the NPC team, you can delete it

2022-05-29 08:19 UTC, JSerf02 commented on src/npc/src/npc.c
> +
Ah, you're right. I actually should have kept the NULL ones before and not the other new ones (NULL is necessary bc there were bugs failing when it wasn't set to NULL, I don't remember why). Just fixed

2022-05-29 08:19 UTC, JSerf02 commented on include/npc/npc.h
> +
Deleted

2022-05-29 08:23 UTC, bvvill commented on src/npc/src/npc.c
> +
yeah utlists and uthashs get really buggy when the head of the list or hash isn't explicitly NULL-initialized

2022-05-29 08:26 UTC, bvvill approved these changes
LGTM , good luck !

2022-05-29 08:33 UTC, bvvill commented on src/quests/src/task.c
> +    }
https://github.com/uchicago-cs/chiventure/commit/9f7a44eff2c6d547ca36015fcbbfc1e20ac57818
and also, respectfully, please grow up.

2022-05-29 14:17 UTC, sglenn-uchi commented
We successfully finished implementation and submitted a PR for the changes, which we moved to branch npc/dialogue-quests-final. We already have gotten approval from one reviewer and successfully implemented changes from his comments. When the PR is approved, this issue will close automatically.

2022-05-29 22:25 UTC, lilyehsani requested changes
Well done on this! Thanks to Will's thorough review, I only have a few comments.

2022-05-29 22:25 UTC, lilyehsani commented on include/game-state/player.h
> +    char * crnt_npc;
Should be `char *crnt_npc`.

2022-05-29 22:25 UTC, lilyehsani commented on src/cli/src/operations.c
> +    if (npc->active_dialogue == NULL)
I believe the null check should be performed before the call to `start_conversation`.

2022-05-29 22:25 UTC, lilyehsani commented on src/npc/examples/pokemon_plus.wdl
> +                            }
Very cute love it!!

2022-05-29 22:57 UTC, JSerf02 commented on include/game-state/player.h
> +    char * crnt_npc;
Fixed

2022-05-29 22:57 UTC, JSerf02 commented on src/cli/src/operations.c
> +    if (npc->active_dialogue == NULL)
Fixed

2022-05-30 00:16 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-30 00:16 UTC, merged

2022-06-07 00:05 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! Like issues, PRs should have closing statements.

<!-- {"score": "excellent", "minor": false} -->