Playerclass: created function, tests for prefab items associated with classes
uchicago-cs/chiventure pull request #1686
Opened 2022-05-28 03:42 UTC by vanolson

In `class_prefabs.h` and `class_prefabs.c`, I wrote a function, `class_prefab_add_items()`, which creates and return an item based on an inputted playerclass. The function creates a starter item for each non-NPC playerclass in the prefabs (it also includes a condition for basic, but doesn't create an item. This could be filled later.). For NPCs, or classes not found in the prefabs, it should return `NULL`. I also wrote tests for this function for each prefab condition in the `test_class_prefabs.c` file, which contains a helper function, `check_item_presence()`, to reduce duplicate code. The item creation could later be expanded to include more fields, but the function is complete.

2022-05-29 00:20 UTC, wellingtj commented
Van did most of the work for this one. He made and coded all of the prefabs, but I helped come up with some of the ideas, and I also handled documentation

2022-05-30 01:29 UTC, jroven approved these changes
This looks great! I really like the item prefabs and descriptions that you made

2022-05-31 15:45 UTC, lilyehsani requested changes
Very cool addition! One comment.

2022-05-31 15:45 UTC, lilyehsani commented on src/playerclass/src/class_prefabs.c
> +    else {
You should either add items for all the prefabs (including the new NPC ones) or make this clause not error.

2022-05-31 20:00 UTC, vanolson commented on src/playerclass/src/class_prefabs.c
> +    else {
removed the error message, though I'm not fully sure that's what you intended?

2022-05-31 20:19 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-31 20:28 UTC, merged

2022-05-31 21:24 UTC, vanolson commented
In the `class_prefabs` header and C files, I created the `class_prefab_add_items()` function, which has base items for the non-NPC player classes we have prefabricated. Jake Wellington helped me with the ideas for these items, as well as helping to document this new part of the prefab module. The function returns `NULL` for NPCs and classes not found in the prefabs. NPC items could be created as part of a future issue. In addition to creating the items, I also wrote tests for all of them and a helper function for those tests. In responding to feedback, I removed the error message that came along with an unfound class and resolved a merge conflict.

2022-06-07 00:07 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->