Tests to confirm Lua functionality in demo
uchicago-cs/chiventure pull request #1692
Opened 2022-05-28 04:38 UTC by mxu24

Due to the new changes in the demo (integrating dark_room.c and gold.c with demonstration.c) and earlier difficulties implementing Lua functionality with WDL, these additional tests confirms the working status of the demo, particularly after further added functionality and final edits.

2022-05-30 06:26 UTC, jackjackkimkim commented on tests/custom-scripts/test_types.c
> +    object_t *ot4 = obj_t_init(data, INT_TYPE,
This looks good! this confirms our LUA script usage is correct and can take three arguments now. Refer to lost_order demo to see it in action!

2022-05-30 06:28 UTC, jackjackkimkim approved these changes

2022-05-31 21:10 UTC, ecoble requested changes
Please also remove the header files under the tests folder and use the header files from the include directory if you can, I know you had trouble doing this with one of the header files so you can leave that one but please remove the other three.

2022-05-31 21:10 UTC, ecoble commented on tests/custom-scripts/Lua_file/arg_3_lua.lua
> +function foo(arg1, arg2, arg3)
Please clean up this file, you have duplicate sections because the merge conflict was not properly resolved, choose either lunes 3-6 or lines 8-10 and delete the other sections. also delete lines 2, 7, 12

2022-05-31 21:10 UTC, ecoble commented on tests/custom-scripts/Lua_file/int_test_args2.lua
> +<<<<<<< HEAD
Same thing here around resolving the merge conflicts properly

2022-05-31 21:45 UTC, ecoble approved these changes

2022-05-31 21:51 UTC, merged

2022-05-31 21:54 UTC, tatmaca commented
This pull request is now closed! The custom-scripts team realized that our new demos for the end of the Spring Quarter incorporates some new Lua functionality. In order to make sure that this functionality is documented and proven in our codebase, we decided to create new tests. These tests have all passed, cover all new cases, and has been successfully merged!

2022-06-07 01:55 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job writing tests for this module!

<!-- {"score": "excellent", "minor": false} -->