NPC DEMO 2022 !!
uchicago-cs/chiventure pull request #1694
Opened 2022-05-28 04:39 UTC by bvvill

This is the PR for NPC 2022's demo, we have made an in-memory game, located in `src/npc/examples` and creatively named (roasting myself here) `npc_example_2022.c`. We plan to show off our developments with NPC hostility levels, actions between the NPC and player (like trading), and NPC movement.

2022-05-29 23:12 UTC, sglenn-uchi commented on include/npc/dialogue.h
> +    START_BATTLE,
The constants in node_action_type are meant to match up directly to those in npc_actions from npc_action as well as actionmanagement. Putting them here does make their implementation more efficient/streamlined, but maybe making a note that these actions don't align with the framework in npc_action/actionmanagement would help.

2022-05-29 23:17 UTC, sglenn-uchi commented on include/npc/dialogue.h
>  } node_action_type;
I'm also wondering if this should be reformatted 

```C```
`typedef enum node_action_type {
...
} node_action_type_t;`
```C```

for consistency.

2022-05-29 23:19 UTC, sglenn-uchi commented on include/npc/npc.h
> + *  - true if the npc does need moved
Minor typo: should be "does"/"does not need to be moved"

2022-05-29 23:21 UTC, bvvill commented on include/npc/dialogue.h
>  } node_action_type;
if you type ``` twice, on different lines, you can create a code block in between them

2022-05-30 00:19 UTC, sglenn-uchi commented on include/npc/npc_move.h
>   *  mov_type: The tpye of movement that the npc will have
should be "type" of movement

2022-05-30 02:22 UTC, sglenn-uchi commented on include/npc/npc_move.h
> +bool check_if_npc_mov_indefinite_needs_moved(npc_mov_t *npc_mov);
there doesn't seem to be a function comment here

2022-05-30 02:30 UTC, sglenn-uchi commented on tests/npc/test_npc_move.c
> +    npc_mov_t *npc_mov = npc_mov_new(NPC_MOV_INDEFINITE, NPC_MOV_ALLOWED, test_room->room_id, 60);
i noticed that there aren't any tests where NPC_MOVE_NOT_ALLOWED is used. was this intentional? maybe if there were tests for restrict_npc_movement this could be added?

2022-05-30 02:48 UTC, sglenn-uchi commented on src/cli/src/operations.c
> +    if (rc != 0)
What was the point of this switch?

2022-05-30 02:49 UTC, sglenn-uchi commented on src/cli/src/operations.c
> +    if (tokens[1] == NULL)
I didn't really work in CLI this quarter so I'm curious what caused this switch (and the resulting switch on line 684).

2022-05-30 03:00 UTC, sglenn-uchi commented on src/cli/src/operations.c
> +#include "game-state/game_state_common.h"
what from game_state_common.h was used here?

2022-05-30 03:11 UTC, sglenn-uchi commented on src/npc/examples/battle_npc_with_time_example_2022.c
> +char *move_to_arena_operation(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
All this file's function headers are unfinished. I don't think this is the standard for example files so I just wanted to check

2022-05-30 03:12 UTC, sglenn-uchi commented on src/npc/examples/example_2022.wdl
> +        "Mansuetto": {
lolol was mansueto supposed to be misspelled?

2022-05-30 03:14 UTC, sglenn-uchi commented on src/npc/examples/example_2022.wdl
> +            "long_desc": "This is the quad. The Reg is to the North and Crear is to the West.",
Crerar?

2022-05-30 03:19 UTC, sglenn-uchi commented on src/npc/src/npc.c
> +    item_hash_t *head = NULL;
Aren't lines 26-28 doing the same as 23-24 functionally? setting npc->inventory to NULL?

2022-05-30 03:35 UTC, sglenn-uchi commented on src/npc/src/rooms_npc.c
>  }
is this file missing an empty line at the EOF now?

2022-05-30 03:42 UTC, sglenn-uchi commented on tests/game-state/test_rooms.c
> +/* Checks transfer_all_npc_items and related functions */
This test is empty.

2022-05-30 03:51 UTC, sglenn-uchi commented on tests/playerclass/test_class_prefabs.c
> +    check_field_pressence(c);
Very minor but pressense is misspelled– maybe you could just go into the header and correct it to "presence"?

2022-05-30 03:55 UTC, sglenn-uchi commented on CMakeLists.txt
> +find_package(Threads REQUIRED)
I haven't worked with threads in Chiventure so I'm not exactly sure what this is doing. But I trust that you or Lily can verify this!

2022-05-30 04:12 UTC, bvvill commented on tests/npc/test_npc_move.c
> +    npc_mov_t *npc_mov = npc_mov_new(NPC_MOV_INDEFINITE, NPC_MOV_ALLOWED, test_room->room_id, 60);
Oh for sure, and the enum for the opposite of NPC_MOV_ALLOWED is currently NPC_MOV_RESTRICTED, do you think NPC_MOV_NOT_ALLOWED would be better?

2022-05-30 04:16 UTC, bvvill commented on include/npc/dialogue.h
> +    START_BATTLE,
i'm sorry, what's npc_action ?

2022-05-30 05:08 UTC, emilybae1705 commented
One issue I'm currently finding is that when I type a command that isn't included in `char* actions_for_sug[NUM_ACTIONS]` in `src/cli/src/operations.c`, I get a seg fault. I think we should include an error message that says "invalid command. Did you mean ___?" or something like that so we can narrow down the scope of the error.

2022-05-30 05:16 UTC, bvvill commented on src/cli/src/operations.c
> +    if (rc != 0)
I'm pretty sure that I actually made a correction to the existing code, `start_conversation()` changes the value of `rc` based firstly on whether an error occurred (which is checked on line 702), and then it if there are no errors then it is changed to reflect the number of available edges in the conversation, with `rc == 0` confusingly meaning that there are still conversation edges remaining (in which conversation mode should be maintained), and `rc == 1` meaning there are no remaining edges in the conversation, so the game_mode should be set back to `NORMAL`, i think I'm going to change this confusion by changing how the value of `rc` is assigned in `start_conversation()`

2022-05-30 05:25 UTC, bvvill commented on src/cli/src/operations.c
> +    if (tokens[1] == NULL)
so the format of the `TALK` command, the way I understand it to be, is that of (it's all case-insensitized btw) `TALK to *insert_npc_id_here*`, and you would think that `if (tokens[1] == NULL || tokens[2] == NULL)` would be fine, right? nah, immediate seg-fault lol, but it's because before the token-list (aka user-input) makes its way to `talk_operation()`, it goes through a function called `remove_fillers()`, which gets rid of the words 'to', 'the', and 'into' so the only tokens getting passed to `talk_operation()` were "talk" and whatever token[2] originally was, but now it's token[1], and since token[2] was out of range, it was segfaulting

2022-05-30 05:28 UTC, bvvill commented on src/cli/src/operations.c
> +#include "game-state/game_state_common.h"
that's probably something I included as some sort of desperate-debugging measure, because it has pretty much all of the essential libraries and macro definitions in it, but that was def unnecessary, and I'm pretty sure it gets included in the file through one of the other inclusions anyways lol. but yeah i'll delete it

2022-05-30 05:29 UTC, bvvill commented on src/npc/examples/battle_npc_with_time_example_2022.c
> +char *move_to_arena_operation(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
i honestly have no clue, this is getting removed anyways, but i have kind of copied the format of the operation descriptions so i'll keep this open

2022-05-30 05:30 UTC, bvvill commented on src/npc/examples/example_2022.wdl
> +        "Mansuetto": {
lmaoooo no idea, i don't think i wrote that

2022-05-30 05:32 UTC, bvvill commented on src/npc/src/npc.c
> +    item_hash_t *head = NULL;
yes definitely, i think this was the result of a merge (which didn't conflict because they are on different lines)

2022-05-30 05:34 UTC, bvvill commented on src/npc/src/rooms_npc.c
>  }
no actually, although I do see why it looks that way, that's weird lol

2022-05-30 05:37 UTC, bvvill commented on tests/playerclass/test_class_prefabs.c
> +    check_field_pressence(c);
if you look in the rest of the file, the function is actually defined as `check_field_pressence()`. There's another player-class test file that has a function named `check_field_presence()`, and I'm assuming that they were getting some sort of declaration error in this file and decided to change the name of the function, which is used quite often in the file, but somehow missed this one iteration of it, which wasn't allowing me build chiventure.

2022-05-30 05:41 UTC, bvvill commented on CMakeLists.txt
> +find_package(Threads REQUIRED)
so my understanding is that line 18 is basically telling cmake to prefer the `pthread` library whenever it needs to deal with threads, and then line 19 loads the `Threads` package, and because the `THREADS_PREFER_PTHREAD_FLAG` is true, then cmake is going to make sure it has the `pthreads` library

2022-05-30 05:42 UTC, bvvill commented
> One issue I'm currently finding is that when I type a command that isn't included in `char* actions_for_sug[NUM_ACTIONS]` in `src/cli/src/operations.c`, I get a seg fault. I think we should include an error message that says "invalid command. Did you mean ___?" or something like that so we can narrow down the scope of the error. Taking a look at operations.c, `action_error_operation()` seems to support this functionality. We could throw this function in our example file to take care of seg faults.

lemme merge my branch into this one, it's probably fixed

2022-05-30 05:43 UTC, emilybae1705 commented
> > One issue I'm currently finding is that when I type a command that isn't included in `char* actions_for_sug[NUM_ACTIONS]` in `src/cli/src/operations.c`, I get a seg fault. I think we should include an error message that says "invalid command. Did you mean ___?" or something like that so we can narrow down the scope of the error. Taking a look at operations.c, `action_error_operation()` seems to support this functionality. We could throw this function in our example file to take care of seg faults.
> 
> lemme merge my branch into this one, it's probably fixed

Whoops sorry just saw this. I added the `action_error_operation()` function and  fixed the issue. Now we get an invalid command error message instead of a seg fault!

2022-05-30 05:45 UTC, sglenn-uchi commented on include/npc/dialogue.h
> +    START_BATTLE,
Oh my bad, I meant like the module called npc_action. npc_actions is the enum in that module for each of the kinds of actions NPCs can perform. The enums there are supposed to line up with the ones here for when actions are fully integrated into dialogue, or at least that's what Jun and I noticed when we tried integrating the two modules.

2022-05-30 05:46 UTC, sglenn-uchi commented on tests/npc/test_npc_move.c
> +    npc_mov_t *npc_mov = npc_mov_new(NPC_MOV_INDEFINITE, NPC_MOV_ALLOWED, test_room->room_id, 60);
Actually I think NPC_MOV_NOT_ALLOWED would be clearer, since restricted implies limited movement but not preventing movement completely? Whereas "NOT_ALLOWED" is very clearly preventing any kind of movement.

2022-05-30 05:48 UTC, sglenn-uchi commented on CMakeLists.txt
> +find_package(Threads REQUIRED)
Ohhhh, I see. That's cool how threads ended up getting involved in the code!

2022-05-30 05:54 UTC, sglenn-uchi commented on src/npc/examples/npc_example_2022.c
> +    //add_node(c, "3", "Wilma: ");
I'm not sure if you meant to delete this. Was wondering if maybe you were going to come back to it and add more things for Wilma to say?

2022-05-30 05:55 UTC, sglenn-uchi commented on src/npc/examples/npc_example_2022.c
> +<<<<<<< HEAD
I think this line is leftover from fixing the merge conflict

2022-05-30 06:02 UTC, sglenn-uchi requested changes
Almost there– there's an error when building tests because of the leftover "<<<< HEAD" from the merge conflict fixing and the undefined variable. But once those are addressed as well as the minor comments are made, I think this PR will be ready to go.

2022-05-30 06:04 UTC, sglenn-uchi commented on src/npc/examples/npc_example_2022.c
> +        sprintf(str, "Error! We need a loaded room to attack.");
Oh I think the other error preventing the tests from building might also result from fixing the merging conflict? The malloc statement defining str is missing.

2022-05-30 06:44 UTC, bvvill commented on src/npc/examples/npc_example_2022.c
> +    //add_node(c, "3", "Wilma: ");
yee i am

2022-05-30 17:02 UTC, bvvill commented on tests/npc/test_npc_move.c
> +    npc_mov_t *npc_mov = npc_mov_new(NPC_MOV_INDEFINITE, NPC_MOV_ALLOWED, test_room->room_id, 60);
I agree , thx for the suggestion !

2022-05-31 01:42 UTC, bvvill commented on include/npc/dialogue.h
> +    START_BATTLE,
i don't see an npc_actions module or an npc_actions enum

2022-05-31 05:21 UTC, lilyehsani requested changes
Looks really good so far! I love how creative you guys were with this. I added a few comments, and since this include tones, we should get that merged first.

2022-05-31 05:21 UTC, lilyehsani commented on src/cli/src/operations.c
> +    if (tokens[1] == NULL)
great catch

2022-05-31 05:21 UTC, lilyehsani commented on src/npc/examples/battle_npc_with_time_example_2022.c
> +    /* if (lobby->npcs->num_of_npcs > 0)
Delete or uncomment

2022-05-31 05:21 UTC, lilyehsani commented on src/npc/examples/battle_npc_with_time_example_2022.c
> +        move_indefinite_npcs_if_needed(g->all_npcs, g->all_rooms);
This is extremely cool

2022-05-31 05:21 UTC, lilyehsani commented on src/cli/src/operations.c
> +            "NPC"};
Why are we including NPC here if we also monkey-patch it into the examples?

2022-05-31 05:41 UTC, bvvill commented on src/npc/examples/battle_npc_with_time_example_2022.c
> +        move_indefinite_npcs_if_needed(g->all_npcs, g->all_rooms);
thank u !

2022-05-31 05:42 UTC, bvvill commented on src/npc/examples/battle_npc_with_time_example_2022.c
> +    /* if (lobby->npcs->num_of_npcs > 0)
whoops, thx !!

2022-05-31 05:45 UTC, bvvill commented on src/cli/src/operations.c
> +            "NPC"};
I feel like it was needed for some reason , but I don't remember , it might've just been an attempt at finding a way to not need to monkey-patch it , which I've just now put in the effort of figuring out (idk how i didn't before) lol , thank u !

2022-05-31 05:47 UTC, bvvill commented
> Looks really good so far! I love how creative you guys were with this. I added a few comments, and since this include tones, we should get that merged first.

i don't think tones is included in this branch?

2022-05-31 12:14 UTC, sglenn-uchi commented on include/npc/dialogue.h
> +    START_BATTLE,
ohhh you know what, npc_actions.h/c were removed when Jun and I transitioned over to working on the actionmanagement.h.c files. so i think this is fine for now!

2022-05-31 12:17 UTC, sglenn-uchi approved these changes
Other than the things Lily mentioned in her review, I think this PR is good to go. So I'll approve it for now. Great job everyone! You all worked really hard on this demo, and I think that'll show at the presentations tomorrow.

2022-05-31 15:26 UTC, lilyehsani commented on src/cli/src/operations.c
> +            "NPC"};
Could you remove it if it is not necessary?

2022-05-31 19:26 UTC, bvvill commented on src/cli/src/operations.c
> +            "NPCS"};
"NPCS" is the command to trigger the `npcs_in_room_operation`, the entry to the lookup table is in cmd.c, line 133 i believe

2022-05-31 19:27 UTC, bvvill commented on src/cli/src/operations.c
> +            "NPCS"};
and on line 20 here i incremented the `NUM_ACTIONS` macro

2022-05-31 19:37 UTC, bvvill commented on src/cli/src/operations.c
> +        through_item = NULL;
part of the `path_t` struct is `item_t *through`, which is meant to be an item that the player must possess in order for them to be able to use the path, but there wasn't (or at least I didn't come across) any implementation that enforced this condition. To fix this, I added a condition to the `if` statement (which controls whether or not a the player can go in a certain direction) here (lines 375-377) that says either the path must not have an `item_t *through` member (aka `NULL`) or the player must possess the `item_t *through` in their inventory (`item_in_inventory()` returns `true` or `false`).

2022-05-31 19:39 UTC, bvvill commented on src/cli/src/operations.c
> +
before, if you typed `ITEMS`, it would print `"These are the items in the room"` regardless of whether there are actually any items present in the room, this is just an extra statement for when there aren't any items in the room

2022-05-31 19:45 UTC, bvvill commented on src/cli/src/operations.c
> +            }
starting from line 585: if the NPC's hostility level isn't friendly (which currently has the consequence that it is possible to kill them), and the NPC's hp is 0 (meaning they are indeed dead, this hp comes from the `npc_battle_t` struct, which if uninitialized, `get_npc_hp()` will return -1, not 0, so those NPCs wouldn't be dead based on this condition), then it'll print out the NPC's name surrounded by those little crosses you see, indicating that they are dead/have been defeated; otherwise, an NPC's name will just be printed normally.

2022-05-31 19:49 UTC, bvvill commented on src/cli/src/operations.c
>      case_insensitize(tokens[2]);
before, this would immediately segfault if the user just typed `NAME` or `NAME (insert token here)` because that would mean `tokens[1] && tokens[2]` or just `tokens[2]` would be nonexistent/`NULL` and there was no check for that before passing both of those tokens onto `case_insensitize()`, so I added the check.

2022-05-31 19:50 UTC, bvvill commented on src/cli/src/operations.c
> +    npc_t *npc = get_npc_in_room(ctx->game->curr_room, tokens[1]);
Piggybacking on the resolved conversation in regarding line 685, `tokens[1]` holds the input npc_id, not `tokens[2]` (which is supposed to be non-existent)

2022-05-31 19:51 UTC, bvvill commented on src/cli/src/operations.c
> +    }
this is just to make sure the player can't start a conversation with a dead NPC

2022-05-31 19:53 UTC, bvvill commented on src/cli/src/operations.c
> +    npc_t *npc = get_npc_in_room(ctx->game->curr_room, npc_id);
i wanted to make sure the input token was case_insensitized before being passed on to `get_npc_in_room()`, but I also didn't want to directly `case_insensitize()` the token itself

2022-05-31 19:56 UTC, bvvill commented on src/game-state/src/game.c
> +        item_free(current_item);
The previous implementation of this function was just unnecessarily complicated and I wasn't sure that it was functioning correctly because of it.

2022-05-31 19:58 UTC, bvvill commented on src/game-state/src/path.c
> +#include "game-state/path.h"
idek how this worked before without this statement

2022-05-31 20:18 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-31 20:18 UTC, merged

2022-06-07 00:14 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work! Like issues, PRs should have closing statements.

<!-- {"score": "excellent", "minor": false} -->