Playerclass: Create 2022 demo
uchicago-cs/chiventure pull request #1698
Opened 2022-05-28 04:46 UTC by vanolson

Jake, Katie, and I have created the 2022 demo. It was based in part on last year's demo, since we are displaying prefab classes and multiclasses (this time with prefabs). I added a function to display the details of our prefab skill trees, which we use for both the regular prefabs and multiclass prefabs. Katie created the new multiclass files and contributed to the helper functions, and wrote the multiclass_prefabs.h file. Jake did the bulk of the multiclass_prefabs.c file as he previously worked heavily on the multiclass module. Overall, this allows us to display the prefab skill trees we created this quarter, as well as our work on the multiclass module and new multiclass prefabs.

2022-05-30 21:33 UTC, Vincent-Zhang4135 requested changes
Great Job! After reviewing through all the files, I just had some styling suggestions (comments styling, function comments, etc.), and so I have decided to request for these small changes before moving onto to approving.

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on include/playerclass/class_prefabs.h
> +//see class_prefabs.c for more information
I appreciate the comment here. It definitely helped me understand the purpose of including it here as just for integrating with multiclass_prefabs. However, I think you can change the styling to use 


/*
 *
 */

instead

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on include/playerclass/multiclass_prefabs.h
> +#endif /* MULTICLASS_PREFABS_H */
Phenomenal documentation of function functionality

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +
This function is very well structure. and is super self explanatory so great job! I guess to nitpick, you had a block comment for skills and names, which I don't think is entirely is necessary, but if you want to stay consistent, i think i could also add one for Description, Type, and (and then possible minimum XP/maximum levle)

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +/* A helper function for printing a class. */
Same thing here! (Even if it seems unnecessary since it is literally taking in one parameter and not returning anything, I think it is still important important to follow the guide on commenting functions, so including the parameters, the expected return (nothing), and notes if there are any notes to consider )

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +/* A helper function for printing a skilltree. */
Even if it seems unnecessary since it is literally taking in one parameter and not returning anything, I think it is still important important to follow the guide on commenting functions, so including the parameters, the expected return (nothing), and notes if there are any notes to consider

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +#define CLASSES_WDL_PATH "../tests/wdl/examples/wdl/classes.wdl"
I think it would be conventional to keep globally definite variables on the top of the file, even if you are using it way later in the file

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +    // Create the zip
small nitpicking, but i think the comment should be moved inline if you do //. or if it is a block on its own line, be sure to following C styling guidelines of using /* */!

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +    // Add DEFAULT.json to the zip
same thing here! (small nitpicking, but i think the comment should be moved inline if you do //. or if it is a block on its own line, be sure to following C styling guidelines of using /* */!)

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +    // Write and save to disk
(same thing here)

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/2022-demo.c
> +    // Read the zip into an obj
and here haha

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/examples/CMakeLists.txt
> +set(PLAYERCLASS_EXAMPLES pc_demo 2021-demo 2022-demo)
i am a little confused as I do not know what set does, but is there a reason why we set PLAYERCLASS EXAMPLES to both 2021-demo and 2022-demo? Instead of replacing 2021-demo with 2022-demo?

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/src/multiclass_prefabs.c
> + * Skills are in a weird place right now: The skill trees team is interested in
I appreciate this comment, as it will inform futures devs of where we can further improve skill trees integration

2022-05-30 21:33 UTC, Vincent-Zhang4135 commented on src/playerclass/src/multiclass_prefabs.c
> +}
This file in particular was really well written, understanding what each function does was really streamlined due to good comments and documentation.

2022-05-30 21:41 UTC, vanolson commented on src/playerclass/examples/2022-demo.c
> +
Adding comments for the rest of them

2022-05-30 21:48 UTC, vanolson commented on src/playerclass/examples/CMakeLists.txt
> +set(PLAYERCLASS_EXAMPLES pc_demo 2021-demo 2022-demo)
I suppose we could have deleted them, but the team last year kept in the 2020 demo (pc_demo) so we decided to just add ours rather than delete theirs. It still generates the old files I think, which isn't super necessary, but was helpful for us in drawing from last year's demo.

2022-05-30 22:08 UTC, Vincent-Zhang4135 approved these changes
LGTM! The styling is more consistent with the actual style guide, and I will be passing this onto Lily for a final approval now! Good job to everyone involved creating a great PR

2022-05-31 05:33 UTC, lilyehsani requested changes
Looking good! Just a couple of comments.

2022-05-31 05:33 UTC, lilyehsani commented on src/playerclass/examples/2022-demo.c
> +static obj_t *get_doc_obj()
Why do we need this function? I don't see it called anywhere.

2022-05-31 05:33 UTC, lilyehsani commented on src/playerclass/examples/2022-demo.c
> +/* Due to having to locate the example WDL file, it is critical that this executable
What WDL file is being used? I don't see one in this PR.

2022-05-31 19:08 UTC, lilyehsani approved these changes
LGTM! Approved.

2022-05-31 19:15 UTC, merged

2022-05-31 21:29 UTC, vanolson commented
Jake, Katie, and I created the 2022 demo. I created a function to display skilltrees and relevant information on their skills. Katie created the `multiclass_prefabs` header and C files, wrote `multiclass_prefabs.h` and added to the helper functions in the module. Jake wrote most of the `multiclass_prefabs.c` file, which expanded in part on `class_prefabs.c`. Vincent suggested a number of mainly style changes in his review, which I fixed.  In addition, Lily noticed old code that was still in the demo module, which I removed. The demo is now merged and ready to be used.

2022-06-07 00:17 UTC, lilyehsani commented
Issue Score: Excellent

Comments:
Great work on this PR!

<!-- {"score": "excellent", "minor": false} -->