1593 create a demo for the action management team
uchicago-cs/chiventure pull request #1704
Opened 2022-05-28 04:56 UTC by HarrisonD123

For our Spring 2022 demo, we will want to above all showcase the work we've done in implementing our new 4th action kind and all the functionality we've implemented around it. This will mean we will want to create a monkeypatched demo .c file in our action_management/examples directory and manually assign values to the structs contained in the game struct.

For this demo, we will want to show the functionality of view stats, view skilltree, view quests, and view inventory. In order to do this, we will need to manually assign items to each associated struct in our demo .c file. We will also want to show off some of the other functionality we've implemented, such as inventory conditionals and teleportation.

2022-05-28 20:13 UTC, Don-Osipov commented on include/action_management/actionmanagement.h
> +                  char **target, char **ret_string);
This change is already implemented in PR #1675

2022-05-28 20:17 UTC, Don-Osipov commented on src/action_management/src/actionmanagement.c
> +                   char **target, char **ret_string)
These changes are also implemented in PR #1675

2022-05-28 20:18 UTC, Don-Osipov commented on src/action_management/examples/sprint2022-demo.c
> +#include <stdio.h>
What is the difference between this sprint2022-demo and the spring2022-demo? Perhaps change the names to make it more clear or delete the duplicate

2022-05-28 20:20 UTC, Don-Osipov reviewed
The demo looks great! Maybe add some documentation on what features will be shown off in the demo code. There are also 2 added demo files, and the difference between them is unclear - either clarify the names or delete the duplicate. There are also some changes in actionmanagement.c/h that are already implemented in other PRs and could lead to merge errors.

2022-05-30 14:10 UTC, ecoble requested changes
This looks really great overall! One small change on the CMakeLists, as well as addressing Don's comments about the duplicated changes.

2022-05-30 14:10 UTC, ecoble commented on src/action_management/examples/CMakeLists.txt
> +set(ACTION_MANAGEMENT_EXAMPLES spring2022-demo)
Instead of removing the spring 2021 demo from the CMakeLists, can you just add your executable? That way both will be built during the build.

2022-05-31 15:01 UTC, HarrisonD123 commented on src/action_management/examples/sprint2022-demo.c
> +#include <stdio.h>
Thanks for pointing this out! I've just deleted sprint2022-demo. It was created accidentally.

2022-05-31 15:03 UTC, HarrisonD123 commented on src/action_management/examples/CMakeLists.txt
> +set(ACTION_MANAGEMENT_EXAMPLES spring2022-demo)
This has been changed!

2022-05-31 18:23 UTC, ecoble approved these changes
Nice job!

2022-05-31 20:05 UTC, Don-Osipov approved these changes
Everything looks fixed!

2022-05-31 20:54 UTC, merged

2022-05-31 21:08 UTC, jbrouwer5 commented
**Closing Statement**

We implemented a 2022 demo showcasing many of the new actions from this quarter. This demo allows us to show off the category of view actions, such as view skills, view quests, view task, and view inventory. We also include the newly implemented feature of conditional item taking depending on whether or not another item is already in your inventory. The demo has multiple rooms throughout crerar, such as 390 and Borja's office, in which you can move and interact with objects. For example, there is a rolex which you cannot pick up until you pick up soap, and then a trophy which you cannot pick up until you pick up the rolex. This demo is now merged and we are closing this request and issue.

2022-06-07 00:59 UTC, ecoble commented
Issue Score: Excellent

Comments:
Great job on a fantastic demo! And great job reviewing this PR as well!

<!-- {"score": "excellent", "minor": false} -->