Graphics Inventory #3 Pull Request
uchicago-cs/chiventure pull request #1706
Opened 2022-05-28 04:58 UTC by imadejski

RunInventoryGraphics function created along with test_inventory_graphics file created to test new init frees. Makefile also created.

2022-05-28 04:59 UTC, dhirpalshah approved these changes
awesome! eyeball tests are nice.

2022-05-30 01:55 UTC, philipchenaux requested changes
A few stylistic comments that must be addressed.

2022-05-30 01:55 UTC, philipchenaux commented on graphics_sandbox/inventory_graphics/test_inventory_graphics.c
> +*/
Is there a reason why all the above tests are commented out?

2022-05-30 01:55 UTC, philipchenaux commented on graphics_sandbox/inventory_graphics/test_inventory_graphics.c
> +Test(slot, new)
Please add comments describing what you are testing.

2022-05-30 16:43 UTC, ukanyanwu commented on graphics_sandbox/inventory_graphics/test_inventory_graphics.c
> +*/
These were going to supplement player_inventory tests, but were temporarily commented out. These are now uncommented, and the player_inventory new/init/free tests area also re-added.

2022-05-30 16:44 UTC, ukanyanwu commented on graphics_sandbox/inventory_graphics/test_inventory_graphics.c
> +Test(slot, new)
Comments have been added to the slot tests, along with the player_inventory tests that were re-added.

2022-05-31 10:54 UTC, philipchenaux approved these changes
Looks good to merge, well done!

2022-05-31 10:55 UTC, merged

2022-06-05 10:21 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Great work, but please make sure that you do a thorough code review and, in the future, make sure to look out for the kind of issues the senior developer pointed out.

<!-- {"score": "excellent", "minor": false} -->