Updated: Game autogeneration helpers, game autogeneration function, and tests
uchicago-cs/chiventure pull request #1709
Opened 2022-05-30 18:35 UTC by williamhu314

In this pull request, we have completed everything we completed in #1681 and have fixed all merge conflict issues and unintentional changes to other files in chiventure. We also fixed a few more bugs we spotted that did not cause an error in the original PR but caused errors in this branch.

2022-05-30 19:35 UTC, helenastc reviewed
The functions look good but more tests would be good. Also more descriptive comments for the tests would be helpful!

2022-05-30 21:22 UTC, williamhu314 commented
Thanks for the comments! I have made more tests for the following functions:

1. roomspec_correlation (in gen_structs)
2. pick_random_direction (in autogenerate)
3. room_exists_in_direction (in autogenerate)
4. find_room_in_direction (in autogenerate)

I have also added comments/descriptions to all tests.

2022-05-30 22:09 UTC, helenastc approved these changes
Looks good! Good job addressing comments

2022-05-31 10:48 UTC, philipchenaux requested changes
Lots of commented out code portion that need to be addressed, but besides that it looks very good!

2022-05-31 10:48 UTC, philipchenaux commented on tests/openworld/test_autogenerate.c
> +}*/
Try to avoid large blocks of commented out code like that of above unless there is a specific reason for this.

2022-05-31 10:48 UTC, philipchenaux commented on tests/openworld/test_autogenerate.c
> +}*/
Especially if this ode is no longer relevant to your code.

2022-05-31 10:48 UTC, philipchenaux commented on tests/openworld/test_autogenerate.c
>  }*/
The same applies to this code above, if the large portion of commented out code is not relevant then you can delete it.

2022-05-31 13:09 UTC, williamhu314 commented
I have removed all commented out tests and functions that are no longer relevant.

2022-05-31 15:09 UTC, philipchenaux approved these changes
Looks good to merge!

2022-05-31 15:09 UTC, merged

2022-06-05 10:23 UTC, philipchenaux commented
Issue Score: Excellent

Comments:
Great work! My only comment is that: When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review. Make sure that, when you create a PR, the code is ready for review and passes all the tests.

<!-- {"score": "excellent", "minor": false} -->