Libobj 3.0 and JSON to obj_t
uchicago-cs/chiventure pull request #814
Opened 2021-03-19 22:33 UTC by dwahme

Related to #813

This PR contains code for Libobj 3.0 and a way to load JSON into an obj_t struct.

Changes:
- Added a sample WDZ-format game at `games/test_game`
- Revamped libobj for version 3.0:
    - Added a LIST datatype for doubly-linked lists
    - Added an OBJ datatype (to differentiate from the NONE type)
    - Refactoring of the obj struct for how children were held and added utlist doubly-linked list support
    - Bug fixes for libobj
    - Removed unnecessary functions from libobj
    - Added tests for libobj
- Refactored a bit of the wdl module:
    - Updated some code for libobj 3.0 behavior
    - Updated tests for compatibility with libobj 3.0
    - Updated some object iteration behavior to use utlist and uthash macros for safety
- Added a way to load JSON into an obj_t along with tests

2021-03-25 23:41 UTC, borjasotomayor requested changes
This looks good overall. A few overarching comments:

- load_json.h should be renamed to load.h. I think it's ok for the implementation to have different load_* modules (since there will be separate code for loading from a ZIP file, etc.) but, from the user's perspective, it makes more sense to think of there being a single "load.h" header with all the functions for loading from disk.
- Do parser.h and stack.h actually have to be public header files? They seem internal to libobj so, if they're not used anywhere else, they should be moved to `src/libobj/include`
- The examples in `src/libobj/examples` will need to be updated at some point, but that doesn't have to be part of this PR.

2021-03-25 23:41 UTC, borjasotomayor commented on include/libobj/load_json.h
> +int _load_obj_json(obj_t *parent, struct json_object *json);
The correct way of exposing this function is to add a header file in `src/libobj/include` and then include that from the tests. You can see an example of this here: https://github.com/uchicago-cs/chiventure/blob/dev/tests/custom-actions/CMakeLists.txt#L17

2021-03-25 23:41 UTC, borjasotomayor commented on include/libobj/obj.h
>      UT_hash_handle hh;
The more correct way of writing this union would be like this:

```
    union
    {
        bool b;
        char c;
        int  i;
        char *s;
        struct {
            struct obj *attr;
            UT_hash_handle hh;
        } obj;
        struct {
            struct obj *head;
            struct obj *next;
            struct obj *prev;
       } lst;
    } data;    
```

This way, the `data` union contains all the information associated with each type. Making this change would require using the utlist and uthash macros for structs with non-default next/prev and hh fields. If making this change is easy, we should do it now. If not, it doesn't have to block this PR, but it has to be changed at some point.

2021-03-26 04:04 UTC, dwahme commented on include/libobj/load_json.h
> +int _load_obj_json(obj_t *parent, struct json_object *json);
Done

2021-03-26 04:13 UTC, dwahme commented on include/libobj/obj.h
>      UT_hash_handle hh;
Regarding the hh change: Unless I'm misunderstanding the uthash library, I think that the hh field needs to be present in all objects, as the child nodes need to have hh (instead of the parents).

Regarding the next/prev fields: I played around with it for a bit but I didn't see a clean and easy way to shift over to nesting them in the `data` union. I think it might be better to hold off on making the change now.

2021-03-26 04:23 UTC, dwahme commented
- The requested load* changes have been made.
- WDL still depends on parser.h and stack.h. I think it might be better to not touch these for now, and then when we're reworking some of WDL for the new libobj/wdz parsing, we can go in and clean those up.
- I did a quick touchup of the obj example to reflect the new changes

2021-03-26 13:30 UTC, borjasotomayor commented on include/libobj/obj.h
>      UT_hash_handle hh;
Sounds good, let's make this change later. That said, could we change the union to something like this?
```
    union
    {
        bool b;
        char c;
        int  i;
        char *s;
        struct {
            struct obj *attr;
        } obj;
        struct obj *lst;
    } data;    
```

That makes it clearer that "there is an object type of data, and that type has one piece of information: its attributes". This also future-proofs this a bit, in case we end up having to associate more information with an object type.

2021-03-26 13:34 UTC, borjasotomayor commented
The changes look good to me, and I agree that we can defer moving parser.h and stack.h until we rework the WDL code. I have just one more requested change (see my comment about the `data` union)

2021-03-26 20:40 UTC, dwahme commented on include/libobj/obj.h
>      UT_hash_handle hh;
I think that this is a good solution. Done

2021-03-26 20:40 UTC, dwahme commented
Data change comment addressed, this should be ready for re-review

2021-03-26 23:47 UTC, borjasotomayor approved these changes

2021-03-26 23:47 UTC, merged