Integrating Skill Trees into Playerclass
uchicago-cs/chiventure pull request #833
Opened 2021-04-24 19:50 UTC by jackcasey067

(Closes #817, Closes #571)
This is connected to my issue (#817), which intends to finish the work of one of last year's issues (#571).  As a result, many of the changes below are not my own.  The goal of both issues was to integrate skill trees into the player class components, even if it is just at a basic level for now.

Overview of changes:
- Replaced the stub skill-tree struct with the actual skill-tree struct.
- Adjusted code that allocates and frees classes to work with skill-trees.
- Added files (class_skill.c and .h) that serve to initialize skill and skill-tree structs.
- Added a rudimentary id system for classes so that we can safely generate tree ids without clashes.

2021-04-24 23:59 UTC, farm-zaq approved these changes
Looks good. All changes I wanted seem to be to include things not yet implemented. Good work!

2021-04-26 19:14 UTC, firatciftci requested changes
I have added some minor changes and directed some questions in terms of the overall design of this subcomponent. Once these are resolved, we can continue on with the merge.

2021-04-26 19:25 UTC, jackcasey067 commented on src/playerclass/src/class.c
> +// Default Classes in alphabetical order.
Fixed.

2021-04-26 19:25 UTC, jackcasey067 commented on src/playerclass/src/class.c
> +// Number of predefined default classes (see above).
Also fixed.

2021-04-26 19:37 UTC, jackcasey067 commented on include/playerclass/class_structs.h
> +#define MAX_SKILLS_IN_TREE (5)
I agree that having MAX_SKILLS_IN_TREE is unnecessary, but I don't know how to change `MAX_ACTIVE_SKILLS` and `MAX_PASSIVE_SKILLS` to be dynamic.  Should I add parameters to `class_new()`, if it is used in ~50 places already, some of which are in other teams' files?

2021-04-26 21:13 UTC, jackcasey067 commented on src/playerclass/src/class.c
> +    }
My most recent commit changes this, along with the stuff above on MAX_SKILLS_IN_TREE and the other constant.  I am going to make some more changes, then I'll request a review.
(I already mistakenly requested one, but that has been deleted)

2021-04-26 21:31 UTC, jackcasey067 commented on src/playerclass/src/class_skills.c
> +    return SUCCESS;
While I didn't make a new function, I did merge all of the functionality in the already existing (but now renamed, for other reasons) `class_add_skills`.  Also, since you can't do a switch statement with strings, the if-else ladder stays (unfortunately).

2021-04-26 21:32 UTC, jackcasey067 commented on src/playerclass/src/class_skills.c
> +        init_success = get_default_wizard(class);
The if-else ladder has to stay, to my dismay.  I did switch over to `strncmp()` though.

2021-04-27 19:32 UTC, firatciftci approved these changes
Everything looks good to me, great work!

2021-04-27 19:32 UTC, merged

2021-04-27 19:47 UTC, jackcasey067 commented
Closing statement: 
After some restructuring of the code, the pull request was merged; the skill-tree and player-class features are now integrated.

2021-05-04 05:42 UTC, firatciftci commented
Issue Score: ✔️+

Comments:
Good work overall! The only feedback I have is that, for future pull requests, you should include a final comment summarizing what was included in the PR after it gets merged into `dev`.

<!-- {"score": "check-plus"} -->

2021-05-04 05:43 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great job!

<!-- {"score": "check-plus-plus"} -->