Implementing validation of number of objects in command
uchicago-cs/chiventure pull request #844
Opened 2021-04-26 02:16 UTC by dchen0258

In relation with issue #357 . Implementing validation of number of objects in command. All changes made in src/operations.c For kind1 and 2 actions, checks to make sure there is not a third token in the array, which would indicate a presence of an extra object in the command.

2021-04-28 20:49 UTC, ecoble requested changes
Looks great! I have one very small change to request. Additionally, this branch will need to be updated since another team has merged into dev. You can do this within you project using git, but you can also do this on Github with the "Update branch" button at the bottom of the pull request screen.

2021-04-28 20:49 UTC, ecoble commented on src/cli/src/operations.c
> +        return "Sorry, You can only go one direction \n";
Nit: "You" should be all lower case

2021-04-28 21:15 UTC, dchen0258 commented on src/cli/src/operations.c
> +        return "Sorry, You can only go one direction \n";
Problem should be fixed now!

2021-04-30 01:00 UTC, ecoble approved these changes
LGTM!

2021-04-30 22:59 UTC, mjgoodman321 approved these changes

2021-05-03 17:19 UTC, merged

2021-05-14 18:21 UTC, ecoble commented
Issue Score: ✔️+

Comments:
Great job on this backlog issue! Just like issues, pull requests should also have closing statements. Also, be sure to keep the milestone up to date when it rolls over into the next sprint.

<!-- {"score": "check-plus"} -->