Action management/attribute list
uchicago-cs/chiventure pull request #846
Opened 2021-04-26 17:08 UTC by jasulcaf

(Closes #624)
This is connected to @LapsededPacifist and my Issue (#624) which set out to create a linked list struct that could contain multiple attributes alongside functions to manipulate said list. The eventual goal for this functionality would be related to Issue(#615) for the eventual goal of having multiple restrictions placed on one item. 

We discovered that there already existed a struct for this `attribute_list_t` as well as an associated delete function called `delete_attribute_llist`. As such, below are the changes we implemented.

Overview of Changes: 
- Implement `create_list_attribute`, to return an empty list of attributes that can be manipulated.
- Implement `list_contains_attribute`, which checks a list to see if a given attribute is found.
- Implement `add_attribute_to_list` and `remove_attribute_from_list` to add or remove an attribute to a list.

2021-04-27 20:20 UTC, WPDolan requested changes
Looks good! My only suggestion is to include a few lines in `create_list_attribute` to handle cases where mallocing rv returns NULL (when memory is full) to prevent segfaults when setting `rv->attribute` and `rv->next`

2021-04-27 20:42 UTC, WPDolan approved these changes
Everything looks good!

2021-04-28 02:22 UTC, afranzese99 commented on src/game-state/src/item.c
> +            LL_DELETE(head, tmp);
Does the LL_DELETE free the attribute that is being removed?

2021-04-28 14:26 UTC, MaxineK36 commented on src/game-state/src/item.c
> +            LL_DELETE(head, tmp);
@afranzese99 @LapsededPacifist Nope, it does not! See here for more details about utlist, and some example use cases that illustrate that you want to call `LL_DELETE` and *then* `free`: https://troydhanson.github.io/uthash/utlist.html#_using_utlist

2021-04-28 14:58 UTC, afranzese99 approved these changes
After the addition of freeing the element that was being deleted from the linked list everything looks good.

2021-04-28 21:23 UTC, MaxineK36 requested changes
A couple of individual things to change, but the general design is great!

2021-04-28 21:23 UTC, MaxineK36 commented on include/game-state/item.h
> +int list_contains_attribute(attribute_list_t *head, char *attr_name);
`SUCCESS` and `FAILURE` are status codes; since this is explicitly checking whether or not an attribute is contained in the list (essentially answering a yes/no question) it should return a boolean value

2021-04-28 21:23 UTC, MaxineK36 commented on include/game-state/item.h
> + *  FAILURE if it failed to add the attribute, SUCCESS if it add/the list contains the attribute
nit: *adds

2021-04-28 21:23 UTC, MaxineK36 commented on src/game-state/src/item.c
> +    if(rv == NULL)
nit: put a space after `if` (below as well)

2021-04-28 21:23 UTC, MaxineK36 commented on src/game-state/src/item.c
> +int list_contains_attribute(attribute_list_t *head, char* attr_name)
This will become `bool`

2021-04-28 21:23 UTC, MaxineK36 commented on src/game-state/src/item.c
> +    attribute_list_t *tmp = head->next;
You should be able to do this using the built-in `LL_SEARCH` function for utlist: see an example here https://github.com/uchicago-cs/chiventure/blob/e9d9e8e66977a5a76a358abd83a300bba6d65dbc/src/game-state/src/game_action.c#L174

2021-04-28 21:23 UTC, MaxineK36 commented on src/game-state/src/item.c
> +    if(list_contains_attribute(head, attr->attribute_key) == SUCCESS)
this if statement should happen before you call `create_list_attribute`

2021-04-28 21:23 UTC, MaxineK36 commented on src/game-state/src/item.c
> +    while(tmp != NULL)
You should use LL_SEARCH here as well

2021-04-29 13:52 UTC, MaxineK36 commented on src/game-state/src/item.c
> +    if (list_contains_attribute(head, attr->attribute_key) == true)
nit : you don't need the `== true`

2021-04-29 13:53 UTC, MaxineK36 approved these changes
One tiny nit, otherwise looks great!

2021-04-29 15:13 UTC, merged

2021-04-30 05:00 UTC, jasulcaf commented
Summary:
create_list_attribute() will output an attribute linked list that can be manipulated by the following functions:
- add_attribute_to_list: Add an attribute to list
- remove_attribute_from_list: Remove an attribute (if it exists) from list 
- list_contains_attribute: Returns Boolean (for ease of utility for users) if an attribute is found in a list or not
- delete_attribute_llist: Free entire list

Additional note about an attribute_list_t: There exists the usage of an initial dummy node in the implementation of an attribute_list_t. While this is not something that will have to be known by users (function calls to add, remove, delete an entire list, or check if list_contains_attribute is true, do _not_ have to know this information i.e. users can simply pass entire list as a function call argument), if future updates are done on the implementation of the above mentioned functions, this should be kept in mind.

2021-05-01 19:00 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! This is an excellent example of a well-described PR with helpful reviews and a great closing statement that summarizes the work completed.

<!-- {"score": "check-plus-plus"} -->