Action management/player free
uchicago-cs/chiventure pull request #866
Opened 2021-04-27 01:25 UTC by LapsededPacifist

Added free(plyr) call to player_free() and fixed errors in test_item_item_actions.c
Errors in tests:
    Test case 7 called twice and test case 8 uncalled
    Freed the items manually before freeing them from the players inventory.
Connected to [issue #785](https://github.com/uchicago-cs/chiventure/issues/785).

2021-04-27 20:40 UTC, WPDolan approved these changes
Changes achieve their goal and tests still pass.

2021-04-28 01:55 UTC, afranzese99 approved these changes
All of the  goals are met. The code builds successfully and passes all of the tests. Any unclear code is documented well, which makes the changes more understandable. Great job!

2021-04-28 14:23 UTC, MaxineK36 requested changes
Looks awesome! One tiny change, then you should be good to go!

2021-04-28 14:23 UTC, MaxineK36 commented on tests/action_management/test_item_item_actions.c
> +    if(choose_condition <= 4){
The `4` and `8` here should be variables; right now, in the code without context, they're what we call "magic numbers". If there's an existing enum for them, please use that, otherwise please make variables for each and then use the variable in the if statement, not the number.

2021-04-28 14:23 UTC, MaxineK36 commented on tests/action_management/test_item_item_actions.c
> +     * free them in this case */
Nit: add a space after `if` on line 191 (`if (choose_condition...`)

2021-04-28 16:44 UTC, MaxineK36 approved these changes
Looks great!

2021-04-28 16:45 UTC, merged

2021-06-03 18:21 UTC, MaxineK36 commented
Issue Score: ✔️+

Comments:
Good work! In general, please also make sure that all PRs have a closing statement to summarize the work that was done, and that they're labeled with the appropriate milestone.

<!-- {"score": "check-plus"} -->