Openworld/level oriented gen
uchicago-cs/chiventure pull request #896
Opened 2021-05-02 01:25 UTC by Justin08784

Implemented multi_rooms_level_generate, which generates a map filled with only rooms whose difficulty level corresponds to player level.

2021-05-03 14:14 UTC, ahmed-sumaiya approved these changes

2021-05-03 14:29 UTC, ahmed-sumaiya approved these changes

2021-05-03 15:45 UTC, ahmed-sumaiya approved these changes

2021-05-03 22:43 UTC, MaxineK36 requested changes
A couple of small fixes, but looks awesome overall!

2021-05-03 22:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        if (player_level < level_scale->thresholds[i]) {
Since this ends up being a little computation-y, you should add a comment explaining what's happening and why

2021-05-03 22:43 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +            return 1;
what do these return codes mean?

2021-05-03 22:43 UTC, MaxineK36 commented on src/openworld/src/gen_structs.c
> +    if (room_level == NULL)
Since you allocate space for the room_name, you should free that as well

2021-05-03 22:43 UTC, MaxineK36 commented on include/openworld/gen_structs.h
> +int hash_room_level(room_level_t **room_levels, char *name, int difficulty_level);
This function should be named something like `add_room_level_to_hash` so it's more clear what's happening

2021-05-03 22:43 UTC, MaxineK36 commented on include/openworld/gen_structs.h
> + *
Your comments should specify what happens if the room existed already in the hash

2021-05-04 02:29 UTC, MaxineK36 reviewed
One more tiny thing, then you should be good to go!

2021-05-04 02:29 UTC, MaxineK36 commented on include/openworld/gen_structs.h
> + *
What does it return if the name is already in the hash?

2021-05-04 02:48 UTC, MaxineK36 approved these changes
LGTM!

2021-05-04 02:49 UTC, merged

2021-05-18 10:24 UTC, Justin08784 commented
Closing statement:
Comments by reviewers have been addressed and branch `openworld/level-oriented-gen` is now merged into dev. Functionality for generating rooms of appropriate difficulty level is now available across all modules.

2021-05-20 04:42 UTC, MaxineK36 commented
Issue Score: ✔️+

Comments:
Great work overall! Two areas of improvement for next time:
- The reviewer for this PR approved the PR without comment. Please make sure that you always do a full review of the code, even if the senior developer has already provided their review. In the rare cases where there truly isn't anything to improve in the PR, make sure to leave a comment confirming that you reviewed the code and don't have any changes to suggest. If the senior dev has left their review, it can also be useful to indicate whether you agree with it or not.
- When you create a PR, you are requesting a review of the code in the branch you want to merge. As such, you should not push any commits to the branch right after creating the PR; you should only do so in response to a code review adding comments/requesting changes. In this case, it looks like commits were pushed immediately after a review approving the PR.

<!-- {"score": "check-plus"} -->