Implementing mode functionality to support NPC dialogue
uchicago-cs/chiventure pull request #897
Opened 2021-05-02 03:56 UTC by pkasner

(Closes #864 )

Previously, the CLI only interpreted user input as commands for actions. To implement NPC dialogue, we needed a way to have user input not treated as a command. By having a game mode option, chiventure can switch between operating through the normal CLI and operating through separate functions, such as a run_conversation function, while still obtaining user input in the same way.

Changes:
- Added mode.h and mode.c file with struct definitions and init/new/free functions
- Added a mode field to the game struct
- When not in normal mode, the print_cli function calls the mode's run_mode function instead of do_cmd.
- The load_yaml_game function also loads the game mode in normal mode.

2021-05-02 16:45 UTC, jeyeong approved these changes

2021-05-04 05:59 UTC, pkasner commented on src/ui/src/print_functions.c
This section of the code is the only part that technically interacts with the CLI, although it is perhaps better described as a diversion than an interaction.

2021-05-04 10:59 UTC, jeyeong commented
This looks good to me.

2021-05-06 00:34 UTC, lilyehsani requested changes
Added a couple relatively minor comments. Overall great job!

2021-05-06 00:34 UTC, lilyehsani commented on src/game-state/src/mode.c
> +    strcpy(mode->mode_ctx, mode_ctx);
Do not use `strcpy` here (and in fact try to avoid using it in general). Instead, use `strncpy(mode->mode_ctx, mode_ctx, MAX_IS_LEN);` as it is a safer option which protects against unterminated strings.

2021-05-06 06:49 UTC, pkasner commented
I've fixed the formatting mistakes for * and switched strcpy to strncpy

2021-05-08 17:15 UTC, pkasner commented
Just realized from last class that some of chiventure's tests don't actually load a WDL file, so the load_yaml_game function won't be called in this case. To ensure that a mode is always initialized, I can add a condition to do so in the context's init function.

2021-05-09 23:24 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-05-09 23:26 UTC, merged

2021-05-09 23:26 UTC, lilyehsani commented
LGTM! Approved.

2021-05-10 23:09 UTC, pkasner commented
The mode functionality is currently working, but there are currently no mode operations or actions implemented for switching mode. The next steps for implementing npc dialogue are writing a mode operation function for conversation mode, which will call run_conversation_step() in the dialogue module, and implementing a "TALK" action to initiate conversations with NPCs.

2021-05-18 18:07 UTC, lilyehsani commented
Issue Score: ✔️++

Comments:
Great work overall! The summary, updates, and closing of this PR are very thorough.

<!-- {"score": "check-plus-plus"} -->