Cleaning up npc.h and implementing integration plan for npc and battle modules.
uchicago-cs/chiventure pull request #899
Opened 2021-05-02 21:55 UTC by amymorrill

We have cleaned up the npc struct in npc.h as outline in #884. We also have implemented our plan to integrate the npc and battle modules as outlined in #883. 

First, we created a new struct called npc_battle_t which holds the information about npcs that is only pertinent to battles. We also created npc_battle_init, npc_battle_new, and npc_battle_free functions.

Second, we updated the existing npc struct, getting rid of repetitions and adding an npc_battle field. We also updated npc_init, npc_new, npc_free, get_npc_health, and change_npc_health to be compatible with the updated npc struct. 

Notably, there are still some warnings and errors that come up in the npc module. However, these warnings/errors either arise from problems with the battle/battle_structs file (item_t is defined here and in game-state/item.h) or problems with the get/set functions for the npc's inventory, which were not edited by us (this may be because of the problem with the battle file because the inventory deals with items). These problems should be addressed by the battle team or by us in a future issue.

2021-05-04 04:16 UTC, amymorrill commented
After discussing with the rest of our team, we are going to temporarily close this pull request. 

There are three reasons for this. The first is that there is a pull request from other members of our team (#904) that also edits the main npc struct, so it will make integration easier if we add our edits to the dev branch after their code has been added. The second is that our branch currently does not build due to a dependency on a file from the battle team (battle_structs.h) that contains an error (redefining item.h which is already defined in game-state). The third is that because we changed the npc_new and npc_init functions, our code will break tests that other teams have written which include those functions. To solve this problem, we will make npc_battle default to NULL in npc_new and npc_init and will then create additional functions to add an npc_battle struct to an npc.  

Thus, we will wait until our team members' pull request goes through (#904), the battle_structs.h file is modified, and we fix our npc_new/npc_init problem before reopening this pull request.

2021-05-12 20:44 UTC, amymorrill commented
Both of the pull requests that we were waiting on were merged with the dev branch, and we've edited our code to resolve all merge conflicts with dev, so this pull request is now being re-opened. Below are a list of all of the changes made in this pull request (both before the initial pull request was made and before re-opening it):
- We created a new struct called npc_battle_t which holds information about npcs that is only pertinent to battles.
- We create a new module called npc_battle which holds the npc_battle_t struct as well as the new/init/free functions for that struct.
- We edited the npc struct to no longer include health, which now is held in the npc_battle struct. We added will_fight to the npc struct, which is a boolean telling whether or not an npc engages in battle (for our reasoning for this, see #883).
- We updated the npc new/init/free functions to reflect the new npc struct. 
      - Note that at first, I added an inventory and dialogue field to the npc_new and npc_init functions, not realizing that those 
         are supposed to be initialized to NULL. Since then, however, I have edited those functions to no longer take those fields. 
      - Also note that I initially made npc_new and npc_init take an npc_battle_t struct as a field, but I later changed it so that 
         npc_battle initializes to NULL, and I removed the npc_battle field from npc_new and npc_init. 
- We updated the test_npc.c and test_rooms_npc.c files to get rid of conflicts with the updated npc_new function. I added @torresszy to review these changes as someone from the npc team.
- We updated the test_quests_state.c file to get rid of conflicts with the updated npc_new function. I added @dillonoloughlin to review these changes as someone from the quest team.

2021-05-19 06:36 UTC, torresszy commented on src/npc/src/npc.c
> +    convo_free(npc->dialogue);
There seems to be a `convo_free` function call in line 55 already

2021-05-19 06:41 UTC, torresszy requested changes
Looking good overall! There is a minor issue I commented on, but correct me if I am not understanding the code correctly.

2021-05-19 18:22 UTC, amymorrill commented on src/npc/src/npc.c
> +    convo_free(npc->dialogue);
Oops I didn't notice that. I've removed the extra line.

2021-05-19 19:35 UTC, torresszy approved these changes
Looks good to me now!

2021-05-19 20:43 UTC, lilyehsani requested changes
Great job! Added a couple comments.

2021-05-19 20:43 UTC, lilyehsani commented on src/npc/src/npc.c
> +    class_free(npc->class);
I believe we should we be freeing the npc_battle_t in the npc struct here as well.

2021-05-19 20:43 UTC, lilyehsani commented on tests/npc/test_npc.c
> -Test(npc, get_npc_health)
Why were these two tests deleted? Are they going to be rewritten in a future test_npc_battle module?

2021-05-19 21:00 UTC, amymorrill commented on tests/npc/test_npc.c
> -Test(npc, get_npc_health)
I deleted these tests because health is now in the npc_battle module, and I haven't yet written a function to add an npc_battle field to the npc struct (which I will be making in my new issue), so it's impossible to assign npcs a health level right now. I will add back these tests when I write other npc_battle function tests!

2021-05-19 21:00 UTC, amymorrill commented on src/npc/src/npc.c
> +    class_free(npc->class);
Oops, that is true. I will add that now.

2021-05-22 01:16 UTC, lilyehsani requested changes
One more thing

2021-05-22 01:16 UTC, lilyehsani commented on src/npc/CMakeLists.txt
> +target_link_libraries(npc battle)
Is there a reason you added this line? I don't believe it is necessary.

2021-05-22 16:29 UTC, amymorrill commented on src/npc/CMakeLists.txt
> +target_link_libraries(npc battle)
I was getting an error in the compiler where it said that move_free (a function in the battle_moves module, which was included in npc_battle.h) was an undefined reference. I went to office hours and Borja recommended that I should add this line, which fixed the problem.

2021-05-24 02:35 UTC, lilyehsani commented on src/npc/CMakeLists.txt
> +target_link_libraries(npc battle)
Awesome! Thanks.

2021-05-24 02:35 UTC, lilyehsani approved these changes
LGTM! Approved.

2021-05-24 02:41 UTC, merged

2021-05-24 22:36 UTC, amymorrill commented
Closing statement: This pull request has been merged into dev. In addition to the changes described in previous comments, we also modified CMakeLists.txt to fix unresolved reference errors.

2021-06-06 05:10 UTC, lilyehsani commented
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this PR are very thorough.

<!-- {"score": "check-plus-plus"} -->