UI/update readme
uchicago-cs/chiventure pull request #901
Opened 2021-05-02 22:35 UTC by eao10000

@xWngl and I have finished cleaning up and updating the READMME.md in the ui directory. We added additional information about the coordinates module while also removing the DFS module from the README.md as it was no longer needed. We were also able to update the how to use section making it easier and more accurate on how to run the ui directory.

2021-05-02 23:53 UTC, xWngl approved these changes
I'd just add that the old DFS module is now part of the coordinates module

2021-05-03 14:57 UTC, MaxineK36 requested changes
Are the `window` and `map` modules still being used? If not, we should note that. Otherwise, looks good modulo my one comment!

2021-05-03 14:57 UTC, MaxineK36 commented on src/ui/README.md
> +to run the executable.
Can we also specify what examples are currently there?

2021-05-04 15:24 UTC, MaxineK36 approved these changes
LGTM!

2021-05-04 15:24 UTC, merged

2021-05-14 02:09 UTC, eao10000 commented
The README.md in the UI module has been updated and implemented. When doing this we noticed that the coordinates section was not completed, so we added the information there, while deleting the unused DFS section. With this the issue is closed.

2021-05-20 04:38 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! Going forward, please make sure that everyone who contributed to the code is an assignee on the PR, and that they are not also assigned as reviewers.

<!-- {"score": "check-plus-plus"} -->