Update quest documentation
uchicago-cs/chiventure pull request #909
Opened 2021-05-03 22:10 UTC by gabigarc03

Updated `quests_state.h` and `quests_structs.h` with more accurate documentation that that reflects what functions are actually doing, what the structs are and their components, and uses proper language (e.g. no longer refers to a quest marked "failed" as marked "started") as described in issue #889.

2021-05-04 16:36 UTC, ddelgado60 commented on include/quests/quests_state.h
>   * - quest: pointer to quest_t
Minor comment, but should this be quest instead of quest_t?

2021-05-04 16:36 UTC, ddelgado60 commented on include/quests/quests_state.h
>   * - quest: pointer to quest_t to be started
Minor comment, but should this be quest instead of quest_t?

2021-05-04 16:36 UTC, ddelgado60 commented on include/quests/quests_state.h
> + * - quest: pointer to a quest_t
Minor comment, but should this be quest instead of quest_t?

2021-05-04 16:40 UTC, ddelgado60 requested changes
Looks good! Great work on updating the documentation from last year. I had a quick comment: when the documentation has an achievement or a quest as input, I'm not sure if it should be like quest: a pointer to quest or quest: a pointer to quest_t. I think it may be the former, so perhaps you could take a look. I only commented directly below on a few.

2021-05-04 23:50 UTC, ddelgado60 approved these changes
Looks great! Thanks for reviewing my comments.

2021-05-06 01:15 UTC, lilyehsani requested changes
Great job! Added a few minor comments

2021-05-07 23:47 UTC, gabigarc03 commented on include/quests/quests_state.h
>   * - pointer to the quest
Fixed! Thank you so much.

2021-05-07 23:47 UTC, gabigarc03 commented on include/quests/quests_state.h
> + * - quest: pointer to quest to be started
Fixed! Thank you so much.

2021-05-10 00:04 UTC, lilyehsani approved these changes
Looks great! Approved.

2021-05-10 00:58 UTC, merged

2021-05-10 18:37 UTC, gabigarc03 commented
`quests_state.h` and `quests_struct.h` now have updated documentation that accurately reflects the structs and functions within them.

2021-05-18 18:17 UTC, lilyehsani commented
Issue Score: ✔️++

Comments:
Great work overall! The summary/closing and peer review comments of this PR are sufficiently thorough.

<!-- {"score": "check-plus-plus"} -->