Playerclass/multiclass
uchicago-cs/chiventure pull request #911
Opened 2021-05-03 22:33 UTC by farm-zaq

Note that this code is incomplete. It should run compile and run, although some outputs may not be the intended outputs. See the wiki page on multiclassing for more specifics.

2021-05-05 06:01 UTC, firatciftci commented
@farm-zaq You have to make sure that the PR passes the automated tests before the reviewers can submit their reviews. Also make sure to have a longer and more detailed title and summary for your PR, and ensure that the fields on the right side of the PR page are all filled in. Let me know if you have any questions/issues with these!

2021-05-06 02:13 UTC, farm-zaq commented
Partial implementation of mutliclassing. This includes updating the class struct to have relevant fields to support multiclass (essentially detailing what base classes a multiclass is formed from) and partially creating a multiclass function. The current multiclass function combines or properly updates the descriptions and the stats for the new multiclass, but it does not combine the attributes, effects, skills, or actions for the new class.

2021-05-06 02:14 UTC, farm-zaq commented
Partial implementation of mutliclassing. This includes updating the class struct to have relevant fields to support multiclass (essentially detailing what base classes a multiclass is formed from) and partially creating a multiclass function. The current multiclass function combines or properly updates the descriptions and the stats for the new multiclass, but it does not combine the attributes, effects, skills, or actions for the new class.

2021-05-10 00:33 UTC, firatciftci commented
@himaanir Just a reminder that as the student reviewer, you should review the PR first, and once your comments are in, I can then go ahead and conduct my own review.

2021-05-15 22:58 UTC, farm-zaq commented
@himaanir I have added one last, isolated function (and a single call to it) for effects, so I'm rerequesting you as a reviewer to review this. I wasn't exactly sure where to put these changes, and I'm sorry for the inconvenience.

2021-05-17 17:52 UTC, himaanir reviewed
I think this looks good, but just make sure to add tests for the multiclass_effects function

2021-05-18 06:41 UTC, firatciftci requested changes
I have requested a bunch of stylistic changes; they should be simple to fix as most are in the same or similar nature to each other.

2021-05-18 06:41 UTC, firatciftci commented on include/playerclass/class.h
> +int has_component_class (class_t* class, char* name);
There shouldn't be a space character between the function name and the `(` character.

2021-05-18 06:41 UTC, firatciftci commented on include/playerclass/class_structs.h
> +    int parent_class_num;
I think a better name for this field would be `num_parent_class` or `num_parent_classes`.

2021-05-18 06:41 UTC, firatciftci commented on src/game-state/src/condition.c
> +    memset(condition_wrapper, 0, sizeof(condition_t));
Is there a specific reason for changing `calloc` to be a `malloc` and a `memset` instead?

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +char* multiclass_shortdesc (class_t* base_class, class_t* second_class){
There shouldn't be a space character between the function name and the `(` character. Also, there should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    strcat (new_longdesc, second_class->shortdesc);
There shouldn't be a space character between `strcat` and the `(` character. Also, using `strncat` is a better idea; as we allocate the length to be concatenated manually, the `n` version is usually a better way to go in terms of efficiency. (This comment applies to all calls to `strcat` in this block.)

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +char* multiclass_longdesc (class_t* base_class, class_t* second_class){
There shouldn't be a space character between the function name and the `(` character. Also, there should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +effects_hash_t* multiclass_effects(effects_hash_t* base_effects, effects_hash_t* second_effects){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (base_effects != NULL){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    else if (second_effects != NULL){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    else return NULL;
You should write out the `else` clause like the other ones above:
```c
else {
    return NULL;
}
```

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (base_effects != NULL){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +        while (second_effects != NULL) {
This line should be indented back once.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +skill_tree_t* multiclass_tree (char* name, skill_tree_t* base_tree, skill_tree_t* second_tree){
There shouldn't be a space character between the function name and the `(` character. Also, there should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    for (int i = 0; i < base_tree->num_nodes; i++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    for (int i = 0; i < second_tree->num_nodes; i ++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +        skill_tree_node_add (new_tree, base_tree->nodes[i]);
There shouldn't be a space character between the function name and the `(` character.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +        skill_tree_node_add (new_tree, second_tree->nodes[i]);
There shouldn't be a space character between the function name and the `(` character.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +skill_inventory_t* multiclass_inventory (skill_inventory_t* base_inventory, skill_inventory_t* second_inventory){
There shouldn't be a space character between the function name and the `(` character. Also, there should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (base_inventory->max_active >= second_inventory->max_active){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    else{
There should be a space character between `else` and `{`.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (base_inventory->max_passive >= second_inventory->max_passive){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    else{
There should be a space character between `else` and `{`.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    skill_inventory_t* new_inventory = inventory_new (max_active, max_passive);
There shouldn't be a space character between `inventory_new` and the `(` character.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    for (int i = 0; i < base_inventory->num_active; i++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    for (int i = 0; i < second_inventory->num_active; i++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    for (int i = 0; i < base_inventory->num_passive; i++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    for (int i = 0; i < second_inventory->num_passive; i++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +class_t* multiclass(class_t* base_class, class_t* second_class, char* name){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    obj_t* combined_attr = NULL; //obj_add_attr(base_class->attributes, second_class->attributes->id, second_class->attributes);
Make sure to remove the unused commented out line here.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    effects_hash_t* combined_effects = multiclass_effects (base_class->effects, second_class->effects);
There shouldn't be a space character between the function name and the `(` character.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    if (new_class == NULL) return NULL;
You should write out this `if` statement in full:
```c
if (new_class == NULL) {
    return NULL;
}
```

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    for (int i = 0; i < new_class->parent_class_num; i++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    while (i < base_class->parent_class_num){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +    while (i < second_class->parent_class_num - base_class->parent_class_num){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +int has_component_class (class_t* class, char* name){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +        if (!(strcmp(class->parent_class_names[i], name))) return 1;
You should write out this `if` statement in full:
```c
if (...) {
    ...
}
```

Also, using `strncmp()` instead of `strcmp()` would be a better idea efficiency-wise (similar to `strcat()` and `strncat()` mentioned above).

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +            free (class->parent_class_names[i]);
There shouldn't be a space character between the function name and the `(` character.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class.c
> +        free (class->parent_class_names);
There shouldn't be a space character between the function name and the `(` character.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class_item_restriction.c
> +    for (int i = 0; i < class->parent_class_num; i++){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on src/playerclass/src/class_item_restriction.c
> +        if (list_contains_attribute(item->class_restrictions, strndup(class->parent_class_names[i], 100))){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on tests/playerclass/test_class_item_restriction.c
> +        if (list_contains_attribute(item->class_restrictions, strndup(class->parent_class_names[i], 100))){
There should be a space character between `)` and `{` at the end of the line.

2021-05-18 06:41 UTC, firatciftci commented on tests/playerclass/test_class_item_restriction.c
> +    if (list_contains_attribute(item->class_restrictions, strndup(class->name, 100))){
There should be a space character between `)` and `{` at the end of the line.

2021-05-22 02:31 UTC, farm-zaq commented on src/game-state/src/condition.c
> +    memset(condition_wrapper, 0, sizeof(condition_t));
I don't actually think I'm the one who did this, which kind of worries me. It was probably just a result of me trying to revert a merge by accident, hopefully.

2021-05-22 03:12 UTC, farm-zaq commented
@firatciftci I believe I have made all your suggested edits, so please look them over. I have also added the last helper function for multiclass, so please look that over, too. This should be my last push to this branch (sorry about the continual updates). Because it is the last helper function, I will also be changing the name of the PR, as multiclassing is now technically complete (although it still needs work).

2021-05-25 02:02 UTC, firatciftci approved these changes
Everything looks good to me!

2021-05-25 02:02 UTC, merged

2021-06-02 22:51 UTC, firatciftci commented
Issue Score: ✔️+

Comments:
Good work overall! I only have one thing to comment on:
- When an PR is done, you should include a final comment summarizing what was merged to `dev` and what work remains to be done, if any.

<!-- {"score": "check-plus"} -->