Skilltrees/skill modify:  Implementation of v1 of effects that describe what a skill does.
uchicago-cs/chiventure pull request #914
Opened 2021-05-03 23:51 UTC by rohangupta2806

This pull request constitutes version 1 of the new implementation of skill effects.  Skill effects are of 3 types: statistics modifiers, damage dealing, and attribute modifying.  These are all contained in a union type called effect, found in effect.h.  Skills can have multiple effects.  The execution for each type of effect, and the initialization of each type of effect will differ distinctly.  As a result, the execute functions and the initialization functions either have no implementation or very minimal implementation.  Going further, implementation for these methods will be split into different issues (1 issue for initialization and execution of statistic modifying effects, 1 for damage dealing effects, 1 for attribute modifying effects).  implementation of these functions will require collaboration with other teams.

2021-05-04 13:41 UTC, jackcasey067 approved these changes
I believe I was only requested because of a weird issue with git not applying one of my commits to this branch... Rohan figured that out (somehow), and just copied the code over into the branch.  Therefore, I am only looking at changes to our player class files.

The two playerclass files have some tiny changes you missed, but they literally do not matter in the slightest (Newline at end of files; apparently an unnecessary include that I'm glad is being removed).  It looks good to me.

Approved.

2021-05-05 19:14 UTC, Joshuashou approved these changes
looks good, makes the clear a lot clearer and changes to effect make sense

2021-05-10 00:24 UTC, firatciftci requested changes
I've requested mainly stylistic and design-related changes. After this PR, I suggest the team to take on rewriting the tests as a top priority issue, as they seem to all be commented out at the moment. They can remain as such for the moment, but having proper tests that fit to these changes are crucial for the continuation of this feature's future development.

2021-05-10 00:24 UTC, firatciftci commented on include/skilltrees/effect.h
> +}damage_effect_t;
Do we have this struct with only one attribute just for this v1 of the code base? This is fine if you anticipate adding more fields to the struct in the future, but if not, I think a different design might be necessary. If the former, I think adding a `TODO` comment somewhere here to display that idea could be necessary.

2021-05-10 00:24 UTC, firatciftci commented on include/skilltrees/effect.h
> +    char *s;
Having these fields written out in their full names would be better as per the style guide.

2021-05-10 00:24 UTC, firatciftci commented on include/skilltrees/effect.h
> +    int num; //Number of effects
I think changing `num` to `num_effects` would be more suitable.

2021-05-10 00:24 UTC, firatciftci commented on include/skilltrees/effect.h
> +int add_node (effects_linked_list_t* ll, effect_t* effect);
There shouldn't be a space character between the function name and the list of input parameters.

2021-05-10 00:24 UTC, firatciftci commented on include/skilltrees/effect.h
> +int remove_node (effects_linked_list_t* ll, effect_t* effect);
There shouldn't be a space character between the function name and the list of input parameters.

2021-05-10 06:03 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +/*List of all the effect types that a skill can have.  We can add more in the future */
Fixed this issue.

2021-05-10 06:05 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +//#include "common/ctx.h"  (Removing the comment causes the code to not compile correctly.  Please advise)
The error we get is that certain structs have duplicate names.  This issue is arising due to battle_flow_structs and battle_structs having structs that have the same name as those in game-state.  RPG battles has been made aware of this and is fixing the issue.  I have added a comment in the code to reflect this too.

2021-05-10 06:07 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +}stat_mod_effect_t;
This was a mistake.  The struct should be called stat_mod_effect.  Fixed the code to reflect this.

2021-05-10 06:07 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +typedef struct stat_effect{
Fixed.

2021-05-10 06:12 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +    char *s;
We have used the same names that were given in obj.h as these values are supposed to reflect how it would be possible to modify objects and their attributes.  As a result, I'm not particularly sure what other name I could give them.  If you could advise us on this, I'll update the names as soon as possible.

2021-05-10 06:12 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +    int num; //Number of effects
Fixed.

2021-05-10 06:12 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +int add_node (effects_linked_list_t* ll, effect_t* effect);
Fixed.

2021-05-10 06:12 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +int remove_node (effects_linked_list_t* ll, effect_t* effect);
Fixed

2021-05-10 08:23 UTC, rohangupta2806 commented on include/skilltrees/effect.h
> +}damage_effect_t;
I think more attributes will probably be added after speaking with the other teams.  I was not sure about them for this version, so I only added this field.  I have updated the code to reflected this.

2021-05-10 08:24 UTC, rohangupta2806 commented
I have fixed all changes suggested by Firat.  However, we are getting a strange error where the effect.c file is not being involved in the build process.  I'm not quite sure how to fix this.

2021-05-10 22:53 UTC, merged

2021-05-26 05:15 UTC, firatciftci commented
Issue Score: ✔️+

Comments:
Good job! I only have one thing to comment on:
- When a PR is merged, you should include a final comment summarizing what codebase/featureset was merged to `dev` and what work remains to be done, if any.

<!-- {"score": "check-plus"} -->