Playerclass/prefab classes: Adding prefabricated classes to the playerclass component
uchicago-cs/chiventure pull request #916
Opened 2021-05-04 01:49 UTC by jackcasey067

See Issue: (#867)

Adds 6 prefabricated classes, each with their own stats.  Also added skills to the warrior class, as a proof of concept, but we are waiting for skill trees to change the way skill effects are handled before finishing the rest of the classes.

Two functions are exposed: `class_prefab_new`, which takes a string and returns the allocated and initialized class, and `class_prefab_add_skills`, which takes the class and adds skills and a skill-tree (implementation not done). We decided to do this 2 function approach in case the developer was interested in having classes in their game, but not skill trees (or maybe they want to customize the skill trees themselves).

There was also some restructuring of the other files; functions that only worked for prefab classes were moved to the prefab class modules.  In one case, a removed function was replaced with a more general function, that works for non-prefab classes.  This restructuring resulted in the deletion of the then class_skills module.

2021-05-04 22:49 UTC, ideclue requested changes
Overall, the code looks great and will be a helpful addition to `playerclass`. Most of my comments related to clarifying documentation and fixing some comments, which I believe will be helpful for future developer users.

2021-05-04 22:49 UTC, ideclue commented on tests/playerclass/test_class_prefabs.c
> + * complete and. */
The comment is cut off, might be helpful to clarify what differentiates the warrior from the rest of the tests explicitly here.

2021-05-04 22:49 UTC, ideclue commented on src/playerclass/src/class_prefabs.c
> +const int DEFAULT_CLASS_COUNT = 10;
Not sure if I'm misinterpreting, but it looks like default class names and count don't match up?

2021-05-04 22:49 UTC, ideclue commented on src/playerclass/src/class_prefabs.c
> +        return FAILURE;
I would recommend including an error message specifying which one of these conditions is failing. These problems could definitely arise from different scenarios and it might be helpful for debugging purposes.

2021-05-04 22:49 UTC, ideclue commented on src/playerclass/src/class_prefabs.c
> +    }
Make sure spacing and comments are consistent in this section to increase readability.

2021-05-05 00:45 UTC, maxsamengo commented on include/playerclass/class_prefabs.h
> + *  - status code
`class_prefab_add_skills()` is currently a work in progress. Most of these functions are up in the air because the skill tree team are still working on skill trees.

2021-05-05 02:11 UTC, ideclue commented on src/playerclass/src/class_prefabs.c
> +    }
Specifically, I think a little more than a one line description might be helpful.

2021-05-05 05:36 UTC, firatciftci requested changes
Some minor stylistic changes requested, but good job overall!

2021-05-05 05:36 UTC, firatciftci commented on src/playerclass/src/class_prefabs.c
> +const int DEFAULT_CLASS_COUNT = 10;
This is a good catch; `DEFAULT_CLASS_COUNT` and the length of `DEFAULT_CLASS_NAMES` should match to one another.

2021-05-05 05:36 UTC, firatciftci commented on src/playerclass/src/class_prefabs.c
> +        return FAILURE;
+1 to @ideclue's point.

2021-05-05 05:36 UTC, firatciftci commented on src/playerclass/src/class_prefabs.c
> +    check_and_add_stat(ctx, stats, "max_magic_energy", max_magic_energy, 100);
These lines should not be styled in this manner; instead, each parameter after should be separated by only a single space character. For more information about styling, check out our style guide: https://uchicago-cs.github.io/dev-guide/style_guide_c.html

2021-05-05 05:36 UTC, firatciftci commented on src/playerclass/src/class_prefabs.c
> +    }
+1 to @ideclue's point.

2021-05-10 00:31 UTC, firatciftci approved these changes
Everything looks good to me!

2021-05-10 00:31 UTC, merged

2021-05-10 00:34 UTC, jackcasey067 commented
Closing statement:
After some editing, the branch `playerclass/prefab-classes` was merged with `dev`.  Chiventure now has prefabricated player classes!

2021-05-26 05:17 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great job!

<!-- {"score": "check-plus-plus"} -->