Memory management in game-state and action_management
uchicago-cs/chiventure pull request #919
Opened 2021-05-04 04:28 UTC by jasulcaf

(Closes #877)
This is connected to @LapsededPacifist and my Issue (#877) which was focused on clearing up the memory leakage that was found in the tests for game-state and action_management. The purpose of clearing the tests was so we could potentially uncover bugs in free functions (or the lack of free functions) which could prove to become detrimental as Chiventure continues to grow.

Overview of implemented changes:
- All tests run without leaking memory
- delete_all_items now _successfully_ deletes duplicate items without memory leakage
- Fixed memory leakage where strings where being malloc'ed instead of using strndup

Something to note was that before, if valgrind was simply ran as: `valgrind ./(Executable)` on the test executables, then it would show no memory leakage. However, when you ran `valgrind` --tool=memcheck --trace-children=yes ./(Executable)` you would get a much more descriptive outcome that showed how much memory was lost.

2021-05-04 20:06 UTC, WPDolan commented on src/game-state/src/item.c
> -      	remove_item_from_hash(items, current_item); /* deletes (items advances to next) */
What does the new iteration loop achieve that the old iterator failed to accomplish? Uthash documentation makes the old method seem like a correct approach.

2021-05-04 20:09 UTC, WPDolan commented
When running the valgrind command provided in the request statement, all of the tests in `tests/game-state` run without memory leakage. However, many of the tests in `tests/action_management` leak memory. I have brought this up in the team slack.

2021-05-04 20:39 UTC, jasulcaf commented on src/game-state/src/item.c
> -      	remove_item_from_hash(items, current_item); /* deletes (items advances to next) */
As can be found in more detail in our Issue Page https://github.com/uchicago-cs/chiventure/issues/877#issuecomment-830861590, with the current implementation of how adding duplicate items to the hash currently works, this loop is necessary to delete all duplicated items. When removing a duplicated item currently, only the "head" item is being removed while the "tail" is being rehashed to the same place in the hash table. However, HASH_ITER would have already moved on to the next hash spot. The purpose of the loop is to thoroughly delete all re-addition (i.e. all duplications) to the same hash spot _before_ continuing the process of iterating through the rest of the hash.

2021-05-04 20:40 UTC, WPDolan commented on src/game-state/src/item.c
> -      	remove_item_from_hash(items, current_item); /* deletes (items advances to next) */
That makes sense. Thanks for the clarification!

2021-05-04 20:47 UTC, WPDolan approved these changes
Changes successfully achieve their goal, valgrind is showing that the proper blocks have been freed in game-state and action_management tests. My original questions have been clarified, and I see no further issues. Approved.

2021-05-04 22:41 UTC, jasulcaf commented
As a summary of what we talked about in the team slack, the tests that had memory leakage in action_management tests (test_item_action, test_item_item_action, and test_path_actions) occurred due to these initializing a chiventure_ctx_t struct which contains a lookup_t** field called table. The free function, lookup_t_free does not function properly and correcting this would require talking with the CLI team and learning what is actually inside (and what should be freed). I have edited the initial summary accordingly to reflect this.

2021-05-05 03:46 UTC, MaxineK36 requested changes
Awesome work! Just a couple nit-picky things to fix

2021-05-05 03:46 UTC, MaxineK36 commented on src/game-state/src/condition.c
>      condition_t *condition_wrapper = malloc(sizeof(condition_t));
Instead of using `malloc` and then `memset` with 0, you should use `calloc`
e.g. `condition_t *condition_wrapper = calloc(1, sizeof(condition_t));`
See the [manual page](https://linux.die.net/man/3/calloc) for more details

2021-05-05 03:46 UTC, MaxineK36 commented on src/game-state/src/stats.c
> +    memset(effect,0, sizeof(stat_effect_t));
Ditto here; use `calloc`

2021-05-05 03:46 UTC, MaxineK36 commented on tests/action_management/test_get_actions.c
> +void free_get_supported_actions(list_action_type_t* head)
Why is this only necessary for tests, and not included in a source file?

2021-05-05 03:46 UTC, MaxineK36 commented on tests/action_management/test_get_actions.c
> +    //head = get_supported_actions();
Please remove any commented-out code that is no longer used!

2021-05-05 03:46 UTC, MaxineK36 commented on tests/action_management/test_item_actions.c
> +    free(ctx_test->table);
do we know why this isn't included in `lookup_t_free`?

2021-05-05 03:46 UTC, MaxineK36 commented on tests/game-state/test_player.c
> +  stats_global_t *health = malloc(sizeof(stats_global_t));
is there a `global_stats_new` function?

2021-05-05 03:46 UTC, MaxineK36 commented on tests/game-state/test_player.c
> +  class_free(class);
Fyi, looks like with the updated player functions, you may  not need to separately free the class anymore

2021-05-05 03:57 UTC, jasulcaf commented on src/game-state/src/condition.c
>      condition_t *condition_wrapper = malloc(sizeof(condition_t));
Incorporated change, didn't think about this, thanks!

2021-05-05 04:05 UTC, jasulcaf commented on tests/action_management/test_get_actions.c
> +void free_get_supported_actions(list_action_type_t* head)
To be quite frank, I didn't know if we should have included this in a source file or not (didn't know if it merited this since I am not sure how often nor the context of how get_supported_actions is called in other places in Chiventure). I know that in src/get_actions.c lies `get_supported_actions()` function, so if you think that it would be a good idea to move it as a function that can be used by other teams in Chiventure, then I can definitely move free_get_supported_actions to be in the same source file as `get_supported_actions()`.

2021-05-05 04:14 UTC, LapsededPacifist commented on tests/action_management/test_item_actions.c
> +    free(ctx_test->table);
No. From what I have seen, I would think that it should be in `lookup_t_free`, but `lookup_t_free` is also not freeing the table very well. I think the entire function needs to be written.
If I had to guess, I would say the probably could potentially be similar to our problem of only freeing the first item in each bucket of the hash, but the function currently doesn't seem to be freeing all of the first item. Just the name and the struct itself (I think it also contains an action).  
Basically, I don't know why much of what is happening in `lookup_t_free` is happening.

2021-05-05 04:19 UTC, jasulcaf commented on tests/game-state/test_player.c
> +  stats_global_t *health = malloc(sizeof(stats_global_t));
Yep, there was! Thank you for pointing that out, I have changed the test to use stats_global_new so this is now resolved.

2021-05-05 04:54 UTC, jasulcaf commented on tests/action_management/test_get_actions.c
> +void free_get_supported_actions(list_action_type_t* head)
In the end, the functions was both renamed and moved to the source file. The new name is now `free_supported_actions ` and is found in src/get_actions.c

2021-05-05 05:06 UTC, LapsededPacifist commented on tests/game-state/test_player.c
> +  class_free(class);
I removed the class_free call. The test will leak memory for a little bit, but the memory side of this test is going to be fixed when freeing effects no longer double frees everything.

2021-05-05 17:02 UTC, MaxineK36 reviewed
One typo, then it should be good to go!

2021-05-05 17:02 UTC, MaxineK36 commented on include/action_management/actionmanagement.h
> +/* free_get_supported_actions: Free's list_action_type_t list that contains ALL
nit: *frees

2021-05-05 17:11 UTC, MaxineK36 approved these changes
Looks great!

2021-05-05 17:13 UTC, merged

2021-05-06 05:30 UTC, jasulcaf commented
As a conclusion to our Pull Request:
We dug through the test code to fix memory leakage related to action_management and game-state functions and in the process we added a new free function called `free_supported_actions` (header file in actionmanagement.h, implemneation found in src/get_actions.c)  to free all supported actions; and we also fixed the following mistake with delete_all_item: 
- delete_all_item was not freeing all resources due to a complication with HASH_ITER and the way that adding duplicated items in a hash table worked. This required incorporating a loop to remove all duplications before continuing the iteration in the hash table

We have also identified some issues that could be looked at in future issues:
1.  the current free function to free a chiventure struct is not implemented 
2. There exists complications with the lookup_t_free functions with the full table not being fully freed. 
3.  Stats and Stats global seem to have some dependencies/relationship that complicates how they are successfully freed.

For more detailed information on these issues, can find at: https://github.com/uchicago-cs/chiventure/issues/877#issuecomment-831684904

2021-05-06 05:32 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! Your conclusion is particularly useful, especially as it details potential future work.

<!-- {"score": "check-plus-plus"} -->