Renamed struct item_t to battle_item_t
uchicago-cs/chiventure pull request #941
Opened 2021-05-05 02:46 UTC by Elsa-Athiley

Because of duplicate definitions between some battle code structs and game-state structs we had to change the naming of our structs. I have changed the item_t struct to battle_item_t and updated all instances of the struct in each file. It builds correctly and our example files still work correctly.

2021-05-05 05:27 UTC, adinilfeld reviewed
Looks good to me, the only thing I'd add is that we should probably update [this wiki page](https://github.com/uchicago-cs/chiventure/wiki/RPG-Battle-Systems:-Design-Document) with the new terminology once this is merged.

Also, are there any comments in the code mentioning `item_t` that should be changed to `battle_item_t`? Just want to make sure that there's not any confusion regarding which item they're referring to.

2021-05-05 05:45 UTC, firatciftci requested changes
I have requested some changes which basically extend the renaming of the notion of an `item` to a `battle item` in more locations of the `battle` codebase. Also, as @adinilfeld has mentioned, the `battle` team should also update their respective wiki page to reflect this substantial change in names.

2021-05-05 05:45 UTC, firatciftci commented on include/battle/battle_logic.h
> +battle_item_t *find_item(battle_item_t *inventory, int id);
The name of this function should probably be changed to `find_battle_item` – this also applies to all other functions with similar names.

2021-05-05 05:45 UTC, firatciftci commented on include/battle/battle_logic.h
> +int consume_item(combatant_t *c, battle_item_t *item);
The name of this function should probably be changed to `consume_battle_item`.

2021-05-05 05:45 UTC, firatciftci commented on include/battle/battle_logic.h
>   *    Returns a pointer to the desired item
We should probably state `... desired battle item` instead.

2021-05-05 05:45 UTC, firatciftci commented on include/battle/battle_logic.h
>   * Consumes an item for the said combatant
We should probably state `Consumes a battle item ...` instead.

2021-05-05 05:45 UTC, firatciftci commented on src/battle/examples/battle_command_example.c
> +int print_items(chiventure_ctx_battle_t *ctx)
The name of this function should probably be changed to `print_battle_items`.

2021-05-05 05:45 UTC, firatciftci commented on src/battle/examples/battle_command_example.c
> +/* Prints out the avaliable items for the player
We should probably state `... available battle items ...` instead.

2021-05-05 05:45 UTC, firatciftci commented on src/battle/examples/battle_command_example.c
> +        printf("Here is the list of available items!\n");
We should probably state `... available battle items!\n` instead.

2021-05-05 05:45 UTC, firatciftci commented on src/battle/examples/battle_command_example.c
> +            printf("Couldn't find the item you were looking for!\n");
We should probably state `... the battle item` instead.

2021-05-05 05:45 UTC, firatciftci commented on src/battle/examples/battle_command_example.c
> +            printf("Sorry you don't have any more of that item!\n");
We should probably state `... that battle item` instead.

2021-05-05 05:45 UTC, firatciftci commented on src/battle/examples/battle_command_example.c
> +        res = use_item(ctx->game->battle->player, atoi(args[1]));
Couldn't comment on the actual file for this function, so adding it here – the name of this function should probably be changed to `use_battle_item`.

2021-05-05 05:48 UTC, firatciftci commented
Also, it seems that the automated tests for this PR is now failing due to another PR from the `battles` team that was merged earlier today. I suggest looking over all of the new modifications to the `battles` module and update this PR accordingly so that the tests pass again. If you'd like me to go over/help with anything in this regard, feel free to let me know!

2021-05-05 17:19 UTC, Elsa-Athiley commented
Applied all of firats suggestions. The automated tests were failing because of a new module added from another Pull request that was still using the old name of item and not battle_item. All test should pass now. However there is another pull request out #905 that hasnt been merged yet that uses the old naming conventions. Depending on which PR gets merged first additional adjustments may need to be made in this PR or the other one.

2021-05-07 18:11 UTC, Elsa-Athiley commented
Fixed the merge conflicts that were a result of my other Pull request going through that had some changes to the `battle_command_example.c` file.

2021-05-07 21:04 UTC, adinilfeld approved these changes
Looks great!

2021-05-10 00:43 UTC, firatciftci approved these changes
All of the changes look good. Great work!

2021-05-10 00:43 UTC, merged

2021-05-12 04:17 UTC, Elsa-Athiley commented
Closing Summary: All instances of item_t have now been changed to battle_item_t in all files in the src/battle, include/battle, and test/battle directories.

2021-05-26 05:32 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great job!

<!-- {"score": "check-plus-plus"} -->