Adding type-specific attribute creation functions to streamline Player Class/Attribute integration
uchicago-cs/chiventure pull request #943
Opened 2021-05-05 03:55 UTC by ideclue

(Closes #851)

In the current class item restriction code, it is necessary to create an attribute directly in order to add it to the `class_restrictions` field of an item. However, the code in `item.c` only contains type-specific `set_attr` functions that combine the creation of an attribute and its addition to the `attributes` hash table. Since class item restrictions are handled via a linked-list, not the `attributes` hash table, I divided up the two processes occurring in the `set_attr` functions in order to allow for creation of attributes in modules other than `game-state`.

Summary of Major Changes:

- Five type-specific attribute creation functions have been added to `item.c` 
- Relevant tests were added and documentation was updated
- Minor changes in `class_item_restriction.c` reflect the addition of these type-specific attribute creation functions

2021-05-05 04:40 UTC, jackcasey067 requested changes
Pretty good work overall; two things to change IMO (see my other comments for more details on both).

1. Make sure to check for NULL right after you malloc.
2. Avoid magic numbers.

2021-05-05 04:40 UTC, jackcasey067 commented on src/game-state/src/item.c
> +    }
In each of these functions, you malloc a new attribute, then use it, and then only at the end do you check for if malloc fails.  `new_attribute->anything` will error if malloc really did fail (I think), so you should move the if statement up to before you access the fields of `new_attribute`.

2021-05-05 04:40 UTC, jackcasey067 commented on src/game-state/src/item.c
> +    new_attribute->attribute_key = strndup(attr_name, 100);
This is maybe debatable, but the `100` here and around your code feel like magic numbers; you should maybe use `MAX_ID_LEN` (which I found used in this file, even though I don't know where it is defined) instead; that way if it changes to allow a different size identifier, your code automatically updates.

2021-05-05 04:40 UTC, jackcasey067 commented on tests/game-state/test_items.c
> +     attribute_t* test_attr = get_attribute(test_item, "Attribute_Test_Name");
Looks like you accidentally added a random space here.

2021-05-05 04:51 UTC, LapsededPacifist requested changes
The only thing that I think needs to be changed is when the NULL check needs to happen. Otherwise, I think things look good.

2021-05-05 04:51 UTC, LapsededPacifist commented on src/game-state/src/item.c
>          res->attribute_value.str_val = value;
I don't know what effect this would have if any, but my initial thought was this should be `strndup(value)`. It looks like they were not using it before, so it is probably fine. You would have to pay attention and free the value before you changed it and have a special case in attribute free. Is there a reason that the string isn't being saved or is it just not necessary as it will always be static?

2021-05-05 04:51 UTC, LapsededPacifist commented on src/game-state/src/item.c
> +}
There is a lot of shared code in these functions. I am not sure if this is a change you want to make, but I would have considered a single attr_new function that also takes as input a tag (And the type of value would need to become a union).
The only functionality comment I have for these functions, I think the NULL check needs to be directly after the malloc. You won't be able to access the memory currently if it is NULL

2021-05-05 04:57 UTC, LapsededPacifist commented on src/game-state/src/item.c
> +    new_attribute->attribute_key = strndup(attr_name, 100);
MAX_ID_LEN is defined as 20 in [game_state_common.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/game-state/game_state_common.h)
I agree with this. This was a pre-existing problem in the code, but it would be nice to actually give it a name instead of just tossing around a random 100.

2021-05-05 05:14 UTC, ideclue commented on src/game-state/src/item.c
> +}
I also noticed this, but I thought in light of the type-specific "set" functions, it would be best to continue the current pattern of implementation.

2021-05-05 05:15 UTC, ideclue commented on src/game-state/src/item.c
> +    new_attribute->attribute_key = strndup(attr_name, 100);
I will definitely make this change. Thank you both for pointing this out!

2021-05-05 05:28 UTC, ideclue commented on src/game-state/src/item.c
>          res->attribute_value.str_val = value;
I think it's the latter (I played around with `attribute_free` and no notable changes occurred).

2021-05-05 05:54 UTC, jackcasey067 approved these changes
Good work!  Approving.

2021-05-05 05:56 UTC, LapsededPacifist approved these changes
Changes to the NULL check look good.

2021-05-05 05:57 UTC, firatciftci commented on src/game-state/src/item.c
> +}
Although the redundancy is not ideal, I think it is fine in terms of its extent – also, as @ideclue mentioned, the `set` functions follow the same pattern, so I think having the file follow the same logical pattern is a better idea than to try and come up with a different function design. That being said, if anyone would like to refactor this file to be less redundant in the future, that could be a good idea.

2021-05-05 05:58 UTC, firatciftci approved these changes
The comments above by the other reviewers are really on point! With all the changes made, I think this is good to go!

2021-05-05 05:59 UTC, merged

2021-05-05 16:05 UTC, ideclue commented
Closing Statement:

After implementing peer feedback, all code has been successfully merged with `dev`. Type-specific attribute creation functions can now be used across modules and will be helpful in managing linked-lists of attributes (and other relevant data structures) for the purpose of developing more complex relationships between items and player classes.

2021-05-12 04:15 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great job!

<!-- {"score": "check-plus-plus"} -->