Cli/credits new
uchicago-cs/chiventure pull request #960
Opened 2021-05-07 03:02 UTC by mberamendiconde

This branch should only include the changes I made for the credits command now.

2021-05-10 17:06 UTC, ecoble requested changes
Looks great! Just a couple small nits

2021-05-10 17:06 UTC, ecoble commented on include/cli/operations.h
> + *  - Some system message
Instead of some system message, it would be better to be more specific, maybe something like "System message listing contributors"

2021-05-10 17:06 UTC, ecoble commented on src/cli/src/operations.c
> +    return "CMSC 22000 Spring 2019\n   CMSC 22000 Spring 2020\n   CMSC 22000 Spring 2021";
It might be better to have these lines be "Class of CMSC ... etc" so it is more clear we are crediting groups of people.

2021-05-10 17:54 UTC, mberamendiconde commented on include/cli/operations.h
> + *  - Some system message
Changed!

2021-05-10 17:54 UTC, mberamendiconde commented on src/cli/src/operations.c
> +    return "CMSC 22000 Spring 2019\n   CMSC 22000 Spring 2020\n   CMSC 22000 Spring 2021";
Changed!

2021-05-14 03:07 UTC, ecoble approved these changes
LGTM!

2021-05-14 03:33 UTC, dchen0258 approved these changes

2021-05-14 03:44 UTC, merged

2021-05-14 18:32 UTC, ecoble commented
Issue Score: ✔️

Comments:
Great job implementing this backlog issue! Even those this PR is one that was reopened, you still have a summary for the work that was done. Also, the PR should have a descriptive title about what goal was accomplished, and a closing statement. Also please remember to add labels and milestones so that issues can be properly picked up by the grading script.

<!-- {"score": "check"} -->