Cli/parse
uchicago-cs/chiventure pull request #961
Opened 2021-05-07 15:25 UTC by mberamendiconde

Pull request for current cli/parse branch, where "and" is a new delimiter. The input by the user for "take cookie and milk" would be processed as "take cookie" and then "milk"

2021-05-10 17:36 UTC, ecoble requested changes

2021-05-10 17:36 UTC, ecoble commented on src/cli/src/parser.c
> +  //  printf("entering function\n");
All commented out printf lines should be removed, or converted to prose comments.

2021-05-10 17:36 UTC, ecoble commented on src/cli/src/parser.c
> +char *strtokstr_r(char *s, char *delim, char **save_ptr){
Please fix the indentation and spacing throughout this file, a lot of the brackets are misaligned. Also, in general we have been using allman style brackets throughout this project, which looks like this

if (...) 
{
      ...
}

instead of this 

if (...) {
    ...
}

You can run the file through astyle to fix this automatically.

2021-05-10 17:36 UTC, ecoble commented on src/cli/src/parser.c
> +        while (strstr(s,delim)==s) {
Please put spaces around operators like == and +=

2021-05-10 17:36 UTC, ecoble commented on src/cli/src/parser.c
> +    big_words = (char**)malloc(sizeof(char*)*4);
4 is a bit of a magic number here, you should define a variable for what this is, or use the previously defined variable TOKEN_LIST_SIZE if it is still appropriate.

2021-05-10 17:36 UTC, ecoble commented on src/cli/src/parser.c
> +    int j = 0;
Fix indentation here again, it is slightly off.

2021-05-10 17:36 UTC, ecoble commented on src/cli/src/parser.c
> +    //int i = 0;
Remove commented code.

2021-05-10 19:18 UTC, samdonio reviewed
Everything seems to make sense logically and should only need slight modification for the falling build, other than that some stylistic changes need to be made just to make the code a little cleaner and more consistent with the rest of the project.

2021-05-17 16:19 UTC, mberamendiconde commented
Changed the small issues in the parser.c function. Beza and I were committing and pushing these changes at the same time but I believe despite the merge conflict, the resolution covers the bases. Next steps are updating tests for the build

2021-05-17 16:27 UTC, mberamendiconde commented
Looked through the test suite for the parser, and the current tests should still work with the helper function. I think the build failed for another variable that was incorporated earlier when trying to add an extra feature. I added an "and" specific test.

2021-05-17 17:49 UTC, ecoble commented
It looks like the test `and_input_3_word` is failing

2021-05-17 17:53 UTC, ecoble requested changes

2021-05-17 17:53 UTC, ecoble commented on include/ui/print_functions.h
> + *   - quitval: not used in this context
Was this branch created off the quit branch? These UI changes from the other PR should not appear here.

2021-05-17 17:53 UTC, ecoble commented on src/cli/src/parser.c
> +
Descriptive comments do not need to be removed, only commented code.

2021-05-29 23:32 UTC, Beza20 commented
what was trying to be accomplished with this pull request resolving issue #275  was done with pull request #1048

2021-05-29 23:32 UTC, closed without merging