Cli/quit working solution
uchicago-cs/chiventure pull request #964
Opened 2021-05-08 00:16 UTC by samdonio

Previously chiventure could only be closed using the keystroke CTRL+D, but now the user can close it by typing "QUIT" into the cli followed by any keypress. This was done by adding an out parameter to many of the ui functions that interacted with the cli, and this out parameter would end the ui loop if the user inputted "QUIT".

Closes #273

2021-05-10 17:09 UTC, ecoble commented on include/ui/window.h
> +typedef void (win_print)(chiventure_ctx_t *ctx, window_t *win, int *quitval);
Instead of calling this quitval for all win_print functions, it would be better to name it something more generic like ret or retval. That way in the future it can be used for its own return values if need be, without it being specific to quitting the game

2021-05-10 17:10 UTC, ecoble commented on src/ui/src/ui.c
> +    quitval = malloc(sizeof(int));
I don't think the value needs to be malloced, have you tried just lines 30 and 32?

2021-05-10 17:15 UTC, ecoble commented on src/ui/src/ui.c
> +    int *quitval;
To clarify, naming this value quitval still makes sense.

2021-05-10 19:50 UTC, samdonio commented on src/ui/src/ui.c
> +    quitval = malloc(sizeof(int));
I have tried that, but after removing the lines where I malloc and also free the int pointer, typing QUIT just results in a seg fault.

2021-05-14 03:10 UTC, ecoble requested changes

2021-05-14 03:10 UTC, ecoble commented on include/ui/print_functions.h
> +void print_info(chiventure_ctx_t *ctx, window_t *win, int *quitval);
All of the parameter names in this file should also be named retval, sorry for being unclear the first time.

2021-05-14 03:12 UTC, ecoble commented on src/ui/src/print_functions.c
> +void print_map(chiventure_ctx_t *ctx, window_t *win, int *quitval)
Great question! All of the printing functions are part of a "win_print" function type defined by the UI team, and they all have to have the same input parameters and output type. So unfortunately in this case, if we want to change the parameters of one win_print function we have to change the type of all of them.

2021-05-15 18:34 UTC, mberamendiconde commented on include/ui/print_functions.h
> +void print_info(chiventure_ctx_t *ctx, window_t *win, int *quitval);
Just changed the parameter names from quitval to retval!

2021-05-16 15:14 UTC, ecoble requested changes

2021-05-16 15:14 UTC, ecoble commented on include/ui/print_functions.h
> + *   - quitval: not used in this context
The header comments should also be updated to reflect the quitval to retval change.

2021-05-16 15:14 UTC, ecoble commented on include/ui/print_functions.h
> +void print_map(chiventure_ctx_t *ctx, window_t *win, int* retval);
Small nit, everywhere else we are doing int *retval, it would be good to be consistent.

2021-05-17 15:36 UTC, mberamendiconde commented on include/ui/print_functions.h
> + *   - quitval: not used in this context
Fixed this issue!

2021-05-17 15:36 UTC, mberamendiconde commented on include/ui/print_functions.h
> +void print_map(chiventure_ctx_t *ctx, window_t *win, int* retval);
Fixed this!

2021-05-17 15:36 UTC, mberamendiconde commented
Revised @ecoble comments! Fixed the header comments to reflect the change from quitval to retval

2021-05-17 15:47 UTC, ecoble requested changes

2021-05-17 15:47 UTC, ecoble commented on include/ui/print_functions.h
> +void print_map(chiventure_ctx_t *ctx, window_t *win, int* retval);
It looks like maybe this change didn't get pushed through, I still see it as "int* retval" not "int *retval"

2021-05-17 15:47 UTC, ecoble commented on src/ui/src/print_functions.c
> +void print_info(chiventure_ctx_t *ctx, window_t *win, int* quitval)
Same small nit here, about changing the placement of the * to be "int *quitval" for consistency.

2021-05-17 15:53 UTC, mberamendiconde commented on src/ui/src/print_functions.c
> +void print_info(chiventure_ctx_t *ctx, window_t *win, int* quitval)
Apologies! I misunderstood your earlier comments, the asterix placement update should be pushed now, and consistent

2021-05-17 16:09 UTC, ecoble requested changes

2021-05-17 16:09 UTC, ecoble commented on include/ui/window.h
> +void window_print(chiventure_ctx_t *ctx, window_t *win, int *quitval);
Sorry for not catching this on the last review, but the parameters names for functions should match across files, meaning this should also be updated to retval. Basically everything should be updated to retval, except for when it is used as the name of a variable in ui.c

2021-05-17 16:09 UTC, ecoble commented on src/ui/src/print_functions.c
> +void print_info(chiventure_ctx_t *ctx, window_t *win, int *quitval)
Update quitval to retval here, and for the rest of the win_print functions in this file.

2021-05-17 16:09 UTC, ecoble commented on src/ui/src/window.c
> +void window_print(chiventure_ctx_t *ctx, window_t *win, int *quitval)
It should be updated here as well.

2021-05-17 16:41 UTC, mberamendiconde commented
Should be fixed now!

2021-05-17 17:32 UTC, ecoble approved these changes
LGTM!

2021-05-17 19:31 UTC, mjgoodman321 approved these changes
Looks like you guys got it. Go for it!

2021-05-17 19:57 UTC, merged

2021-05-17 20:00 UTC, mberamendiconde commented
Closing statement: Success! This issue was resolved, now the user can input "QUIT" into the command line and the game will quit and the terminal will close equivalently to the "Ctrl+D" input. This implementation mainly affected UI code.

2021-06-07 21:04 UTC, ecoble commented
Issue Score: ✔️+

Comments:
Great work fixing this, I know the UI code can be super tricky to work with! Be sure all issues and PRs are properly labelled and have the right milestones.

<!-- {"score": "check-plus"} -->