Add new quest structs
uchicago-cs/chiventure pull request #974
Opened 2021-05-10 22:04 UTC by ddelgado60

Updated and created new structs and union types for quests for our issue on Sprint 3. Later during Sprint 3, we will try to implement and edit existing functions in quests_state.c to reflect these changes, since the changes here will probably break existing code.

2021-05-14 18:55 UTC, zsp255 commented on include/quests/quests_structs.h
> +    mission_type_t* mission_type;
Where is mission_type_t defined

2021-05-14 18:55 UTC, zsp255 commented on include/quests/quests_structs.h
> +    mission_type_t* mission_type;
nvm

2021-05-14 18:56 UTC, zsp255 commented on include/quests/quests_structs.h
> +   item_t *item;
not sure if money is implemented into the game engine. perhaps we could think about adding an additional field next sprint

2021-05-14 18:58 UTC, zsp255 approved these changes
This commit looks quite good. As you said it will probably present errors in compiling and/or failures in our tests. I think it can be merged however, as long as the old version is archived.

2021-05-17 05:33 UTC, lilyehsani requested changes
The code and documentation updates look good for the most part, but the compilation errors must be fixed before this can be merged.

2021-05-17 05:33 UTC, lilyehsani commented on include/quests/quests_structs.h
> +    mission_type_t* mission_type;
Move * over so it's `*mission_type`

2021-05-17 21:47 UTC, zsp255 commented on include/quests/quests_structs.h
> +typedef union mission {
This will impact the implementation of the trees. Hold off on integration of this code.

2021-05-22 01:13 UTC, lilyehsani approved these changes
LGTM! Approved

2021-05-31 18:53 UTC, ddelgado60 commented
It was decided to close this PR and move the added data on this PR to implement_new_quest_fcts branch. This branch branches off of quests/implement-trees since it relies on work done in that branch. We thought it would make more sense to do this, and so this PR is closed.

2021-05-31 18:53 UTC, closed without merging

2021-06-07 03:51 UTC, lilyehsani commented
Issue Score: ✔️+

Comments:
Great work overall! I have a few comments:
- Make sure to add anyone who is working on this PR as an Assignee
- Make sure to assign new PRs to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")
- Make sure to select your team's identifier under "Labels"

<!-- {"score": "check-plus"} -->