Creation of struct and functions to allow for temporary stat changes
uchicago-cs/chiventure pull request #978
Opened 2021-05-11 01:58 UTC by jintae412

Created support for temporary stat effects through the creation of a double linked list. The double linked list holds all of the stat changes and decrements the turns left by 1 each turn. Once the turns left is 0, it removes the item from the list. Basic tests have been written. Note: The function to add a node from an item does not yet add a turn count, because we have not yet changed other existing code to integrate this new functionality.

2021-05-11 17:55 UTC, sonnykaiyuenlee approved these changes
seems like you added a lot of good functionality to keep track of stat changes. It all makes sense to me, good job!

2021-05-18 05:59 UTC, firatciftci requested changes
I have requested minor stylistic changes, so once they are taken care of everything should be good to go (make sure to check the full extent of the files that you are working on and change the items that I mention below everywhere you see fit).

2021-05-18 05:59 UTC, firatciftci commented on src/battle/src/battle_state.c
> +stat_changes_t *stat_changes_new(){
A very minor stylistic thing: Make sure that the is a space between `)` and `{` here (and also in all of the other function declarations and/or if/for/while loop statements where applicable).

2021-05-18 05:59 UTC, firatciftci commented on src/battle/src/battle_state.c
> +    if(sc == NULL)
Similar minor stylistic point: Make sure there is a single space between `if` or `for` or `while` and `(...` (here and wherever applicable in the code).

2021-05-18 05:59 UTC, firatciftci commented on src/battle/src/battle_state.c
> +    while(current != NULL){
For `for`, `while`, and `if` statements, the style must be like the following (there must be spaces around the statement bloc):

`while (...) {`

2021-05-18 05:59 UTC, firatciftci commented on src/battle/src/battle_state.c
> +        }else{
Spaces around `else` here as well.

2021-05-18 17:50 UTC, jintae412 commented
I believe that all of the requested changes have been made. Please let me know if I missed anything or if there are any other changes that I should make.

2021-05-18 18:21 UTC, firatciftci approved these changes
Everything looks good to me, good work!

2021-05-18 18:22 UTC, merged

2021-05-19 17:04 UTC, jintae412 commented
Summary of PR: In this PR a new double linked list struct was created to handle temporary stat effects for the player (such as boosting attack by 30 for 3 turns). In addition, functions were made to facilitate this such as decrementing the turn count of all effects inside a given instance of this struct and removing the stat change if the turns it had left becomes 0, mechanically undoing the effects of the stat change while doing so. This code has not been integrated in our current code however, in that starting a new battle will not create an instance of this struct.

2021-05-26 05:59 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Great job!

<!-- {"score": "check-plus-plus"} -->