Refactor level-oriented generation code
uchicago-cs/chiventure pull request #987
Opened 2021-05-12 07:44 UTC by wmingyan

This Pull Request is for refactoring the level-oriented generation code, which puts the functionality of filtering a speclist with a difficulty level into a separate function so that the filtered speclist can be used for other level-oriented autogeneration functions in addition to multi_room_level_generate. 
This involves updating the autogenerate module. Tests are added to test_autogenerate.c. Updates in the autogenerate module include adding filter_speclist_with_difficulty function and modifying multi_room_level_generate function. 
This PR is related to issue #982.

2021-05-12 08:30 UTC, Justin08784 requested changes

2021-05-12 08:30 UTC, Justin08784 commented on tests/openworld/test_autogenerate.c
> +    speclist_t *list2 = speclist_new(rspec2);
make_default_room creates a hash table of 5 roomspecs–– rspec1 and rspec2 are not singular room specs. This might be a problem when you call speclist_new on them because some hash table slots (including the rspec pointer) may be NULL. 

Instead, I think you should HASH_FIND_STR to obtain a specific rspec from each table and then use roomspec_to_room to convert it into a room.

2021-05-12 08:30 UTC, Justin08784 commented on tests/openworld/test_autogenerate.c
> +    speclist_t *list1 = speclist_new(rspec1);
Same as above.

2021-05-12 13:52 UTC, Justin08784 approved these changes
That works too, GJ!

2021-05-13 17:46 UTC, MaxineK36 requested changes
You should also add a test that ensures that `filter_speclist_with_difficulty` runs correctly when the resulting list should be non-empty but not the whole list (i.e. input a list with rooms of multiple difficulty levels including the target, and make sure you get the right output)

2021-05-13 17:46 UTC, MaxineK36 commented on include/openworld/autogenerate.h
> + * Creates a speclist by filtering the given speclist with a difficulty level
Does this return only items of matching difficulty level? or does it return anything that's, for example, that level or lower? 
Either way, this detail should be specified in the header

2021-05-14 16:45 UTC, wmingyan commented on include/openworld/autogenerate.h
> + * Creates a speclist by filtering the given speclist with a difficulty level
The returned speclist only contains roomspecs of the one level. I've added it to the header and hope that is clear.

2021-05-14 19:34 UTC, MaxineK36 approved these changes
Looks great!

2021-05-14 19:38 UTC, merged

2021-05-16 09:02 UTC, wmingyan commented
Closing statement:
Comments by reviewers have been addressed and branch `openworld/refactor-level-gen` is now merged into `dev.`

2021-05-20 04:24 UTC, MaxineK36 commented
Issue Score: ✔️++

Comments:
Great work! Your summary is very detailed and helpful; for the future, you could also consider using bullet points to improve readability.

<!-- {"score": "check-plus-plus"} -->