Playerclass/item interactions: Adding Efficiency Multipliers based on a player's class to Items.
uchicago-cs/chiventure pull request #991
Opened 2021-05-12 21:43 UTC by jackcasey067

In issue #959, we sought out to improve the ways items and classes interact.  Previously, items could be restricted from being used by certain classes.  We chose to expand this system so that, in addition to prohibiting classes, you can also give classes special proficiencies with particular items.  This information is stored as attributes (basically key-value pairs where the class name is the key and a double is the value) in the `class_multipliers` field of an item.

### In broad strokes, the following changes were made:
- The `class_item_restriction` module was renamed to the `class_item` module, resulting in name changes for 3 files.
- Game State's `item` module was modified:
    - The `class_restrictions` field became a `class_multipliers` field.
    - Code was added for retrieving data in attributes from an attribute list (this mirrors code for retrieving from a full item).
- New functions were added to `class_item`, for adding, reading, and removing these item multipliers.  Old code was modified to call the more general new code, but the older functions still exist.
- Tests were updated to call the new code, both in `class_item` and Game State's `item`.  An example file was also updated.
- The README was also updated.

2021-05-13 18:20 UTC, himaanir commented on src/playerclass/src/class_item.c
> +    /* I am open to returning an error instead of doing this. */
I think an error here would be more representative of what the function is doing, but it still accomplishes the goal this way

2021-05-13 18:20 UTC, himaanir commented on src/playerclass/src/class_item.c
> +    /* I am open to returning an error instead of doing this. */
If you choose to leave it this way add a comment explaining why it returns a success

2021-05-13 18:20 UTC, himaanir commented on src/playerclass/src/class_item.c
> +    if (!list_contains_attribute(item->class_multipliers, strncpy(buffer, class->name, 100)))
I would make this an error since in case of a typo this would return a success instead of the multiplier intended to be removed being shown to not exist. If you choose to leave it this way add a comment explaining why there is a success returned.

2021-05-13 18:20 UTC, himaanir commented on tests/game-state/test_items.c
> +Test(attribute_list, list_get_double_attr)
Add documentation on what exactly is being tested here

2021-05-13 18:20 UTC, himaanir commented on tests/game-state/test_items.c
> +Test(attribute_list, list_get_double_attr)
and with the following Tests as well

2021-05-13 19:44 UTC, WPDolan commented on src/game-state/src/item.c
> +    like->attribute = calloc(1, sizeof(attribute_t));
Make sure to check if either calloc call returns NULL in the case memory allocation fails.

2021-05-13 21:45 UTC, jackcasey067 commented on src/playerclass/src/class_item.c
> +    /* I am open to returning an error instead of doing this. */
I am going to leave it, but I modified the comment to be more clear about why this is.  The function documentation in class_item.h was also updated.

2021-05-13 21:46 UTC, jackcasey067 commented on src/game-state/src/item.c
> +attribute_t *list_get_attribute(attribute_list_t *head, char* attr_name)
Good idea, I added a comment here.

2021-05-13 21:51 UTC, jackcasey067 commented on src/playerclass/src/class_item.c
> +    if (!list_contains_attribute(item->class_multipliers, strncpy(buffer, class->name, 100)))
As above, I am keeping the behavior, but updating comments in this file and the .h file.

2021-05-13 22:00 UTC, ideclue commented on tests/game-state/test_items.c
> +Test(attribute_list, list_get_double_attr)
Good catch! Added comments explaining these tests.

2021-05-13 22:15 UTC, jackcasey067 commented on include/playerclass/class_item.h
> + * Return:
Isabella and I discussed this in Slack; we think that it might make sense in the future, if other multiplier sources are added, but that it doesn't make sense yet.

2021-05-13 22:35 UTC, WPDolan approved these changes
The changes concerning action-management/game-state modules (in `item.h` and `item.c`) successfully achieve their purpose, and my suggestion to handle cases where calloc fails in `list_get_attribute` has been implemented.

2021-05-14 05:26 UTC, afranzese99 approved these changes
Other than the minor comment about fixing header comments in `item.h`, the code related to the game-state/action-management team (`item.h` and `item.c`) seems to be implemented well and accomplishes its purpose. (Note: I only reviewed the code pertaining to game-state and action management).

2021-05-14 05:26 UTC, afranzese99 commented on include/game-state/item.h
> +/* list_get_str_attr() returns the bool value of an attribute of an item
It seems that after list_get_str_attr() you copied and pasted the header documentation for the rest of the functions but forgot to change the name of the function to the one you are actually making a comment for.

2021-05-14 13:27 UTC, jackcasey067 commented on include/game-state/item.h
> +/* list_get_str_attr() returns the bool value of an attribute of an item
Good catch.

2021-05-14 18:05 UTC, himaanir approved these changes
Ok looks good!

2021-05-18 06:23 UTC, firatciftci requested changes
I have requested changes that fall into two very minor stylistic issues; other than that the logic and the design of the PR seems good, great work!

2021-05-18 06:23 UTC, firatciftci commented on src/playerclass/src/class_item.c
> +    if ((item == NULL) | (class == NULL)) {
This `|` should be a `||` instead.

2021-05-18 06:23 UTC, firatciftci commented on src/playerclass/src/class_item.c
> +    if ((item == NULL) | (class == NULL)) {
This `|` should be a `||` instead.

2021-05-18 06:23 UTC, firatciftci commented on src/playerclass/src/class_item.c
> +    if ((item == NULL) | (class == NULL)) {
This `|` should be a `||` instead.

2021-05-18 06:23 UTC, firatciftci commented on src/playerclass/src/class_item.c
> +    if ((item == NULL) | (class == NULL)) {
This `|` should be a `||` instead.

2021-05-18 06:23 UTC, firatciftci commented on src/playerclass/src/class_item.c
> +    if ((item == NULL) | (class == NULL)) {
This `|` should be a `||` instead.

2021-05-18 06:23 UTC, firatciftci commented on src/playerclass/src/class_item.c
> +    if ((item == NULL) | (class == NULL)) {
This `|` should be a `||` instead.

2021-05-18 06:23 UTC, firatciftci commented on src/playerclass/src/class_item.c
> +    if (!is_restricted(item, class)){
There should be a space character between `(` and `}`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, add_sword_multiplier){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, add_bow_multiplier){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +void check_remove_multiplier(item_t* item, class_t* class){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, remove_wand_multiplier){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, remove_bow_multiplier){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, add_sword_restriction){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, add_bow_restriction){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +void check_remove_restriction(item_t* item, class_t* class){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, remove_wand_restriction){
There should be a space character between `)` and `{`.

2021-05-18 06:23 UTC, firatciftci commented on tests/playerclass/test_class_item.c
> +Test(class_item, remove_bow_restriction){
There should be a space character between `)` and `{`.

2021-05-18 14:33 UTC, jackcasey067 commented
As mentioned in my last commit, on the CS Linux machine, this branch does not build and test correctly.  I am actually a little alarmed that it passed Travis.

Here is what I know:
- If you build from scratch (deleting and remaking the whole build dir), you get the following warning when you run `make`.
    - The Travis logs actually agree here.

```
Scanning dependencies of target test-battle
[ 54%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_ai.c.o
[ 55%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_flow.c.o
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_flow.c: In function ‘battle_flow_set_battle_player_impl’:
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_flow.c:27:19: warning: implicit declaration of function ‘set_player’; did you mean ‘new_ctx_playe’? [-Wimplicit-function-declaration]
   27 |     comb_player = set_player(ctx_player);
      |                   ^~~~~~~~~~
      |                   new_ctx_player
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_flow.c:27:17: warning: assignment to ‘combatant_t *’ {aka ‘struct combatant *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   27 |     comb_player = set_player(ctx_player);
      |                 ^
[ 55%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_flow_structs.c.o
[ 56%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_logic.c.o
[ 56%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_moves.c.o
[ 57%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_move_maker.c.o
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c: In function ‘class_moves_bard_impl’:
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c:18:31: warning: implicit declaration of function ‘set_player’; did you mean ‘new_ctx_player’? [-Wimplicit-function-declaration]
   18 |     combatant_t *ret_player = set_player(player);
      |                               ^~~~~~~~~~
      |                               new_ctx_player
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c:18:31: warning: initialization of ‘combatant_t *’ {aka ‘struct combatant *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c: In function ‘class_moves_wizard_impl’:
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c:52:31: warning: initialization of ‘combatant_t *’ {aka ‘struct combatant *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   52 |     combatant_t *ret_player = set_player(player);
      |                               ^~~~~~~~~~
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c: In function ‘class_moves_knight_impl’:
/home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c:86:31: warning: initialization of ‘combatant_t *’ {aka ‘struct combatant *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   86 |     combatant_t *ret_player = set_player(player);
      |                               ^~~~~~~~~~
[ 57%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_print.c.o
[ 59%] Building C object tests/battle/CMakeFiles/test-battle.dir/test_battle_state.c.o
```

- If you run tests, some tests in Battle fail
    - Travis does not have these tests fail, oddly enough.  So Travis says the build passes

```
test 2
      Start  2: test-battle

2: Test command: /home/jcasey/cs/cmcs22000/chiventure/build/tests/battle/test-battle
2: Test timeout computed to be: 10000000
2: [----] /home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_flow.c:16: Unexpected signal caught below this line!
2: [FAIL] battle_flow::set_battle_player: CRASH!
2: [----] /home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c:10: Unexpected signal caught below this line!
2: [FAIL] class_moves::bard: CRASH!
2: [----] /home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c:77: Unexpected signal caught below this line!
2: [FAIL] class_moves::knight: CRASH!
2: [----] /home/jcasey/cs/cmcs22000/chiventure/tests/battle/test_battle_move_maker.c:43: Unexpected signal caught below this line!
2: [FAIL] class_moves::wizard: CRASH!
2: [====] Synthesis: Tested: 60 | Passing: 56 | Failing: 4 | Crashing: 4 
 2/14 Test  #2: test-battle ......................***Failed    0.19 sec
 ```    
 
 Note that this was not the result of the last two commits; this behavior was the case before those commits.

2021-05-18 16:16 UTC, jackcasey067 commented
Update: I locally merged in the changes in PR #969, and all tests passed.

I think this PR could be merged now; the code in dev is what is broken, and our code does not break it any further.  Alternatively, it could be best to wait for #969.

2021-05-18 17:21 UTC, jackcasey067 commented
#969 was just merged, so this PR is also completely clear for merging.

2021-05-18 17:27 UTC, firatciftci approved these changes
Everything looks good to me, great work!

2021-05-18 17:28 UTC, merged

2021-05-18 17:31 UTC, jackcasey067 commented
Closing Statement:

This branch was merged into `dev` after we integrated changes recommended by both the player class and action management teams.  Items can now have an effectiveness multiplier based on a user's class.

2021-05-26 06:01 UTC, firatciftci commented
Issue Score: ✔️++

Comments:
Good job!

<!-- {"score": "check-plus-plus"} -->