Cli/operation items
uchicago-cs/chiventure pull request #993
Opened 2021-05-12 23:36 UTC by Beza20

the code needs more detailed comments but wanted to see your feedback first. Seems to build perfectly on my end.

2021-05-14 03:19 UTC, ecoble requested changes

2021-05-14 03:19 UTC, ecoble commented on include/cli/operations.h
> +/* tried the same thing as the inventory_operation function
The header comments should follow the convention of other header comments, with a short description of the function, as well as its inputs and outputs.

2021-05-14 03:19 UTC, ecoble commented on src/cli/src/parser.c
> +    char *token = strtok(input, " and");
Is this change related to the current pull request?

2021-05-14 04:45 UTC, Beza20 commented on src/cli/src/parser.c
> +    char *token = strtok(input, " and");
No it's not. Professor Borja had to do sth because my local repo  was being weird.

2021-05-14 04:45 UTC, Beza20 commented on include/cli/operations.h
> +/* tried the same thing as the inventory_operation function
I think we should be good to go now. I have re-requested your review.

2021-05-14 18:26 UTC, ecoble requested changes

2021-05-14 18:26 UTC, ecoble commented on src/cli/src/parser.c
> +    char *token = strtok(input, " and");
In that case, this change should be removed from this PR, and implemented with the "support for and command" PR.

2021-05-14 20:31 UTC, ecoble requested changes

2021-05-14 20:31 UTC, ecoble commented on include/cli/operations.h
> + * - Said description as a string
"Said description" might be a little confusing, even though the function is named items_in_room_operation, I think it would be better to make this more descriptive, something like "List of items in the current room given as a string"

2021-05-14 20:33 UTC, ecoble commented
Looks good, just one more change. Also, be sure to update the summary with a description of what this PR accomplishes, and give the title a short description of what was accomplished as well. Also be sure to add milestones, labels, and assignees.

2021-05-14 20:43 UTC, Beza20 commented
Chiventure now supports a feature where a user can type in "items" on the command line and will get a list of the items a player is currently in. An additional function that does said feature was added to the operations module and the command to trigger said function was added using the "add-entry" function."

2021-05-14 20:57 UTC, ecoble approved these changes
LGTM!

2021-05-14 21:13 UTC, dchen0258 approved these changes

2021-05-14 21:15 UTC, Beza20 commented
Chiventure now supports a feature where a user can type in "items" on the command line and will get a list of the items a player is currently in. An additional function that does said feature was added to the operations module and the command to trigger said function was added using the "add-entry" function."

2021-05-14 21:25 UTC, merged

2021-05-17 15:17 UTC, ecoble commented
Issue Score: ✔️+

Comments:
Great job implementing this! I think it is a really useful feature to have. Be sure that your title conveys a clear goal, such as "Implement items_in_room function" or something along those lines. If you are the student reviewer for a PR, be sure to provide some feedback, even if it is just a "Looks good" for simple PRs.

<!-- {"score": "check-plus"} -->