Openworld: Implement autogeneration for rooms within a radius (aka recursive generation)
uchicago-cs/chiventure pull request #997
Opened 2021-05-13 15:32 UTC by Justin08784

Introduces the recursive_generate function which generates arbitrarily many connected (in paths) layers of rooms around a given room in a branchwise fashion. The number of layers is specified in number of paths away from the original room, denoted as the radius.

Relevant tests have been added to test_autogenerate.c.
This PR is related to issue #925.

Some terminology
Pivot: the room around which more rooms will be generated

Branchwise:
- for each pivot, we fill as many paths/branches around it with new rooms
- branches are disjoint from each other; we can cross from one branch to another only by travelling through the pivot

2021-05-13 16:47 UTC, ahmed-sumaiya approved these changes

2021-05-13 17:56 UTC, MaxineK36 requested changes
Looks good overall, a couple of style things + other small fixes

2021-05-13 17:56 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +            copy_item_to_hash(dst, src, current->item_id);
was this a bug from earlier?

2021-05-13 17:56 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    // base case
Style: Comment like these (that precede a block of code and exist on their own line) should be block comments (`/* comment */`)

2021-05-13 17:56 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +            roomspec_t *rspec = random_room_lookup(speclist);
Could any of these be refactored into a helper? This function is currently quite long

2021-05-13 17:56 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +        assert(SUCCESS == recursive_generate(game, next_room, speclist,
Could this be `int rc = recursive_generate(game, next_room, speclist, `...?

2021-05-13 17:56 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    return SUCCESS;
does this function ever return FAILURE? In keeping consistent with the rest of chiventure, you may want to change line 338 to `rc` (see above comment) and then have `return rc` here

2021-05-14 01:09 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +            copy_item_to_hash(dst, src, current->item_id);
Yep! It was from last year's team.

2021-05-14 01:22 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +            roomspec_t *rspec = random_room_lookup(speclist);
Lines 314-334 checks if a path from the current_room is empty and generates a single room at the end of the path if it is empty.

Now this is essentially copy-pasted code from room_generate. The only reason we're redefining this code instead of simply calling upon room_generate is because room_generate can only generate around the 'curr_room' that's defined in the game struct. 

We figured that we could modify room_generate so that it generates around any given room, which could be passed in as a parameter, but we weren't sure if this was worth the effort. Advice?

2021-05-14 01:24 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +    return SUCCESS;
Currently, there is no fail condition.

2021-05-14 01:47 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +            roomspec_t *rspec = random_room_lookup(speclist);
Is there a reason this one has "UP" and "DOWN" as directions and `room_generate` doesn't? 

And I think that that should make sense in the long run, but if it's a change that will take longer you can create up a backlog issue for it (you don't need to add any assignees yet) and it can be done later on. For now, just note in a comment above that section that the code is similar to the `room_generate` code

2021-05-14 01:47 UTC, MaxineK36 commented on src/openworld/src/autogenerate.c
> +    return SUCCESS;
@Justin08784 Why not return `FAILURE` if `recursive_generate` returns failure?

2021-05-14 02:10 UTC, Justin08784 commented on src/openworld/src/autogenerate.c
> +            roomspec_t *rspec = random_room_lookup(speclist);
The reason we have UP and DOWN is because we tried to support all six default directions (NESW + UP + DOWN). Actually, I am not 100% sure if there really are default directions hardcoded into chiventure.

2021-05-14 02:55 UTC, MaxineK36 approved these changes
Looks great!

2021-05-14 02:55 UTC, merged

2021-05-16 08:42 UTC, Justin08784 commented
Comments by reviewers have been addressed and the relevant branch is now merged into `dev.`

2021-05-20 04:23 UTC, MaxineK36 commented
Issue Score: ✔️+

Comments:
Good work overall! One area of improvement for next time:
- The reviewer for this PR approved the PR without comment. Please make sure that you always do a full review of the code, even if the senior developer has already provided their review. In the rare cases where there truly isn't anything to improve in the PR, make sure to leave a comment confirming that you reviewed the code and don't have any changes to suggest. If the senior dev has left their review, it can also be useful to indicate whether you agree with it or not.

<!-- {"score": "check-plus"} -->