Added all_npcs field to game and Completed Integrating Conversations into Chiventure with Example
uchicago-cs/chiventure pull request #999
Opened 2021-05-13 22:08 UTC by pkasner

Closes #922  and #984 
This branch implements a run_conversation_mode() function, which acts as a mode_operation function for conversation mode.
Here are the major changes required to do so:
 - A hash table of npcs, called all_npcs was added to chiventure's game struct, along with corresponding functions 
   add_npc_to_game(), and delete_all_npcs() for managing that field.
 - The run_conversation_mode() function was implemented, which parses the users input, passes that information to the 
    run_conversation_step() function in the dialogue module, and prints the corresponding response to the ui.
 - A new file conversation_mode_example.c, runs an instance of chiventure which allows for a monkey patched "talk" action. 
   This allows conversations to be tested in a complete instance of chiventure.

2021-05-14 21:12 UTC, jeyeong requested changes
Apart from that one small matter, the code looks good to me!

2021-05-14 21:12 UTC, jeyeong commented on src/game-state/src/mode.c
> +    int end_convo;
I've changed the implementation of run_conversation_step (which has not been merged), so that it sets the int out-parameter to 1 if the convo has ended, 0 if the convo is still ongoing, and -1 if an error occured. While that change has not been merged, it could be a good idea to rename the variable end_convo in preparation for that.

2021-05-14 23:34 UTC, pkasner commented on src/game-state/src/mode.c
> +    int end_convo;
It seems the only change then is the addition of the error possibility if my understanding is correct. In this case, I'm still using it to check if the conversation is over, so the variable name seems appropriate. Or do you just mean that I change it to a more general return code esque variable name?

2021-05-16 16:58 UTC, jeyeong commented on src/game-state/src/mode.c
> +    int end_convo;
That's true. The only (potential) issue is that since -1 evaluates to true, that could give an incorrect impression.

2021-05-16 16:59 UTC, jeyeong commented on src/game-state/src/mode.c
> +    int end_convo;
Either way, once error checking has been added, I don't think it will make that big of a difference, so you could keep it as it is if you like.

2021-05-16 16:59 UTC, jeyeong approved these changes

2021-05-16 18:52 UTC, pkasner commented on src/game-state/src/mode.c
> +    int end_convo;
Ah, that makes sense. Although I think if an error occurs it probably makes sense to end the conversation anyways, so the logic should be fine.

2021-05-17 02:39 UTC, pkasner commented on src/game-state/src/mode.c
> +    int end_convo;
Just added an error check for the future.

2021-05-19 20:12 UTC, lilyehsani requested changes
Looks really great. Added one minor comment

2021-05-19 20:12 UTC, lilyehsani commented on src/game-state/src/mode.c
> +}
Great job on this function

2021-05-19 20:12 UTC, lilyehsani commented on src/npc/examples/conversation_mode_example.c
> +    /* Creating merchant npc
Delete commented code or explain why it is commented

2021-05-21 20:31 UTC, lilyehsani approved these changes
Looks great! Approved

2021-05-21 20:31 UTC, merged

2021-05-23 00:12 UTC, pkasner commented
The run_conversation_mode() functions is working, and consequently, our example allows for a full demo of conversation mode running in an instance of chiventure. However, this demo makes use of a monkey patched "talk" command, so the final step for making this functionality fully available is to implement such a command in chiventure by default. This should be fairly simple given how the mode functionality is structured.

2021-06-07 01:56 UTC, lilyehsani commented
Issue Score: ✔️++

Comments:
Great work overall! The summary and closing of this PR are very thorough.

<!-- {"score": "check-plus-plus"} -->